### PR TITLE
Update the verifier to recognize new constructor <vnew> of value type

### PR DESCRIPTION
**Pull request by hangshao0**
1. The VT constructors are compiled into `<vnew>`. Update all places using `<new>` to `<vnew>`.
1. Enable all the code inside J9VM_OPT_VALHALLA_NEW_FACTORY_METHOD.
2. Remove obsolete code that checks `<init>` as VT constructor.

issue #14959

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
There is a corresponding JIT PR: https://github.com/eclipse-openj9/openj9/pull/16357.

**Comment by tajila** [comment]
@ChengJin01 Please review these changes

**Comment by hangshao0** [comment]
FYI @ehrenjulzert This PR enables the code to handle new VT factory method.

**Comment by ChengJin01** [comment]
As talked to @hangshao0, there is no special concern from my side as it just enables the previously implemented code to deal with the new keyword `<vnew>` in the Spec, assuming the code has been verified with Valhalla specific tests.

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity plinuxvalst jdknext

**Review by tajila — APPROVED** [review]

**Pull request merged**
