### PR TITLE
Inline interface calls only when the named interface can be found

### LINKED ISSUE #16400: crash building xmac vmState=0x000501ff
https://openj9-jenkins.osuosl.org/job/Build_JDK19_x86-64_mac_Nightly/127

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK19_x86-64_mac_Nightly/127/Build_JDK19_x86-64_mac_Nightly-127-20221130-200617-diagnostics.tar.gz

vmState [0x501ff]: {J9VMSTATE_JIT} {inlining}
```
20:05:07  Type=Segmentation error vmState=0x000501ff
20:05:07  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
20:05:07  Handler1=0000000008A37C60 Handler2=0000000008D36AB0 InaccessibleAddress=0000000000000018
20:05:07  RDI=000000000E89DF00 RSI=0000000000000000 RAX=0000000000000000 RBX=00007F88A2806BF0
20:05:07  RCX=000000000A30F838 RDX=0000000000000000 R8=00000000055FA5EB R9=FFFFFFFF00000001
20:05:07  R10=00007F88A20082B0 R11=00007F8897037C70 R12=0000000000000000 R13=000000000E89DF00
20:05:07  R14=000000000E89DF00 R15=0000000000000000
20:05:07  RIP=000000000A1BE3E5 GS=0000 FS=0000 RSP=000070000921E908
20:05:07  RFlags=0000000000010206 CS=002B RBP=000070000921E920 ERR=0000001800000004
20:05:07  TRAPNO=000000040000000E CPU=0018000000040000 FAULTVADDR=0000000000000018
20:05:07  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM8 0f0f0f0f0f0f0f0f (f: 252645136.000000, d: 3.815737e-236)
20:05:07  XMM9 0302020102010100 (f: 33620224.000000, d: 3.524484e-294)
20:05:07  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
20:05:07  Module=/Users/jenkins/workspace/Build_JDK19_x86-64_mac_Nightly/build/macosx-x86_64-server-release/jdk/lib/default/libj9jit29.dylib
20:05:07  Module_base_address=0000000008EA4000 Symbol=instanceOfOrCheckCast
20:05:07  Symbol_address=000000000A1BE3D0
20:05:07  
20:05:07  Method_being_compiled=jdk/internal/module/ModuleInfo.doRead(Ljava/io/DataInput;)Ljdk/internal/module/ModuleInfo$Attributes;
20:05:07  Target=2_90_20221130_127 (Mac OS X 10.15.7)
20:05:07  CPU=amd64 (12 logical CPUs) (0x400000000 RAM)
20:05:07  ----------- Stack Backtrace -----------
20:05:07  instanceOfOrCheckCast+0x16 (0x000000000A1BE3E6 [libj9jit29.dylib+0x131a3e6])
20:05:07  _ZN7TR_J9VM12isInstanceOfEP19TR_OpaqueClassBlockS1_bbb+0xf9 (0x0000000008F4F4D9 [libj9jit29.dylib+0xab4d9])
20:05:07  _ZN18TR_J9SharedCacheVM12isInstanceOfEP19TR_OpaqueClassBlockS1_bbb+0x35 (0x0000000008F62205 [libj9jit29.dylib+0xbe205])
20:05:07  _ZN22TR_J9InterfaceCallSite18findCallSiteTargetEP12TR_CallStackP14TR_InlinerBase+0xf4 (0x000000000908FBB4 [libj9jit29.dylib+0x1ebbb4])
20:05:07  _ZN19TR_EstimateCodeSize12isInlineableEP12TR_CallStackP11TR_CallSite+0xa7 (0x0000000008FDB867 [libj9jit29.dylib+0x137867])
20:05:07  _ZN19InterpreterEmulator34findTargetAndUpdateInfoForCallsiteEP11TR_CallSitei+0x3e (0x000000000908CC5E [libj9jit29.dylib+0x1e8c5e])
20:05:07  _ZN19InterpreterEmulator35findAndCreateCallsitesFromBytecodesEbb+0x235 (0x000000000908AE75 [libj9jit29.dylib+0x1e6e75])
20:05:07  _ZN21TR_J9EstimateCodeSize20realEstimateCodeSizeEP13TR_CallTargetP12TR_CallStackbRN2TR6RegionE+0xb4c (0x0000000009080F8C [libj9jit29.dylib+0x1dcf8c])
20:05:07  _ZN21TR_J9EstimateCodeSize16estimateCodeSizeEP13TR_CallTargetP12TR_CallStackb+0x3f (0x00000000090803EF [libj9jit29.dylib+0x1dc3ef])
20:05:07  _ZN19TR_EstimateCodeSize17calculateCodeSizeEP13TR_CallTargetP12TR_CallStackb+0xcd (0x0000000008FDB6BD [libj9jit29.dylib+0x1376bd])
20:05:07  _ZN16TR_J9InlinerUtil29estimateAndRefineBytecodeSizeEP11TR_CallSiteP13TR_CallTargetP12TR_CallStackRi+0x9d (0x000000000907761D [libj9jit29.dylib+0x1d361d])
20:05:07  _ZN14TR_InlinerBase20applyPolicyToTargetsEP12TR_CallStackP11TR_CallSite+0x669 (0x00000000092E8F79 [libj9jit29.dylib+0x444f79])
20:05:07  _ZN14TR_InlinerBase29getSymbolAndFindInlineTargetsEP12TR_CallStackP11TR_CallSiteb+0x2de (0x00000000092DD7BE [libj9jit29.dylib+0x4397be])
20:05:07  _ZN28TR_MultipleCallTargetInliner17inlineCallTargetsEPN2TR20ResolvedMethodSymbolEP12TR_CallStackP24TR_InnerPreexistenceInfo+0x50c (0x00000000090700CC [libj9jit29.dylib+0x1cc0cc])
20:05:07  _ZN14TR_InlinerBase15performInliningEPN2TR20ResolvedMethodSymbolE+0x6f (0x00000000092DAB8F [libj9jit29.dylib+0x436b8f])
20:05:07  _ZN10TR_Inliner7performEv+0xe0 (0x000000000906E6C0 [libj9jit29.dylib+0x1ca6c0])
20:05:07  _ZN3OMR9Optimizer19performOptimizationEPK20OptimizationStrategyiii+0x1afa (0x00000000093C947A [libj9jit29.dylib+0x52547a])
20:05:07  _ZN3OMR9Optimizer8optimizeEv+0x32e (0x00000000093C764E [libj9jit29.dylib+0x52364e])
20:05:07  _ZN3OMR11Compilation7compileEv+0x5ed (0x000000000920D29D [libj9jit29.dylib+0x36929d])
20:05:07  _ZN2TR28CompilationInfoPerThreadBase7compileEP10J9VMThreadPNS_11CompilationEP17TR_ResolvedMethodR11TR_J9VMBaseP19TR_OptimizationPlanRKNS_16SegmentAllocatorE+0x7ed (0x0000000008F0A7BD [libj9jit29.dylib+0x667bd])
20:05:07  _ZN2TR28CompilationInfoPerThreadBase14wrappedCompileEP13J9PortLibraryPv+0x4bb (0x0000000008F0812B [libj9jit29.dylib+0x6412b])
20:05:07  omrsig_protect+0x392 (0x0000000008D355A2 [libj9prt29.dylib+0x215a2])
20:05:07  _ZN2TR28CompilationInfoPerThreadBase7compileEP10J9VMThreadP21TR_MethodToBeCompiledRN2J917J9SegmentProviderE+0x390 (0x0000000008F032F0 [libj9jit29.dylib+0x5f2f0])
20:05:07  _ZN2TR24CompilationInfoPerThread12processEntryER21TR_MethodToBeCompiledRN2J917J9SegmentProviderE+0x20a (0x0000000008F029BA [libj9jit29.dylib+0x5e9ba])
20:05:07  _ZN2TR24CompilationInfoPerThread14processEntriesEv+0x1a8 (0x0000000008F01D38 [libj9jit29.dylib+0x5dd38])
20:05:07  _ZN2TR24CompilationInfoPerThread3runEv+0xde (0x0000000008F01AFE [libj9jit29.dylib+0x5dafe])
20:05:07  _Z30protectedCompilationThreadProcP13J9PortLibraryPN2TR24CompilationInfoPerThreadE+0x90 (0x0000000008F018C0 [libj9jit29.dylib+0x5d8c0])
20:05:07  omrsig_protect+0x392 (0x0000000008D355A2 [libj9prt29.dylib+0x215a2])
20:05:07  _Z21compilationThreadProcPv+0x23c (0x0000000008EFFCAC [libj9jit29.dylib+0x5bcac])
20:05:07  thread_wrapper+0x13a (0x00000000071E26DA [libj9thr29.dylib+0xa6da])
20:05:07  _pthread_start+0x94 (0x00007FFF6F1E0109 [libsystem_pthread.dylib+0x6109])
20:05:07  ---------------------------------------
```

### PR DESCRIPTION
**Pull request by jdmpapin**
Fixes #16400

### CODE REVIEW

**Comment by jdmpapin** [comment]
@0xdaryl, could you please review?

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17

**Comment by 0xdaryl** [comment]
I suspect the JitServer failure is not related to this PR.

**Comment by jdmpapin** [comment]
Yes, that's #14706

**Pull request merged**
