### PR TITLE
Convert jvmtiThread.c to jvmtiThread.cpp

### PR DESCRIPTION
**Pull request by babsingh**
This will simplify future changes for virtual thread support.

### CODE REVIEW

**Comment by babsingh** [comment]
jenkins test extended.openjdk zlinux jdk21

**Comment by babsingh** [comment]
Failure seen in the builds are unrelated to the PR:
- [KNOWN] https://github.com/eclipse-openj9/openj9/issues/18426
- [KNOWN] https://github.com/eclipse-openj9/openj9/issues/18456

> https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/6/consoleFull

A timeout in `GetThreadStateTest` is seen, which is seen for the first time. Locally, this failure occurs intermittently. This PR doesn't change any functionality so it is not cause for this failure. I will open an issue to document the intermittent `GetThreadStateTest` failure.

**Comment by babsingh** [comment]
@gacholio Requesting your review. Taking an approach similar to https://github.com/eclipse-openj9/openj9/pull/18413 w.r.t. the cpp conversion.

**Comment by gacholio** [comment]
I personally prefer `(type*)` to `(type *)` but I won't insist. What is the reason for this change?

**Comment by gacholio** [comment]
Every test suite failed - this is not a sensible situation to be in.

**Comment by gacholio** [comment]
Given the compile successes, this is ready for merge.

**Comment by babsingh** [comment]
> I personally prefer (type*) to (type *) but I won't insist.

`(type *)` used to be consistent with the existing format in the file.

> What is the reason for this change?

To support a follow up change in https://github.com/babsingh/openj9/commits/main3 (WIP).

**Comment by tajila** [comment]
@babsingh you may need to triple deliver to 0.42 and 0.43

**Comment by babsingh** [comment]
Backports: 
- #18494
- #18495

**Pull request merged**
