### PR TITLE
Print footprint statistics using verbose #METHOD STATS

### PR DESCRIPTION
**Pull request by gita-omr**
Depends on: https://github.com/eclipse/omr/pull/7309

### CODE REVIEW

**Comment by gita-omr** [comment]
Fixed line endings.

**Comment by gita-omr** [comment]
Cosmetic fix.

**Review by dsouzai — APPROVED** [review]
LGTM

**Comment by dsouzai** [comment]
jenkins test sanity all jdk17 depends eclipse/omr#7309

**Comment by dsouzai** [comment]
I guess the `depends` command doesn't work because the OMR PR was already merged; will need to wait until that change propagates into the `openj9` branch of `openj9-omr`.

**Comment by pshipton** [comment]
jenkins test sanity all jdk17 depends eclipse/omr#master

**Pull request merged**
