### PR TITLE
Add assertions to stack walker caching

### PR DESCRIPTION
**Pull request by gacholio**
Before computing the maximum number of frames that might exist, verify that
the SP is between the start and end of the stack.

Related: #13910

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by gacholio** [comment]
jenkins compile win jdk11

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by gacholio** [comment]
jenkins compile win jdk11

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by gacholio** [comment]
jenkins compile win jdk11

**Comment by gacholio** [comment]
jenkins test sanity plinux jdk11

**Comment by tajila** [comment]
jenkins test sanity win jdk8

**Review by tajila — APPROVED** [review]

**Pull request merged**
