### PR TITLE
Compile jdk8, 11 alinux with gcc 10.3, p,zlinux with gcc 11.2

### PR DESCRIPTION
**Pull request by pshipton**
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/726

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,sanity.openjdk alinux64,plinux,zlinux jdk8,jdk11

**Comment by keithc-ca** [comment]
I'm surprised that jdk8 built _without_ the equivalent of the fix in https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/726; or were you planning to back-port that fix anyway?

**Comment by pshipton** [comment]
I assume jdk8 doesn't have warnings as errors for some reason. I think we should backport it, but maybe wait until it's better tested in jdk11 first.

**Comment by keithc-ca** [comment]
Jenkins test sanity,sanity.openjdk alinux,plinux,zlinux jdk11

**Comment by pshipton** [comment]
I believe the test failures are known issues.

**Comment by keithc-ca** [comment]
> I believe the test failures are known issues.

I've been trying to check the failures, but https://openj9-jenkins.osuosl.org/ is not cooperating right now.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
