### PR TITLE
Fix recognizedMethod canSkipNullChecks & canSkipBoundChecks list

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Removed `java_lang_String_startsWith` from `canSkipNullChecks` list;
Removed `java_lang_StringUTF16_charAt` & `java_lang_StringUTF16_checkIndex` from `canSkipBoundChecks` list.

Verified that the test suite `openjdk/jdk_lang` passes with this PR.

Introduced by https://github.com/eclipse/openj9/pull/12209

fixes https://github.com/eclipse/openj9/issues/12578

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8

**Comment by pshipton** [comment]
jenkins test sanity.openjdk plinux jdk8

**Comment by pshipton** [comment]
Jenkins test sanity xlinux,zlinux,win,win32,aix,osx jdk8

**Comment by pshipton** [comment]
Jenkins test sanity xlinux,zlinux,win,win32,aix,osx jdk8

**Comment by pshipton** [comment]
Jenkins test sanity xlinux,zlinux,win,win32,aix,osx jdk8

**Comment by pshipton** [comment]
Jenkins test sanity,sanity.openjdk plinux jdk8

**Comment by pshipton** [comment]
There are infra issues with the win32 testing. I've restarted it a couple of times. In the last run half the tests passed and the other half had the infra issue
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_Personal_testList_0/149/ - passed

@fjeremic not sure if you want to wait and try to get a clean run or if the current results are good enough. Considering the only problem we've seen (for sure) is on P in the sanity.openjdk tests.

There are couple of recent crashes on P which I'm not sure are related to this or not.
https://github.com/eclipse-openj9/openj9/issues/12594
https://github.com/eclipse-openj9/openj9/issues/12595

**Comment by fjeremic** [comment]
The lines being removed here were not present a week ago before the original change so I'm fairly confident this is safe. I'm proceeding with the merge.

**Comment by pshipton** [comment]
For the record, the win32 test did pass fully this time.

**Pull request merged**
