### PR TITLE
VectorAPI: Don't generate lshl by const 0

### PR DESCRIPTION
**Pull request by BradleyWood**

### CODE REVIEW

**Comment by BradleyWood** [comment]
@gita-omr Can you review?

**Review by gita-omr — APPROVED** [review]

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk19

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk19

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk20

**Comment by gita-omr** [comment]
Power build failure seems to be unrelated.

**Pull request merged**
