### PR TITLE
Update J9Runtime.hpp

### PR DESCRIPTION
**Pull request by SurajKarmakar1**
Issue #17450  
Rename TR_InlinedSiteHastTableEntry to TR_InlinedSiteHashTableEntry

### CODE REVIEW

**Comment by SurajKarmakar1** [comment]
@0xdaryl  review please.

**Review by hzongaro — CHANGES_REQUESTED** [review]
@SurajKarmakar1, thanks for your contribution!

You might have missed it, but I mentioned in my [review](https://github.com/eclipse-openj9/openj9/pull/17460#pullrequestreview-1449520643) for your original pull request #17460, that there are several references to `TR_InlinedSiteHastTableEntry` in `runtime/compiler/codegen/J9CodeGenerator.cpp` that will need to be updated as well.  Please include those changes in this pull request.

I think you also missed another [comment in that pull request](https://github.com/eclipse-openj9/openj9/pull/17460#issuecomment-1567177035) recommending some changes to the description of the change in the git commit itself:

> please take a look at [**Contributing to Eclipse OpenJ9**](https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md) for some further guidance.  In particular, please update the first line of your commit to better describe the effect of applying the commit - something along the lines of `Correct typo in name of TR_InlinedSiteHastTableEntry`.  It's also good practice to attempt to build and test OpenJ9 with your changes, to ensure that it will build and operate as expected with your changes.

**Comment by hzongaro** [comment]
Hi, @SurajKarmakar1.  Have you had a chance to look at the review comments for your pull request?

**Comment by hzongaro** [comment]
Issue #17450 was fixed under pull request #17848.  Closing this one.

**Pull request closed without merging**
