### PR TITLE
Modify the translated PII files nls folder

### PR DESCRIPTION
**Pull request by panlei080988**
Check in the Shipment 1 translation package for J182F's TVT

Signed-off-by: Lei Pan <pleinb@cn.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Last time the copyright check failed as well, please check the output in the copyright job Details to see the list of files.

**Comment by pshipton** [comment]
23:36:50 The following files were modified and have incorrect copyrights
[Pipeline] echo
23:36:51 runtime/nls/dump/j9dmp_fr.nls
23:36:53 runtime/nls/dump/j9dmp_sl.nls
[Pipeline] echo
[Pipeline] echo
23:36:56 runtime/nls/exel/exelib_cs.nls
23:36:58 runtime/nls/exel/exelib_fr.nls
[Pipeline] echo
23:37:01 runtime/nls/exel/exelib_pl.nls
[Pipeline] echo
23:37:04 runtime/nls/exel/exelib_pt_BR.nls
[Pipeline] echo
[Pipeline] echo
23:37:07 runtime/nls/exel/exelib_sl.nls
23:37:10 runtime/nls/j9gc/j9modron_ca.nls
[Pipeline] echo
[Pipeline] echo
23:37:12 runtime/nls/j9gc/j9modron_cs.nls
23:37:13 runtime/nls/j9gc/j9modron_de.nls
[Pipeline] echo
[Pipeline] echo
23:37:18 runtime/nls/j9gc/j9modron_es.nls
23:37:21 runtime/nls/j9gc/j9modron_fr.nls
[Pipeline] echo
[Pipeline] echo
23:37:24 runtime/nls/j9gc/j9modron_hu.nls
[Pipeline] echo
23:37:28 runtime/nls/j9gc/j9modron_it.nls
[Pipeline] echo
23:37:29 runtime/nls/j9gc/j9modron_ja.nls
[Pipeline] echo
23:37:32 runtime/nls/j9gc/j9modron_ko.nls
23:37:34 runtime/nls/j9gc/j9modron_pl.nls
[Pipeline] echo
23:37:41 runtime/nls/j9gc/j9modron_pt_BR.nls
[Pipeline] echo
[Pipeline] echo
23:37:45 runtime/nls/j9gc/j9modron_ru.nls
[Pipeline] echo
23:37:46 runtime/nls/j9gc/j9modron_sk.nls
[Pipeline] echo
23:37:50 runtime/nls/j9gc/j9modron_sl.nls
23:37:51 runtime/nls/j9gc/j9modron_tr.nls
[Pipeline] echo
[Pipeline] echo
23:37:56 runtime/nls/j9gc/j9modron_zh.nls
23:37:57 runtime/nls/j9gc/j9modron_zh_CN.nls
[Pipeline] echo
[Pipeline] echo
23:38:02 runtime/nls/j9gc/j9modron_zh_TW.nls
23:38:05 runtime/nls/j9ri/j9ri_fr.nls
[Pipeline] echo
[Pipeline] echo
23:38:09 runtime/nls/j9ti/jvmti_fr.nls
[Pipeline] echo
23:38:10 runtime/nls/j9ti/jvmti_it.nls
[Pipeline] echo
23:38:12 runtime/nls/j9ti/jvmti_ko.nls
[Pipeline] echo
23:38:14 runtime/nls/j9ti/jvmti_sk.nls
[Pipeline] echo
23:38:16 runtime/nls/jitm/j9jit_cs.nls
23:38:18 runtime/nls/jitm/j9jit_fr.nls
[Pipeline] echo
[Pipeline] echo
23:38:20 runtime/nls/jitm/j9jit_hu.nls
[Pipeline] echo
23:38:21 runtime/nls/jitm/j9jit_pl.nls
[Pipeline] echo
23:38:23 runtime/nls/jitm/j9jit_sl.nls
[Pipeline] echo
23:38:24 runtime/nls/jnck/jnichk_fr.nls
[Pipeline] echo
23:38:26 runtime/nls/jnck/jnichk_hu.nls
[Pipeline] echo
23:38:28 runtime/nls/jnck/jnichk_it.nls
[Pipeline] echo
23:38:30 runtime/nls/jnck/jnichk_pl.nls
23:38:33 runtime/nls/port/port_fr.nls
[Pipeline] echo
[Pipeline] echo
23:38:36 runtime/nls/port/port_it.nls
[Pipeline] echo
23:38:37 runtime/nls/port/port_ko.nls
23:38:39 runtime/nls/port/port_tr.nls
[Pipeline] echo
[Pipeline] echo
23:38:42 runtime/nls/verb/verbose_cs.nls
23:38:44 runtime/nls/verb/verbose_fr.nls
[Pipeline] echo
[Pipeline] echo
23:38:50 runtime/nls/verb/verbose_pl.nls
23:38:52 runtime/nls/vmut/j9vmutil_ca.nls
[Pipeline] echo
[Pipeline] echo
23:38:55 runtime/nls/vmut/j9vmutil_cs.nls
[Pipeline] echo
23:38:56 runtime/nls/vmut/j9vmutil_de.nls
[Pipeline] echo
23:38:59 runtime/nls/vmut/j9vmutil_es.nls
[Pipeline] echo
23:39:00 runtime/nls/vmut/j9vmutil_fr.nls
[Pipeline] echo
23:39:01 runtime/nls/vmut/j9vmutil_hu.nls
[Pipeline] echo
23:39:02 runtime/nls/vmut/j9vmutil_it.nls
[Pipeline] echo
23:39:04 runtime/nls/vmut/j9vmutil_ja.nls
[Pipeline] echo
23:39:06 runtime/nls/vmut/j9vmutil_ko.nls
[Pipeline] echo
23:39:06 runtime/nls/vmut/j9vmutil_pl.nls
[Pipeline] echo
23:39:08 runtime/nls/vmut/j9vmutil_pt_BR.nls
[Pipeline] echo
23:39:09 runtime/nls/vmut/j9vmutil_ru.nls
[Pipeline] echo
23:39:09 runtime/nls/vmut/j9vmutil_sk.nls
[Pipeline] echo
23:39:10 runtime/nls/vmut/j9vmutil_sl.nls
[Pipeline] echo
23:39:11 runtime/nls/vmut/j9vmutil_tr.nls
[Pipeline] echo
23:39:12 runtime/nls/vmut/j9vmutil_zh.nls
[Pipeline] echo
23:39:14 runtime/nls/vmut/j9vmutil_zh_CN.nls
[Pipeline] echo
23:39:16 runtime/nls/vmut/j9vmutil_zh_TW.nls
[Pipeline] echo
23:39:18 runtime/nls/vrfy/j9bcv_sl.nls

**Comment by panlei080988** [comment]
How to repair the fail of travis-ci?

**Comment by pshipton** [comment]
You can ignore the travis-ci failure, its not related to your change.

**Comment by pshipton** [comment]
Ignore last comment, the failure is related.
```
* Failure occured during the process *
Error: J9NLS_JIT_OPTIONS_XLP_UNRECOGNIZED_OPTION Message "A rendszerkonfiguráció nem támogatja a(z) '%s' paraméter használatát az '-Xlp' beállításban" in /home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/nls/jitm/j9jit_hu.nls is different from "System configuration does not support parameter '%.*s' in option '-Xlp'" in /home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/nls/jitm/j9jit.nls
* Failure occured during the process *
Error: J9NLS_VM_LOADING_CONSTRAINT_OVERRIDE_VIOLATION Message "betöltési korlátsértés a(z) "%2$.*1$s.%4$.*3$s%6$.*5$s" metódus felülbírálásakor: a(z) "%8$.*7$s@%9$x" betöltő a(z) "%11$.*10$s" osztályban és a(z) "%13$.*12$s@%14$x" betöltő a(z) "%16$.*15$s" osztályban eltérő típusú metódusaláírásokat tartalmaznak" in /home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/nls/j9vm/j9vm_hu.nls is different from "loading constraint violation when overriding method "%2$.*1$s.%4$.*3$s%6$.*5$s" during creation of class "%18$.*17$s": loader "%8$.*7$s@%9$x" of class "%11$.*10$s" and loader "%13$.*12$s@%14$x" of class "%16$.*15$s" have different types for the method signature" in /home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/nls/j9vm/j9vm.nls
```

**Comment by pshipton** [comment]
In j9jit_hu.nls "%.*s" was changed to "%s", which takes a different number of parameters.

In j9vm_hu.nls the parameters "%18$.*17$s" are missing

**Comment by pshipton** [comment]
About the copyright failures: 

"the translated files are translated according to the English source file. In the English source file, the copyright is 2017, so according to the translating rules the translated files have to keep the same copyright content with English file. So translators cannot change the copyright to 2018 when in the English source file the year is 2017.

The rule is from the whole translation center for all the translation project. For one project they will not change the rule."

**Pull request closed without merging**
