### PR TITLE
Fix testvmcheck failures from ContainsRuntimeAnnotationTest

### PR DESCRIPTION
**Pull request by EricYangIBM**
Fixes: #13120
Signed-off-by: Eric Yang <eric.yang@ibm.com>

### CODE REVIEW

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test extended plinux jdk11

**Comment by tajila** [comment]
Jenkins test extended zlinux jdk16

**Comment by tajila** [comment]
Jenkins test extended plinux jdk11

**Comment by pshipton** [comment]
As this is a test only change, I'll test it via grinders.

**Comment by pshipton** [comment]
testvmcheck is passing with this change
11: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/98
16: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/101/

Running all sanity and extended as well
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/99
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/100

**Review by pshipton — APPROVED** [review]

**Pull request merged**
