### PR TITLE
Fix resetting global lists issue in CRIU reinitializeForRestore

### PR DESCRIPTION
**Pull request by LinHu2016**
We need to reset the root of global lists(unfinalizedObjectLists,
OwnableSynchronizerObjectLists, ContinuationObjectLists) for rebuilding
the lists(array of sublists, the size of array match to gcThreadCount),
in case the gcThreadCount in restore env is more than the gcThreadCount
in original env.
Backup and reset root of global lists before reinitializeForRestore
and restore the root of global lists if the lists were not rebuilt
during reinitializeForRestore.

fix:https://github.com/eclipse-openj9/openj9/issues/19421

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
This PR fixed `j9mm.107  *  ** ASSERTION FAILED ** at openj9-openjdk-jdk/openj9/runtime/gc_api/HeapIteratorAPI.cpp:543: ((false && (__null != continuationObjectList)))` discovered by 
* https://github.com/eclipse-openj9/openj9/pull/19405

**Comment by amicic** [comment]
try it differently:

- backup the head pointers and reset them before region loop iteration that might rebuild the lists and set the head pointers
- if head pointers are still null, then restore them from backup, otherwise leave them

**Comment by amicic** [comment]
jenkins test sanity aix,win jdk21

**Comment by amicic** [comment]
jenkins test sanity.functional xLinux jdk21

**Comment by amicic** [comment]
jenkins test sanity.functional xLinux jdk21

**Comment by amicic** [comment]
jenkins test sanity.functional xLinux jdk21

**Comment by amicic** [comment]
jenkins test sanity.functional xLinux jdk21

**Comment by amicic** [comment]
xLinux repetedly failing due to network issues

**Review by amicic — APPROVED** [review]

**Pull request merged**
