### PR TITLE
Standardize evaluator names across backends

### PR DESCRIPTION
**Pull request by fjeremic**
Standardize evaluator names across all backends to be of the form:

```
<ilName>Evaluator
```

The tree evaluator table is now generated using Opcodes.enum IL macro definitions and has been commoned up in the common code generator. Backends must implement all of the evaluator functions to be able to compile. As we continue our unification journey we can start to pull up common definitions into the common codegen. For example we can reach a state where all the evaluators are implemented in the common codegen to delegate to `unImpOpEvaluator` as an example.

Further, backends and downstream projects are now able to override evaluator implementations by using the extensible class mechanism and simply defining a function in the `TreeEvaluator` class. For example in a hypothetical downstream project, one can do:

```
DownstreamProject::X86::TreeEvaluator::iaddEvaluator(TR::Node *node, TR::CodeGenerator *cg)
{
    // My custom iadd evaluator
}
```

Depends on eclipse/omr#5720

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#5720

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#5720

**Comment by fjeremic** [comment]
S390 failure is due to #12719.

**Comment by fjeremic** [comment]
@dsouzai / @0xdaryl this will require a coordinated merge from one of you.

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
