### PR TITLE
Add support for JFR ThreadStart/End events

### PR DESCRIPTION
**Pull request by gacholio**

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity wind jdk8

**Comment by tajila** [comment]
jenkins test sanity xlinux jdk17

**Comment by tajila** [comment]
jenkins test sanity win jdk8

**Comment by gacholio** [comment]
Line endings failure is infra.

**Comment by pshipton** [comment]
jenkins line endings check

**Comment by tajila** [comment]
```
09:34:46  runtime/oti/j9nonbuilder.h:380: trailing whitespace.
09:34:46  +	UDATA stackTraceSize;	
```

**Pull request merged**
