### PR TITLE
Print compilation thread shutdown message

### PR DESCRIPTION
**Pull request by singh264**
Closes: #421
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com

### CODE REVIEW

**Comment by singh264** [comment]
@mpirvu @ymanton I think this pull request is approved and could be merged.

**Comment by mpirvu** [comment]
@ymanton could you please approve this PR if you are satisfied with the current version?

**Review by ymanton — APPROVED** [review]
LGTM.

All of the tests have passed despite `Test_openjdk11_j9_sanity.functional_x86-64_mac_Personal` showing as still running.

**Comment by mpirvu** [comment]
Merging based on the above comment

**Pull request merged**
