### PR TITLE
Ensure inlined method classes are dependencies

### PR DESCRIPTION
**Pull request by cjjdespres**

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu. This does not seem to affect the failure rate much, if at all, because these classes will generally be mentioned in other relo records and so be captured as dependencies there. It's still good to make sure they're counted, I think.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity all jdk21

**Comment by mpirvu** [comment]
AIX compilation error:
```
16:06:08  /home/jenkins/workspace/Build_JDK21_ppc64_aix_Personal/openj9/runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp:254:118: error: too few arguments to function call, expected 5, have 4
16:06:08           acaRecord->setClassChainForInlinedMethod(reloTarget, classChainOffsetInSharedCache, self(), classChainRecord);
16:06:08           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                    ^
16:06:08  /home/jenkins/workspace/Build_JDK21_ppc64_aix_Personal/openj9/runtime/compiler/runtime/RelocationRecord.hpp:1811:7: note: 'setClassChainForInlinedMethod' declared here
16:06:08        void setClassChainForInlinedMethod(TR_RelocationTarget *reloTarget, uintptr_t classChainOffsetInSharedCache,
16:06:08        ^
```

**Comment by cjjdespres** [comment]
I'll fix that. I also see that I missed adding a dependency in `TR_RelocationRecordPointer::setClassChainForInlinedMethod`, which is distinct from `TR_RelocationRecordProfiledInlinedMethod::setClassChainForInlinedMethod`. That should be the last place.

I tested https://github.com/eclipse-openj9/openj9/pull/20770 with this change added to make sure the failures weren't a result of the lack of dependencies. I'll double-check that PR with this last dependency added.

**Comment by cjjdespres** [comment]
This should be fixed. Adding that last dependency did not seem to affect anything.

**Review by mpirvu — APPROVED** [review]

**Comment by mpirvu** [comment]
jenkins test sanity all jdk21

**Pull request merged**
