### PR TITLE
Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### PR DESCRIPTION
**Pull request by gacholio**
Testing no change PR build

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity.openjdk alinux64 jdk11

**Comment by pshipton** [comment]
We run these tests week nights, i.e. https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly/468/

You can also use a [Grinder](https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/) to test the latest, or a [Personal Build](https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/) to build and test.

**Comment by gacholio** [comment]
@pshipton We seemed to experience different behaviour in grinders and PR builds, perhaps just by bad luck, so I wanted to try exactly the same kind of build here.

**Comment by pshipton** [comment]
The test pipelines are the same no matter how you run them, as long as the SHAs are the same, the testing is the same. They may end up running on different machines, or bad luck as you say.

**Comment by pshipton** [comment]
> The test pipelines are the same no matter how you run them

Actually not quite true. A grinder won't automatically split a suite (like sanity.openjdk) into the same number of child jobs, you need to do that manually.

FYI we did recently split sanity.openjdk into 3 child jobs fairly recently, for PR/nightly/personal builds.
https://github.com/eclipse-openj9/openj9/pull/17698

**Pull request closed without merging**
