### PR TITLE
Add JFR flags

### PR DESCRIPTION
**Pull request by tajila**

### CODE REVIEW

**Review by JasonFengJ9 — APPROVED** [review]
It looks good.

Do we need a `JPP` flag for `JFR` though it could be added later if needed?

**Comment by tajila** [comment]
> Do we need a JPP flag for JFR though it could be added later if needed?

We may need it at some point. Not sure right now

**Comment by tajila** [comment]
@gacholio Please review/merge these changes

**Comment by gacholio** [comment]
jenkins compile zlinux jdk8

**Pull request merged**
