### PR TITLE
Remove TR_DebugExt

### PR DESCRIPTION
**Pull request by dsouzai**
See https://github.com/eclipse-openj9/openj9/issues/12520

### CODE REVIEW

**Comment by dsouzai** [comment]
@fjeremic do you mind being committer for this one?

**Comment by dsouzai** [comment]
```
17:24:25  The following files were modified and have incorrect copyrights
[Pipeline] echo
17:24:25  runtime/compiler/build/scripts/j9jit.aix.exp
[Pipeline] echo
17:24:25  runtime/compiler/build/scripts/j9jit.linux.debug.exp
[Pipeline] echo
17:24:25  runtime/compiler/build/scripts/j9jit.linux.exp
[Pipeline] echo
17:24:25  ###################################
```
These files never had a copyright header; not really sure what a comment looks like in these `.exp` files.

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
Failing jobs seem to be because the pipeline was cancelled :S

**Comment by pshipton** [comment]
I think too much PR testing for the farm to handle was started yesterday.

**Comment by dsouzai** [comment]
> @dsouzai just confirming this is not a breaking change? That is, I can merge this right now?

Yup, not a breaking change; OpenJ9 will break if the OMR PR is merged first though.

**Pull request merged**
