### PR TITLE
Re-organize TestUtilities

### PR DESCRIPTION
**Pull request by smlambert**
Related to https://github.com/eclipse-openj9/openj9/issues/14028
Signed-off-by: Shelley Lambert <slambert@gmail.com>

### CODE REVIEW

**Comment by smlambert** [comment]
FYI, the copyright check is complaining about the .project and .classpath files that I have included (for Eclipse IDE users presumably) because they are present for the TestUtilities directory already in the repository.

I can either remove those files (and pooch those using Eclipse IDE), or we ignore the copyright check in this case, thoughts?

**Comment by llxia** [comment]
One of the copyright failures is about build.xml. I think it needs to be updated to 2022. 
For .project and .classpath files, I do not have a strong preference. I am ok either way. 

```
23:30:43  The following files were modified and have incorrect copyrights
[Pipeline] echo
23:30:43  test/functional/Java8andUp/build.xml
[Pipeline] echo
23:30:43  test/functional/TestUtilitiesJ9/.classpath
[Pipeline] echo
23:30:43  test/functional/TestUtilitiesJ9/.project
```

**Comment by smlambert** [comment]
This is still a WIP, some failures to address...

| JDK_IMPL | JDK_VERSION | TARGET | PLATFORM | Grinder status | 
| ----- | ------- | --------- | -------- | -------- |
| openj9 | 8 | sanity.functional | x86-64_linux  | - | 
| openj9 | 11 | truncatedReturnTest | x86-64_mac | [fail](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2963/) - compilation failure in Java10AndUp  |
| hotspot | 8 | sanity.functional | x86-64_linux | [pass](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2960/) |
| hotspot | 11 | sanity.functional | x86-64_windows | [pass](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2962) |

**Comment by smlambert** [comment]
@llxia - thanks for your initial comments, this PR is now ready for review (and noting that without it, we have all functional test jobs failing in JDK17+ for hotspot builds).

**Review by pshipton — APPROVED** [review]

**Comment by llxia** [comment]
sanity.functional JDK11: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/502/
extended.functional JDK11: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/503/

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
