### PR TITLE
Prepare to use perform() API for TR_Liveness analysis

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@vijaysun-omr : I'd appreciate a review from you on this please.  This is a follow-on to eclipse/omr#6642.  It is essentially just calling the API to perform the liveness analysis.  All of the logic for performing liveness is still happening in the constructor but Kevin will change that shortly.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17

**Review by vijaysun-omr — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Jenkins test sanity win jdk17

Previous testing aborted.

**Comment by 0xdaryl** [comment]
Testing is complete and successful.  Would you mind merging @vijaysun-omr please?

**Pull request merged**
