### PR TITLE
Add OffHeap Query in J9VM

### PR DESCRIPTION
**Pull request by rmnattas**

### CODE REVIEW

**Comment by rmnattas** [comment]
Testing https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/23954/

**Comment by rmnattas** [comment]
@zl-wang

**Review by dsouzai — COMMENTED** [review]
You might need to add similar APIs to the JITServer Frontends.

**Comment by rmnattas** [comment]
Added the APIs for the JITServer part, is the change correct for it @dsouzai?
Most of the code queries the ObjectModel for OffHeap, this will be the case for all in the future but for the time being this query will remain to be used.

**Review by zl-wang — APPROVED** [review]
LGTM

**Comment by zl-wang** [comment]
jenkins test sanity aix,plinux,zlinux jdk21

**Comment by dsouzai** [comment]
I think you also need to update the `MINOR_NUMBER` in CommunicationStream.hpp whenever adding or modifying a Front End Query, but given that this is merged, maybe you can just open another PR for that.

**Pull request merged**
