### PR TITLE
Add @Hidden annotation to Continuation enter/yield methods

### PR DESCRIPTION
**Pull request by fengxue-IS**
Fixes: #18052

### CODE REVIEW

**Comment by babsingh** [comment]
jenkins test sanity,extended.openjdk zlinux jdk21

**Comment by fengxue-IS** [comment]
[Personal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/18122/) (Test failure due to missing test update commit
[Grinder on GetStackTrace](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/34783/)

**Comment by babsingh** [comment]
> https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/3/testReport/

- [GetStackTraceSuspendedStressTest](https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/3/testReport/serviceability_jvmti_stress_StackTrace_Suspended_GetStackTraceSuspendedStressTest/java/GetStackTraceSuspendedStressTest/) failure is a known issue: https://github.com/eclipse-openj9/openj9/issues/17871#issuecomment-1679167995.
- [DynamicLoadWarningTest](https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/3/testReport/com_sun_tools_attach_warnings_DynamicLoadWarningTest/java/DynamicLoadWarningTest/) failure seems unrelated to this PR but it is undocumented. We can merge this PR once an issue is opened to document this failure.

**Comment by fengxue-IS** [comment]
Opened https://github.com/eclipse-openj9/openj9/issues/18125 to track new failure

**Review by babsingh — APPROVED** [review]

**Pull request merged**
