### PR TITLE
(0.31.0) Replace forceUnresolvedDispatch() with isResolved*DispatchGuaranteed()

### PR DESCRIPTION
**Pull request by jdmpapin**
This is the v0.31.0-release PR corresponding to #14430. The commit to be merged here is the identical commit that was already merged into master as part of the original PR

### CODE REVIEW

**Review by dsouzai — APPROVED** [review]
SHAs of the commits are identical to the commits in https://github.com/eclipse-openj9/openj9/pull/14430

**Comment by dsouzai** [comment]
@0xdaryl @pshipton can this now be merged?

**Comment by 0xdaryl** [comment]
Let's wait one more day for things to settle.

**Comment by pshipton** [comment]
For jdk18 https://github.com/eclipse-openj9/openj9/issues/14465 was opened. Not sure if it's related, probably not. The failures aren't new, they've occurred for some time as seen in https://github.com/eclipse-openj9/openj9/issues/13946. We just didn't know if they would be fixed by this change or not.

In the head stream builds for jdk8, 11, 17, the following new issues were opened on the builds last night, both on AIX.
https://github.com/eclipse-openj9/openj9/issues/14469 jit_tr_0 testNOPing expected:<?> but was:<B>
https://github.com/eclipse-openj9/openj9/issues/14470 threadMXBeanTimedParkTest Blocked time is lower than expected

**Comment by 0xdaryl** [comment]
Is the concern with merging this that #14469 and #14470 might be regressions caused by it?  If so, @IBMJimmyk do you have any insight into those failures yet?  Could we revert this PR in a private build and grind these failing tests to confirm?

Given the number of failures this PR fixes then I don't want to keep it out of the builds for too much longer.

**Comment by 0xdaryl** [comment]
Agreed.  @dsouzai, please merge if you have no objections since this is assigned to you.

**Pull request merged**
