### PR TITLE
Tidy up m4 assembler source

### PR DESCRIPTION
**Pull request by keithc-ca**
* indent consistently (only with tabs)
* don't use tabs in other places

### CODE REVIEW

**Comment by keithc-ca** [comment]
Few changes other than whitespace: https://github.com/eclipse-openj9/openj9/pull/14708/files?w=1.

**Comment by gacholio** [comment]
I'm comfortable merging this without taking up any build/test resource.

**Comment by keithc-ca** [comment]
Wow, that was quick. Thanks, @gacholio.

**Comment by gacholio** [comment]
We aim to please :)

**Pull request merged**
