### PR TITLE
Support the new changes to the VirtualThread states

### PR DESCRIPTION
**Pull request by babsingh**
`RUNNABLE=2` state was removed, and all other states are re-numbered
due to the removal of the `RUNNABLE` state.

Two new states are added: `UNPARKED=9` and `YIELDED=11`.

Currently, `VirtualThread.yield` incorrectly consumes the parking
permit. The parking permit should only be consumed when continuing
from `VirtualThread.park`. The two new states are added to address
this incorrect behaviour.

Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/103

### CODE REVIEW

**Comment by babsingh** [comment]
This is to support the fix for https://bugs.openjdk.org/browse/JDK-8321270. The fix is currently in JDK22 and JDK23 (JDK-next). The fix will eventually be ported to JDK21 as per https://bugs.openjdk.org/browse/JDK-8321270.

**Commit title** -- `8321270: Virtual Thread.yield consumes parking permit`

This PR doesn't have ifdefs for JDK22+. So, this PR shouldn't be merged until the fix is ported to JDK21. 

https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/103 backports the fix to JDK21. To avoid any side-effects from **JDK-8321270**'s fix, the backport can wait until the 0.42 and 0.43 targets are released.

If **JDK-8321270**'s fix is ported by the RI to JDK21, then we can just merge this PR and close https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/103.

fyi @pshipton @tajila

**Review by hangshao0 — APPROVED** [review]
LGTM.

**Comment by hangshao0** [comment]
Jenkins test sanity.functional,sanity.openjdk aix jdk21 depends https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/103

**Comment by hangshao0** [comment]
> To avoid any side-effects from JDK-8321270's fix, the backport can wait until the 0.42 and 0.43 targets are released.

Does this really matter ? 0.42 and 0.43 have already branched.

**Comment by pshipton** [comment]
> Does this really matter ? 0.42 and 0.43 have already branched.

It does make it easier to merge 21.0.2 to 0.43, and any other fixes in the extensions for 0.42/0.43 (and we do need one). I won't merge it now. 

I've added it to the 0.43 milestone just in case JDK-8321270 shows up in 21.0.2.

**Comment by babsingh** [comment]
We should show caution with these changes. Before merging, we should also run the `extended.openjdk` test suite, which has the JVMTI tests, at least on two platforms (`aix` and `alinux`). This is to make sure that these changes have no side-effects (such as timeouts).

**Comment by hangshao0** [comment]
Jenkins test extended.openjdk aix jdk21 depends https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/103

**Comment by hangshao0** [comment]
Jenkins test extended.openjdk alinux jdk21 depends https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/103

**Comment by babsingh** [comment]
In the `extended.openjdk` builds, only known and unrelated failures are seen:
- https://github.com/eclipse-openj9/openj9/issues/18426
- https://github.com/eclipse-openj9/openj9/issues/18675 (might be related to https://github.com/eclipse-openj9/openj9/issues/18671 and https://bugs.openjdk.org/browse/JDK-8311218)
- https://github.com/eclipse-openj9/openj9/issues/14504
- https://github.com/eclipse-openj9/openj9/issues/18602
- https://github.com/eclipse-openj9/openj9/issues/14948

**Comment by hangshao0** [comment]
> I've added it to the 0.43 milestone just in case JDK-8321270 shows up in 21.0.2.

Does 21.0.2 have the JDK-8321270 fix ?

**Comment by hangshao0** [comment]
> Does 21.0.2 have the JDK-8321270 fix ?

I see this is moved to Release 0.44, so I guess the answer is no.

**Comment by babsingh** [comment]
> I see this is moved to Release 0.44, so I guess the answer is no.

Yes, @pshipton plans to merge it  in a few days after monitoring the new extension repo changes.

**Comment by hangshao0** [comment]
OK, I'll let Peter merge this.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
