### PR TITLE
Fix compilation error on Windows Value Type build

### LINKED ISSUE #13384: VT build fails to compile on Windows
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_windows_vt_standard_Personal/1/consoleFull

```
14:44:21  NativeHelpers.cpp
14:44:21  ObjectFieldInfo.cpp
14:44:22  [ 51%] Building CXX object runtime/vm/CMakeFiles/j9vm.dir/ObjectMonitor.cpp.obj
14:44:22  f:\users\jenkins\workspace\build_jdknext_x86-64_windows_vt_standard_personal\openj9\runtime\vm\ObjectFieldInfo.cpp(53): error C2220: the following warning is treated as an error
14:44:22  f:\users\jenkins\workspace\build_jdknext_x86-64_windows_vt_standard_personal\openj9\runtime\vm\ObjectFieldInfo.cpp(53): warning C4244: 'initializing': conversion from 'UDATA' to 'U_32', possible loss of data
14:44:22  f:\users\jenkins\workspace\build_jdknext_x86-64_windows_vt_standard_personal\openj9\runtime\vm\ObjectFieldInfo.cpp(77): warning C4319: '~': zero extending 'U_32' to 'UDATA' of greater size
14:44:22  make[6]: *** [runtime/vm/CMakeFiles/j9vm.dir/build.make:1618: runtime/vm/CMakeFiles/j9vm.dir/ObjectFieldInfo.cpp.obj] Error 2
14:44:22  make[6]: *** Waiting for unfinished jobs....
14:44:22  ObjectMonitor.cpp
```

### PR DESCRIPTION
**Pull request by hangshao0**
Closes #13384

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
@tajila

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity,extended winval jdknext

**Comment by tajila** [comment]
seeing `14:40:50  error: object directory /home/jenkins/openjdk_cache/objects does not exist; check .git/objects/info/alternates`

Not sure if thats the cause of the build failure 

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
I don't _think_ that is why we're seeing the compile fail. It seems to continue past that point fine.
I did see this which looks more promising
```
00:08:21.574  f:\users\jenkins\workspace\build_jdknext_x86-64_windows_valhalla_personal\openj9\runtime\vm\resolvefield.cpp(1113): error C2220: the following warning is treated as an error
00:08:21.574  f:\users\jenkins\workspace\build_jdknext_x86-64_windows_valhalla_personal\openj9\runtime\vm\resolvefield.cpp(1113): warning C4244: 'initializing': conversion from 'UDATA' to 'U_32', possible loss of data
00:08:21.574  f:\users\jenkins\workspace\build_jdknext_x86-64_windows_valhalla_personal\openj9\runtime\vm\resolvefield.cpp(1137): warning C4244: '=': conversion from 'UDATA' to 'U_32', possible loss of data
00:08:22.121  make[6]: *** [runtime/vm/CMakeFiles/j9vm.dir/build.make:1858: runtime/vm/CMakeFiles/j9vm.dir/resolvefield.cpp.obj] Error 2
00:08:22.121  make[6]: *** Waiting for unfinished jobs....
00:08:22.121  [ 49%] Building CXX object runtime/vm/CMakeFiles/j9vm.dir/resolvesupport.cpp.obj
00:08:22.121  [ 49%] Building CXX object runtime/compiler/CMakeFiles/j9jit.dir/env/annotations/TRNoSideFXAnnotation.cpp.obj
00:08:22.121  resolvesupport.cpp
00:08:22.121  Compiling 94 files for jdk.xml.dom
00:08:22.121  TRNoSideFXAnnotation.cpp
00:08:22.667  Compiling 14 files for jdk.zipfs
00:08:22.667  make[5]: *** [CMakeFiles/Makefile2:10580: runtime/vm/CMakeFiles/j9vm.dir/all] Error 2
00:08:22.667  make[5]: *** Waiting for unfinished jobs....
```

**Comment by hangshao0** [comment]
Change updated to fix the errors in https://github.com/eclipse-openj9/openj9/pull/13415#issuecomment-931638160

**Comment by tajila** [comment]
Jenkins test sanity,extended winval jdknext

**Comment by hangshao0** [comment]
The compilation passed. There is class path issue in the extended test:

```
Testing: Create core file
Test start time: 2021/10/01 07:47:57 Central Standard Time
Running command: "F:/Users/jenkins/workspace/Test_openjdkValhalla_j9_extended.functional_x86-64_windows_valhalla_Personal_testList_1/openjdkbinary/j2sdk-image\\bin\\java"   -Xmx24m -Xint -Xverify:none --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -cp F:/Users/jenkins/workspace/Test_openjdkValhalla_j9_extended.functional_x86-64_windows_valhalla_Personal_testList_1/aqa-tests///..//jvmtest\TKG\lib\asm-all.jar:F:/Users/jenkins/workspace/Test_openjdkValhalla_j9_extended.functional_x86-64_windows_valhalla_Personal_testList_1/aqa-tests///..//jvmtest\TKG\lib\jcommander.jar:F:/Users/jenkins/workspace/Test_openjdkValhalla_j9_extended.functional_x86-64_windows_valhalla_Personal_testList_1/aqa-tests///..//jvmtest\TKG\lib\testng.jar:F:/Users/jenkins/workspace/Test_openjdkValhalla_j9_extended.functional_x86-64_windows_valhalla_Personal_testList_1/aqa-tests///..//jvmtest\functional\Valhalla\ValhallaTests.jar org.openj9.test.lworld.DDRValueTypeTest
Time spent starting: 16 milliseconds
Time spent executing: 235 milliseconds
Test result: FAILED
 [ERR] JVMJ9VM193W Since Java 13 -Xverify:none and -noverify were deprecated for removal and may not be accepted options in the future.
 [ERR] Error: Could not find or load main class org.openj9.test.lworld.DDRValueTypeTest
 [ERR] Caused by: java.lang.ClassNotFoundException: org.openj9.test.lworld.DDRValueTypeTest
```

I will open another issue to track the the class path problem here. This PR is to fix the compilation error.

**Comment by hangshao0** [comment]
> I will open another issue to track the the class path problem here

https://github.com/eclipse-openj9/openj9/issues/13612

**Pull request merged**
