### PR TITLE
Avoid shared lambda form statics name comparison

### PR DESCRIPTION
**Pull request by cjjdespres**
When lambda form sharing is enabled, distinct lambda forms can end up with identical names and signatures, since that option causes the non-deterministic address suffix in their name to be replaced with a NULL address. Thus, the existing name comparison in TR_ResolvedJ9JITServerMethod::staticsAreSame() could cause distinct lambda forms to be identified together inappropriately, leading to crashes in remotely-compiled code. The new code instead always treats two lambda forms with identical names as being distinct, relying on the existing fallback in TR_J9ServerVM::jitStaticsAreSame() to ensure that equal lambda forms are correctly identified as such.

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit,alinux64jit jdk21

**Comment by mpirvu** [comment]
xlinux sanity.functional:  floatSanityTests_1 crash
xlinux openjdk: Many VectorAPI failures but also jdk_util_0 timeout
aarch64 openjdk: many VectorAPI failures. Known issue
plinux openjdk: many VectorAPI failures. Known issue
zlinux openjdk: many VectorAPI failures. Known issue

**Comment by mpirvu** [comment]
10x grinder for the floatSanityTests: https://openj9-jenkins.osuosl.org/job/Grinder/4035/

**Comment by mpirvu** [comment]
The grinder passed and I don't have reasons to believe the problem was introduced by this PR.

**Pull request merged**
