### PR TITLE
Use exclusive access correctly in getThreads

### PR DESCRIPTION
**Pull request by gacholio**
Fixes: #15917

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
@gacholio What was the actually issue with the original acquireExclusive placement?

**Comment by gacholio** [comment]
Objects were allocated (directly and via exception throw) while holding exclusive. This has always been illegal. Explicit calls to the GC are legal while holding exclusive, but allocation is not.

**Comment by gacholio** [comment]
I only moved the acquire to avoid having to release before throwing the first OOM. Moving the release was the key to the fix here.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
jenkins test sanity amac jdk19

**Comment by pshipton** [comment]
Are these rules written down anywhere?

**Comment by gacholio** [comment]
> Are these rules written down anywhere?

I laugh in your general direction.

**Pull request merged**
