### PR TITLE
Replace writeLine usage with writeLineLocked

### PR DESCRIPTION
**Pull request by cjjdespres**
A `TR_VerboseLog::CriticalSection` is not acquired by this point in the function, so this log line should be writeLineLocked and not writeLine.

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu. I saw a couple of vlogs with lines that got merged together, and I think this is the cause.

**Review by mpirvu — COMMENTED** [review]
There are other lines in this file that suffer from the same problem. Could you please fix them all?

**Comment by cjjdespres** [comment]
So there are. Fixed.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity zlinux jdk21

**Pull request merged**
