### PR TITLE
Port ASGCT to PPC64

### PR DESCRIPTION
**Pull request by tajila**

### CODE REVIEW

**Comment by tajila** [comment]
jenkins compile plinux jdk8

**Comment by tajila** [comment]
jenkins compile plinux jdk8

**Comment by tajila** [comment]
jenkins compile plinux jdk8

**Comment by tajila** [comment]
@gacholio Please review these changes

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins test sanity xlinux,plinux jdk21

**Comment by gacholio** [comment]
Failure on P is clearly unrelated to this change.

**Pull request merged**
