### PR TITLE
Check if instanceDescription is an immediate value in loop

### PR DESCRIPTION
**Pull request by a7ehuo**
There is a case where the number of object slots are greater than the number of bits in a word and `instanceDescription` is used as an immediate value instead of a pointer, such as when the class doesn't have any references. We need to break the loop in this case before `instanceDescription` is dereferenced as a pointer.

This fixes `openj9-jit-xopt/issues/529`

Thanks to Henry @hzongaro for tracking down the issue to hasReferneces change https://github.com/eclipse-openj9/openj9/pull/10651

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by hzongaro** [comment]
As I discussed this change with Annabelle @a7ehuo as she was writing it, I probably shouldn't be the only reviewer.  Nazim @nbhuiyan and Tobi @tajila, may I ask you to review this change?

**Comment by hzongaro** [comment]
Brad @BradleyWood, may I ask you to review this pull request as well?

**Review by tajila — APPROVED** [review]

**Comment by BradleyWood** [comment]
LGTM

**Comment by hzongaro** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by hzongaro** [comment]
Jenkins test sanity all jdk17

**Pull request merged**
