### PR TITLE
AArch64 macOS: Enable DDR build

### PR DESCRIPTION
**Pull request by knn-k**
This commit enables DDR of AArch64 macOS builds.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
jenkins test sanity amac jdk17

**Comment by knn-k** [comment]
jenkins test sanity.system amac jdk17

**Comment by knn-k** [comment]
jenkins test sanity.functional,sanity.system amac jdk18

**Comment by knn-k** [comment]
jenkins test extended.system amac jdk17

**Comment by knn-k** [comment]
jenkins test extended.system amac jdk17

**Comment by knn-k** [comment]
jenkins compile amac jdk11

**Comment by knn-k** [comment]
jenkins test extended.system amac jdk18

**Comment by knn-k** [comment]
jenkins test special.system amac jdk18

**Comment by knn-k** [comment]
This PR depends on https://github.com/eclipse/omr/pull/6471 and #14921.

**Comment by knn-k** [comment]
jenkins compile amac jdk11

**Comment by knn-k** [comment]
jenkins compile amac jdk11

**Comment by knn-k** [comment]
Segmentation faults in `dwarfdump-classic` and `omr_ddrgen`.  I cannot reproduce this locally.

```
[2022-04-19T05:51:56.511Z] sh: line 1: 49005 Segmentation fault: 11  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dwarfdump-classic /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9ddr_misc29.dylib.dSYM/Contents/Resources/DWARF/libj9ddr_misc29.dylib 2>&1
[2022-04-19T05:51:56.512Z] /bin/sh: line 1: 48983 Segmentation fault: 11  /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/omr_ddrgen /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9ddr_misc29.dylib.dSYM/Contents/Resources/DWARF/libj9ddr_misc29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9gc29.dylib.dSYM/Contents/Resources/DWARF/libj9gc29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libjclse29.dylib.dSYM/Contents/Resources/DWARF/libjclse29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9jvmti29.dylib.dSYM/Contents/Resources/DWARF/libj9jvmti29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9prt29.dylib.dSYM/Contents/Resources/DWARF/libj9prt29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9trc29.dylib.dSYM/Contents/Resources/DWARF/libj9trc29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9shr29.dylib.dSYM/Contents/Resources/DWARF/libj9shr29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9thr29.dylib.dSYM/Contents/Resources/DWARF/libj9thr29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9vrb29.dylib.dSYM/Contents/Resources/DWARF/libj9vrb29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libj9vm29.dylib.dSYM/Contents/Resources/DWARF/libj9vm29.dylib /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/libomrsig.dylib.dSYM/Contents/Resources/DWARF/libomrsig.dylib --show-empty --macrolist /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/ddr_info/sets/j9ddr.macros --excludes /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/openj9/runtime/ddr/excludes --blob /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/j9ddr.dat --superset /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/superset.dat --overrides /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/openj9/runtime/ddr/overrides
[2022-04-19T05:51:56.512Z] make[10]: *** [/Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/build/macosx-aarch64-normal-server-release/vm/runtime/j9ddr.dat] Error 139
```

**Comment by knn-k** [comment]
PRs #14376 and #14427 disabled DDR tests on AArch64 macOS, and this PR enables them back.

**Comment by knn-k** [comment]
jenkins compile amac jdk17

**Comment by knn-k** [comment]
I opened an issue for the build failure: https://github.com/eclipse/omr/issues/6491

**Comment by knn-k** [comment]
jenkins compile amac,xmac jdk17 depends eclipse/omr#5800

**Comment by knn-k** [comment]
I separated the changes for enabling DDR tests to PR #14961.

**Comment by knn-k** [comment]
jenkins compile amac,xmac jdk17 depends eclipse/omr#5800

**Comment by knn-k** [comment]
jenkins test extended.functional xmac jdk17 depends eclipse/omr#5800

**Comment by knn-k** [comment]
jenkins test sanity amac jdk11 depends eclipse/omr#5800

**Comment by keithc-ca** [comment]
jenkins test sanity osx jdk8,jdk11 depends eclipse/omr#6527

**Comment by knn-k** [comment]
jenkins test sanity amac jdk11 depends https://github.com/eclipse/omr/pull/6527

**Comment by pshipton** [comment]
The OMR changes are merged and promoted now.

jenkins test sanity amac jdk11

**Comment by pshipton** [comment]
We should unexclude the ddr tests as part of this PR to enabled DDR.

**Comment by pshipton** [comment]
I see re-enabling the tests was moved to https://github.com/eclipse-openj9/openj9/pull/14961, but that means it's not easily PR tested to enable DDR and run the tests to ensure they are working.

**Comment by pshipton** [comment]
jenkins compile amac jdk17,jdk18,jdknext

**Comment by knn-k** [comment]
jenkins test sanity.functional,extended.functional amac jdk11

I moved the changes from PR #14961 back to this PR.

**Comment by knn-k** [comment]
You can see the DDR tests in sanity.functional and extended.functional finished successfully.

- https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_mac_Personal/45/
- https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_aarch64_mac_Personal/10/

https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/64 needs to be merged for enabling DDR builds in internal builds.

**Comment by knn-k** [comment]
jenkins test sanity amac jdk11

I enabled one more test back, cmdLineTester_GCCheck, which I had overlooked in #14961.  The test uses jdmpview.

**Review by pshipton — APPROVED** [review]

**Comment by knn-k** [comment]
How about enabling DDR on AArch64 macOS with v0.33.0?

**Comment by 0xdaryl** [comment]
> How about enabling DDR on AArch64 macOS with v0.33.0?

What dependent PRs need to be merged into 0.33 since the release split?

**Comment by knn-k** [comment]
Only the following PRs after the 0.33 split are required:
- https://github.com/eclipse/omr/pull/5800 (DwarfParser.cpp)
- https://github.com/eclipse/omr/pull/6527 (DwarfParser.cpp)
- This PR (configure option and testcases)

**Comment by knn-k** [comment]
I opened the following PRs for 0.33.
- https://github.com/eclipse-openj9/openj9-omr/pull/144
- #15147

**Pull request merged**
