### PR TITLE
Fix inconsistency between J9Class and annotation data when redefine (take 2)

### PR DESCRIPTION
**Pull request by EricYangIBM**
This reverts commit 06ae571.
Fixes a cast causing failures on 32 bit systems.

Closes: #10026
Signed-off-by: Eric Yang eric.yang@ibm.com

### CODE REVIEW

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity plinux jdk11,17

**Comment by keithc-ca** [comment]
Jenkins test sanity win32 jdk8

**Comment by keithc-ca** [comment]
Jenkins test sanity plinux jdk17

('17' is not a version understood by jenkins)

**Comment by keithc-ca** [comment]
Jenkins test sanity plinux jdk11

(It seems jdk11 was skipped because jenkins didn't understand '17')

**Comment by tajila** [comment]
thanks @keithc-ca that was a typo

**Comment by tajila** [comment]
Seems like a network issue is causing the jdk17 test failure

```
18:28:21  git clone --depth 1 -b master https://github.com/eclipse-openj9/openj9.git
18:28:42  fatal: unable to access 'https://github.com/eclipse-openj9/openj9.git/': gnutls_handshake() failed: Error in the pull function.
```

**Comment by tajila** [comment]
Jenkins test sanity plinux jdk17

**Comment by EricYangIBM** [comment]
New test failure: https://github.com/eclipse-openj9/openj9/issues/14066

**Comment by EricYangIBM** [comment]
Could it be due to reverting the PR?

**Comment by pshipton** [comment]
Maybe something is inconsistent in the internal builds? There wasn't any problem in the open nightly builds.

**Comment by EricYangIBM** [comment]
The PR was merged 24 hours ago, reverted 21 hours ago but the tests were run 1d 2h ago

**Comment by tajila** [comment]
I think there may have been a mismatch between the JDK and the test source.

It says:

```
[2021-12-02T15:48:45.330Z] ---SUMMARY OF FAILED TESTS---
[2021-12-02T15:48:45.330Z] rc021
```

So it definitely picked up the new test that you added.

But 

```

[2021-12-02T15:14:28.437Z]  [ERR] 	Error: 103   JVMTI_ERROR_ILLEGAL_ARGUMENT
[2021-12-02T15:14:28.437Z]  [ERR] 		Unknown testcase: [rc021]
[2021-12-02T15:14:28.437Z]  [ERR] 
[2021-12-02T15:14:28.437Z]  [ERR] 		Location: null -> [null():0]
```

Seems to imply that the jvmtitest lib doesnt have the latest changes

**Comment by EricYangIBM** [comment]
Running zos tests again: https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/30183/

**Comment by yaohwu** [comment]
🎉

**Pull request merged**
