### PR TITLE
Remove NULL appendix in linkToStaticSpecial call

### PR DESCRIPTION
**Pull request by fengxue-IS**
Replaces: #12522
Depends: #13388

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
This change requires JIT changes to handle special case of `-Xjit:rtResolve` @nbhuiyan

**Review by tajila — APPROVED** [review]

**Review by babsingh — APPROVED** [review]
LGTM. The commits need to be squashed.

**Comment by fengxue-IS** [comment]
Update comments, squashed commits, compile passed.
@tajila can you please run the PR testing

**Comment by tajila** [comment]
Jenkins test sanity,extended plinux jdk17

**Comment by tajila** [comment]
@fengxue-IS  can you prepare another PR for the 0.28 stream

**Pull request merged**
