### PR TITLE
[FFI/Jtreg_JDK20] Keep the downcall address alive for downcall

### PR DESCRIPTION
**Pull request by ChengJin01**
The changes aim to prevent the downcall address from being
released unexpectedly by leveraging the existing code to
hold the downcall address during the downcall.

Fixes: #17524

Signed-off-by: ChengJin01 <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
The idea of the PR (built on top of  is to hold the downcall address by performing `acquire/release` in OpenJDK when the corresponding scope is still alive, in which case `Arena.close()` in the process of downcall will end up with [IllegalStateException](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/foreign/Arena.html#close()) as expected.

**Comment by ChengJin01** [comment]
The changes are verified in OpenJ9 FFI test suites  & Jtreg test suites in JDK17 & 20.

Reviewer:  @pshipton
FYI: @tajila

**Comment by ChengJin01** [comment]
Launched Grinders x50 at https://openj9-jenkins.osuosl.org/job/Grinder/2489/ with the compiled build at https://openj9-jenkins.osuosl.org/job/Build_JDKnext_s390x_linux_Personal/90/ to see how it goes with the changes.

**Comment by pshipton** [comment]
5x x 5 https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2495/

**Comment by pshipton** [comment]
Seems https://openj9-jenkins.osuosl.org/job/Grinder/2492 has passed, although it's still archiving results.

@ChengJin01 pls create PRs for 0.39 and 0.40.

**Comment by ChengJin01** [comment]
> @ChengJin01 pls create PRs for 0.39 and 0.40.

PRs are created at https://github.com/eclipse-openj9/openj9/pull/17563 (0.39) and https://github.com/eclipse-openj9/openj9/pull/17565 (0.40).

**Pull request merged**
