### PR TITLE
AArch64: Add JITServer spec to Jenkins pipeline

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds alinux64jit to Jenkins pipeline.

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins test sanity.functional alinux64jit jdk8,jdk11,jdk17

**Comment by knn-k** [comment]
Jenkins test sanity.system alinux64jit jdk8,jdk11,jdk17

**Comment by knn-k** [comment]
The pipelines work, and I think this PR can be merged now.
There are failures with `jit_jitt_array_compress_3`, and I am addressing it in #17929.

**Review by ymanton — APPROVED** [review]
LGTM. Will merge shortly if there are no further comments.

**Review by mpirvu — APPROVED** [review]
LGTM but I would like a review from @AdamBrousseau as well because I am not very familiar with the jenkins infra.

**Review by AdamBrousseau — APPROVED** [review]

**Pull request merged**
