### PR TITLE
Allow verifier to run in valuetype tests

### PR DESCRIPTION
**Pull request by ehrenjulzert**
For issue #14741

- Fix bugs in ValueTypeGenerator.java/ValueTypeTests.java
- Enable verification when running valuetype tests

Signed-off-by: Ehren Julien-Neitzert <ehren.julien-neitzert@ibm.com>

### CODE REVIEW

**Comment by ehrenjulzert** [comment]
@hangshao0

**Review by hangshao0 — APPROVED** [review]
LGTM

**Comment by hangshao0** [comment]
Can https://github.com/eclipse-openj9/openj9/issues/14741 be closed after this is merged ?

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity,extended plinuxval jdknext

**Pull request merged**
