### PR TITLE
Add tracepoints to decompilation paths

### PR DESCRIPTION
**Pull request by tajila**
Add tracepoints to decompilation paths

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
I'd like to make these level1 but I worried about the potential overhead. Also, I'm not sure how frequently some of these paths are taken. My assumption is that OSR should be infrequent. What are your thoughts @DanHeidinga @0xdaryl @jdmpapin

**Comment by pshipton** [comment]
Reminder that level 1 is only for tracepoints that need to be active during startup. Level 2 is active after the startup phase is complete.

**Comment by tajila** [comment]
> Reminder that level 1 is only for tracepoints that need to be active during startup. Level 2 is active after the startup phase is complete.

Okay, level2 is more appropriate then

**Review by DanHeidinga — APPROVED** [review]
lgtm

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux jdk17

**Pull request merged**
