### PR TITLE
Revert "Stop recognizing UTF16_Encoder.encodeUTF16 methods"

### PR DESCRIPTION
**Pull request by knn-k**
This commit restores the changes for encodeUTF16Big and encodeUTF16Little that were removed by #20613.

### CODE REVIEW

**Comment by knn-k** [comment]
I split the changes in the OMR side into two PRs to avoid coordinated merge.

**Comment by knn-k** [comment]
No need for coordinated merge:
- Merge https://github.com/eclipse-omr/omr/pull/7577 first
- Merge this PR after the OMR PR above promotes
- Finally merge https://github.com/eclipse-omr/omr/pull/7578

I changed the enum symbols `sun_nio_cs_UTF_16_Encoder_encodeUTF16Big` and `sun_nio_cs_UTF_16_Encoder_encodeUTF16Little` to `sun_nio_cs_UTF16_Encoder_encodeUTF16Big` and `sun_nio_cs_UTF16_Encoder_encodeUTF16Little` by removing the `_` between `UTF` and `16` in this PR to avoid confusion, because the class name is `sun/nio/cs/UTF16_Encoder`.

**Comment by knn-k** [comment]
The test failure on xlinux Java 8 is a known issue: #18599

**Comment by knn-k** [comment]
Jenkins test sanity plinux,xlinux,zlinux jdk8 depends https://github.com/eclipse-omr/omr/pull/7578

**Comment by knn-k** [comment]
Jenkins test sanity plinux,xlinux,zlinux jdk11 depends https://github.com/eclipse-omr/omr/pull/7578

**Comment by knn-k** [comment]
Some failures with JITServerTest using Java 11 on plinux: https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_0/366/

**Comment by hzongaro** [comment]
JITServerTest failure in JDK 11 plinux testing should be fixed by pull request #20757

**Comment by pshipton** [comment]
I've promoted OMR.

**Comment by hzongaro** [comment]
It looks like pull request eclipse-omr/omr#7577 has been merged, so you should be able to move this pull request to "Ready for review" status.

**Review by hzongaro — APPROVED** [review]
I think the changes look good.  Thanks!

**Comment by hzongaro** [comment]
Testing with both eclipse-omr/omr#7577 and eclipse-omr/omr#7578 only failed due to known issues.  Merging.

**Pull request merged**
