### PR TITLE
Use --with-openssl=fetched on Windows

### PR DESCRIPTION
**Pull request by keithc-ca**
Issue: #14302:
* update build variables
* update build instructions

### CODE REVIEW

**Comment by keithc-ca** [comment]
jenkins compile win32 jdk8 depends ibmruntimes/openj9-openjdk-jdk8#543

**Comment by keithc-ca** [comment]
jenkins compile win,win32 jdk8 depends ibmruntimes/openj9-openjdk-jdk8#543

**Comment by keithc-ca** [comment]
jenkins compile win jdk11 depends ibmruntimes/openj9-openjdk-jdk11#471

**Comment by keithc-ca** [comment]
jenkins compile win jdk17 depends ibmruntimes/openj9-openjdk-jdk17#61

**Comment by keithc-ca** [comment]
jenkins compile win jdk18 depends ibmruntimes/openj9-openjdk-jdk18#9

**Comment by keithc-ca** [comment]
jenkins compile win jdk19 depends ibmruntimes/openj9-openjdk-jdk19#395

**Comment by keithc-ca** [comment]
jenkins compile win jdk19 depends ibmruntimes/openj9-openjdk-jdknext#395

**Comment by keithc-ca** [comment]
jenkins compile win jdknext depends ibmruntimes/openj9-openjdk-jdk#395

**Comment by pshipton** [comment]
jenkins compile all jdk8 depends ibmruntimes/openj9-openjdk-jdk8#543

**Comment by pshipton** [comment]
jenkins compile all jdk11 depends ibmruntimes/openj9-openjdk-jdk11#471

**Comment by pshipton** [comment]
jenkins compile all jdk17 depends ibmruntimes/openj9-openjdk-jdk17#61

**Comment by pshipton** [comment]
There are problems on other platforms.

**Comment by keithc-ca** [comment]
jenkins compile all jdk8 depends ibmruntimes/openj9-openjdk-jdk8#543

**Comment by pshipton** [comment]
jenkins compile all jdk11 depends ibmruntimes/openj9-openjdk-jdk11#471

**Comment by pshipton** [comment]
jenkins compile all jdk17 depends ibmruntimes/openj9-openjdk-jdk17#61

**Comment by keithc-ca** [comment]
jenkins compile aix jdk11 depends ibmruntimes/openj9-openjdk-jdk11#471

**Comment by pshipton** [comment]
@jdekonin the AIX build that failed happened on p8-java1-ibm03. Maybe these machines aren't as ready to go as we hoped. Or maybe they are just faster and expose a timing hole. The failure isn't new, we see it occasionally, but not very often.
https://openj9-jenkins.osuosl.org/job/Build_JDK11_ppc64_aix_Personal/216/

**Comment by pshipton** [comment]
The new build is running on the same machine, we'll see if it works.
https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/1466/

Either way, it's not an issue with this PR.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
