### PR TITLE
Stop using unsafe sprintf() in InterpreterEmulator

### PR DESCRIPTION
**Pull request by jdmpapin**
In particular, in the debug tracing. The much safer `snprintf()` is now used instead, though with the usual caveat that only `_snprintf()` (with the underscore) is available in older versions of MSVC.

The implementations of `Operand::printToString()` are moved into InterpreterEmulator.cpp to avoid putting `#define snprintf ...` into a header file.

A wrapper is added that checks the result and prints a warning to the log when truncation is detected. It also ensures NUL-termination in case we are using `_snprintf()`.

Call sites are updated to call the wrapper instead of calling the method directly, and to use a larger buffer size. The old sizes were either barely large enough (50), or definitely too small (20). The new size is defined as a constant `OPERAND_STR_BUF_SIZE` to keep all of the call sites in sync.

----

There are a few additional minor cleanup commits.

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8

**Comment by jdmpapin** [comment]
There was a crash in `j9vm.test.arraycopy.MultiThreadedBackwardArrayCopyTest` on Mac (x86). I'm not sure how to tell whether it's related to the changes here

**Comment by 0xdaryl** [comment]
Not likely.  It crashed on macOS during arraycopy with the direction flag set, so most likely a dup of #9782.

**Comment by 0xdaryl** [comment]
Minor nit: can you fit the spelling of "InterpreterEmulator" in the PR title and the commit title for 148db55351605cf48ae7adc21d0e4f3a01383e41 ?

**Comment by 0xdaryl** [comment]
For the record, CI testing passed successfully.  No need to re-run once the commit metadata is updated.

**Comment by jdmpapin** [comment]
OK, I've fixed the spelling. The force-push diff is empty

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
