### PR TITLE
Update jdmpview !coreinfo to print vm properties

### PR DESCRIPTION
**Pull request by pshipton**
and also sort the environment variables.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity alinux64 jdk11

**Comment by pshipton** [comment]
I'm tempted to put spaces around the `=` to make the output easier to read. The environment variables don't have spaces, but that is consistent with `env` output

**Comment by keithc-ca** [comment]
> I'm tempted to put spaces around the `=` to make the output easier to read. The environment variables don't have spaces, but that is consistent with `env` output

If you're going to tweak the output, I'd also suggest a little indentation (e.g. two spaces) before each system property name or environment variable name. That would be consistent with the introduction headers for those groups, and consistent with the presentation in `-XshowSettings:properties` output.

**Comment by keithc-ca** [comment]
Jenkins test sanity,extended alinux64 jdk17

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
