### PR TITLE
JFR CMake adds jfr.cpp

### PR DESCRIPTION
**Pull request by JasonFengJ9**
`JFR` `CMake` adds `jfr.cpp`

closes https://github.com/eclipse-openj9/openj9/issues/19431

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity xlinux jdknext

**Comment by tajila** [comment]
jenkins test sanity xlinux jdknext

**Comment by keithc-ca** [comment]
On the contrary, I think we should ifdef declarations (so an inappropriate reference yields a compile error (earlier) rather than a link error) and should avoid effectively empty compilation units.

**Review by keithc-ca — APPROVED** [review]

**Comment by JasonFengJ9** [comment]
```
12:44:45  Attempting retry #1
12:44:45  [consumer_0] An exception occurred during execution:
12:44:45  java.lang.RuntimeException: java.net.NoRouteToHostException: No route to host (Host unreachable)
12:44:45  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
12:44:45  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
12:44:45  	at java.base/java.lang.Thread.run(Thread.java:840)
12:44:45  Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
12:44:45  	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
```

The build succeeded but failed with `NoRouteToHostException` afterwards.

**Comment by pshipton** [comment]
That is because the artifactory server at UNB is down, building on plinux, xlinux, amac, xmac is not supported atm.

**Comment by pshipton** [comment]
We may have limited xlinux and mac support after https://github.com/eclipse-openj9/openj9/pull/19425 is merged. There is a risk jenkins will crash if we run too much testing, we'll have to see how it goes.

**Pull request merged**
