### PR TITLE
Clear vmthread from thread object at shutdown

### PR DESCRIPTION
**Pull request by tajila**
Related to: https://github.com/eclipse-openj9/openj9/issues/16659

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk21

**Comment by tajila** [comment]
will investigate the jitserver failures

**Comment by gacholio** [comment]
This is already done in the java code that runs when a thread ends.

**Comment by tajila** [comment]
> This is already done in the java code that runs when a thread ends.

If there is an exception in that code then the threadref is not guaranteed to be cleared. I thought about updating that code and putting ` eetop = Thread.NO_REF;` in a finally block, however, with Java code its always possible that someone can modify it such that the threadref is not cleared. So I figure the safest thing is to do it natively.

**Comment by gacholio** [comment]
The java code holds a lock while setting it (not sure if that actually does anything), so the native code is not quite the same.

I would say anyone modifying Thread internals in way that avoids the finally block gets what they deserve, so I think the java solution would be better (especially considering the native code has introduced failures).

**Comment by tajila** [comment]
Replaced with https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/679

**Pull request closed without merging**
