### PR TITLE
Add custom_openj9_repo false in runAqaConfig file

### PR DESCRIPTION
**Pull request by renfeiw**
[ci skip]

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewers: @llxia @sophia-guo

**Review by sophia-guo — APPROVED** [review]

**Comment by llxia** [comment]
Approve this PR. But I think we need to investigate why we need to have runAqaConfig file in each repo.

**Review by llxia — APPROVED** [review]

**Comment by renfeiw** [comment]
> Approve this PR. But I think we need to investigate why we need to have runAqaConfig file in each repo.

Agreed, do you know why did we need this file in the adopt repo? @sophia-guo

**Comment by sophia-guo** [comment]
The reason is to avoid duplicate runAqaArgParse.py in all repos.   https://github.com/adoptium/aqa-tests/pull/2465

**Comment by llxia** [comment]
Why do we need to have runAqaConfig.json in each repo to define what custom repo can or cannot be set? We should allow all custom repos to be set by the users. In runAqaArgParse.py, if users set custom repos, then use them. Otherwise, use the default values.

**Pull request merged**
