### PR TITLE
Disable safe point OSR if sampled object allocate hook is used

### PR DESCRIPTION
**Pull request by gacholio**
Use of the `can_generate_sampled_object_alloc_events` JVMTI capability must disable safe point OSR because the event would be sent when not at an OSR safe point, leading to assertions or hangs.

Fixes: #16480

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk19

**Comment by tajila** [comment]
FYI @vijaysun-omr @0xdaryl

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
jenkins test sanity win jdk8

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk19

**Comment by vijaysun-omr** [comment]
What does "safe point OSR" mean exactly ? From the JIT perspective we are either in "voluntary OSR" mode (the default when HCR is enabled, i.e. our current default) or "involuntary OSR" mode (e.g. used when debug is enabled). Are we saying that this change will put us into involuntary OSR mode (where previously we would have been in voluntary OSR mode) if the relevant allocate hook mentioned earlier is used, or does it mean something else ?

**Comment by gacholio** [comment]
The safe point optimization means we can not OSR at an object allocation point - it has nothing to do with voluntary or not. I gather it was a savings on OSR code / metadata.

**Comment by vijaysun-omr** [comment]
Having fewer program points where OSR is allowed is indeed a savings in code/metadata size and also better in terms of JIT code quality (leads to better throughput). I think I agree that having allocations be (additional) OSR points probably won't result in much performance degradation and so can be done if we need to for that JVMTI capability. I hope that the JIT is set up to check for changes in what is or isn't an OSR point, i.e. that there won't be any functional concerns @hzongaro

**Comment by gacholio** [comment]
There's a command line option to disable this already, but we don't run any testing with it, so it's possible that errors might creep into that path.

**Comment by gacholio** [comment]
Can this be merged?

**Pull request merged**
