### PR TITLE
[WIP] Fix and disable cmdLineTester_pltest_aix_0

### PR DESCRIPTION
**Pull request by singh264**
Closes: #12706
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile aix jdk8

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
jenkins compile aix,plinux jdk8 depends eclipse/omr#master

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/6085/
https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/6086/

**Comment by pshipton** [comment]
AIX result with this PR and without the OMR change
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1819/console
```
21:14:55   [ERR] 1: j9vmem_testFindValidPageSize(64K large page size)
21:14:55   [ERR] 	/home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x10000, pageFlags: 0x1, but found pageSize: 0x1000, pageFlags: 0x1
21:14:55   [ERR] 
21:14:55   [ERR] 		LastErrorNumber: -108
21:14:55   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
21:14:55   [ERR] 
21:14:55   [ERR] 2: j9vmem_testFindValidPageSize(64K and 16M large page size)
21:14:55   [ERR] 	/home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x10000, pageFlags: 0x1, but found pageSize: 0x1000, pageFlags: 0x1
21:14:55   [ERR] 
21:14:55   [ERR] 		LastErrorNumber: -108
21:14:55   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
21:14:55   [ERR] 
21:14:55   [ERR] 3: j9vmem_testFindValidPageSize(all possible page sizes)
21:14:55   [ERR] 	/home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x10000, pageFlags: 0x1, but found pageSize: 0x1000, pageFlags: 0x1
21:14:55   [ERR] 
21:14:55   [ERR] 		LastErrorNumber: -108
21:14:55   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
```

**Comment by pshipton** [comment]
With this PR and with the OMR change
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1820/console
```
22:11:04   [ERR] 1: j9vmem_testFindValidPageSize(64K large page size)
22:11:04   [ERR] 	/home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x10000, pageFlags: 0x1, but found pageSize: 0x1000, pageFlags: 0x1
22:11:04   [ERR] 
22:11:04   [ERR] 		LastErrorNumber: -108
22:11:04   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
22:11:04   [ERR] 
22:11:04   [ERR] 2: j9vmem_testFindValidPageSize(64K and 16M large page size)
22:11:04   [ERR] 	/home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x10000, pageFlags: 0x1, but found pageSize: 0x1000, pageFlags: 0x1
22:11:04   [ERR] 
22:11:04   [ERR] 		LastErrorNumber: -108
22:11:04   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
22:11:04   [ERR] 
22:11:04   [ERR] 3: j9vmem_testFindValidPageSize(all possible page sizes)
22:11:04   [ERR] 	/home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x10000, pageFlags: 0x1, but found pageSize: 0x1000, pageFlags: 0x1
22:11:04   [ERR] 
22:11:04   [ERR] 		LastErrorNumber: -108
22:11:04   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
22:11:04   [ERR] 
```

**Comment by pshipton** [comment]
Actually, ignore the last comment, my PR build picked up the revert.

**Comment by pshipton** [comment]
jenkins compile aix,plinux jdk8 depends eclipse-openj9/openj9-omr#109

**Comment by pshipton** [comment]
With this PR and with the OMR change, passed.
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1821/console

**Comment by pshipton** [comment]
Ideally this PR should be fixed to allow the test to pass with or without the OMR change. Then it can be delivered first, and the OMR change afterwards.

**Comment by singh264** [comment]
https://github.com/eclipse-openj9/openj9/pull/12778 supersedes these changes

**Pull request closed without merging**
