### PR TITLE
Implement initial logging JNI natives

### PR DESCRIPTION
**Pull request by tajila**
This PR does the bare minimum to enable JFR logging capabilities for debugging purposes. Full support will be addded in a later PR.

Also, fix the JNI method signatures

### CODE REVIEW

**Comment by tajila** [comment]
@hangshao0 Please review

**Comment by hangshao0** [comment]
jenkins test sanity.functiona xlinux jdk21

**Comment by hangshao0** [comment]
jenkins test sanity.functional amac jdk17

**Comment by hangshao0** [comment]
jenkins test sanity.functional xlinux jdk21

**Comment by hangshao0** [comment]
jenkins test sanity.functional xlinux jdk21

**Comment by tajila** [comment]
`jenkins test sanity.functional xlinux jdk21` has already passed, its  `jenkins test sanity.functiona xlinux jdk21` that failed

**Review by hangshao0 — APPROVED** [review]

**Pull request merged**
