### PR TITLE
Add VectorAPIExpansion to optimization strategies

### PR DESCRIPTION
**Pull request by gita-omr**
- Add VectorAPIExpansion to optimizer strategies using OMR::IfVectorAPI
- It's experimental but, for now, the pass will run just before GRA
- Add other currently necessary optimizations, also using OMR::IfVectorAPI
- extra LocalCSE pass is needed to improve GlobalVP and is added right after it

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins test sanity xlinux,zlinux,plinuz jdk17

**Comment by fjeremic** [comment]
Jenkins test sanity xlinux,zlinux,plinux jdk17

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
This looks ok to me since it is specific for VectorAPI, however we should get at least another dev. from the optimizer side to sign off here before merging. @0xdaryl @jdmpapin could I get an additional review here for one of you?

**Comment by gita-omr** [comment]
> 
> 
> This looks ok to me since it is specific for VectorAPI, however we should get at least another dev. from the optimizer side to sign off here before merging. @0xdaryl @jdmpapin could I get an additional review here for one of you?

Sure. Please note that the location of the optimization and the additional opts that had to be added might change in the future. This is what is necessary right now for the vector expansion to work.

**Review by jdmpapin — APPROVED** [review]
LGTM given that everything is guarded by `OMR::IfVectorAPI`

I'm not sure though why no extra local CSE pass is added to `reducedWarmStrategyOpts` or `AOTStrategyOpts`, while I assume it's necessary in all of the other strategies.

**Comment by fjeremic** [comment]
> I'm not sure though why no extra local CSE pass is added to `reducedWarmStrategyOpts` or `AOTStrategyOpts`, while I assume it's necessary in all of the other strategies.

@gita-omr any thoughts on this?

**Comment by gita-omr** [comment]
> 
> 
> > I'm not sure though why no extra local CSE pass is added to `reducedWarmStrategyOpts` or `AOTStrategyOpts`, while I assume it's necessary in all of the other strategies.
> 
> @gita-omr any thoughts on this?

Perhaps the issue did not come up in any of the benchmarks so far. But let me add it just for completeness.

**Comment by gita-omr** [comment]
Added extra pass of LocalCSE for AOT. It is needed to improve on GlobalVP. Since reducedWarm does not have GlobalVP did not add it there. Added this info to the commit message. @fjeremic

**Comment by fjeremic** [comment]
Jenkins test sanity xlinux,zlinux,plinux jdk17

**Pull request merged**
