### PR TITLE
Create OMR_<LANG>_WARNINGS_AS_ERROR_FLAG CMake variables

### PR DESCRIPTION
**Pull request by fjeremic**
Depends on eclipse/omr#6071

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#6071

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#6071

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#6071

**Comment by dsouzai** [comment]
@dnakamura could you please review?

**Comment by dsouzai** [comment]
@dnakamura could you also review this PR (as it'll require a coordinated merge with https://github.com/eclipse/omr/pull/6071)

**Comment by dsouzai** [comment]
@dnakamura review reminder.

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
