### PR TITLE
Move f2i, f2l, d2i, d2l evaluators from OMR to OpenJ9

### PR DESCRIPTION
**Pull request by BradleyWood**
Signed-off-by: BradleyWood <bradley.wood@ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins build all xlinux,win,osx jdk8,jdk11

**Comment by 0xdaryl** [comment]
See copyright check failure:  runtime/compiler/x/codegen/J9TreeEvaluator.hpp

**Comment by 0xdaryl** [comment]
Could you also confirm that you have tested this on Windows and Linux 32-bit please (this would be an IBM-internal test run)?

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux,win,osx jdk11

**Review by 0xdaryl — CHANGES_REQUESTED** [review]
Sorry, one minor nit.  The bracing style is not consistent with the rest of Testarossa.  I'm not sure if it was like that in the code in OMR, but can you fix that up here before we merge?

**Comment by BradleyWood** [comment]
Done. Sorry, my IDE refuses to cooperate with that style and often changes it on me.

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Minor formatting change only.  I won't re-run CI. Merging.

**Comment by pshipton** [comment]
Reverting due to https://github.com/eclipse-openj9/openj9/issues/12720

**Pull request merged**
