### PR TITLE
Remove CRIU required in cmdLineTester_criu_jitserverAcrossCheckpoint

### PR DESCRIPTION
**Pull request by annaibm**
related:https://github.ibm.com/runtimes/backlog/issues/1525

### CODE REVIEW

**Comment by llxia** [comment]
Please run Grinder with 
- TEST_FLAG empty (CRIU is auto-detected), the test is expected to run
- TEST_FLAG = JITAAS, the test is not expected to run

**Comment by llxia** [comment]
This is related to https://github.com/adoptium/TKG/pull/614. Since we will update TKG logic, this PR is to ensure we do not break the current behavior.

**Comment by annaibm** [comment]
Grinder run:
TEST_FLAG = JITAAS
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/43505/
TEST_FLAG = EMPTY
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/43507/

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
