### PR TITLE
Enable runaqa PR build

### PR DESCRIPTION
**Pull request by renfeiw**
- tailor runaqa action and workflow files for openj9
- current runaqa version doesn't support build openj9

[ci skip]

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
This PR will work util the updated run-aqa action is released. The update is in https://github.com/adoptium/run-aqa/pull/87

**Comment by renfeiw** [comment]
reviewers: @llxia @smlambert

**Comment by renfeiw** [comment]
Copyright check is failed due to the configuration json file, which I assume that we don't need.

**Comment by renfeiw** [comment]
The new run-aqa action is realeased, this PR is ready to merge.

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
Yay!

**Pull request merged**
