### PR TITLE
Update to OpenSSL 1.1.1o

### PR DESCRIPTION
**Pull request by keithc-ca**
Issue: #7633.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile all jdk8,jdk11,jdk17

**Comment by AdamBrousseau** [comment]
Since you two are normally ontop of these, can you open a PR for Adopt/Semeru too please?
https://github.com/adoptium/temurin-build/blob/955033fa85f139fef1f5aad593c205947258e95b/sbin/prepareWorkspace.sh#L267

**Comment by keithc-ca** [comment]
I created adoptium/temurin-build#2911.

**Comment by keithc-ca** [comment]
jenkins compile aix jdk11

**Review by pshipton — APPROVED** [review]

**Pull request merged**
