### PR TITLE
Deprecate Decimal Floating Point (DFP) related support

### PR DESCRIPTION
**Pull request by fjeremic**
This PR is a series of commits which deprecates Decimal Floating Point (DFP) related support. See commit message of each commit to see what was removed. I tried to avoid making syntactic changes to the code so that only lines were deleted. This hopefully minimizes the number of additions vs. deletions and makes reviewing this PR easier.

Closes: #12533

### CODE REVIEW

**Comment by fjeremic** [comment]
Depends on eclipse/omr#5966.

**Comment by fjeremic** [comment]
Jenkins copyright check

**Comment by fjeremic** [comment]
Jenkins test sanity.functional,sanity.system,extended.functional,extended.system all jdk8,jdk11 depends eclipse/omr#5966

**Comment by fjeremic** [comment]
For reviewers since code mainly touches Z and Power I tested internally (build ID 470510).

**Comment by fjeremic** [comment]
For reviewers since code mainly touches Z and Power I tested internally (build ID 470510). Suggesting @0xdaryl as committer here since this is a breaking change. There was no way around that.

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Review by 0xdaryl — APPROVED** [review]

**Comment by fjeremic** [comment]
I just checked all the failures are due to timeout issues. I'll refrain from launching the tests again and leave it to the committer to do once the reviews are done. Just in case I need to make extra code changes. I'm fairly confident the current change will pass 100% sans the infrastructure problems.

**Comment by fjeremic** [comment]
Actually I take that back, I see Daryl has approved, so all we need is clean testing. Let's see how this stress test goes 🤞 . Going to re-launch only the failed tests 😅 .

Jenkins test sanity.functional,sanity.system,extended.functional,extended.system plinux,xlinux,win jdk8,jdk11 depends eclipse/omr#5966

**Comment by fjeremic** [comment]
Jenkins test sanity.functional,sanity.system,extended.functional,extended.system xlinux jdk11 depends eclipse/omr#5966

**Comment by fjeremic** [comment]
@0xdaryl not sure what to do about testing here. All of the failures reported are because the job never ran due to infrastructure issues. Some of the tests look like they're stuck not doing anything even though the jobs already reported infra failures if you click the link.

I'm pretty confident in the change given the internal testing and all the passed tests here so far. Not sure how much we want to wrestle with the infrastructure to get green builds here. Let me know as the committer how you'd like to proceed. If you want I can force push to wipe the history and we can try the testing again.

**Comment by 0xdaryl** [comment]
Let's try with just the sanity builds and see where that gets us:  `Jenkins test sanity all jdk8,jdk11 depends eclipse/omr#5966`

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8,jdk11 depends eclipse/omr#5966

**Comment by 0xdaryl** [comment]
Testing looks good.  I'll merge off-hours.

**Pull request merged**
