### PR TITLE
Inline jdk/internal/util/Preconditions.checkIndex

### PR DESCRIPTION
**Pull request by gita-omr**
- this method contains a simple check whether provided index is greater than 0 and less than provided upper bound. This check lands itself well to various JIT optimizations (e.g. moving out of a loop).

### CODE REVIEW

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk8,jdk11,jdk17,jdk18,jdk19

**Comment by gita-omr** [comment]
@jdmpapin @vijaysun-omr fyi

**Review by vijaysun-omr — APPROVED** [review]

**Comment by jdmpapin** [comment]
The cmdLineTester_getPid_0 failure is unrelated:  #11795, #13085, #16098. Restarting the failed build

Jenkins test sanity zlinux jdk17

**Comment by jdmpapin** [comment]
Everything has passed except another cmdLineTester_getPid_0 failure and a JITServer timeout like #14594 (just in testServer instead of testServerUnreachableForAWhile)

**Pull request merged**
