### PR TITLE
Add Extension Class Loader to permanent roots

### PR DESCRIPTION
**Pull request by dmitripivkine**
Extension Cladss Loader can not be unloaded and can be treated as a permanent root the same way as System and Application Class Loaders.

### CODE REVIEW

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux jdk11

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux jdk11

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux jdk11

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux jdk11

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux jdk11

**Comment by dmitripivkine** [comment]
Jenkins test functional xLinux jdk21

**Comment by dmitripivkine** [comment]
Jenkins test extended.functional xLinux jdk21

**Comment by dmitripivkine** [comment]
Jenkins test extended.system xLinux jdk11

**Comment by dmitripivkine** [comment]
Jenkins test extended.system xLinux jdk11

**Comment by amicic** [comment]
Jenkins test sanity aix,win  jdk17

**Review by amicic — APPROVED** [review]

**Pull request merged**
