### PR TITLE
Disable inlining of intrinsics

### PR DESCRIPTION
**Pull request by gita-omr**
- https://github.com/eclipse-openj9/openj9/pull/17222 seems to cause a slowdown
- disable for further performance investigation

### CODE REVIEW

**Comment by gita-omr** [comment]
@jdmpapin @pshipton @vijaysun-omr

**Comment by jdmpapin** [comment]
Do you want to be able to re-enable this at runtime for investigation purposes?

**Comment by gita-omr** [comment]
> Do you want to be able to re-enable this at runtime for investigation purposes?

I was thinking about it but that would require yet another option. Maybe we can do it later, after investigating the simple case that I was able to reproduce.

**Review by jdmpapin — APPROVED** [review]

**Comment by jdmpapin** [comment]
Jenkins test sanity xlinux jdk21

**Comment by jdmpapin** [comment]
Jenkins compile all jdk21

**Pull request merged**
