### PR TITLE
Fix potential cycle in JFR ThreadGroupEntry

### PR DESCRIPTION
**Pull request by tajila**
Fix potential cycle in JFR ThreadGroupEntry

Related to https://github.com/eclipse-openj9/openj9/issues/20624

### CODE REVIEW

**Comment by tajila** [comment]
@gacholio Please take a look

**Comment by gacholio** [comment]
Should there be a mutex here? I don't see why the new check is necessary unless it was to protect against another thread adding the entry.

**Comment by tajila** [comment]
Conccurent access is not the issue. Its that adding a threadGroup may result in adding another threadGroup which results in adding the original threadGroup. Something like tg1->tg2->...->tg1. When this occurs you end up with a cycle in the thread group list. Later on when we iterate it, we spin indefinitely.

**Comment by tajila** [comment]
Actually, the real issue is that different threadGroups can have the same name. For the threadGroup table we use the name as the key. This is what produces the cycle.

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins compile xlinux jdk21

**Pull request merged**
