### PR TITLE
Revert "Revert "Fix and re-enable inliner ILGen reduction of getCallerClass""

### PR DESCRIPTION
**Pull request by fjeremic**
Exact same change that was reverted plus a force-pushed compilation error fix for JITServer.

### CODE REVIEW

**Comment by fjeremic** [comment]
[Force-pushed](https://github.com/eclipse-openj9/openj9/compare/89fb600923feb7c019b077efacd6edc1d64f10aa..c16a5e06c173c812ca8b3a42dc4db431b2535319) the fix which is very simple.

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by fjeremic** [comment]
Jenkins test sanity osx,xlinux jdk11

**Comment by fjeremic** [comment]
Jenkins test sanity aix jdk8

**Comment by fjeremic** [comment]
Jenkins test sanity aix jdk8

**Comment by fjeremic** [comment]
Leaving a comment here as I was directed to #12881 as the reason for the JDK11 x86 builds failing. Not sure what we can do about that one. Here is one final try:

Jenkins test sanity xlinux jdk11

**Comment by pshipton** [comment]
@fjeremic https://github.com/eclipse-openj9/openj9/issues/12881 doesn't explain https://github.com/eclipse-openj9/openj9/pull/13070#issuecomment-871739495 although it may be hiding the problem.

**Comment by pshipton** [comment]
nm, I see now you've already fixed it.

**Review by pshipton — DISMISSED** [review]
Not sure this should be merged if it's going to cause the xlinux builds to break again.

**Comment by fjeremic** [comment]
> Not sure this should be merged if it's going to cause the xlinux builds to break again.

It shouldn't. The only thing that failed is JDK11 on x86 and that is due to infra issues. We've agreed with Vijay we will wait for a fully green build before merging this as it is not as high priority to get in (yet).

The original build break was on plinux and xlinux due to JITServer ifdefed code due to a typo. The plinux builds did pass. Let's see if we can get the xlinux working now:

Jenkins test sanity all jdk8,jdk11

**Comment by fjeremic** [comment]
@vijaysun-omr I also pushed a typo fix which @joransiu and I discovered which was introduced while fixing a review comment left by you. You can see the fix [here](https://github.com/eclipse-openj9/openj9/compare/c16a5e06c173c812ca8b3a42dc4db431b2535319..be1615bd42c051a6b97f2858d9497d3475ca9c85).

If the top-level frame is marked with the `J9AccMethodFrameIteratorSkip` flag then we **do** want to skip the frame at depth 0. The code before accidentally had `!=` instead of `==`. The net effect of this was that the optimization was not kicking in if the top-level method being compiled is the one that called `Method.invoke`.

**Comment by fjeremic** [comment]
Jenkins test sanity win32 jdk8

**Comment by fjeremic** [comment]
@vijaysun-omr all tests passed sans the copyright check on a file which doesn't even have a copyright header. I think we're good to go here.

**Review by vijaysun-omr — APPROVED** [review]

**Pull request merged**
