### PR TITLE
Update criu machine requirements

### PR DESCRIPTION
**Pull request by tajila**

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity xlinux jdk21

**Comment by tajila** [comment]
link to the test job https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK21_x86-64_linux/406/

**Comment by tajila** [comment]
@llxia `cmdLineTester_criu_jitserverAcrossCheckpoint_0` failed https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_x86-64_linux_Personal/39/tapResults/

All the other tests were skipped, do you know why this one wasnt?

**Comment by tajila** [comment]
NVM, I think I know what the issue was

**Comment by tajila** [comment]
jenkins test sanity xlinux jdk21

**Comment by tajila** [comment]
I just realized we only have one machine newer than cent7 for x86 externally.

**Comment by tajila** [comment]
jenkins test sanity xlinuxcriu jdk17

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3541/ ran on cent7 and the following `cmdLineTester_criu_jitserverAcrossCheckpoint` and `cmdLineTester_criu_jitserverPostRestore` were not skipped.

```
00:16:19.775  PASSED test targets:
00:16:19.775  	cmdLineTester_criu_jitserverAcrossCheckpoint_0
00:16:19.775  	cmdLineTester_criu_jitserverPostRestore_0
00:16:19.775  	cmdLineTester_criu_jitserverPostRestore_1
00:16:19.775  	cmdLineTester_criu_jitserverPostRestore_2
00:16:19.775  	cmdLineTester_criu_jitserverPostRestore_3
```

I think it is related to `<platformRequirements>os.linux,^arch.arm,bits.64</platformRequirements>`.  https://github.com/eclipse-openj9/openj9/blob/1085bee1c270dbf5b08620015e39fabba60893ed/test/functional/cmdLineTests/criu/playlist.xml#L320C1-L326C30

We need to have it added for each line. For example:
```
		<platformRequirementsList>
			<platformRequirements>os.linux,^arch.arm,bits.64,os.linux.ubuntu.22+</platformRequirements>
			<platformRequirements>os.linux,^arch.arm,bits.64,os.linux.rhel.8+</platformRequirements>
			<platformRequirements>os.linux,^arch.arm,bits.64,os.linux.sles.15+</platformRequirements>
			<platformRequirements>os.linux,^arch.arm,bits.64,os.linux.cent.8+</platformRequirements>
		</platformRequirementsList>
```

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/3542/console on cent7-x64-2
All tests are skipped as expected.
```
00:02:35.521  TEST TARGETS SUMMARY
00:02:35.521  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
00:02:35.521  DISABLED test targets:
00:02:35.521  	cmdLineTester_criu_0
00:02:35.521  	cmdLineTester_criu_1
00:02:35.521  	cmdLineTester_criu_2
00:02:35.521  	cmdLineTester_criu_softmx_0
00:02:35.521  
00:02:35.521  TOTAL: 62   EXECUTED: 0   PASSED: 0   FAILED: 0   DISABLED: 4   SKIPPED: 58
00:02:35.521  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Pull request merged**
