### PR TITLE
Remove redundant register native call

### PR DESCRIPTION
**Pull request by tajila**
Completes: https://github.com/eclipse-openj9/openj9/pull/18169

### CODE REVIEW

**Comment by tajila** [comment]
jenkins compile win jdk99

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk21

**Comment by tajila** [comment]
jenkins compile win jdk8

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk21

**Review by babsingh — APPROVED** [review]

**Pull request merged**
