### PR TITLE
Add implementation of Class.isValue()

### LINKED ISSUE #14519: Class.isPrimitiveClass() needs to check for ACC_PRIMITIVE
Currently `Class.isPrimitiveClass()` is essentially checking for flag `ACC_VALUE`, which is not correct anymore. As new flag` ACC_PRIMITIVE` is addded, it needs to be updated to check for `ACC_PRIMITIVE`. Instead,` Class.isValue()` should check for `ACC_VALUE`.

### PR DESCRIPTION
**Pull request by hangshao0**
1. Add implementation of Class.isValue()
2. Update Class.isPrimitiveClass() to check for ACC_PRIMITIVE

Closes #14519

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity,extended plinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by hangshao0** [comment]
The change was recently added by: https://github.com/eclipse-openj9/openj9/pull/14549

**Comment by hangshao0** [comment]
> The PR build picked up an outdated SHA [1], latest one [2] has the API in question [3].

Thanks @JasonFengJ9. 
@tajila You may want to re-launch the VT PR builds.

**Comment by tajila** [comment]
Thanks for looking into this @hangshao0 @JasonFengJ9

**Comment by tajila** [comment]
Jenkins test sanity,extended plinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Pull request merged**
