### PR TITLE
AArch64 macOS: Disable J9VM_INTERP_ATOMIC_FREE_JNI_USES_FLUSH

### PR DESCRIPTION
**Pull request by knn-k**
This commit disables the J9VM_INTERP_ATOMIC_FREE_JNI_USES_FLUSH flag
on AArch64 macOS.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
This is based on @Akira1Saitoh's observation in https://github.com/eclipse-openj9/openj9/issues/14426#issuecomment-1089715888 .
It does not disable the whole atomic free JNI, but only its `USES_FLUSH` feature.

We will see if other known intermittent failures disappear or not with this change, and enable the feature later again when we have any solution for the `flushProcessWriteBuffers()` behavior.

**Comment by knn-k** [comment]
jenkins test sanity amac jdk17

**Comment by knn-k** [comment]
I opened Issue #14870 for investigation of the `flushProcessWriteBuffers()` behavior.

**Review by gacholio — APPROVED** [review]

**Comment by knn-k** [comment]
I made sure that the build with this change passes the testcase in #14426 by running it locally.

**Comment by knn-k** [comment]
jenkins test sanity.functional,extended.functional amac jdk17

Updated the commit to enable the testcase threadMXBeanTestSuite2 on AArch64 macOS.

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Can you open a PR for 0.32 for this one too please?

**Comment by knn-k** [comment]
I opened #14875 for v0.32.0.

**Comment by knn-k** [comment]
I opened PR #14889 for disabling J9VM_INTERP_TWO_PASS_EXCLUSIVE on AArch64 macOS.

**Pull request merged**
