### PR TITLE
AArch64 macOS: Stop assigning x18

### PR DESCRIPTION
**Pull request by knn-k**
This commit stops the JIT assigning the x18 register.

### CODE REVIEW

**Comment by knn-k** [comment]
Test jobs on AArch64 macOS with this change was successful.
- JDK 11 sanity.functional: job/Test_openjdk11_j9_sanity.functional_aarch64_mac_Personal/124/
- JDK 17 sanity.functional: job/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal/96/

Also waiting for a test jobs on AArch64 Linux to complete:
- JDK 11 sanity.functional: job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Personal/325/

**Comment by pshipton** [comment]
Does this change need to get into the 0.41 release? I"m not sure of the impact, but seems the JVM doesn't work on the latest macOS 13 versions?

**Comment by 0xdaryl** [comment]
> Does this change need to get into the 0.41 release? I"m not sure of the impact, but seems the JVM doesn't work on the latest macOS 13 versions?

It could if there is still time. I hadn't considered it because I thought we were well past accepting new changes (even critical ones for that matter).

**Comment by 0xdaryl** [comment]
Because of the infra problems affecting macOS on Apple Silicon, @knn-k has been testing internally.  I believe all looks good there, but I'd like him to confirm here before merging.

**Comment by knn-k** [comment]
If this PR fixes Issue #18336, I think it is worth making it a go for v0.41. 

Our internal machine macaarch64rt8 runs macOS 13, and the jobs on that machine are passing without this PR.

Examples:
- Test_openjdk11_j9_sanity.functional_aarch64_mac/355/
- Test_openjdk11_j9_extended.functional_aarch64_mac/355/
- Test_openjdk11_j9_sanity.system_aarch64_mac/354/
- Test_openjdk17_j9_sanity.functional_aarch64_mac/372/
- Test_openjdk17_j9_extended.functional_aarch64_mac/370/
- Test_openjdk17_j9_sanity.system_aarch64_mac/366/

On the other hand, the test job on AArch64 Linux with this PR above finished successfully.

**Comment by 0xdaryl** [comment]
> This change is not without risk though. It does change the generated code as different register assignment and spilling choices may be taken. Normally, I'd like a change of this nature to soak in a few test cycles rather than rushing into an already delayed release with no opportunity for remediation.

As this is a user-raised issue, and `-Xint` isn't really a practical workaround, then I'd be willing to forgo these usual concerns and support it going into 0.41 if the release schedule allows for it.

**Comment by Akira1Saitoh** [comment]
I am able to launch MemoryAnalyzer with the steps described in #18336 using the binary that includes this fix.
- /job/Build_JDK17_aarch64_mac_Personal/187/

**Comment by pshipton** [comment]
Ideally this is merged before the weekend testing starts Friday evening, and then we'll have those results.

I believe the internal machine is running 13.0, and the OpenJ9 machine is 13.4. I'm wondering if it's only a problem on newer versions.
@Akira1Saitoh what version is your laptop?

**Comment by Akira1Saitoh** [comment]
It's Ventura 13.6.

**Comment by knn-k** [comment]
I opened PR #18357 for v0.41.0-release.

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
This is a macOS on Arm specific change.  This has been tested extensively internally.  Given the infrastructure problems with macOS on Arm hardware in the open project a Jenkins CI test is pointless.

**Pull request merged**
