### PR TITLE
Update java.specification.maintenance.version

### PR DESCRIPTION
**Pull request by keithc-ca**
To match the reference implementation:
* [8330415: Update system property for Java SE specification maintenance version](https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/a5c1d62d0b22fbeabe7509dabf700f974381983a)

### CODE REVIEW

**Comment by keithc-ca** [comment]
In draft while I add changes for other versions, e.g. [jdk11](https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/c581e12c9d45200047edd0a25c7edbe194a663ce).

**Comment by keithc-ca** [comment]
The property is set (as appropriate) by openjdk code in jdk17+.

**Comment by pshipton** [comment]
https://jcp.org/aboutJava/communityprocess/maintenance/jsr337/337-mr6-changes.html
https://jcp.org/aboutJava/communityprocess/maintenance/jsr384/jsr384-mr3-changes.html

**Comment by pshipton** [comment]
I'll merge this at the same time as we promote the new jdk8 and jdk11 levels.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
