### PR TITLE
Enable Portable SCC detection on aarch64

### PR DESCRIPTION
**Pull request by dsouzai**
Fixes https://github.com/eclipse-openj9/openj9/issues/15801

### CODE REVIEW

**Comment by dsouzai** [comment]
@pshipton @knn-k

**Comment by pshipton** [comment]
[A grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27027/console) with the updated JVM is still failing in the same way.

**Comment by pshipton** [comment]
Lan explained the test uses the docker image from dockerhub, so it can only work once there is a new docker image on dockerhub which contains the fix.

**Review by pshipton — APPROVED** [review]

**Comment by llxia** [comment]
Yes, we are working on the story of building docker image for nightly/weekly testing. aot_test is a quick test that we added for now.
Since the dockerhub image will not be updated until the next release, @LongyuZhang could you please disable the aot_test on aarch64 for now? Thanks.

**Pull request merged**
