### PR TITLE
Fix asm.jar path mismatch in valuetype tests

### PR DESCRIPTION
**Pull request by llxia**
related: https://github.com/eclipse-openj9/openj9/pull/18597#issuecomment-1885142840

### CODE REVIEW

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/3171

**Comment by hangshao0** [comment]
Jenkins test sanity,extended winval jdknext

**Comment by hangshao0** [comment]
Jenkins test sanity,extended aixval jdknext

**Review by hangshao0 — APPROVED** [review]
LGTM. Thanks for fixing this.

**Pull request merged**
