### PR TITLE
Add tests for jitIsFieldStable

### PR DESCRIPTION
**Pull request by EricYangIBM**
Tests whether a field contains the "Stable" annotation

Related: #12679
Signed-off-by: Eric Yang <eric.yang@ibm.com>

### CODE REVIEW

**Comment by EricYangIBM** [comment]
The tests are passing for 8, 11, and 16

**Comment by tajila** [comment]
Jenkins test sanity plinux jdk8,jdk11,jdk16

**Comment by tajila** [comment]
Jenkins test sanity win,zlinux jdk11

**Review by tajila — APPROVED** [review]

**Comment by EricYangIBM** [comment]
Should I squash the two commits after the PR builds finish?

**Comment by tajila** [comment]
> Should I squash the two commits after the PR builds finish?

yes

**Comment by tajila** [comment]
@eric98zhang You can squash your commits, ill re-run the tests once the extension repo changes are merged

**Comment by EricYangIBM** [comment]
@tajila All extension repo changes have been merged and I have squashed the commits

**Comment by EricYangIBM** [comment]
@smlambert Originally I had an extra option after this line https://github.com/eclipse-openj9/openj9/pull/13002/files#diff-dbd49d79e01ededa0324e16bd902bff6431b60b0cde7b9a76970e97f599c7ee0R2620: 
`-Djava.library.path=$(TEST_JDK_HOME)$(D)..$(D)test$(D)openj9`. I'm not sure if I should keep it. If I don't, local tests will fail (since libanntests.so is in ...images/test/openj9) unless `LD_LIBRARY_PATH` or `NATIVE_TEST_LIBS` is exported as .../images/test/openj9. I haven't seen this exporting in the test docs so I don't know if this is known? I don't want people to get local failures because of my test

**Comment by tajila** [comment]
Jenkins test sanity win,zlinux jdk11

**Comment by tajila** [comment]
Jenkins test sanity plinux jdk8,jdk11,jdk16

**Comment by tajila** [comment]
@llxia Please review these changes

**Comment by llxia** [comment]
PR build links:
https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/474/
https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/473/

**Comment by llxia** [comment]
https://github.com/eclipse-openj9/openj9/pull/13002#issuecomment-871699613, no, we do not need to add `-Djava.library.path=$(TEST_JDK_HOME)$(D)..$(D)test$(D)openj9` in playlist. This path does not exist in the automation run. For the local run, users need to set `NATIVE_TEST_LIBS` if the test image is not in the expected location. https://github.com/eclipse-openj9/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md#environment-variables

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
