### PR TITLE
Fix hangTest failure with dynamic compile

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Add dependency for hangTest dynamic compile
[skip ci]

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test links on hyc_Jenkins:
- jdk17 with dynamic compile (19317)
- jdk17 without dynamic compile (19319)
- jdk11 with dynamic compile (19318)
- jdk11 without dynamic compile (19320)

**Comment by LongyuZhang** [comment]
@llxia @renfeiw Could you review it? Thanks.

**Review by llxia — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
If I set BUILD_LIST=functional, the Grinder failed:
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/352/

```
Error: Unable to access jarfile /home/jenkins/jenkins-agent/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar

cmdLineTester_hangTest_0_FAILED
```

**Comment by LongyuZhang** [comment]
The grinder failed since it is using original openj9 branch, with this PR branch, the test passed with BUILD_LIST=functional, link is hyc_jenkins/view/Test_grinder/job/Grinder/19307

> If I set BUILD_LIST=functional, the Grinder failed: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/352/
> 
> ```
> Error: Unable to access jarfile /home/jenkins/jenkins-agent/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar
> 
> cmdLineTester_hangTest_0_FAILED
> ```

**Pull request merged**
