### PR TITLE
Remove unnecessary exports from java.base

### PR DESCRIPTION
**Pull request by keithc-ca**

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile amac jdk11,jdk17,jdk21,jdk22

**Comment by pshipton** [comment]
jenkins compile alinux jdk11,jdk17,jdk21,jdk22

**Comment by keithc-ca** [comment]
The alinux failure
```
[2024-02-28T21:51:00.709Z] IOException caught during compilation: Resource deadlock avoided
```
is a problem that seems to occur more frequently lately (on most or all platforms).

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Do you ever see it on builds you do locally?

**Comment by keithc-ca** [comment]
> Do you ever see it on builds you do locally?

Not that I can recall.

**Pull request merged**
