### PR TITLE
Add testing for VT hashcodes

### PR DESCRIPTION
**Pull request by ehrenjulzert**
Relies on https://github.com/eclipse-openj9/openj9/pull/15922 being merged
Part of solution of issue #15529

Signed-off-by: Ehren Julien-Neitzert <ehren.julien-neitzert@ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
Can you mention the issue https://github.com/eclipse-openj9/openj9/pull/15922 in the description ?

**Comment by ehrenjulzert** [comment]
> Can you mention the issue #15922 in the description ?

sure, I just added the issue number

**Comment by tajila** [comment]
@ehrenjulzert you need to rebase your changes

**Comment by ehrenjulzert** [comment]
Okay, it's been rebased

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Pull request merged**
