### PR TITLE
Check for NULL before using the APIs in TR_J9SharedCache

### PR DESCRIPTION
**Pull request by dsouzai**
Closes https://github.com/eclipse-openj9/openj9/issues/14004

### CODE REVIEW

**Comment by dsouzai** [comment]
@mpirvu could you please review?

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity zlinux jdk8

**Comment by mpirvu** [comment]
Tests have passed: https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/1253/

**Pull request merged**
