### PR TITLE
Fix cast accessing ramConstantPool

### PR DESCRIPTION
**Pull request by keithc-ca**
Addresses this [comment](https://github.com/eclipse-openj9/openj9/pull/13836#pullrequestreview-821714454).

### CODE REVIEW

**Comment by keithc-ca** [comment]
Marked as draft - may not be needed since #13836 was reverted and its replacement should incorporate this.

**Comment by EricYangIBM** [comment]
Running builds: https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/30170/
With branch https://github.ibm.com/Eric-Yang/openj9/tree/castFix

**Comment by EricYangIBM** [comment]
Seems like all tests passed. New PR: https://github.com/eclipse-openj9/openj9/pull/14063

**Comment by keithc-ca** [comment]
This fix was included in #14063: closing.

**Pull request closed without merging**
