### PR TITLE
Fix GetCurrentContendedMonitor on mounted CarrierThread

### PR DESCRIPTION
**Pull request by fengxue-IS**
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
locally verified on top of #16855, 400/400 passed.

**Comment by babsingh** [comment]
jenkins test sanity.functional,extended.openjdk amac jdk19

**Comment by babsingh** [comment]
jenkins compile win jdk19

**Comment by babsingh** [comment]
For compressedrefs coverage.

jenkins test sanity zlinux jdk19

**Review by babsingh — APPROVED** [review]

**Comment by babsingh** [comment]
A new intermittent failure in `serviceability/jvmti/vthread/VThreadMonitorTest` is seen with https://github.com/eclipse-openj9/openj9/pull/16855. This PR fixes the intermittent failure without affecting existing functionality, and it should be back-ported to the 0.37 release branch.

**Comment by babsingh** [comment]
@fengxue-IS Can you open an issue for the VThreadMonitorTest failure and link it to the two PRs?

**Pull request merged**
