### PR TITLE
Update <plat> to <platform> for playlist disabled tag

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewers: @llxia @smlambert

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8,jdk11

**Comment by llxia** [comment]
@renfeiw could resolve the merge conflicts? Thanks

**Comment by renfeiw** [comment]
This PR depends on https://github.com/adoptium/TKG/pull/202

**Comment by llxia** [comment]
jenkins test sanity all jdk8,jdk11

**Comment by renfeiw** [comment]
internal grinder: Grinder_TKG/1250

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list functional --target sanity.functional.regular --jdk_version 11 --jdk_impl openj9 --platform x86-64_linux

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list functional --target jsigjnitest --jdk_version 11 --jdk_impl openj9 --platform x86-64_windows

**Comment by llxia** [comment]
The above run aqa failure is related to repo rename.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
