### PR TITLE
Correct references to Unsafe.compareAndExchange methods

### PR DESCRIPTION
**Pull request by keithc-ca**
The `Unsafe` method names no longer end with 'Volatile' so table entries for such names would never match. The misleading suffix was removed from the related INL methods.

The references were added before the initial release of OpenJ9 which was after they were removed
upstream; see https://github.com/ibmruntimes/openj9-openjdk-jdk9/commit/eeee04c2f0487c31a1b5d805e89a1b73756f2941.

### CODE REVIEW

**Comment by gacholio** [comment]
Are the volatile methods gone from the current OpenJDK Java 8 releases (the headstream VM has to support every JDK level, though only the current release of each level).?

**Comment by keithc-ca** [comment]
I couldn't find them in any flavour of Java 8 (not Semeru builds, nor IBM builds).

**Comment by gacholio** [comment]
How have we been running the non-volatile versions? If we already have those implementations, should we not just delete the volatile versions?

**Comment by keithc-ca** [comment]
This simply makes the names of the implementing functions match the names of the methods they support, and removes  table entries that would only be useful if the `compareAndExchange*Volatile` methods actually existed.

The Java 9 commit linked above includes this change to `Unsafe.java`:
```
<   public final native Object compareAndExchangeObjectVolatile(Object o, long offset,
<                                                               Object expected,
<                                                               Object x);
--
>   public final native Object compareAndExchangeObject(Object o, long offset,
>                                                       Object expected,
>                                                       Object x);
```
Prior to this change both `compareAndExchangeObject` and `compareAndExchangeObjectVolatile` would be recognized and handled the same way. Support for the latter method is no longer needed.

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Pull request merged**
