### PR TITLE
Update IBM copyright notices to remove last-modified year

### LINKED ISSUE #16669: Stop maintaining a last-modified year in copyright notices
(This issue is the same as eclipse/omr#6879 but as it applies to OpenJ9.)

All of our source files start with a copyright notice containing two years, like the following:

```Copyright (c) 2000, 2019 IBM Corp. and others```

The first year tells us when the file contents were first written, and the second tells us when they were last modified.

Because the copyright notices are in this form, the second year needs to be updated the first time each file is modified in a given year. These updates are a widespread paper cut that affect many contributions, as contributors generally need to manually carry them out. Furthermore, committers need to ensure that the year is updated appropriately, and remembering to do so is so error prone that we have had to develop an automated check that runs in each PR. When the check fails, before merging we have to wait for (roughly speaking) a round trip through two humans. Sometimes it can be combined with another round trip that was necessary anyway, i.e. when review has found problems that need to be addressed, but sometimes it can't be. Finally, setting aside raw efficiency, some (many?) of us find dealing with these updates to be a hassle. It's annoying to have to appease a failing copyright check.

Recently there have been [rumblings](https://hynek.me/til/copyright-years/) online about the (lack of) necessity of updating copyright years in this way for open source projects, which prompted me to look into why we do this. It turns out that maintaining the last-modified year was a requirement from IBM (my current employer) at the time of open-sourcing. However, IBM has since dropped that requirement, so it's simply no longer necessary.

As such, I propose changing our copyright notices to the following format (which is acceptable to IBM):

```Copyright IBM Corp. and others <initial-year>```

For instance, the example copyright notice from above would become:

```Copyright IBM Corp. and others 2000```

By removing the last-modified year, it no longer needs to be maintained, and we can all save a little bit of time and be a little bit less annoyed.

I would be happy to personally carry out this change. I'd like to update all of the files at once so that we aren't still left with the problem of making sure that they are updated piecemeal as other changes flow into them. The only disruption would be some (extremely easy to resolve) merge conflicts in in-flight changes that already include updates to the year in the copyright notice.

Any objections?

### PR DESCRIPTION
**Pull request by jdmpapin**
With the last-modified year removed, PRs no longer need to ensure that it is up-to-date.

The bulk of this change is in the last commit, which has been generated based on a regex substitution. It modifies the vast majority of files in the repository (though only one line in all but a few). There are some much smaller commits leading up to that one. The full list of commits is as follows:
- Update CONTRIBUTING.md to reflect changes to copyright notices
- Delete the (now unnecessary) Jenkins copyright check script
- Fix line endings in jdmpview (Eclipse IDE).launch
- Use the new single-year IBM copyright notice in generated sources
- Clean up some copyright/license notice headers
- Update IBM copyright notices to remove last-modified year

Because the last commit touches so many files, it's tricky to review. I left some suggestions for how to review the corresponding OMR commit in eclipse/omr#6923. Here I've used the same regex substitution script that I posted there.

In the event of conflicts, I will rebase and regenerate the last commit.

Fixes #16669

### CODE REVIEW

**Comment by jdmpapin** [comment]
https://github.com/eclipse/omr/pull/6923#issuecomment-1462268005 applies to this PR as well

**Review by dsouzai — APPROVED** [review]
I reviewed a sample of the files manually. Since the script used to generate the copyright update commit is the same as the one used in https://github.com/eclipse/omr/pull/6923, it has already been reviewed and shown to be correct. As with the OMR PR, I ran the script used to generate the copyrights and verified that the commit it generates is exactly the same as [Update IBM copyright notices to remove last-modified year](https://github.com/eclipse-openj9/openj9/pull/16881/commits/7cf506db3b37e1ccbf20925555b6b21e20fcc771).

**Comment by dsouzai** [comment]
jenkins test sanity all jdk17

**Comment by jdmpapin** [comment]
AIX failure is #8625

**Comment by jdmpapin** [comment]
Jenkins test sanity aix jdk17

**Comment by dsouzai** [comment]
The Pull Request job shows as failed because the AIX build failed in https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/3470/ (as described in https://github.com/eclipse-openj9/openj9/pull/16881#issuecomment-1464716626); however, the job Devin started (https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/3471/) passed.

**Pull request merged**
