### PR TITLE
Implement vabs and sqrt IL Opcodes

### PR DESCRIPTION
**Pull request by midronij**
Handles newly added vector IL Opcodes (vabs and vsqrt) introduced in OMR

Depends on https://github.com/eclipse/omr/pull/6489

### CODE REVIEW

**Comment by midronij** [comment]
@gita-omr @IBMJimmyk could you please review when you have a chance?

**Review by gita-omr — APPROVED** [review]

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#6489

**Comment by gita-omr** [comment]
Jenkins test sanity win jdk8 depends eclipse/omr#6489

**Comment by gita-omr** [comment]
Re windows build see: https://github.ibm.com/runtimes/infrastructure/issues/6861#issuecomment-43532726

**Comment by knn-k** [comment]
Jenkins test sanity all jdk17 depends eclipse/omr#6489

**Comment by knn-k** [comment]
Jenkins test sanity amac jdk17 depends https://github.com/eclipse/omr/pull/6489

**Comment by knn-k** [comment]
Please remove "WIP:" from the commit title when it is ready.

**Comment by pshipton** [comment]
https://github.com/eclipse-openj9/openj9/issues/15074#issuecomment-1129888478 is not resolved.

**Comment by midronij** [comment]
My bad, looks like I missed part of the problem. https://github.com/eclipse/omr/pull/6522 should fully fix it.

**Comment by knn-k** [comment]
Jenkins test sanity all jdk17

**Comment by knn-k** [comment]
OK.  The failures on s390x_linux do not seem to be related to vector operations.

**Pull request merged**
