### PR TITLE
Print Openj9 options in effect into the verbose log

### PR DESCRIPTION
**Pull request by EmanElsaban**
Options that don't have the first character of the message as "F" in the option table entry will not 
be printed in "options in effect" when the option is specified. 
Thus, I added 'F' to the messages of Openj9 options, so that the options specified would also 
be printed to "options in effect" in verbose logs.

Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>

### CODE REVIEW

**Comment by EmanElsaban** [comment]
@mpirvu can you please take a look? Thanks

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity zlinux jdk11

**Comment by mpirvu** [comment]
`cmdLineTester_pltest_0` failed on zLinux, but there should be no reason for doing so.

**Comment by mpirvu** [comment]
jenkins test sanity plinux jdk11

**Pull request merged**
