### PR TITLE
(0.28.0) JITServer support for ```TR_J9VMBase::delegatingMethodHandleTarget```

### PR DESCRIPTION
**Pull request by EmanElsaban**
A v0.28.0 backport of PR: #13408

Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>

### CODE REVIEW

**Comment by EmanElsaban** [comment]
@mpirvu  Can you please review? Thanks.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
Linter shows some errors, but I don't understand how they can appear if this code hasn't changed those parts of the code.
```
../compiler/control/CompilationThread.cpp:1278:53: error: use of undeclared identifier 'TR_AOT'
   if (!TR::Options::getCmdLineOptions()->getOption(TR_AOT))
../compiler/control/CompilationThread.cpp:1279:59: error: use of undeclared identifier 'TR_DisableCompilationThread'
      return !TR::Options::getCmdLineOptions()->getOption(TR_DisableCompilationThread);
../compiler/control/CompilationThread.cpp:1280:55: error: use of undeclared identifier 'TR_EnableCompilationThread'; did you mean 'TR_EnableCompilationSpreading'?
   return TR::Options::getCmdLineOptions()->getOption(TR_EnableCompilationThread);
```

**Comment by mpirvu** [comment]
@EmanElsaban Just to confirm, this code was a straight cherry pick from the master branch, correct?

**Comment by mpirvu** [comment]
I see the same linter errors in other PRs that were ported to 0.28.0, so it's not like this PR introduced some bad code.

**Comment by EmanElsaban** [comment]
yes I just cherry picked he commit in master
```
root@flood1:~/openj9# git cherry-pick b995355c7462d05238fdb2a5a4e76b8955cf1577
[overrideFrontEndCall-0.28 eb8d7a8b3] [WIP] Overrode ```TR_J9VMBase::delegatingMethodHandleTarget``` for JITServer
 Date: Fri Aug 27 16:20:16 2021 -0700
 7 files changed, 43 insertions(+), 12 deletions(-)
```

**Pull request merged**
