### PR TITLE
Use the new centos6 image to build xlinux with gcc 11.2

### PR DESCRIPTION
**Pull request by pshipton**
See https://github.com/eclipse-openj9/openj9/pull/18477

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile xlinux jdk8,jdk11

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/4771/

**Comment by pshipton** [comment]
The original PR build finished successfully.

**Comment by pshipton** [comment]
Updated to address the latest (internal) review comments.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
