### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by LinHu2016**
Need to pass structure pointer instead of structure for the parameter of Assert_GC_true_with_message2().

Signed-off-by: Lin Hu <linhu@ca.ibm.com>

### CODE REVIEW

**Comment by amicic** [comment]
jenkins compile all jdk19

**Comment by pshipton** [comment]
jenkins compile aix jdk8

**Comment by pshipton** [comment]
Should helpers not needed earlier than jdk19 be #ifdef'ed out so they don't affect the earlier versions?

**Comment by pshipton** [comment]
For the record, the "typo" breaks compilation with xlc 13 on Java 8.

**Comment by amicic** [comment]
> Should helpers not needed earlier than jdk19 be #ifdef'ed out so they don't affect the earlier versions?

The helpers should not be active for earlier versions (higher level should would not try to use them), but even if they do, helpers should not cause any harm. But we could ifdef the body of the methods and in else clause assert unreachable, although I'm not very eager to do that. 

@dmitripivkine

**Comment by dmitripivkine** [comment]
I agree with Aleks. This is common GC code and continuation object happen to be exist (and helper called) in Java 19 only. I prefer cleaner easy to read code without ifdefs for particular Java version over possibility to reduce size of executable slightly.

**Review by dmitripivkine — APPROVED** [review]

**Review by pshipton — APPROVED** [review]

**Pull request merged**
