### PR TITLE
Return NULL from getStackTraceForThread for unsteady virtual threads

### PR DESCRIPTION
**Pull request by babsingh**
If `inspectorCount` is `-1`, then the virtual thread is in an unsteady
state (mounting or unmounting). In such cases, `NULL` should be returned
and the JCL code should retry in order to avoid unexpected behavior.

Related: #18910

### CODE REVIEW

**Comment by babsingh** [comment]
jenkins test sanity.functional,sanity.openjdk xmac,amac,zlinux jdk23

**Comment by babsingh** [comment]
jenkins test sanity.functional,sanity.openjdk xmac jdk21

**Review by fengxue-IS — APPROVED** [review]
lgtm

**Comment by babsingh** [comment]
@tajila Requesting your review. A [250x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/43889) has passed along with internal personal builds. Further, the PR builds have also passed.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
please make a 0.48 PR

**Comment by babsingh** [comment]
0.48 PR: https://github.com/eclipse-openj9/openj9/pull/20313.

**Pull request merged**
