### PR TITLE
Fix compile error for JAVA_SPEC_VERSION < 19

### PR DESCRIPTION
**Pull request by keithc-ca**
Introduced in https://github.com/eclipse-openj9/openj9/pull/18964.

### CODE REVIEW

**Comment by keithc-ca** [comment]
FYI @tajila

**Comment by keithc-ca** [comment]
Jenkins compile alinux jdk17,jdk21

**Comment by keithc-ca** [comment]
Added the required (empty) statement after the label.

**Comment by keithc-ca** [comment]
Jenkins compile alinux jdk17,jdk21

**Review by pshipton — APPROVED** [review]

**Pull request merged**
