### PR TITLE
Add copyFieldsFromContinuation helper to internalVMFunctions

### PR DESCRIPTION
**Pull request by fengxue-IS**
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
jenkins test sanity amac,win jdk19

**Comment by babsingh** [comment]
@fengxue-IS There is a merge conflict from https://github.com/eclipse-openj9/openj9/pull/15876.

**Comment by babsingh** [comment]
Old builds: https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/2696/

**Comment by babsingh** [comment]
Tried the GUI feature to resolve merge conflicts but it added another commit and didn't correctly rebase.

**Comment by fengxue-IS** [comment]
Fixed rebase with force push

**Comment by babsingh** [comment]
jenkins test sanity amac jdk19

**Review by babsingh — APPROVED** [review]

**Pull request merged**
