### PR TITLE
Delay Continuation's native allocation to first mount

### PR DESCRIPTION
**Pull request by fengxue-IS**
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
Is this ready @fengxue-IS

**Comment by fengxue-IS** [comment]
local testing on xlinux passed for me, launched [personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/15010/) to verify no test failure. will mark this as ready once test passed.

**Review by gacholio — APPROVED** [review]
`createContinuation` should be made static.

**Comment by tajila** [comment]
jenkins test sanity win jdk19

**Pull request merged**
