### PR TITLE
Fix Inlining Bugs

### PR DESCRIPTION
**Pull request by dsouzai**
This PR fixes two bugs relating to inlining that prevented the inlining of clearly beneficial candidates.

#### Bug 1:
Previously, if the linked list in `TR_LinkedListProfilerInfo` contained two
nodes, then adding a third one would result in a memory leak as the
third node was not added to the end of the list, but rather as the next
node of the first node. This meant that there was no longer any pointer
to the original second node in the list. This PR fixes this by ensuring 
that a new node is always added to the end of the list.

#### Bug 2:
The estimated code size of methods can be negative; this is to indicate
that the method is a good candidate for inlinling. However, the logic in
weighCallSite, which contains several heuristics that adjust the size of
a candidate method, used a variable of type uint32_t.

The first issue is that the code that compares the size of a method to
the inlining budget results in promoting the inlining budget value from a
signed 32-bit integer to an unsigned 32-bit integer, because the
variable that represents the size of the candidate method is an unsigned
32-bit integer. This means that any negative size, which is supposed to
represent a good candidate method, will actually cause the inliner to
make the determination that it is a very bad candidate method.

The second issue is that even if if the comparison was fixed to cast the
size variable to be a signed 32-bit integer, the heuristics prior to
that point that adjust the size can result in an overflow that now
leaves the size variable with a very large signed positive number, which
again, causes the inliner to make the determination that the candidate
method is very bad for inlining.

This PR fixes both issues by
1. Changing the size variable to be of type int32_t
2. Only allowing the heuristics to adjust the size if it is positive.

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
Jenkins test sanity all jdk17

**Comment by dsouzai** [comment]
jenkins test sanity.functional all jdk17

**Review by nbhuiyan — COMMENTED** [review]
If `size` is negative by the time we get to 

https://github.com/eclipse-openj9/openj9/blob/b669217a6bfffc51e01fd48d364af4bf120e3c21/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L3678

Then we perform right shifts on negative int, which is undefined behaviour:

https://github.com/eclipse-openj9/openj9/blob/b669217a6bfffc51e01fd48d364af4bf120e3c21/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L3693-L3699

So perhaps since this is somewhat related, it might be worth ensuring we only do the right shifts if weight/size is positive.

**Comment by nbhuiyan** [comment]
While this fix is necessary, I also do not think
https://github.com/eclipse-openj9/openj9/blob/b669217a6bfffc51e01fd48d364af4bf120e3c21/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L3421
should be returning a negative.

Looking at a log that @dsouzai shared with me:
```
Reduced size estimate to -3 (subtract num args * 4)
*** Depth 0: Adjusting size for java/lang/Object.<init>()V because of constants in args from 1 to -3
--- Done Iterating over Bytecodes in call to java/lang/Object.<init>()V.  size = -3 _recursionDepth = 0 _optimisticSize = 0 _realSize = 0 _sizeThreshold = 1024
```

The size turned into a negative value because of the following:
https://github.com/eclipse-openj9/openj9/blob/b669217a6bfffc51e01fd48d364af4bf120e3c21/runtime/compiler/optimizer/J9EstimateCodeSize.cpp#L538-L542

That's strange because this adjustment is disabled by default, guarded by the env variable:
https://github.com/eclipse-openj9/openj9/blob/b669217a6bfffc51e01fd48d364af4bf120e3c21/runtime/compiler/optimizer/J9EstimateCodeSize.cpp#L429-L431

**Comment by dsouzai** [comment]
I recently rebased on my changes onto a more recent master, and I don't see the same message anymore; I guess my build was based on a SHA before you added https://github.com/eclipse-openj9/openj9/commit/92821ae22d35c783f370ac842e90938e87a828f2. Now it looks more like:
```
Depth 0: Opt Server is reducing size of call to 1
--- Depth 0: Checking Optimistic size vs Size Threshold: _optimisticSize 1 _sizeThreshold 2500 sizeThreshold 2500
*** Depth 0: ECS end for target 0x7f51ffd17f80 signature java/lang/Object.<init>()V. It is a full inline Candidate with a full size of 1
--- Depth 0: Checking _real size vs Size Threshold A second Time: _realSize 1 _sizeThreshold 2500 sizeThreshold 2500
WeighCallSite: For Target 0x7f51ffd17f80 node 0x7f51ffc88790 signature java/lang/Object.<init>()V, estimation returned a size of 1
WeighCallSite: Considering shrinking call 0x7f51ffc88790 with frequency 10000

WeighCallSite: Adjusted call-graph size for call node 0x7f51ffc88790, from 1 to 0

WeighCallSite: For Target 0x7f51ffd17f80 node 0x7f51ffc88790, size after size mangling 0
Beginning of Weight Calculation. Setting weight to 0
Setting weight to 0 after frontend adjusted weight for address parm 0x7f51ffc88740

Setting weight to -4 (subtracting numArgs*4)
Setting weight to -8 because method is a leaf method
WeighCallSite:  Adding call target 0x7f51ffd17f80 node 0x7f51ffc88790 with calleeSymbol = 0x7f51ffcd4330 to list of call sites with guard 0x7f51ffd17f40 kind = 8type = 3 weight = -8 (adjusted by frequencyAdjustment of 249758756) callGraphAdjustedWeight = 1
^^^ Done Weighing of all targets in CallSite 0x7efed51c9900 callnode 0x7f51ffc88790
```

**Comment by dsouzai** [comment]
jenkins test sanity.functional all jdk17

**Comment by nbhuiyan** [comment]
I think the root cause of the perf regressions that #17900 was attempting to address (by disabling some adjustments) was actually caused by the negative sizes obtained from ECS. I was able to replicate this behaviour today (without this fix) in some local testing with `TR_enableArgCountWeightAdjustment` set and we do end up with negative sizes that blow up during `weighCallSite`.

@vijaysun-omr Based on that, we could perhaps consider re-enabling those size adjustments disabled by #17900 after this PR is merged. What do you think?

**Comment by vijaysun-omr** [comment]
I certainly feel you should re-evaluate that change with this negative size issue in mind, @nbhuiyan

**Comment by vijaysun-omr** [comment]
Given the above discussion, there is still utility in having these changes in since they address a scenario that @nbhuiyan prototype changes did create in past experimentation (and may well create in future). If there are no counterpoints, I will merge later in the day

**Pull request merged**
