### PR TITLE
Build jdk19+ Windows with VS 2022

### PR DESCRIPTION
**Pull request by pshipton**
Issue https://github.com/eclipse-openj9/openj9/issues/16701

Created https://github.com/adoptium/temurin-build/pull/3251 for the Adoptium pipelines.

Doc issue https://github.com/eclipse-openj9/openj9-docs/issues/1055

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,sanity.openjdk win jdk19,jdk20

**Comment by pshipton** [comment]
The failure in Windows sanity.openjdk is a known issue.
https://github.com/eclipse-openj9/openj9/issues/16657

**Comment by pshipton** [comment]
@AdamBrousseau this is ready to go but we need to be ready internally before this is merged.

**Comment by AdamBrousseau** [comment]
See #15495
I don't think the 2012 machines have VS2022.
Although we seem to only have the build label on a few machines at the moment.
https://openj9-jenkins.osuosl.org/label/sw.os.windows&&ci.role.build/
image
So if we aren't going back to compiles on the old 2012s then I think this is good as is.

**Comment by pshipton** [comment]
> So if we aren't going back to compiles on the old 2012s then I think this is good as is.

I'm not expecting to go back. Compiling on 2019s isn't perfect, as per https://github.com/eclipse-openj9/openj9/issues/16515, but is the way forward.

**Pull request merged**
