### PR TITLE
(0.30.0) Add release documentation for java option `-XX:[+|-]EnsureHashed`

### PR DESCRIPTION
**Pull request by pshipton**
See https://github.com/eclipse-openj9/openj9/pull/14042

Cherry pick https://github.com/eclipse-openj9/openj9/pull/14060 for the 0.30 release.

### CODE REVIEW

**Comment by pshipton** [comment]
The copyright check failed because of the cherry pick from a change made last year, but it will get updated when https://github.com/eclipse-openj9/openj9/pull/14305 is ported to 0.30.

**Review by keithc-ca — CHANGES_REQUESTED** [review]
Please fix copyright date.

**Comment by pshipton** [comment]
> Please fix copyright date or provide a link to the PR that will fix it.

I suspect I need this merged before I cherry pick https://github.com/eclipse-openj9/openj9/pull/14316 for the 0.30 branch.

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9/pull/14317

**Comment by keithc-ca** [comment]
> I suspect I need this merged before I cherry pick #14305 for the 0.30 branch.

That doesn't appear to be the case, so we can merge the cherry-pick of 14305 then this.

**Comment by keithc-ca** [comment]
jenkins copyright check

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
