### PR TITLE
Disable certain weight adjustments during early ECS

### PR DESCRIPTION
**Pull request by nbhuiyan**
Weight adjustments done during ECS based on arg count and whether args are load consts or boxed primitive can have a negative impact on certain workloads due to overly aggressive inlining. They are now guarded within environment variables.

### CODE REVIEW

**Comment by nbhuiyan** [comment]
@vijaysun-omr / @0xdaryl requesting review. Guarding the problematic weight adjustments through environment variables addresses the regression seen in some workloads.

**Comment by vijaysun-omr** [comment]
I'll defer to @0xdaryl on this since I will be away.

**Comment by 0xdaryl** [comment]
Jenkins test all sanity jdk17

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity aix,win jdk11

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
