### PR TITLE
Auto-download OpenSSL on Windows

### PR DESCRIPTION
**Pull request by AdamBrousseau**
If OpenSSL is not present on machine, download
it to our expected location

Related #14208

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
jenkins compile win jdk11

**Comment by AdamBrousseau** [comment]
jenkins compile win jdk11

**Comment by AdamBrousseau** [comment]
jenkins compile win jdk11

**Comment by AdamBrousseau** [comment]
jenkins compile win jdk11

**Comment by AdamBrousseau** [comment]
jenkins compile win jdk11

**Comment by AdamBrousseau** [comment]
Use case "OpenSSL exists"
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_windows_Personal/298/console
```
18:20:15  Check for OpenSSL install...
[Pipeline] sh
18:20:16  + test -e /cygdrive/f/Users/jenkins/openssl/OpenSSL-1.1.1m-x86_64-VS2017
18:20:16  + echo true
[Pipeline] echo
18:20:17  OpenSSL found at /cygdrive/f/Users/jenkins/openssl/OpenSSL-1.1.1m-x86_64-VS2017
[Pipeline] stage
[Pipeline] { (Get Source)
[Pipeline] sh
18:20:18  + git clone -b openj9 https://github.com/ibmruntimes/openj9-openjdk-jdk11.git . --reference /home/jenkins/openjdk_cache
```
Use Case "No OpenSSL present"
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_windows_Personal/299/console
```
18:21:54  Check for OpenSSL install...
[Pipeline] sh
18:21:55  + test -e /cygdrive/f/Users/jenkins/openssl/OpenSSL-1.1.1m-x86_64-VS2017
18:21:55  + echo false
[Pipeline] echo
18:21:56  Downloading OpenSSL...
[Pipeline] dir
18:21:56  Running in F:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_Personal\openssl
[Pipeline] {
[Pipeline] sh
18:21:57  + curl -Ok https://openj9-jenkins.osuosl.org/userContent/OpenSSL-1.1.1m-x86_64-VS2017.zip
18:21:57    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
18:21:57                                   Dload  Upload   Total   Spent    Left  Speed
18:21:59  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 18.7M    0 48536    0     0  94062      0  0:03:28 --:--:--  0:03:28 94612
 73 18.7M   73 13.7M    0     0  9252k      0  0:00:02  0:00:01  0:00:01 9264k
100 18.7M  100 18.7M    0     0  10.6M      0  0:00:01  0:00:01 --:--:-- 10.6M
18:21:59  + unzip OpenSSL-1.1.1m-x86_64-VS2017.zip
18:21:59  Archive:  OpenSSL-1.1.1m-x86_64-VS2017.zip
18:21:59     creating: OpenSSL-1.1.1m-x86_64-VS2017/
...
...
18:22:03  + rm OpenSSL-1.1.1m-x86_64-VS2017.zip
18:22:03  + mkdir -p /cygdrive/f/Users/jenkins/openssl
18:22:03  + mv OpenSSL-1.1.1m-x86_64-VS2017 /cygdrive/f/Users/jenkins/openssl/
[Pipeline] }
[Pipeline] // dir
[Pipeline] cleanWs
18:22:03  [WS-CLEANUP] Deleting project workspace...
18:22:03  [WS-CLEANUP] Deferred wipeout is used...
18:22:03  [WS-CLEANUP] done
[Pipeline] stage
[Pipeline] { (Get Source)
[Pipeline] sh
18:22:05  + git clone -b openj9 https://github.com/ibmruntimes/openj9-openjdk-jdk11.git . --reference /home/jenkins/openjdk_cache
```

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
@AdamBrousseau I've seen this a couple of times.
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-32_windows_OMR/162/console
```
13:02:23  + rm OpenSSL-1.1.1m-x86_32-VS2013.zip
13:02:23  + mkdir -p /cygdrive/f/Users/jenkins/openssl
13:02:23  + mv OpenSSL-1.1.1m-x86_32-VS2013 /cygdrive/f/Users/jenkins/openssl/
[Pipeline] }
[Pipeline] // dir
[Pipeline] cleanWs
13:02:23  [WS-CLEANUP] Deleting project workspace...
13:02:23  [WS-CLEANUP] Deferred wipeout is used...
13:02:23  ERROR: Cannot delete workspace :Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_OMR'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[Pipeline] cleanWs
13:02:24  [WS-CLEANUP] Deleting project workspace...
13:02:24  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
13:02:24  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
ERROR: Cannot delete workspace: Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_OMR'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Finished: FAILURE
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_windows_OpenJDK17/18/console

**Comment by pshipton** [comment]
Something's not working, there is another failure on win2012-x86-9
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_windows_OMR/165/console

**Comment by AdamBrousseau** [comment]
We've seen this before with windows cleanWS. We have a function to deal with it. I'll open a PR. Once the openssl version is populated on each machine for each of the 4 versions we won't go down this code path anymore.

**Pull request merged**
