### PR TITLE
Disallow error report/abort during ASGCT stack walk

### PR DESCRIPTION
**Pull request by gacholio**
Do not allow printing of error messages or aborting the VM during the
stack walk in AsyncGetCallTrace.

Add a new stackwalk flag for this to replace the unreliable errorMode
field and update the other users accordingly.

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity xlinux jdk8

**Comment by tajila** [comment]
Jenkins test sanity,extended win jdk11

**Comment by tajila** [comment]
failure looks like network/machine issues

**Comment by tajila** [comment]
Jenkins test sanity xlinux jdk8

**Comment by pshipton** [comment]
This seems to be causing illegal instruction crashes on zlinux 32-bit in an internal build
jobs_by_status.php?build_id=6469&status=FAILED&categories=17

I expect to revert this shortly.

**Comment by gacholio** [comment]
I don't see how that's possible.

**Pull request merged**
