### PR TITLE
Fix jvmnativestest test_EnsureWallClockTime()

### PR DESCRIPTION
**Pull request by keithc-ca**
Fixes: #11293.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity aix,osx,plinux,win32 jdk8

**Comment by pshipton** [comment]
Grinders can handle the testing. The test isn't enabled on jdk8 for some reason, tested jdk11.

AIX - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/377
OSX - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/378
plinux - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/379
zlinux - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/380
win - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/381

**Comment by pshipton** [comment]
There aren't any OSX machines available atm, but all other platforms passed. I'll assume OSX won't be a problem.

**Review by pshipton — APPROVED** [review]

**Comment by keithc-ca** [comment]
The implementation of `omrtime_current_time_nanos()` is different on OSX, but not enough so to be concerned that we'll see failures there.

**Comment by pshipton** [comment]
I'll check the grinder later.

**Comment by pshipton** [comment]
The OSX grinder did pass.

**Comment by pshipton** [comment]
I'm going to revert this. In PR testing for https://github.com/eclipse-openj9/openj9/pull/13899, jvmnativestest_0 failed twice, both on zlinux.

**Pull request merged**
