### PR TITLE
(0.38) Handle lock reservation in single thread mode

### PR DESCRIPTION
**Pull request by tajila**
(0.38) Handle lock reservation in single thread mode

Cancel reservation on blocking enter in single thread mode to prevent throwing blocking exceptions on uncontended acquires. This PR just attempts to cancel the reservation once and acquire the lock again. We only need to attempt the cancel once since its single thread mode.

### CODE REVIEW

**Comment by tajila** [comment]
@pshipton Please review and merge

**Comment by tajila** [comment]
@babsingh Peter is away, can you take a look

**Comment by tajila** [comment]
backport of https://github.com/eclipse-openj9/openj9/pull/16812

**Review by babsingh — APPROVED** [review]
also backports https://github.com/eclipse-openj9/openj9/pull/16819

**Pull request merged**
