### PR TITLE
Minor corrections for checkpointthreads NLS

### PR DESCRIPTION
**Pull request by amicic**
Adding periods at the end of messages

### CODE REVIEW

**Comment by dmitripivkine** [comment]
Jenkins line endings check

**Review by dmitripivkine — APPROVED** [review]

**Comment by dmitripivkine** [comment]
Jenkins compile win,xLinux jdk21

**Comment by dmitripivkine** [comment]
Jenkins compile win,xLinux jdk21

**Review by pshipton — APPROVED** [review]

**Comment by keithc-ca** [comment]
Why do we want these message to end with periods when the vast majority of other messages do not?

**Comment by pshipton** [comment]
They are sentences. I expect they should all end in periods, as they seem to do in the IBM published documentation (https://www.ibm.com/docs/en/sdk-java-technology/8?topic=messages-j9gc). Fixing the others was left as an exercise for the future. I'm not aware the IBM docs are being actively updated with new messages.

**Comment by keithc-ca** [comment]
The explanations, etc, end with periods in that documentation, but not the actual messages, so my question remains.

**Comment by pshipton** [comment]
The messages in this case consist of two sentences. It would be weird to not end the second sentence with a period. These messages are printed to the console when command line options are incorrect, it makes sense they are sentences that end with periods.

**Pull request merged**
