### PR TITLE
TGC alloc stats for dual TLH

### PR DESCRIPTION
**Pull request by amicic**
Print pre-thread refresh and remaining size of TLHs for both zero and non-zero case.

### CODE REVIEW

**Comment by amicic** [comment]
Sample print:

```
   JVM thread ID |                                                                             name | refresh/remaining cache size | refresh/remaining non-0 cache | obj alloc count/bytes | TLH fresh count/bytes | TLH discards
00000000007F3A00 |                                                                  RunDataWriter.1 |           4096             0 |          24576          11952 |        0            0 |        1        20480 |            0
000000000080FA00 |                                                                       Controller |          20480          6224 |         102400          25976 |        0            0 |       11       765952 |         2576
000000000080E100 |                                                                     MapReducer.1 |          28672         10528 |          77824          43152 |        0            0 |       14       561152 |          256
```

**Comment by amicic** [comment]
@dmitripivkine Any preference if non-0 should be printed first (since it's always used if both are present)?

**Comment by dmitripivkine** [comment]
I think P and Z uses both zeroed and not zeroed. I am not sure about current status for X and A. I think current output format is good enough.

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux,AIX,win jdk11

**Pull request merged**
