### PR TITLE
x86: add option to disable AVX-512

### PR DESCRIPTION
**Pull request by BradleyWood**

### CODE REVIEW

**Comment by BradleyWood** [comment]
FYI, @hzongaro @JamesKingdon

**Comment by vij-singh** [comment]
FYI @0xdaryl

**Comment by 0xdaryl** [comment]
Jenkins test sanity.functional,sanity.openjdk xlinux,win,osx jdk21

**Review by 0xdaryl — APPROVED** [review]
I think enough of these tests have run to demonstrate that this change is not causing any issues.

Eventually, a solution beyond the JIT will be needed to prevent AVX512 usage, but as nothing else leverages this now that is beyond the experimental stage, this is adequate for now.

**Comment by 0xdaryl** [comment]
This seems safe enough to put into 0.48 as well.  Please make it so.

**Comment by pshipton** [comment]
It looks safe enough. We're about to start 0.48 RC1 asap.

**Comment by vij-singh** [comment]
@BradleyWood Can you please merge into 0.48 asap?

**Comment by BradleyWood** [comment]
@pshipton See #20360

**Pull request merged**
