### PR TITLE
Clean up x86 monent/monexit inline sequences

### PR DESCRIPTION
**Pull request by 0xdaryl**
Remove many deprecated and experimental features.  Miscellaneous code cleanup.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux,osx,win jdk17

**Comment by 0xdaryl** [comment]
@BradleyWood : I'd appreciate a review from you please.

**Review by BradleyWood — APPROVED** [review]

**Comment by 0xdaryl** [comment]
I'll also add that I tested this internally within IBM on IBM SDK 8 32-bit Linux and Windows platforms.

**Comment by 0xdaryl** [comment]
@zongaro : would you mind final reviewing and merging this please?  Brad has already reviewed and approved.

**Comment by 0xdaryl** [comment]
The Linux test failure is very likely the intermittent #13577, but it does make me a bit uneasy as this PR directly affects the JIT lockword code that that test is stressing.  I will re-run the Linux tests just to be sure.

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux jdk17

**Comment by 0xdaryl** [comment]
All tests have passed now.  @hzongaro : please proceed when you have a chance.  Thanks.

**Comment by hzongaro** [comment]
> All tests have passed now. @hzongaro : please proceed when you have a chance. Thanks.

Sorry!  I had missed the review request.  Taking a look now.

**Review by hzongaro — APPROVED** [review]
Looks good

**Pull request merged**
