### PR TITLE
Adopt TR::InstOpCode on x86

### PR DESCRIPTION
**Pull request by fjeremic**
This PR is a sequence of commits each of which is able to compile on its own and which systematically eliminate `TR_X86OpCodes` and `TR_X86OpCode` in favour of `TR::InstOpCode::Mnemonic` and `TR::InstOpCode` respectively. Please see each commit message for what was done and why. Semantically there should be no change in behaviour following these changes.

There is still two large pieces of work do be done which will be handled in separate PRs so as to avoid introducing hundreds (thousands?) more changes here:

1. Currently we have a temporary “defines” file which for every opcode does for example #define   ADC1AccImm1 OMR::InstOpCode::ADC1AccImm1. Ideally we would like to get rid of this defines file and qualify all x86 instruction mnemonics with TR::InstOpCode:: as we do on all other platforms. This unfortunately introduces many many lines changed as you can imagine. It is largely mechanical work though.
2. Introduce OMRInstOpCodeProperties.hpp as we do on other platforms instead of using X86Ops.inc. This is also a mechanical change. After reading more of the x86 codegen I believe we should standardize a way to do this cross-platform similarly to how we centralized the IL opcodes. Looks like x86 more or less does this but in its own custom way. It would be really nice to do this cross-platform. This change will get us consistent with other platforms, making such future work of centralizing instruction properties, names, descriptions, encodings, etc. much easier if we start from a common “look and feel”. This will introduce many more lines changed but is all mechanical.

Depends on eclipse/omr#6020

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins test sanity.functional,extended.functional,sanity.system,extended.system,special.system,sanity.openjdk xlinux,win,osx jdk8,jdk11 depends eclipse/omr#6020

**Comment by fjeremic** [comment]
@0xdaryl @BradleyWood this one should be ready for review.

**Comment by fjeremic** [comment]
Jenkins test extended.system,sanity.openjdk mac,win jdk8,jdk11 depends eclipse/omr#6020

**Comment by fjeremic** [comment]
Jenkins test extended.system,sanity.openjdk osx,win jdk8,jdk11 depends eclipse/omr#6020

**Comment by fjeremic** [comment]
Jenkins test sanity.openjdk win jdk11 depends eclipse/omr#6020

**Comment by 0xdaryl** [comment]
Jenkins test sanity osx,win,linux jdk8,jdk11 depends eclipse/omr#6020

**Comment by 0xdaryl** [comment]
For the record, the week-old extended system and sanity test was completely clean.

**Comment by 0xdaryl** [comment]
Jenkins test sanity osx,win,xlinux jdk8,jdk11 depends eclipse/omr#6020

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Both sanity failures are infrastructural as the Jenkins nodes went offline during the run.  With the successful stress test run from a week ago coupled with the sanity platforms that did succeed last night I am confident in this change.  Merging.

**Pull request merged**
