### PR TITLE
Check for Qtype static field

### LINKED ISSUE #13344: Invalid instanceClass in VM_BytecodeInterpreterCompressed::checkcast for Value Type
I'm seeing a crash when running a microbench `ACMPPrimitiveAlwaysEqualBench` with `-Xint`. The microbench compares VT array elements with a static VT field instance. It crashed on the path of `VM_BytecodeInterpreterCompressed::checkcast`. The `instanceClass` is either corrupted or `NULL`. It looks to me it tries to check whether the static field instance on the stack is a type of `java/lang/Object`. (Attached `BumbleBenchValhalla.jar` and `ACMPPrimitiveAlwaysEqualBench.java` at the end of the description)

```
root/home/ahuo/src/openj9-openjdk-jdk17/build/linux-x86_64-server-release/images/jdk/bin/java -XX:+EnableValhalla -Xint -Xverify:none -jar BumbleBenchValhalla.jar ACMPPrimitiveAlwaysEqualBench

JVMJ9VM193W Since Java 13 -Xverify:none and -noverify were deprecated for removal and may not be accepted options in the future.

-= BumbleBench series 7 version 5.10 running ACMPPrimitiveAlwaysEqualBench  Wed Aug 18 13:40:01 PDT 2021 =-

              Target	Est	Uncert%	MaxPeak	Peak	Peak%	%paused
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007FA9E7C147E0 Handler2=00007FA9E73E41A0 InaccessibleAddress=0000000000000018
RDI=0000000000000000 RSI=0000000000041200 RAX=0000000000000000 RBX=0000000000000000
RCX=00000000001E0000 RDX=0000000000041200 R8=00000000020E0001 R9=0000000000000000
R10=00000000001CB9E0 R11=0000000000000012 R12=0000000000120C10 R13=00000000A2EB08E8
R14=000000000001AA00 R15=0000000000000000
RIP=00007FA9E7C8360C GS=0000 FS=0000 RSP=00007FA9ECFF0130
EFlags=0000000000010246 CS=0033 RBP=00000000001CB4B0 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000018
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 676e616c2f617661 (f: 794916480.000000, d: 1.692010e+190)
xmm2 ffffffffffffffff (f: 4294967296.000000, d: -nan)
xmm3 0073004500090074 (f: 589940.000000, d: 1.691150e-306)
xmm4 00007fa9ecff0530 (f: 3976135936.000000, d: 6.935091e-310)
xmm5 ffffffffffffffff (f: 4294967296.000000, d: -nan)
xmm6 ffffffffffffffff (f: 4294967296.000000, d: -nan)
xmm7 0000000000275fb0 (f: 2580400.000000, d: 1.274887e-317)
xmm8 0000000000276030 (f: 2580528.000000, d: 1.274950e-317)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/root/home/ahuo/src/openj9-openjdk-jdk17/build/linux-x86_64-server-release/images/jdk/lib/default/libj9vm29.so
Module_base_address=00007FA9E7BD4000
Target=2_90_20210816_000000 (Linux 4.15.0-147-generic)
CPU=amd64 (8 logical CPUs) (0x17477d000 RAM)
----------- Stack Backtrace -----------
(0x00007FA9E7C8360C [libj9vm29.so+0xaf60c])
(0x00007FA9E7C68F65 [libj9vm29.so+0x94f65])
(0x00007FA9E7D359F2 [libj9vm29.so+0x1619f2])
---------------------------------------
```

```
...
#12 <signal handler called>
#13 0x00007fb82547961e in VM_VMHelpersCompressed::isSameOrSuperclass (subClass=<optimized out>, superClass=<optimized out>)
    at /root/hostdir/openj9/runtime/oti/VMHelpers.hpp:521
#14 VM_VMHelpersCompressed::inlineCheckCast (updateCache=<optimized out>, castClass=0x1b600, instanceClass=0xfff38200)
    at /root/hostdir/openj9/runtime/oti/VMHelpers.hpp:548
#15 VM_BytecodeInterpreterCompressed::checkcast (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /root/hostdir/openj9/runtime/vm/BytecodeInterpreter.hpp:7616
#16 VM_BytecodeInterpreterCompressed::run (this=0x0, this@entry=0x7fb826443fb0, vmThread=0xfff38200)
    at /root/hostdir/openj9/runtime/vm/BytecodeInterpreter.hpp:10722
#17 0x00007fb82545ef65 in bytecodeLoopCompressed (currentThread=<optimized out>)
    at /root/hostdir/openj9/runtime/vm/BytecodeInterpreter.inc:112
#18 0x00007fb82552b9f2 in c_cInterpreter () at /root/hostdir/build/linux-x86_64-server-release/vm/runtime/vm/xcinterp.s:158
...

(gdb) fr 15
#15 VM_BytecodeInterpreterCompressed::checkcast (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /root/hostdir/openj9/runtime/vm/BytecodeInterpreter.hpp:7616
7616					if (!VM_VMHelpers::inlineCheckCast(instanceClass, castClass)) {
(gdb) print instanceClass
$2 = (J9Class *) 0xfff38200
(gdb) print castClass
$3 = (J9Class * volatile) 0x1b600

> !j9class 0xfff38200
J9Class at 0xfff38200 {
  Fields for J9Class:
	0x0: UDATA eyecatcher = 0x60807060C4216000 (6953681385569738752)
...
> > !j9class 0x1b600
J9Class at 0x1b600 {
  Fields for J9Class:
	0x0: UDATA eyecatcher = 0x0000000099669966 (2573637990)
...
}
Class name: java/lang/Object
To view static fields, use !j9statics 0x000000000001B600
To view instance shape, use !j9classshape 0x000000000001B600

...

> !stackslots 0x0001aa00                       
<1aa00> *** BEGIN STACK WALK, flags = 00400001 walkThread = 0x000000000001AA00 ***
<1aa00> 	ITERATE_O_SLOTS
<1aa00> 	RECORD_BYTECODE_PC_OFFSET
<1aa00> Initial values: walkSP = 0x00000000000E2F88, PC = 0x0000000000000001, literals = 0x0000000000000000, A0 = 0x00000000000E2FA0, j2iFrame = 0x0000000000000000, ELS = 0x00007FB826444220, decomp = 0x0000000000000000
<1aa00> Generic special frame: bp = 0x00000000000E2FA0, sp = 0x00000000000E2F88, pc = 0x0000000000000001, cp = 0x0000000000000000, arg0EA = 0x00000000000E2FA0, flags = 0x0000000000000000
<1aa00> Bytecode frame: bp = 0x00000000FFEEA7E0, sp = 0x00000000000E2FA8, pc = 0x00007FB8202F7335, cp = 0x00000000001857C0, arg0EA = 0x00000000FFEEA818, flags = 0x0000000000000000
<1aa00> 	Method: net/adoptopenjdk/bumblebench/valhalla/ACMPPrimitiveAlwaysEqualBench.doBatch(J)J !j9method 0x0000000000185470
<1aa00> 	Bytecode index = 29
Aug 18, 2021 4:46:30 PM com.ibm.j9ddr.vm29.events.DefaultEventListener corruptData
WARNING: CorruptData encountered iterating o-slots. walkThread = 0x000000000001AA00
com.ibm.j9ddr.CorruptDataException: Corrupt frame detected : 140428790690613
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkBytecodeFrameSlots(StackWalker.java:908)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkBytecodeFrame(StackWalker.java:1010)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:451)
...

        if (ints[j] == VALUE1)
==>
        22: aload_0
        23: getfield      #11                 // Field ints:[Qnet/adoptopenjdk/bumblebench/valhalla/SingleFieldPrimitive;
        26: iload         6
        28: aaload
        29: checkcast     #18                 // class java/lang/Object
        32: getstatic     #15                 // Field VALUE1:Qnet/adoptopenjdk/bumblebench/valhalla/SingleFieldPrimitive;
        35: checkcast     #18                 // class java/lang/Object
        38: if_acmpne     44
```

[Archive.zip](https://github.com/eclipse-openj9/openj9/files/7016190/Archive.zip)

### PR DESCRIPTION
**Pull request by hangshao0**
Fixes #13344

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by hangshao0** [comment]
The jdknext builds triggered failed the same way as https://github.com/eclipse-openj9/openj9/pull/13395#issuecomment-906690576. I guess PR https://github.com/eclipse-openj9/openj9/pull/13397 needs to be merged to unblock jdknext builds.

**Comment by tajila** [comment]
Yes, Id like to promote the JDKnext staging branch. That should fix all the issues.

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
@JasonFengJ9 it is still failing with 

```
14:52:02  ERROR: Build failed for target 'all' in configuration 'linux-x86_64-server-release' (exit code 2) 
14:52:02  
14:52:02  === Output from failing command(s) repeated here ===
14:52:02  * For target jdk_modules_java.compiler__the.java.compiler_batch:
14:52:02  /home/jenkins/workspace/Build_JDKnext_x86-64_linux_vt_standard_Personal/src/java.compiler/share/classes/javax/tools/ToolProvider.java:144: warning: [removal] AccessController in java.security has been deprecated and marked for removal
14:52:02          return AccessController.doPrivileged(pa);
14:52:02                 ^
14:52:02  error: warnings found and -Werror specified
14:52:02  1 error
14:52:02  1 warning
```

Even though jdknext has promoted staging changes

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by JasonFengJ9** [comment]
> 16:53:38  Unhandled exception
16:53:38  Type=Segmentation error vmState=0x000501ff
16:53:38  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
16:53:38  Module=/home/jenkins/workspace/Build_JDKnext_x86-64_linux_valhalla_Personal/build/linux-x86_64-server-release/jdk/lib/default/libj9jit29.so

This seems the known issue https://github.com/eclipse-openj9/openj9/issues/13411

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Pull request merged**
