### PR TITLE
Force a GC pre-checkpoint Part1

### PR DESCRIPTION
**Pull request by tajila**
Force a GC pre-checkpoint

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
Hi Dmitri can you please take a look at this.

Im wondering if this is any different from using the `J9MMCONSTANT_EXPLICIT_GC_IDLE_GC` flag

**Comment by dmitripivkine** [comment]
> I'm wondering if this is any different from using the J9MMCONSTANT_EXPLICIT_GC_IDLE_GC flag

The difference of IDLE_GC is extra walk over heap pages and release each unused by calling `madvise(MADV_DONTNEED)` in `decommit()`. I don't know can it reduce size of CRIU image. I believe it has been tested at early stages and image size reduction has not been observed.

@amicic What do you think?

**Comment by amicic** [comment]
I do prefer a bit more IDLE over NATIVE_OUT_OF_MEMORY. The latter is not really wrong reason (we did not do it because of native OOM), and the former is relatively close to being correct (VM is about to idle for very long period of time till snapshot has been restored).

As far the effects of doing one over the other.... One can see what can of attributes are associated with a type of global GC here:
https://github.com/eclipse/omr/blob/master/gc/base/GCCode.cpp

These are the attributes:
- isExplicit: true for both (which indeed is the case, for snapshot creation scenario)
- shouldAggressivelyCompact: false for both, which is probably good enough for snapshot creation scenario  (aggressive compact are really needed for just desperate OOM scenarios and won't really affect much free memory in a typical scenario)
- isOutOfMemoryGC: true for NATIVE_OUT_OF_MEMORY and false for IDLE, and as I explained earlier (from the context of reporting a reason in Verbose GC), I prefer to go with IDLE
- isPercolateGC: false for both (which indeed is the case, for snapshot creation scenario)

What isOutOfMemoryGC being true will do is it will treat soft refs weak, hence clear them all regardless of the age. It's a tradeoff, but I don't think it's very good to do it, since it will make the restoration slower (all those objects that were softly reachable have to be recreated), and not worth the memory savings.

You are free to create a new reason and set those 4 attributes (really, 2nd and 3rd where there is a bit of dilemma) the way you want, and give a proper string reason to be reported by Verbose GC.

**Comment by amicic** [comment]
The reason while IDLE did not create smaller snapshot might be multiple. As Dmitri said, MADV_DONTNEED might not be aggressive enough. But even if it is, realistically when snapshot is typically created, relatively early just after ramp up is finished, I don't think Tenure heap is really that much expanded/committed - probably just a bit more than what the live Tenure set is.

**Comment by tajila** [comment]
Jenkins test sanity xlinuxcriu jdk11

**Comment by tajila** [comment]
I'll go with this for the time being as we have a feature cut this Friday for CRIU. 

I am working on some other changes in parallel to introduce a new explicit GC  mode `J9MMCONSTANT_EXPLICIT_GC_PREPARE_FOR_CHECKPOINT` which will take a bit longer to complete.

**Review by amicic — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity xlinuxcriu jdk11

**Pull request merged**
