### PR TITLE
Minor enhancements for performance investigation of Escape Analysis

### PR DESCRIPTION
**Pull request by hzongaro**
This pull request contains two enhancements for investigation of the run time performance impact of Escape Analysis:

1. Check the setting of the `suppressEA` option to decide whether a particular candidate for stack allocation should be prevented from being stack allocated.  This can help test the effect on performance of individual opportunities for stack allocation.
2. Added dynamic debug counters to gauge the number of contiguous and non-contiguous stack allocation opportunities that were found.

There are also a number of minor clean-up items:

1. There are two `findIgnoreableUses` methods, one of which finds uses that can be ignored, the other which marks them as ignorable.  Renamed the second to `markUsesAsIgnorable` for clarity.  Also corrected the spelling of "ignorable."
2. Fixed some trace code that printed the address of a `Candidate` object rather than the address of the `TR::Node` object associated with the `Candidate` - that is, the `Candidate::_node` field.
3. Removed method `checkAllNewsOnRHSInLoop` which was only used under control of an environment variable.  After three years, it is probably safe to remove it.

Depends on OMR pull request eclipse/omr#6872

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
I looked at the changes and they look fine to me. Maybe this ought to be changed to WIP until the OMR prereq is merged ?

**Comment by jdmpapin** [comment]
> Maybe the title of this PR ought to be changed to WIP

It's already a draft, which IMO is better than a WIP title prefix, at least because GitHub knows about it and actually blocks merging. I think we only ever had the WIP convention because draft PRs didn't exist yet.

**Comment by hzongaro** [comment]
@vijaysun-omr Vijay, this is ready for review now that eclipse/omr#6872 has been promoted.

**Comment by vijaysun-omr** [comment]
Jenkins test sanity all jdk8,jdk11,jdk19

**Review by vijaysun-omr — APPROVED** [review]

**Pull request merged**
