### PR TITLE
AArch64: Simplify stack offsets for FFI upcall on macOS

### PR DESCRIPTION
**Pull request by knn-k**
This commit partially removes macOS-specific code from FFI upcall for AArch64.

Linux and macOS use different layout for arguments passed in the stack. Arguments are always aligned at the 8-byte boundary in the stack on Linux, while macOS places arguments at 1/2/4/8-byte boundary depending on their types.
However, the arguments saved by the upcall thunk do not need to follow the layout when getArgPointer() knows it.

This commit changes the argument layout on macOS to "always at the 8-byte boundary" for the stack extended by the upcall thunk, to simplify the code.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins test sanity alinux64,amac jdk19

**Comment by knn-k** [comment]
I ran the following tests with this change on Linux and macOS manually.

- TestUpcallAsync.java
- TestUpcallHighArity.java
- TestUpcallScope.java
- TestUpcallStack.java

All the tests passed, except for TestUpcallStack.java on macOS (See Issue #16336).

**Comment by knn-k** [comment]
In the updated code,
- `stackOffset1` (for arguments in the extended stack) in `getArgPointer()` is always a multiple of 8.  `createUpcallThunk()` generates the thunk in that way.
- `stackOffset2` (for arguments in the original stack) follows the platform-specific argument layout in the stack.  `createUpcallThunk()` does not need to know it.

**Comment by knn-k** [comment]
FYI.  @zl-wang @0xdaryl

**Review by zl-wang — APPROVED** [review]
LGTM

**Pull request merged**
