### PR TITLE
Update Eclipse OMR GitHub links to eclipse-omr organization

### PR DESCRIPTION
**Pull request by 0xdaryl**

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@pshipton : I updated links in the historical OpenJ9 release notes too (in a separate commit).  I presume this is ok, but please let me know otherwise.

@AdamBrousseau : I changed the OMR repo in the dependent PR launcher, but I didn't do anything to change the trigger (it is still `eclipse/omr` as far as I can tell).  It might make sense to support both the shorter `depends eclipse/omr#1234` as well as the more "correct" `depends eclipse-omr/omr#1234`, and the existing logic might actually do that.  Can you review the groovy file changes in any case?

**Comment by AdamBrousseau** [comment]
jenkins compile amac jdk17 depends eclipse/omr#7541

**Comment by AdamBrousseau** [comment]
jenkins compile amac jdk11 depends eclipse-omr/omr#7541

**Review by AdamBrousseau — APPROVED** [review]
lftm. The depends trigger works for both `eclipse-omr/omr` and `eclipse/omr`.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
