### PR TITLE
Improve java thread test for dynamic heapification

### PR DESCRIPTION
**Pull request by gacholio**
Helperize the CRIU thread detection code.

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity xlinuxcriu jdk11

**Comment by gacholio** [comment]
Jenkins test sanity xlinuxcriu jdk11

**Comment by gacholio** [comment]
Updated include paths in CRIU directory, so no need to re-test the non-CRIU targets.

**Comment by gacholio** [comment]
Could this be caused by me or is it known intermittent?
```
14:33:33  Testing: Create and Restore Criu Checkpoint Image twice
14:33:33  Test start time: 2022/04/27 15:33:32 Atlantic Standard Time
14:33:33  Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java  -Xjit:count=0  TwoCheckpoints
14:33:33  Time spent starting: 12 milliseconds
14:33:39  Time spent executing: 6567 milliseconds
14:33:39  Test result: FAILED
14:33:39  Output from test:
14:33:39   [OUT] start running script
14:33:39   [OUT] Two checkpoints:
14:33:39   [OUT] Pre-checkpoint
14:33:39   [OUT] Post-checkpoint 1
14:33:39   [OUT] finished script
14:33:39   [ERR] /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_criu_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 26: 32009 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" CRIUSimpleTest $4 > testOutput 2>&1
14:33:39   [ERR] pie: 32009: Error (criu/pie/restorer.c:1790): Unable to create a thread: 32015
14:33:39   [ERR] pie: 32015: Error (criu/pie/restorer.c:573): Thread pid mismatch 32015/32014
14:33:39   [ERR] pie: 32015: Error (criu/pie/restorer.c:626): Restorer abnormal termination for 32009
14:33:39   [ERR] Error (criu/cr-restore.c:2447): Restoring FAILED.
14:33:39  >> Success condition was found: [Output match: Killed]
14:33:39  >> Required condition was found: [Output match: Pre-checkpoint]
14:33:39  >> Required condition was found: [Output match: Post-checkpoint 1]
14:33:39  >> Required condition was not found: [Output match: Post-checkpoint 2]
14:33:39  >> Failure condition was not found: [Output match: CRIU is not enabled]
14:33:39  >> Failure condition was not found: [Output match: Operation not permitted]
14:33:39  >> Failure condition was not found: [Output match: ERR]
```

**Comment by tajila** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/791/

**Comment by tajila** [comment]
Ya just did a run, it appears intermittent

**Pull request merged**
