### PR TITLE
Fix TimeUtilities thread number counting synchronization

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Fix TimeUtilities thread number counting synchronization

Use `AtomicInteger` to update the thread number atomically.

closes https://github.com/eclipse-openj9/openj9/issues/20464

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
jenkins test sanity.functional alinux64 jdk21

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_linux_Personal/444/consoleFull
```
15:00:35  ERROR: Build failed for target 'all' in configuration 'linux-aarch64-server-release' (exit code 2) 
15:00:35  
15:00:35  === Output from failing command(s) repeated here ===
15:00:35  * For target buildtools_tools_jigsaw_classes__the.BUILD_JIGSAW_TOOLS_batch:
15:00:35  [stderr] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6af42aba[Not completed, task = javacserver.server.CompilerThreadPool$$Lambda/0x0000000018251f10@99c81b05] rejected from java.util.concurrent.ThreadPoolExecutor@eeeffb29[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 9]
15:00:35  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
15:00:35  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
15:00:35  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
15:00:35  [stderr] 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
15:00:35  [stderr] 	at javacserver.server.CompilerThreadPool.dispatchCompilation(CompilerThreadPool.java:49)
15:00:35  [stderr] 	at javacserver.server.Server.handleRequest(Server.java:211)
15:00:35  [stderr] 	at javacserver.server.Server.lambda$start$1(Server.java:173)
15:00:35  [stderr] 	at java.base/java.lang.Thread.run(Thread.java:1595)
```

This is a known issue that is not related to this PR change.
* https://github.com/eclipse-openj9/openj9/issues/20338

**Comment by tajila** [comment]
jenkins test sanity.functional alinux64 jdk21

**Comment by tajila** [comment]
Please backport to 0.49

**Comment by JasonFengJ9** [comment]
@tajila Please review https://github.com/eclipse-openj9/openj9/pull/20659

**Pull request merged**
