### PR TITLE
Tag test.fil file as binary

### PR DESCRIPTION
**Pull request by psoujany**
This PR tags below file as binary
https://github.com/eclipse-openj9/openj9/blob/master/test/functional/cmdLineTests/jvmtitests/jars/test.fil

### CODE REVIEW

**Comment by psoujany** [comment]
Without tagging the .fil, test fails as below
```
Running command: "/home/jenkins/workspace/Grinder_CR/jdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump    -agentlib:jvmtitest=test:abcl001,args:/home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jars/test.fil -cp "/home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
18:16:01  Time spent starting: 9 milliseconds
18:16:02  Time spent executing: 1048 milliseconds
18:16:02  Test result: FAILED
18:16:02  Output from test:
18:16:02   [OUT] *** Testing [1/1]:	testAddToBootpathDuringOnload
18:16:02   [OUT] *** Test took 28 milliseconds
18:16:02   [OUT] FAILED
18:16:02   [OUT] 
18:16:02   [ERR] Unable to load class TestClass in null
18:16:02   [ERR] java.lang.ClassNotFoundException: TestClass
```

**Comment by pshipton** [comment]
Pls fix the commit title and description. This doesn't tag .fil files, it only tags `test/functional/cmdLineTests/jvmtitests/jars/test.fil`.

**Comment by pshipton** [comment]
In case it's unclear, the commit itself needs to be reworded, since the title is "Tag .fil files as binary".
Also the description of the PR should be updated from "This PR tags .fil files as binary. Below tests will pass only when .fil files are tagged as binary".

**Comment by psoujany** [comment]
@pshipton Could you please check if the commit and description is clear now?

**Review by pshipton — APPROVED** [review]

**Pull request merged**
