### PR TITLE
(0.27.0) Fix incorrect J9Class pointer in ClassCastException

### PR DESCRIPTION
**Pull request by a7ehuo**
When running 64 bit compressed refs, if clazz is an address
above the 2G boundary then we can't use a push 32bit immediate
instruction to pass it on the stack to the jitThrowClassCastException
helper as the address gets sign extended. It needs to be
stored in a temp register and then push the register to the stack.

Port #12852 into 0.27.0 release 

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux jdk11

Sniff test.

**Comment by pshipton** [comment]
`test sanity xlinux jdk11` doesn't work on the release branch. you need to specify the 0.27 branches for omr and the extensions if you really want to PR test. As long as the patch is the same as head stream, I'd just go ahead and merge it. We run weekly testing on the release branches, and will pick up any problems then. Otherwise I don't expect anybody is using the release branches for anything.

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux jdk11 depends eclipse-openj9/openj9-omr#v0.27.0-release

**Comment by pshipton** [comment]
I think that will work because the latest extensions repo is compatible, but in general the 0.27 branch for the extensions should be specified as well.

**Pull request merged**
