### PR TITLE
Add -Xint to testVirtualThread, re-enable test

### PR DESCRIPTION
**Pull request by fengxue-IS**
Fixes: #15650
Fixes: #15651 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
Grinder run 20/20 passed for aarch64, ppc64le, x86-64_windows

**Comment by fengxue-IS** [comment]
@JasonFengJ9 can you take a look
FYI @tajila

**Review by JasonFengJ9 — APPROVED** [review]
LGTM

**Review by tajila — APPROVED** [review]

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
