### PR TITLE
AArch64: Save return address in VMThread in NEW_DUAL_MODE_HELPER

### LINKED ISSUE #14530: Invalid JIT return address reported running value types ValueTypeTestsJIT_1 test on aarch64_linux
Failure running functional/Valhalla test ValueTypeTestsJIT_1 aarch64_linux. Failure can be found in [internal server Pipeline-Build-Test-Personal build #11817](https://%3Cinternal-server-name%3E/job/Pipeline-Build-Test-Personal/11817/).

[Grinder run](https://%3Cinternal-server-name%3E%3E/job/Grinder/21032/) failed 10/10.

```
*** Invalid JIT return address 0000000083921C08 in 0000FFFF5CBF7138

16:07:06.154 0x185900    j9vm.249    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDKnext_aarch64_linux_valhalla_Personal/openj9/runtime/vm/swalk.c:1605: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/02/15 11:07:06 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16449411956518/ValueTypeTestsJIT_1/core.20220215.110706.14162.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16449411956518/ValueTypeTestsJIT_1/core.20220215.110706.14162.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16449411956518/ValueTypeTestsJIT_1/javacore.20220215.110706.14162.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16449411956518/ValueTypeTestsJIT_1/javacore.20220215.110706.14162.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16449411956518/ValueTypeTestsJIT_1/Snap.20220215.110706.14162.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16449411956518/ValueTypeTestsJIT_1/Snap.20220215.110706.14162.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail ""
```

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds lines in NEW_DUAL_MODE_HELPER for saving the return address in VMThread->jitReturnAddress.

Fixes #14530

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins test sanity alinux64,amac jdk17

**Comment by knn-k** [comment]
See the code in pnathelp.m4 for comparison.

https://github.com/eclipse-openj9/openj9/blob/ca3e24809118914786124dc85a4e5e68050298d6/runtime/codert_vm/pnathelp.m4#L209-L210

https://github.com/eclipse-openj9/openj9/blob/ca3e24809118914786124dc85a4e5e68050298d6/runtime/codert_vm/pnathelp.m4#L240-L241

**Comment by knn-k** [comment]
NEW_DUAL_MODE_HELPER is used only for jitNewValue on AArch64 at the moment.
Functional tests (sanity, extended) passed with a Valhalla build in #14530.

**Comment by a7ehuo** [comment]
Could you add `Fixes #14530` in the commit message to auto close the issue once this PR is merged? Thank you Konno-san @knn-k!

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
