### PR TITLE
Update Java8 build specs for off-heap

### PR DESCRIPTION
**Pull request by LinHu2016**
new define J9VM_GC_SPARSE_HEAP_ALLOCATION for the build specs

### CODE REVIEW

**Comment by LinHu2016** [comment]
@amicic @dmitripivkine please review the changes, Thanks

**Comment by amicic** [comment]
I don't know what these _cross_ specs are...

we seem to miss CR variant of specs, right?

**Comment by dmitripivkine** [comment]
What is "gc_inlinedAllocFields" flag for? How it relates to "gc_enableSparseHeapAllocation"?

**Comment by dmitripivkine** [comment]
> What is "gc_inlinedAllocFields" flag for? How it relates to "gc_enableSparseHeapAllocation"?

Sorry, missed that flag just moved

**Comment by LinHu2016** [comment]
> I don't know what these _cross_ specs are...
> 
> we seem to miss CR variant of specs, right?

for CR, the update is in buildspecs/cmprssptrs.feature.

**Comment by amicic** [comment]
ok, seems like we follow the pattern: add offheap whereever we have

 		<flag id="env_data64" value="true"/>


ideally, we could have a common spec file for all full64 specs, but we don't, so we have to update each full64 spec individually

ok, looks good then

then only thing is perhaps if we should enable for ZPTF even at compile level (since we suspect it won't really be able to properly run due to nonfunctional commit/decommit) @dmitripivkine

**Comment by LinHu2016** [comment]
I will update the changes due to the define J9VM_GC_ENABLE_SPARSE_HEAP_ALLOCATION has been renamed toJ9VM_GC_SPARSE_HEAP_ALLOCATION in PR https://github.com/eclipse-openj9/openj9/pull/20461

**Comment by amicic** [comment]
jenkins compile xLinux jdk21

**Comment by amicic** [comment]
jenkins compile aix jdk8

**Review by amicic — APPROVED** [review]

**Pull request merged**
