### PR TITLE
CRIU Restore Softmx Functional Tests

### PR DESCRIPTION
**Pull request by kangyining**
Add supporting test cases and related testing scripts.

Softmx functionalities: #18168

Functional changes: #19037

### CODE REVIEW

**Comment by kangyining** [comment]
Jenkins line endings check

**Comment by kangyining** [comment]
Grinder results:
x86-64 linux:
jdk 8: CRIU not supported?
jdk 11: [38705](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38705/)
jdk 17: [38703](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38703/)
jdk 21: [38707](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38707/)
jdk 22: not blocking [38709](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38709/)
cannot test due to docker semeru missing 22 now

**Comment by LongyuZhang** [comment]
@kangyining Could you also add some test links with Build_List `functional` and testTarget `testList TESTLIST=cmdLineTester_criu_keepCheckpoint,cmdLineTester_criu_softmx`, especially for jdk 22, to make sure the added source files compile successfully, and the result should show `cmdLineTester_criu_softmx` disabled, and `cmdLineTester_criu_keepCheckpoint` passed. FYI @llxia

**Comment by kangyining** [comment]
> @kangyining Could you also add some test links with Build_List `functional` and testTarget `testList TESTLIST=cmdLineTester_criu_keepCheckpoint,cmdLineTester_criu_softmx`, especially for jdk 22, to make sure the added source files compile successfully, and the result should show `cmdLineTester_criu_softmx` disabled, and `cmdLineTester_criu_keepCheckpoint` passed. FYI @llxia

Grinder tests:

x86-64 linux: [38761](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38761/)
ppcle linux: [38767](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38767/)
s390x linux: [38762](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38762/)

**Comment by llxia** [comment]
The test only compiles in regular build. The test executes in the docker environment. See https://github.com/adoptium/aqa-tests/pull/5144

**Pull request merged**
