### PR TITLE
putfield/putstatic/withfield must narrow values before storing

### PR DESCRIPTION
**Pull request by gacholio**
Static and instance fields in OpenJ9 are never smaller than 32 bits, so it is possible (via bytecode assembly or modification) to store an out-of-range value in boolean/byte/char/short fields.

This PR correctly restricts the stored values by masking or sign-extending the values before storing.

Fixes: #16498

### CODE REVIEW

**Review by tajila — COMMENTED** [review]
we will need changes in `withfield` as well

**Comment by gacholio** [comment]
I'll fix withfield in this PR.

**Comment by gacholio** [comment]
withfield fixed.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
jenkins test sanity win jdk8

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk21

**Comment by gacholio** [comment]
Note that I've only run regression testing on this - I have not run the test in the issue.

**Comment by gacholio** [comment]
All of the failures are CRIU, which seems unlikely to be affected by this change.

**Comment by tajila** [comment]
Im not able to get test results

**Comment by tajila** [comment]
jenkins test sanity plinux jdk21

**Comment by tajila** [comment]
FYI @hzongaro, just added interpreter support for sub 32 bit field narrowing

**Comment by hzongaro** [comment]
> just added interpreter support for sub 32 bit field narrowing

Thanks for the update!  @BradleyWood is working on the corresponding JIT compiler changes.

**Pull request merged**
