### PR TITLE
AArch64 macOS: Call pthread_jit_write_protect_np()

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds calls to pthread_jit_write_protect_np() for AArch64 macOS.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
This PR depends on https://github.com/eclipse/omr/pull/6270.

**Comment by 0xdaryl** [comment]
Some of the uses of `FINISH_MODIFYING_CODE` do not flush the icache afterwards as macOS requires (`sys_icache_invalidate`).

In some other cases, the flush occurs before the page protections are changed.  I honestly don't know if this makes a functional difference, but to strictly follow Apple's guidelines then the flush should occur after the write protection is re-established.

It would be convenient if the cache flush were part of the `FINISH_MODIFYING_CODE` macro.

**Comment by knn-k** [comment]
> Some of the uses of `FINISH_MODIFYING_CODE` do not flush the icache afterwards as macOS requires (`sys_icache_invalidate`).

I don't think rewriting data in snippets requires flushing the icache.  They are not CPU instructions but just data.

**Comment by knn-k** [comment]
jenkins compile all jdk17

**Comment by knn-k** [comment]
jenkins compile all jdk17

**Comment by 0xdaryl** [comment]
Jenkins compile all jdk17

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11

**Comment by 0xdaryl** [comment]
Upstream OMR commit has promoted.  This can be merged once AArch64 testing is complete.

**Review by 0xdaryl — APPROVED** [review]

**Comment by knn-k** [comment]
Test complete.  This PR does not break AArch64 Linux.

**Pull request merged**
