### PR TITLE
Fix invalid OMR_PRI* usage on Windows

### LINKED ISSUE #17319: 1TIDMPDURATION always returns 64d on Windows
Java -version output
--------------------

```
java -version
openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Windows 11 amd64-64-Bit Compressed References 20230117_367 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```

Summary of problem
------------------

On Windows, the new java dump line `1TIDMPDURATION` added by PR #15964 incorrectly returns a constant `64d`:

```
1TIDMPDURATION Approximate time to produce this dump: 64d ms
```

[javacore.20230502.061258.26772.0001.txt](https://github.com/eclipse-openj9/openj9/files/11372537/javacore.20230502.061258.26772.0001.txt)

### PR DESCRIPTION
**Pull request by kgibm**
Fixes #17319

Verified on Windows:

```
1TIDMPDURATION Approximate time to produce this dump: 235 ms
```

### CODE REVIEW

**Comment by kgibm** [comment]
@keithc-ca @pshipton I can't request a review but please review when you have a chance. As noted in the description, I verified this fixes the issue on Windows.

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
I notice that other durations don't have the space before the units, for example
```
 * 4HKDURATION        Duration: 10us
```
Do we want to remove the space before `ms` while we're here? The example would be
```
1TIDMPDURATION Approximate time to produce this dump: 235ms
```

**Comment by kgibm** [comment]
> Do we want to remove the space before `ms` while we're here? The example would be

Sure. Updated and force-pushed.

**Comment by pshipton** [comment]
Do you want this fix in the 0.40 release (23_03)? If so please create a PR on https://github.com/eclipse-openj9/openj9/tree/v0.40.0-release

**Comment by kgibm** [comment]
> Do you want this fix in the 0.40 release (23_03)?

Yes, thanks. Created: https://github.com/eclipse-openj9/openj9/pull/17569

**Pull request merged**
