### PR TITLE
AArch64: Fix getArgPointer() for FFI upcall

### PR DESCRIPTION
**Pull request by knn-k**
This commit fixes getArgPointer() for AArch64 for FFI upcall.

The function needs to maintain two offsets in the stack: one for the arguments stored by the upcall thunk, another one for the arguments stored in the stack by the caller.

Fixes: #16237

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins test sanity alinux64,amac jdk19

**Comment by knn-k** [comment]
FYI.  @ChengJin01

**Comment by knn-k** [comment]
Jenkins test sanity alinux64,amac jdk19

**Comment by ChengJin01** [comment]
FYI: @zl-wang, @0xdaryl

**Comment by knn-k** [comment]
I ran the following tests with this fix on Linux and macOS manually.

TestUpcallAsync.java
TestUpcallHighArity.java
TestUpcallScope.java
TestUpcallStack.java
Jep424Tests_testLinkerFfi_UpCall (in functional test)

TestUpcallStack.java failed only on macOS, and #16336 tracks it.  All other tests were successful.

**Comment by zl-wang** [comment]
maintaining two stack-pointer(s) sounds more complicated than necessary.  it can be done relatively simply:  saving-frame is of fixed size ... original passed-in-stack arg pointer can be calculated according to that fixed size and arg's offset together. z (and to a lesser degree, p where the ABI dictates the stack saving area either none or all) implemented this way.

**Comment by zl-wang** [comment]
your fix did implement that way.  implementation details are slightly different.  LGTM ... approved!

**Review by zl-wang — APPROVED** [review]

**Pull request merged**
