### PR TITLE
(0.48) -agentpath: libraries require no path/name decoration & Refactor a few CRIU APIs to take J9JavaVM* instead of J9VMThread*

### PR DESCRIPTION
**Pull request by JasonFengJ9**
#### `-agentpath:` libraries require no path/name decoration

The agent library specified via `-agentpath:` has an absolute path/name, it should not be decorated again during the agent library loading;
For `-agentpath:` option in the restore option file, compare the actual platform-dependent library name.

Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20202

#### Refactor a few CRIU APIs to take `J9JavaVM*` instead of `J9VMThread*`

The currentThread passed into `isCRaCorCRIUSupportEnabled(J9VMThread*)`, `isCheckpointAllowed(J9VMThread*)` and
`isDebugOnRestoreEnabled(J9VMThread*)` are just for redirection of `currentThread->javaVM`, changed the APIs to take `J9JavaVM*` directly.

Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20205

Note: these two PRs were in last night's builds, and no failure seems related to those changes.

In addition, there were merging conflicts, verified in a personal build [JDK17_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDK17_x86-64_linux_Personal/2858/console).

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by keithc-ca** [comment]
Is the failure in https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_mac_Release/86/ related to the https://github.com/eclipse-openj9/openj9/pull/20202? If we think so, that should be fixed before propagating to the 0.48 release branch.

**Comment by JasonFengJ9** [comment]
```
11:31:32  JVMT stderr JVMJ9TI001E Agent library /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_mac_Release_testList_0/jvmtest/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/osx/libsharedClasses.so could not be opened (dlopen(/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_mac_Release_testList_0/jvmtest/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/osx/liblibsharedClasses.so.dylib, 0x0001): tried: '/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_mac_Release_testList_0/jvmtest/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/osx/liblibsharedClasses.so.dylib' (no such file))
```
This is to be fixed by this PR in 0.48.

**Comment by keithc-ca** [comment]
I think the problem is in https://github.com/adoptium/openj9-systemtest/blob/master/openj9.test.sharedClasses.jvmti/src/test.sharedClasses.jvmti/net/openj9/stf/SharedClassesAPI.java#L216 so I don't see how this could fix that.

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_mac_Release/86/
> -agentpath:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_mac_Release_testList_0/jvmtest/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/osx/libsharedClasses.so=expectedCacheCount=5,deleteCaches=true,cachePrefix=DefaultLocGrpAccessJVMTI

> liblibsharedClasses.so.dylib

The wrong library name was due to additional decoration introduced by https://github.com/eclipse-openj9/openj9/pull/19754 which was merged into 0.48 this morning, the build was launched afterwards but w/o this PR.
This PR is to fix that problem for  `-agentpath`.

**Comment by keithc-ca** [comment]
I think https://github.com/adoptium/openj9-systemtest/pull/158 is need to fix that failure.

**Comment by pshipton** [comment]
The problem seen in https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_mac_Release/86/ was fixed in the head stream via https://github.com/eclipse-openj9/openj9/pull/20202

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
