### PR TITLE
Prevent javacore generation from interfering with stack walker

### PR DESCRIPTION
**Pull request by gacholio**
Add a flag to getOwnedObjectMonitors to prevent the stack walker from asserting and marking the thread stack corrupt.

Also remove the private flag for stack corruption - it has served no purpose for many releases.

### CODE REVIEW

**Comment by gacholio** [comment]
@keithc-ca Please verify that my removal of the private flag won't break DDR.

**Comment by gacholio** [comment]
This is related to RTC story 150400.

**Comment by keithc-ca** [comment]
> Please verify that my removal of the private flag won't break DDR.

I don't see any potential problems for DDR.

Please identify the assertion(s) that will be avoided by this change.

**Comment by gacholio** [comment]
> Please identify the assertion(s) that will be avoided by this change.

It avoids the "invalid JIT return address" assertion if the stack walker is called from getOwnedObjectMonitors with the reportErrors flag FALSE (at the moment, only javacore generation calls this way).

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
> I don't see any potential problems for DDR.

Actually, I take that back. We should keep `J9_PRIVATE_FLAGS_STACK_CORRUPT` (perhaps only as a (reverse) compatibility constant in `CompatibilityConstants29.dat`) so it is properly recognized in old core files.

Add to `CompatibilityConstants29.dat`:
```
J9Consts.J9_PRIVATE_FLAGS_STACK_CORRUPT = 0 /* no longer used */
```
and don't change `DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackwalker/StackWalker.java`.

**Comment by gacholio** [comment]
The tag bit is meaningless - stacks are never corrupt when running, and the tagging of foreign threads in the javacore writer is both unsafe an incorrect. DDR should not be processing this flag at all.

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Jenkins test sanity alinux jdk17

**Pull request merged**
