### PR TITLE
Add missing java preprocessor flag for wi32 platform

### PR DESCRIPTION
**Pull request by keithc-ca**

### CODE REVIEW

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
I often let it slide, but the commit comment could use more context, i.e. it should contain "jpp" or "java preprocessor" so anyone reading the title would have an idea where the platform was missing.

**Comment by keithc-ca** [comment]
> I often let it slide, but the commit comment could use more context, i.e. it should contain "jpp" or "java preprocessor" so anyone reading the title would have an idea where the platform was missing.

Since just a single file is modified, I thought it was clear, but I'll expand it.

**Comment by pshipton** [comment]
There is no problem when looking at the change, but if you are looking through a list of changes, such as https://github.com/eclipse-openj9/openj9/releases/tag/openj9-0.30.0, it's nice to have as much context as possible in the "title".

**Comment by keithc-ca** [comment]
You're right, I hadn't thought of that context. Updated.

**Pull request merged**
