### PR TITLE
Add a NULL check on threadObject in destroyThreadData

### PR DESCRIPTION
**Pull request by babsingh**
This will fix the crash in #18621.

Co-authored-by: Graham Chapman <graham_chapman@ca.ibm.com>
Co-authored-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Review by pshipton — APPROVED** [review]

**Comment by babsingh** [comment]
@pshipton Should I also open PRs to port this fix to 0.42 and 0.43?

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk21

**Comment by pshipton** [comment]
> Should I also open PRs to port this fix to 0.42 and 0.43?

Is it a new problem? If it's been a problem forever it can wait for the next release.

**Comment by babsingh** [comment]
> Is it a new problem? If it's been a problem forever it can wait for the next release.

This is not a new problem; it can wait for the next release.

**Comment by pshipton** [comment]
Looks like it may have been introduced a little over a year ago. It's a simple low risk change, I'm fine with backporting to 0.42 and 0.43.

**Comment by babsingh** [comment]
### Backports
- https://github.com/eclipse-openj9/openj9/pull/18690
- https://github.com/eclipse-openj9/openj9/pull/18689

**Pull request merged**
