### PR TITLE
Add isFieldNullRestricted() and expose it to JIT

### PR DESCRIPTION
**Pull request by hangshao0**
issue #17340

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
FYI @a7ehuo @hzongaro

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Pull request merged**
