### PR TITLE
Enable warnings as errors on Aarch64 in the JIT

### PR DESCRIPTION
**Pull request by dylanjtuttle**
"Warnings as errors" is enabled on a component-by-component basis throughout OpenJ9 and OMR. For the JIT, warnings as errors is enabled on every platform in OMR and on x86 and Z in OpenJ9.

This PR enables warnings as errors on Aarch64 in OpenJ9 by:
- Turning the `OMR_WARNINGS_AS_ERRORS` flag on if `OMR_ARCH_AARCH64` is true
- Removing the `--disable-warnings-as-errors` flag which is passed into Aarch64 builds on Jenkins by default

This will ensure all builds on Aarch64 compile code with the `-Werror` flag, which will halt compilation if a warning is reported.

### CODE REVIEW

**Comment by dylanjtuttle** [comment]
@0xdaryl as we discussed earlier today...

**Comment by 0xdaryl** [comment]
@knn-k : any objections to enabling this now?

**Review by knn-k — APPROVED** [review]
No objection.
I built AArch64 OpenJ9 JDK 17 for Linux and macOS locally, and both of them were OK with warnings-as-errors.

**Comment by knn-k** [comment]
Build jobs at internal servers finished successfully:
- job/Build_JDK17_aarch64_linux_Personal/461/ (Linux)
- job/Build_JDK17_aarch64_mac_Personal/193/ (macOS)

**Comment by 0xdaryl** [comment]
There are no community build jobs to test this, but internal testing runs fine.

**Comment by pshipton** [comment]
> There are no community build jobs to test this, but internal testing runs fine.

@0xdaryl are you referring to the UNB testing problems or something else? alinux isn't at UNB, and we can do builds at UNB, the main problem is running testing.

**Comment by 0xdaryl** [comment]
Yes, I was referring to the UNB problems.  My mistake about alinux.

Konno-san tested this internally on a couple of configurations before we merged this so I don't think we'll see any problems.

**Comment by pshipton** [comment]
I wasn't concerned, I just wanted you to be aware that we can build JVMs at UNB even if we can't test them all concurrently (we can run a limited amount of testing).

**Pull request merged**
