### PR TITLE
Do not set backfillOffset of VT to -1

### PR DESCRIPTION
**Pull request by hangshao0**
1. Set backfillOffset of VT to instance size as normal classes.
2. Copy the VT hash code when doing copyObjectFields().

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
This change prevents the crash in GC to unblock performance testing for the JIT team. 

We still need to calculate the hashcode of value type based on the value rather than the identity, which can be done through a separate PR.

**Review by dmitripivkine — APPROVED** [review]

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity,extended plinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by hangshao0** [comment]
The hang in the PR [build](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDKnext_x86-64_linux_vt_standard/41/) should be fixed by https://github.com/eclipse-openj9/openj9/pull/15528

**Pull request merged**
