### PR TITLE
AArch64: Fix usage of ScratchRegisterManger in VMinlineCompareAndSwap

### PR DESCRIPTION
**Pull request by Akira1Saitoh**
Add registers allocated by ScratchRegisterManager to RegisterDependency.
Call `stopUsingRegister` when scratch registers become unnecessary.

Signed-off-by: Akira Saitoh <saiaki@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11

**Comment by Akira1Saitoh** [comment]
force-pushed https://github.com/eclipse-openj9/openj9/commit/52bdd2a2c62966865209cf3da898df94143e910d to fix an error for the case when `offsetReg` is NULL.

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11

**Review by knn-k — APPROVED** [review]
LGTM.

**Pull request merged**
