### PR TITLE
AArch64: Clean up UpcallThunkGen.cpp

### PR DESCRIPTION
**Pull request by knn-k**
This commit cleans up UpcallThunkGen.cpp code for AArch64 for better readability.

- Rename the variable tempInt to argSize and resultSize.
- Stop using the variables useMoreGPRs and useMoreFPRs.
- Stop using the variables gprCount and fprCount.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins test sanity alinux64,amac jdk19

**Comment by knn-k** [comment]
FYI.  @zl-wang @0xdaryl

**Comment by knn-k** [comment]
Jenkins test sanity alinux64,amac jdk19

**Review by zl-wang — APPROVED** [review]
LGTM

**Comment by zl-wang** [comment]
tested already ... merge

**Pull request merged**
