### PR TITLE
Fix the crash issue with the error message framework in Verifier

### PR DESCRIPTION
**Pull request by ChengJin01**
The change is to resolve the crash issue specific to a stackmap
frame without any element in 'locals' and 'stack' when allocating
the memory of stackmap frame in the error message framework
during the runtime verification.

Fixes: #15639

Signed-off-by: Cheng Jin <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
The PR was verified in internal & open builds.

Reviewer: @DanHeidinga
FYI: @gacholio, @tajila, @pshipton

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
Is there also a missing check for allocation failure (due to the huge size) later on?

**Comment by gacholio** [comment]
OK, but I'm wondering why we crashed before - if the huge allocation were properly checked, wouldn't that result in an out of memory error being reported?

**Comment by ChengJin01** [comment]
> OK, but I'm wondering why we crashed before - if the huge allocation were properly checked, wouldn't that result in an out of memory error being reported?

The crash occurred in `releaseVerificationTypeBuffer` (called by `generateJ9RtvExceptionDetails`) when attempting to release an invalid stackmap frame without any memory allocated before as follows at https://github.com/eclipse-openj9/openj9/blob/master/runtime/verbose/errormessageframeworkrtv.c
```
U_8*
generateJ9RtvExceptionDetails(J9BytecodeVerificationData* verifyData, U_8* initMsgBuffer, UDATA* msgBufferLength)
{

case BCV_ERR_STACK_SIZE_MISMATCH:
		printMessage(&msgBuf, "Current frame's stack size doesn't match stackmap.");
returned false due to out-of-memory ---> printStackFrame = setStackMapFrameWithIndex(verifyData, &methodInfo, &stackMapFrameTarget);
		break;
...
/* Stackmap Frame: */
	if (printStackFrame) { <-------- false
		/* Specify if the stack frame is from classfile or internal */
		if (verifyData->createdStackMap) {
			printMessage(&msgBuf, "\n%*sStackmap Frame (FallBack):", INDENT(2));
		} else {
			printMessage(&msgBuf, "\n%*sStackmap Frame:", INDENT(2));
		}
		printTheStackMapFrame(&msgBuf, &stackMapFrameTarget, &methodInfo);
	}

	/* Release memory allocated for the stackmap frame */
	releaseVerificationTypeBuffer(&stackMapFrameTarget, &methodInfo); <-------


void
releaseVerificationTypeBuffer(StackMapFrame* stackMapFrame, MethodContextInfo* methodInfo)
{
	if (NULL != stackMapFrame->entries) {
		PORT_ACCESS_FROM_PORT(methodInfo->portLib);
		j9mem_free_memory(stackMapFrame->entries); <------- crashed as the pointer was invalid
	}
}
```
in which case I just set `stackMapFrame->entries` to null after releasing the memory to avoid wild pointer in this case.

In addition, we skip the stackmap frames in huge size in the case of out-of-memory in our error message framework to ensure the rest of stackmaps frames in an appropriate size are correctly allocated & outputted to the error message so as to provide users with sufficient information of what is really happening in the problematic class.

**Comment by ChengJin01** [comment]
Please note the issue detected at https://github.com/eclipse-openj9/openj9/issues/15639 had nothing to do with the out-of-memory case but an incorrect last `local` index was wrongly set & converted to a huge size in allocating the stackmap frame, which misleadingly ended up with an out-of-memory case.

**Comment by gacholio** [comment]
Right, the original issue was corruption from an overrun.

**Pull request merged**
