### PR TITLE
Update JFR metadata.blob file

### PR DESCRIPTION
**Pull request by tajila**
The existing metadata.blob doesnt capture all JFR events. This PR updates blob file used to support more JFR events.

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity.functional xlinux jdk17

**Comment by tajila** [comment]
@babsingh Please review these changes

**Comment by babsingh** [comment]
Is the blob file auto-generated?

**Comment by tajila** [comment]
> Is the blob file auto-generated?

No, this was manually generated. In the future we will add support to aut generate at runtime.

**Comment by babsingh** [comment]
Only the hpp file needs to be reviewed since the blob file is generated through a script?

**Comment by tajila** [comment]
yes

**Review by babsingh — APPROVED** [review]

**Pull request merged**
