### PR TITLE
Recognize new HashMap keysToArray and valuesToArray methods

### PR DESCRIPTION
**Pull request by hzongaro**
By default any method in `java.util.HashMap` is recognized using the `TR::RecognizedMethod` enumerated value, `java_util_HashMap_all`.  That enumerated value is included in the `canSkipArrayStoreChecks[]` array defined in `J9MethodSymbol.cpp`, which is used to suppress `ArrayStoreCHK` operations where they are known not to be required.

However, recently introduced `keysToArray` and `valuesToArray` methods in `java.util.HashMap` could throw `ArrayStoreException`, and should not be included in `canSkipArrayStoreChecks`.

This change adds recognition of those two new methods, along with the new `prepareArray` method, using their own enumerated values, so that IL generation will not suppress `ArrayStoreCHK` operations in the IL generated for them.

### CODE REVIEW

**Comment by hzongaro** [comment]
Daryl @0xdaryl, may I ask you to review this change?

**Comment by 0xdaryl** [comment]
My apologies for being obtuse, but how does adding these three methods to the recognized method table fix the problem?  Won't these HashMap methods still be marked "HashMap_all" here -> https://github.com/eclipse-openj9/openj9/blob/7d96165088433cf41142d9709f2170ea81db7ff9/runtime/compiler/env/j9method.cpp#L4310

**Comment by hzongaro** [comment]
Just above that series of tests for the class name, there is a [pair of nested loops](https://github.com/eclipse-openj9/openj9/blob/7d96165088433cf41142d9709f2170ea81db7ff9/runtime/compiler/env/j9method.cpp#L4273-L4293) that checks for matches against specific class and method names and signatures.  If a match is found, the call to `setRecognizedMethodInfo` will set the appropriate enum value for that method, and the test that follows the loops will fail:

```
if (TR::Method::getMandatoryRecognizedMethod() == TR::unknownMethod)
```

The check at [line 4310](https://github.com/eclipse-openj9/openj9/blob/7d96165088433cf41142d9709f2170ea81db7ff9/runtime/compiler/env/j9method.cpp#L4310) should only occur for methods that weren't found in the table.

It's the not most elegant of code.

**Comment by 0xdaryl** [comment]
ah, thanks for clarifying that Henry!

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17

**Comment by hzongaro** [comment]
Opened pull request #13527 against v0.28.0-release branch for this change as well.

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
