### PR TITLE
Remove unused TR::idoz opcode

### LINKED ISSUE #6108: Remove unused TR::idoz opcode
This is the OpenJ9-dependent work for eclipse/omr#1400. Remove references in OpenJ9. This will depend on any OMR PR created for the work.

### PR DESCRIPTION
**Pull request by agarwalrounak**
Fixes #6108

Signed-off-by: Rounak Agarwal <rounakr.ag73@gmail.com>

### CODE REVIEW

**Comment by agarwalrounak** [comment]
@0xdaryl Can you please review this?

**Comment by 0xdaryl** [comment]
Jenkins compile all jdk11 depends eclipse/omr#4006

**Comment by 0xdaryl** [comment]
Jenkins compile all jdk11 depends eclipse/omr#4006

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk11 depends eclipse/omr#4006

**Comment by andrewcraik** [comment]
For testing to proceed the changes here will need to be rebased sine there were changes in the opcode table. Once rebased I think this can proceed with testing and merge. Removal is straight forward since the opcode is unused.

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by 0xdaryl** [comment]
It appears this opcode has already been removed from the codebase.

**Pull request closed without merging**
