### PR TITLE
Rename External MM Barrier APIs

### PR DESCRIPTION
**Pull request by RSalman**
Use generic pre and post prefixes in Barrier APIs, rather implying anything about underlying technology, like Metronome, SATB, Card Dirtying etc. This is required for generalizing Metronome APIs for Standard SATB use.

`J9MetronomeWriteBarrierStore` -> `J9WriteBarrierPreStore`

`J9MetronomeWriteBarrierJ9ClassStore` -> `J9WriteBarrierJ9PreClassStore`

`J9WriteBarrierStore` -> `J9WriteBarrierPostStore`

`J9WriteBarrierJ9ClassStore` -> `J9WriteBarrierJ9PostClassStore`

Signed-off-by: Salman Rana <salman.rana@ibm.com>

### CODE REVIEW

**Comment by RSalman** [comment]
fyi @amicic @dmitripivkine

**Comment by amicic** [comment]
This looks good cleanup. We should also rename MM_ObjectAccessBarrier::preBatchObjectStore to _post_, but not necessarily as a part of this change.

**Review by amicic — APPROVED** [review]

**Comment by amicic** [comment]
Jenkins test sanity win,aix jdk11

**Comment by gacholio** [comment]
The new names are somewhat incorrect - the second `J9` refers expressly to `J9Class`, so the names should be:

`J9MetronomeWriteBarrierJ9ClassStore -> J9WriteBarrierPreJ9ClassStore`

etc.

@dmitripivkine @amicic

**Comment by amicic** [comment]
> The new names are somewhat incorrect - the second `J9` refers expressly to `J9Class`, so the names should be:
> 
> `J9MetronomeWriteBarrierJ9ClassStore -> J9WriteBarrierPreJ9ClassStore`
> 

Agreed, this isn't quite correct. But now I wonder, do we need to emphasize that second `J9`, at all.

**Comment by gacholio** [comment]
Given all the work the GC has done to de-magic j.l.Class, I don't forsee a situation where we would need specific barriers for that type of object, so yes, the second `J9` could simply be removed.

**Pull request merged**
