### PR TITLE
Extend usage of ForceInline annotation in JIT

### PR DESCRIPTION
**Pull request by gita-omr**
- use ForceInline inside tryToInine() and alwaysWorthInlining() for all methods
- use ForceInline in callMustBeInlined() for Vector API methods

### CODE REVIEW

**Comment by jdmpapin** [comment]
Code change LGTM

Have you done any performance testing to see the effect of querying `@ForceInline` for methods outside the vector API in `tryToInline()` and `alwaysWorthInlining()`?

**Comment by jdmpapin** [comment]
Jenkins test extended all jdk8,jdk11,jdk17

**Comment by gita-omr** [comment]
> 
> 
> Code change LGTM
> 
> Have you done any performance testing to see the effect of querying `@ForceInline` for methods outside the vector API in `tryToInline()` and `alwaysWorthInlining()`?

Yes, we measured the effect of both Stable and ForceInline annotations and did not see big effect either way.

**Comment by jdmpapin** [comment]
Jenkins test extended all jdk8,jdk11,jdk17

**Review by jdmpapin — APPROVED** [review]

**Pull request merged**
