### PR TITLE
Disable javac server on ppc64_aix

### PR DESCRIPTION
**Pull request by keithc-ca**
Avoid all-too-frequent build failures:
```
  IOException caught during compilation: Deadlock condition if locked
```

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile xmac jdk11

**Comment by pshipton** [comment]
jenkins compile aix,xmac jdk11

**Comment by pshipton** [comment]
Nightly xmac build from 21:27:49 to 21:52:12 = ~22 min
PR build from 15:53:26 to 16:38:20 = ~45 min

Nightly AIX build from 21:34:58 to 22:53:39 = ~79 (1:19) min
PR build from 16:05:12 to 17:37:44 = ~93 (1:33) min

I think we should turn it off for xmac initially and I can track how many builds fail. It doesn't fail nearly as often as AIX.

**Comment by keithc-ca** [comment]
Updated to apply only to AIX.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
