### PR TITLE
Enable String Compression by default in OpenJ9

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
Tagging @pshipton. If we can get started with testing for JDK 11 and 17 that would be great. I'll provide an update here if my internal builds for JDK 19 are clear. Then we can test for that here as well.

**Comment by pshipton** [comment]
The builds is https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-CompactString/1/ but it has some unexpected failures.

**Comment by dchopra001** [comment]
The Java 11 failures all look to be in `testDDRExt_General_0` and `testDDRExtJunit_FindExtThread_0`. I had initially ruled them out in my internal testing because the failure was occurring despite the environment variable `EXTRA_OPTIONS=-XX:-CompactStrings` being set. It looks like though that this option doesn't always propagate to some of the sub-tests.

@mikezhang1234567890 is investigating this issue. Placing an internal comment from him regarding the issue:
> For the test error itself, String.split seems to fail to split an output correctly, and the core dump itself looks correct when running commands manually.

Once this is fixed the Java 11 builds should be clean.

**Comment by dchopra001** [comment]
The remaining failures are in Java 17. Here are my notes:

1. ppc64_aix - Only failure is in FFI related test which should be unrelated.
2. s390x_linux
- sanity.functional: Failures in `cmdLineTester_jython_*`: Looks to be a real issue: `[ERR] Exception in thread "main" TypeError: compile() expected string without null bytes`
- extended.functional, sanity.system, special.system: Failures while trying to compile java tests and when running DDR tests. All related to `java.lang.NoClassDefFoundError: org.apache.tools.ant.util.DateUtils` exception being thrown unexpectedly.

**Comment by mikezhang1234567890** [comment]
Ran a 10x grinder of `cmdLineTester_jython` [here](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30300/) which passed.

**Comment by dchopra001** [comment]
> Ran a 10x grinder of cmdLineTester_jython [here](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30300/) which passed.

I haven't been able to reproduce this in 200 jobs on our internal Jenkins as well.

**Comment by pshipton** [comment]
Started a couple of rebuilds
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Personal_testList_1/204/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Personal_testList_1/205/

**Comment by mikezhang1234567890** [comment]
For the `cmdLineTester_jython` issue, I managed to reproduce the error manually on a z15 rhel9 machine. The issue seems to be that `"somestring".contains("\0")` evaluates to `true` on the machine. Trying this on a z14 ubuntu 18 machine  produces `false` as expected. I set both the locales to `en_GB.UTF-8` and in Java, `Charset.defaultCharset()` returned `UTF-8` on both machines as well.

**Comment by dchopra001** [comment]
I was able to reproduce the `jython` failure using Mike's setup. Test program:
```
public class StrTest {
        public static void main(String[] arg) throws Throwable {
                System.out.println("teststring".indexOf("\0")); // contains calls indexOf internally
        }
}
```
Java Command:
```
jdk/bin/java -XX:+CompactStrings -Xjit:noJitUntilMain,count=0,{java/lang/StringLatin1.indexOfChar\([BIII\)I}\(traceFull,traceCG,log=trace.log,lastOptIndex=0\) -Xnoaot --add-opens java.base/java.lang=ALL-UNNAMED StrTest.java
```
The problem happens inside the following evaluator: https://github.com/eclipse-openj9/openj9/blob/6025e997fc82ce3da01b241747b58230a7203179/runtime/compiler/z/codegen/J9TreeEvaluator.cpp#L981-L988

This evaluator was added several years ago to accelerate StringLatin1.indexOfChar. Looking at git blame, I see we've had a couple of issues with this in the past. Last year another z15 related bug was fixed here. During this time the `-Xjit:disableIndexOfStringIntrinsic` option was introduced to disable this optimization. Running the above command with this option fixes the problem. I'll try to have a fix out for this problem soon.

**Comment by dchopra001** [comment]
I ran another batch of tests here: https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-CompactString/7/
**Summary of Results**
**Java 11:**
- aarch64_linux, aarch64_mac, ppc64_aix, ppc64le_linux, x86-64_mac **passed**.
- **x86-64-windows and x86-64-linux** show failures in `CryptoTests_0` which are unrelated.
- **x86-64-windows** has the following two failures as well: `MiniMix_5m_0`, `MiniMix_aot_5m_0`.

Failure comes down to a ClassNotFoundException:
```
[2023-02-13T08:19:25.205Z] LT  java.lang.ClassNotFoundException: gnu.testlet.java.util.FormatterClosedException.classInfo.getSimpleName
[2023-02-13T08:19:25.205Z] LT  	at java.base/java.lang.Class.forNameImpl(Native Method)
[2023-02-13T08:19:25.205Z] LT  	at java.base/java.lang.Class.forName(Class.java:354)
[2023-02-13T08:19:25.205Z] LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
[2023-02-13T08:19:25.205Z] LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2023-02-13T08:19:25.205Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2023-02-13T08:19:25.205Z] LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2023-02-13T08:19:25.205Z] LT  	at java.base/java.lang.Thread.run(Thread.java:839)
```

I haven't been able to reproduce this problem yet. Here are grinder links: original builds: [1](https://openj9-jenkins.osuosl.org/job/Grinder/2030/),  [2](https://openj9-jenkins.osuosl.org/job/Grinder/2035/), nightly builds: [1](https://openj9-jenkins.osuosl.org/job/Grinder/2032), [2](https://openj9-jenkins.osuosl.org/job/Grinder/2036/)

There are multiple failures in s390-linux
- extended.functional - `functional_s390x_linux_Personal_testList_1` job got cancelled due to timeout. Ran it again and it [passed](https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Personal_testList_1/53/).
- sanity.system - Failures similar to `TestJlmRemoteClassAuth_0`. All reproducible in the original build and nightly build: [original](https://openj9-jenkins.osuosl.org/job/Grinder/2026/), [nightly build](https://openj9-jenkins.osuosl.org/job/Grinder/2027/)
- extended.system,special.system - `MiniMix_5m`, `DBBLoadTest_5m_1`, `MiniMix_3h_0` - Assertion failures due to connection issues. These all look like `java.net.NoRouteToHostException: No route to host (Host unreachable)` errors that eventually nest down to a `java.lang.NullPointerException`. I was able to reproduce this issue in both nightly and original builds: [original build](https://openj9-jenkins.osuosl.org/job/Grinder/2028/). [nightly build](https://openj9-jenkins.osuosl.org/job/Grinder/2029/).

There's one more failure in Java 11 which looks like a legitimate issue. I'll comment further on it in the next comment.

**Comment by dchopra001** [comment]
Following on from my last comment, sanity.functional on s390 shows a  segmentation fault in `Compiled_method=java/lang/String.getCharsNoBoundChecks(II[CI)V` in `j9vm.test.jni.CriticalRegionTest` in `J9vmTest_4`
 [5x grinder to reproduce](https://openj9-jenkins.osuosl.org/job/Grinder/2023/) - failed, [5x grinder with nightly](https://openj9-jenkins.osuosl.org/job/Grinder/2024/) - Passed, [40x grinder with nightly](https://openj9-jenkins.osuosl.org/job/Grinder/2025)- Passed.

So the problem so far is only reproducible with the compressed strings enabled build. Considering a crash in a JITT'ed method, the problem looks to be JIT related. I will try and collect logs/core for this and proceed from there.

**Comment by pshipton** [comment]
The zlinux problems are https://github.com/eclipse-openj9/openj9/issues/16673

**Comment by pshipton** [comment]
Windows ClassNotFoundException is probably https://github.com/eclipse-openj9/openj9/issues/16513

**Comment by pshipton** [comment]
The zlinux DDR failures are related to string compression afaik.

> Additionally, seems like testList_1 for this build got timed out. I've launched another one [here](https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Personal_testList_1/31/).

Depending on the machine it lands on, it won't work until the machines are fixed. Avoid rh7 machines.

**Comment by pshipton** [comment]
> The zlinux DDR failures are related to string compression afaik.
> extended.functional sees failures in DDR tests that are non-JIT related.

Considering they only happen on zlinux, it seems suspicious.

**Comment by dchopra001** [comment]
> Considering they only happen on zlinux, it seems suspicious.

Just to clarify the problem looks to be related to String Compression, just not to JIT specifically. I had a grinder from a couple weeks ago showing the same failure with `-Xint`. It's expired now. I'll try and reproduce the issue again in a grinder later today.

**Comment by pshipton** [comment]
> I had a grinder from a couple weeks ago showing the same failure with -Xint

We need to look carefully at what the testing is doing. Possibly the -Xint option isn't being passed to the JVM which is failing. Instead of using EXTRA_OPTIONS, you can create a new playlist entry that sets an environment variable `exports OPENJ9_JAVA_OPTIONS=-Xint` before starting the test so everything is affected.

**Comment by pshipton** [comment]
See https://github.com/adoptium/aqa-tests/blob/master/doc/userGuide.md#how-to-pass-in-environment-variables

**Comment by dchopra001** [comment]
The problem described in https://github.com/eclipse-openj9/openj9/pull/16452#issuecomment-1430117490 can be resolved by disabling the inlining of `StringLatin1.inflate` routine when arraylets are enabled in OpenJ9. I will have a PR open to resolve this issue today. I launched a JDK11 and JDK17 build here to test this change: https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-CompactString/8/.

Java 11 build is clean. 3 of the Java 17 builds failed, all exhibiting the same symptoms as we have been seeing in the DDR tests. The failures happen when trying to compile the tests. Interestingly they all happen on RH7 machines.

I'll try to reproduce this locally on an RH7 machine.

**Comment by dchopra001** [comment]
With the change introduced in https://github.com/eclipse-openj9/openj9/pull/17546, string compression enabled builds look to be stable now. Here's a recent build I ran: https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-CompactString/13/.

The failures on x86 in the build above are unrelated existing issues. The s390 failures look like infra failures because I'm not able to reproduce them in 100x grinders: https://openj9-jenkins.osuosl.org/job/Grinder/2489/. I'll do some additional testing while we wait for https://github.com/eclipse-openj9/openj9/pull/17546 to be merged. Following that I think we should be able to merge this as well.

**Comment by dchopra001** [comment]
@pshipton #17546 is now merged. My build in https://github.com/eclipse-openj9/openj9/pull/16452#issuecomment-1588358789 didn't produce any reproducible/new problems either. Can we now proceed with a review/merge for this PR?

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
We'll see how it goes.

**Comment by pshipton** [comment]
Re-enabled in https://github.com/eclipse-openj9/openj9/pull/17703

@dchopra001 pls create a doc issue at https://github.com/eclipse-openj9/openj9-docs/issues

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9-docs/issues/1160

**Pull request merged**
