### PR TITLE
Update getVirtualThreadState to handle all mounted scenarios

### PR DESCRIPTION
**Pull request by babsingh**
A mounted virtual thread is associated to a valid J9VMThread.

For virtual threads, targetThread is non-null for PARKING and YIELDING
states. getVirtualThreadState has been updated to use carrier thread's
state whenever targetThread is non-null for a virtual thread. This
correctly returns the JVMTI_THREAD_STATE_SUSPENDED flag for virtual
threads.

Related: #15762

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
All four tests in the following test suite pass: https://github.com/ibmruntimes/openj9-openjdk-jdk19/tree/openj9/test/hotspot/jtreg/serviceability/jvmti/thread/GetThreadState.

**Comment by babsingh** [comment]
getVirtualThreadState is called from two locations, which verify that the input thread parameter is a virtual thread instance.

**Comment by babsingh** [comment]
@hangshao0 Can you please review the PR? View the changes with whitespace hidden.

**Review by hangshao0 — APPROVED** [review]
LGTM.

**Comment by babsingh** [comment]
@pshipton Can you please review/merge these changes?

**Comment by pshipton** [comment]
jenkins test sanity,extended alinux64 jdk8,jdk19

**Comment by babsingh** [comment]
> https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_aarch64_linux_Personal/80/tapResults/

In the above build, the below failure is seen 6 times:
```
FAILED: test_deleteCharAt
java.lang.AssertionError: Index >= buffer length should have failed
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from sun.misc.Launcher$AppClassLoader@4b914c4f(file:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_aarch64_linux_Personal_testList_1/aqa-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.lang.Test_StringBuffer.test_deleteCharAt(Test_StringBuffer.java:323) from sun.misc.Launcher$AppClassLoader@4b914c4f(file:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_aarch64_linux_Personal_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

This PR contains changes which are ifdef'ed between `JAVA_SPEC_VERSION >= 19`. So, the above JDK8 failure is unrelated to this PR.

**Comment by pshipton** [comment]
I expect the jdk8 failures are a mismatch between having a new test and not having the corresponding JCL changes. Related to https://github.com/eclipse-openj9/openj9/pull/15979

**Review by pshipton — APPROVED** [review]

**Pull request merged**
