### PR TITLE
Fix check in JITServer AOT class chain compilation

### PR DESCRIPTION
**Pull request by cjjdespres**
Fixes: #16099
Signed-off-by: Christian Despres <despresc@ibm.com>

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu @AlexeyKhrabrov. This does eliminate the class chain record failures.

**Review by AlexeyKhrabrov — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk17

**Review by mpirvu — APPROVED** [review]

**Comment by cjjdespres** [comment]
The test that failed was `cmdLineTester_jvmtitests_debug_11`, with a segfault that looks like #14704.

**Pull request merged**
