### PR TITLE
RISC-V: backport libffi commit aa3fce08

### PR DESCRIPTION
**Pull request by janvrany**
This commit backports changes in upstream libffi, namely change in
commit

   commit aa3fce08ba620c50db17215a9f14dd0f1facf741
   Author: Andreas Schwab <schwab@linux-m68k.org>
   Date:   Sun Feb 13 21:04:33 2022 +0100

This change properly widens integral return value narrower than
XLEN bits as documented [1]. Changes done in OpenJ9 commit 4c0adb
depend on this (documented) libffi behavior.

[1]: https://github.com/libffi/libffi/blob/ab1677106605aba1c27665964ff90bea59612ce3/doc/libffi.texi#L216-L221

### CODE REVIEW

**Comment by janvrany** [comment]
FYI: @ChengJin01 , @pshipton , @sxa

**Comment by ChengJin01** [comment]
Hi @janvrany,  what we usually do is to pull back the last version of `libffi/riscv` in github  (specifically https://github.com/libffi/libffi/tree/master/src/riscv in this case) to replace `runtime/libffi/riscv` instead of directly fixing them up in our code to keep it up-to-date and avoid any inconsistency in `libffi` in the future when updating, which means you need to raise an request with the proposed fix at first at https://github.com/libffi/libffi/issues for their review.

**Comment by janvrany** [comment]
@ChengJin01 The fix is already merged in upstream: https://github.com/libffi/libffi/pull/680

The OpenJ9 version of `libffi/riscv/ffi.c` pulled into OpenJ9 was not the upstream version anyway - beside IBM copyright, OpenJ9 version uses `ALIGN()` macro whereas at that time upstream was using `FFI_ALIGN()` macro for the same purpose. So it seems to me the RISC-V support was back-ported to some older version of libffi which has been pulled into openj9 before RISC-V support got in libffi. 

In any case, I can copy the upstream version, add IBM copyright (I guess that's required) and change `FFI_ALIGN()` back to `ALIGN()` - but then the diff would be exactly the same.

That being said, if you now update whole libffi from upstream, nothing will break and there will be no inconsistency.

**Comment by ChengJin01** [comment]
@janvrany,
> The OpenJ9 version of libffi/riscv/ffi.c pulled into OpenJ9 was not the upstream version anyway - beside IBM copyright, OpenJ9 version uses ALIGN() macro whereas at that time upstream was using FFI_ALIGN() macro for the same purpose. So it seems to me the RISC-V support was back-ported to some older version of libffi which has been pulled into openj9 before RISC-V support got in libffi.

`FFI_ALIGN()` was already redefined as `ALIGN()` in https://github.com/eclipse-openj9/openj9/blob/master/runtime/include/ffi_common.h given we updated liff/x86 a couple of months ago, in which all setting/dependency should be kept up-to-date.
The only thing you need to do is to compare `/runtime/libffi/riscv` with the latest version of `/libffi/riscv` at https://github.com/libffi/libffi/tree/master/src/riscv and replace them if any difference and also double-check `/runtime/libffi/preconf/rv64` to see whether anything in there needs to be updated.

> That being said, if you now update whole libffi from upstream, nothing will break and there will be no inconsistency.

We have a bunch of settings in /runtime/libffi specific to OpenJ9 which are totally different from the upstream, which means replacing them all will screw up the whole code related to libiffi in OpenJ9.

**Comment by janvrany** [comment]
> The only thing you need to do...

This is exactly what I did.

**Review by sxa — APPROVED** [review]
Looks reasonable to me but since I'm not an openJ9 committer I don't believe my review counts ;-)

**Comment by ChengJin01** [comment]
FYI: @tajila, @DanHeidinga, @gacholio

**Comment by gacholio** [comment]
Would it make sense to reimport the project wholesale?

**Comment by janvrany** [comment]
@gacholio I do not know, but given that it is already a patchwork I'm not sure is it worth. I'm certainly not keen reimporting it myself.

**Review by gacholio — APPROVED** [review]

**Pull request merged**
