### PR TITLE
Add CT helpers for detecting geneirc annotations

### PR DESCRIPTION
**Pull request by tajila**
Add CT helpers for detecting geneirc annotations

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
FYI @jdmpapin @nbhuiyan

**Comment by tajila** [comment]
@gacholio Please review

**Comment by gacholio** [comment]
cthelpers.cpp needs copyright update.

**Review by gacholio — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by gacholio** [comment]
Question: What is the value if these helpers over just calling the relevant existing functions?

**Comment by tajila** [comment]
> Question: What is the value if these helpers over just calling the relevant existing functions?

The existing functions are defined in j9util which AFAIK the j9jit.so isn't built with

**Comment by tajila** [comment]
Actually thats not true, it looks like its linked with j9util

**Comment by tajila** [comment]
@nbhuiyan can you try using `methodContainsRuntimeAnnotation` directly? If that works then Ill close this

**Comment by nbhuiyan** [comment]
@tajila I am able to use `methodContainsRuntimeAnnotation` directly from JIT, so maybe this change is not necessary.

**Pull request closed without merging**
