### PR TITLE
Correct reading BuildVersionCommand from OSX core files

### PR DESCRIPTION
**Pull request by keithc-ca**
It was not reading the `platform` field causing misinterpretation of the following fields.

The `sdk` field was read as the number of tools yielding unreasonable values (e.g. 11.3.0 is expressed as 0x000b0300 = 721664), with significant expense of both time and space.

Also, the decomposition of versions was incorrect due to off-by-one errors in the loop bounds (e.g. 11.3.0 was decomposed as 0.110.30).

(Discovered while investigating #15114).

### CODE REVIEW

**Comment by keithc-ca** [comment]
Note: see `struct build_version_command` at https://opensource.apple.com/source/cctools/cctools-973.0.1/include/mach-o/loader.h.auto.html.

**Comment by pshipton** [comment]
jenkins test extended xmac,amac jdk11

**Comment by pshipton** [comment]
jenkins test extended xmac,amac jdk11

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
This seems a good candidate for 0.33

**Pull request merged**
