### PR TITLE
Update the value of ACC_VALUE and remove j.l.IdentityObject

### PR DESCRIPTION
**Pull request by hangshao0**
1. Update the value of ACC_VALUE
2. remove ACC_PERMITS_VALUE
3. Add ACC_IDENTITY
4. remove IdentityObject
5. Update test code
6. Re-include PackageAnnotation tests which were excluded because of 
the injected j.l.IdentityObject.
7. OpenJDK ASM code is not updated for ACC_IDENTITY yet, it does not
allow ACC_IDENTITY to be set. Exclude tests testGCRetransform and
test_EXTENDED_HCR which failed on access flags check of ACC_IDENTITY

issue #15081, #12878

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
Because OpenJDK updated the value of `ACC_VALUE`, the valhalla builds are broken. This PR should unblock the valhalla builds.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity alinuxvalst jdknext

**Comment by pshipton** [comment]
@hangshao0 @tajila this broke at least internal DDR compilation. See /job_output.php?id=35316088
Pls fix quickly or revert.
```
    [javac] /tmp/bld_29819/job_35316088/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ValueTypeHelper.java:225: error: cannot find symbol
    [javac] 			return romClass.modifiers().allBitsIn(J9JavaAccessFlags.J9AccPermitsValue);
    [javac] 			                                                       ^
    [javac]   symbol:   variable J9AccPermitsValue
    [javac]   location: class J9JavaAccessFlags
```

**Comment by keithc-ca** [comment]
I have a small change that should fix this. I'll launch an internal build to verify first.

**Comment by keithc-ca** [comment]
#15150 should fix the internal build failure.

**Pull request merged**
