### PR TITLE
Ensure class flags are set before class is visible

### PR DESCRIPTION
**Pull request by gacholio**
Fixes: #15633

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
This is a direct copy/paste of the code with `result` changed to `state->ramClass`

**Comment by gacholio** [comment]
jenkins test sanity all jdk8

**Comment by gacholio** [comment]
jenkins test sanity xlinuxval jdk17

**Comment by gacholio** [comment]
jenkins test sanity xlinux jdk11

**Comment by gacholio** [comment]
jenkins test sanity xlinuxval jdk19

**Comment by tajila** [comment]
Jenkins test sanity,extended plinuxval jdknext

**Comment by gacholio** [comment]
Jenkins test sanity,extended plinuxval jdknext

**Comment by gacholio** [comment]
jenkins compile win jdk8

**Review by tajila — APPROVED** [review]

**Pull request merged**
