### PR TITLE
Disclaim IProfiler memory

### PR DESCRIPTION
**Pull request by mpirvu**
This commit allocates memory for IProfiler data using a dedicated persistent memory allocator. 
This allocator is instructed to use mmap and to back the allocator memory by a file or swap.
Heuristics dictate when to issue the disclaim operations.
The disclaim can be disabled with -Xjit:disableIprofilerDataDisclaiming

### CODE REVIEW

**Comment by mpirvu** [comment]
jenkins compile win jdk17

**Comment by mpirvu** [comment]
jenkins test sanity xlinux,plinux,zlinux,alinux64 jdk17

**Comment by mpirvu** [comment]
plinux has a few failures:
```
testJITServer_0 Start Time: Tue Apr 23 15:43:27 2024 Epoch Time (ms): 1713887007521
variation: Mode610
JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon 
...
Expected an exit value of 0 or 143, got 255 instead.
Dumping the contents of log file: /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Personal_testList_1/aqa-tests/TKG/output_1713882975557/testJITServer_0/testServer.client.out
////////////////////////////////////////////////////////////////////////
//// Unhandled exception
//// Type=Segmentation error vmState=0x00000000
//// J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
//// Handler1=00007FFFB0EA1350 Handler2=00007FFFB0DC88E0
//// R0=00007FFFAB2A2348 R1=00007FFFB161C390 R2=00007FFFABFBEC00 R3=0000000000000000
//// R4=00000000000FFF4F R5=0000000000000000 R6=0000000000000000 R7=0000000000000000
//// R8=0000000000000000 R9=0000000000000000 R10=0000000000000001 R11=0000000000000000
//// R12=00007FFFB18AEF50 R13=00007FFFB16268E0 R14=00007FFFB161D3F8 R15=0000000028D21722
//// R16=00007FFFABFE5C14 R17=00007FFFABFE59D8 R18=0000000000000001 R19=00007FFFABFD3474
//// R20=00007FFFAC0E7698 R21=00007FFFABFEADE0 R22=00007FFFABFEAED8 R23=00007FFFABFE5FA0
//// R24=0000000000095800 R25=00007FFFAC0E7690 R26=00007FFFB1591F90 R27=000000000001FFE9
//// R28=00007FFFABFE31B0 R29=00000000000FFF58 R30=00000000000FFF48 R31=0000000000000000
//// NIP=00007FFFAB2A2074 MSR=800000000280F033 ORIG_GPR3=00007FFFAB2A2344 CTR=00007FFFB18AEF50
//// LINK=00007FFFAB2A2348 XER=0000000020040000 CCR=0000000044884282 SOFTE=0000000000000001
//// TRAP=0000000000000300 DAR=0000000000000008 dsisr=0000000040000000 RESULT=0000000000000000
//// FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR1 ffffffffffffffff (f: 4294967296.000000, d: -nan)
//// FPR2 3fefdcb192d872ff (f: 2463658752.000000, d: 9.956901e-01)
//// FPR3 3fc9999980000000 (f: 2147483648.000000, d: 2.000000e-01)
//// FPR4 3fce840b4ac4e4d2 (f: 1254417664.000000, d: 2.384047e-01)
//// FPR5 7fffffff7fffffff (f: 2147483648.000000, d: nan)
//// FPR6 0000000400000320 (f: 800.000000, d: 8.487984e-314)
//// FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR8 0000003500002710 (f: 10000.000000, d: 1.124658e-312)
//// FPR9 000001900000012c (f: 300.000000, d: 8.487983e-312)
//// FPR10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR13 0000015500000154 (f: 340.000000, d: 7.236006e-312)
//// FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
//// Module=/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Personal_testList_1/jdkbinary/j2sdk-image/lib/default/libj9jit29.so
//// Module_base_address=00007FFFAB030000
//// Target=2_90_20240423_654 (Linux 4.18.0-535.el8.ppc64le)
//// CPU=ppc64le (4 logical CPUs) (0x1dbbc0000 RAM)
//// ----------- Stack Backtrace -----------
//// _ZN2J919PersistentAllocator16allocateInternalEm+0x64 (0x00007FFFAB2A2074 [libj9jit29.so+0x272074])
//// _ZN2J919PersistentAllocator8allocateEmSt9nothrow_tPv+0x18 (0x00007FFFAB2A2348 [libj9jit29.so+0x272348])
//// _ZN12TR_IProfilerC1EP11J9JITConfig+0x12c (0x00007FFFAB5A237C [libj9jit29.so+0x57237c])
//// _ZN18JITClientIProfilerC1EP11J9JITConfig+0x20 (0x00007FFFAB62D0E0 [libj9jit29.so+0x5fd0e0])
//// _ZN18JITClientIProfiler8allocateEP11J9JITConfig+0x40 (0x00007FFFAB62D150 [libj9jit29.so+0x5fd150])
//// onLoadInternal+0x1354 (0x00007FFFAB1D6984 [libj9jit29.so+0x1a6984])
//// J9VMDllMain+0x67c (0x00007FFFAB1AEA0C [libj9jit29.so+0x17ea0c])
//// runJ9VMDllMain+0x108 (0x00007FFFB0EBCD88 [libj9vm29.so+0x5cd88])
```
```
testJitserverArguments_0
 [ERR] protectedBacktrace+0x24 (0x00003FFF81902CC4 [libj9prt29.so+0x32cc4])
 [ERR] omrsig_protect+0x3e4 (0x00003FFF81909D94 [libj9prt29.so+0x39d94])
 [ERR] omrintrospect_backtrace_thread_raw+0xe4 (0x00003FFF819032E4 [libj9prt29.so+0x332e4])
 [ERR] protectedIntrospectBacktraceThread+0x24 (0x00003FFF81902904 [libj9prt29.so+0x32904])
 [ERR] omrsig_protect+0x3e4 (0x00003FFF81909D94 [libj9prt29.so+0x39d94])
 [ERR] omrintrospect_backtrace_thread+0x94 (0x00003FFF81902A14 [libj9prt29.so+0x32a14])
 [ERR] generateDiagnosticFiles+0xd4 (0x00003FFF819E0D24 [libj9vm29.so+0x40d24])
 [ERR] omrsig_protect+0x3e4 (0x00003FFF81909D94 [libj9prt29.so+0x39d94])
 [ERR] structuredSignalHandler+0x194 (0x00003FFF819E1084 [libj9vm29.so+0x41084])
 [ERR] structuredSignalHandlerVM+0x58 (0x00003FFF819E13A8 [libj9vm29.so+0x413a8])
 [ERR] mainSynchSignalHandler+0x298 (0x00003FFF81908B78 [libj9prt29.so+0x38b78])
 [ERR] __kernel_sigtramp_rt64+0x0 (0x00003FFF82270478)
 [ERR]  (0x0000010026FD2470 [<unknown>+0x0])
 [ERR] _ZN2J919PersistentAllocator8allocateEmSt9nothrow_tPv+0x18 (0x00003FFF79F42348 [libj9jit29.so+0x272348])
 [ERR] _ZN12TR_IProfilerC1EP11J9JITConfig+0x12c (0x00003FFF7A24237C [libj9jit29.so+0x57237c])
 [ERR] _ZN18JITServerIProfilerC2EP11J9JITConfig+0x20 (0x00003FFF7A2CC890 [libj9jit29.so+0x5fc890])
 [ERR] _ZN18JITServerIProfiler8allocateEP11J9JITConfig+0x40 (0x00003FFF7A2CC940 [libj9jit29.so+0x5fc940])
 [ERR] onLoadInternal+0x1360 (0x00003FFF79E76990 [libj9jit29.so+0x1a6990])
 [ERR] J9VMDllMain+0x67c (0x00003FFF79E4EA0C [libj9jit29.so+0x17ea0c])
```

**Comment by mpirvu** [comment]
jenkins test sanity zlinux jdk17

**Comment by mpirvu** [comment]
jenkins test sanity all jdk17

**Comment by mpirvu** [comment]
There was one failure on ARM with JITServer due to:
`[ERR] can't bind server address: Address already in use`

**Comment by mpirvu** [comment]
@ymanton Could you please review/merge this PR? Thanks

**Review by ymanton — APPROVED** [review]
The code looks alright to me, sorry it took a while to process.

**Pull request merged**
