### PR TITLE
In PR testing redefine `all` to exclude UNB platforms

### PR DESCRIPTION
**Pull request by pshipton**
Issue https://github.com/eclipse-openj9/openj9/issues/18111

### CODE REVIEW

**Comment by pshipton** [comment]
@hzongaro fyi, you can merge if it looks good.

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

**Comment by hzongaro** [comment]
Jenkins compile all jdk17

**Comment by pshipton** [comment]
Reverted via https://github.com/eclipse-openj9/openj9/pull/19223

**Pull request merged**
