### PR TITLE
Simplify lw5 tests after removal of aconst_init and withfield

### PR DESCRIPTION
**Pull request by theresa-m**
makeRef and makeGenericValue can be combined since they both use `<init>` now

### CODE REVIEW

**Review by hangshao0 — APPROVED** [review]
LGTM.

**Comment by hangshao0** [comment]
The PR [description](https://github.com/eclipse-openj9/openj9/pull/18551#issue-2021527636) is:

> makeRef and makeGenericValue can be combined since they both use now. 

Looks to me that `<init>` is missing. Could you update that ?

**Comment by theresa-m** [comment]
Fixed now.

**Comment by hangshao0** [comment]
Jenkins test sanity,extended winval jdknext

**Comment by hangshao0** [comment]
Jenkins test sanity,extended aixval jdknext

**Pull request merged**
