### PR TITLE
Improve DDR compatibility story for fields

### PR DESCRIPTION
**Pull request by keithc-ca**
This represents the changes discussed in #12370.

A new file is introduced which must mention any field accessed in hand-written DDR code. Fields which have always been present are marked as 'required', for others, their type must be provided. The generated methods for optional fields may throw `NoSuchFieldException` which must be caught and dealt with appropriately.

The updated build process compiles that hand-written DDR code with *only* those fields so using a new field will require updating `AuxFieldInfo29.dat`. No new, required fields should be listed there. If a field is removed from VM code, it must be then be listed as an optional field and DDR code updated accordingly.

The following must be merged together with this:
* ibmruntimes/openj9-openjdk-jdk8#500
* ibmruntimes/openj9-openjdk-jdk11#407
* ibmruntimes/openj9-openjdk-jdk16#50
* ibmruntimes/openj9-openjdk-jdk#313

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,extended win,xlinux jdk8 depends ibmruntimes/openj9-openjdk-jdk8#500

**Comment by pshipton** [comment]
jenkins test sanity,extended aix,plinux jdk11 depends ibmruntimes/openj9-openjdk-jdk11#407

**Comment by pshipton** [comment]
jenkins compile plinux,zlinux,osx,aix,win32 jdk8 depends ibmruntimes/openj9-openjdk-jdk8#500

**Comment by pshipton** [comment]
jenkins compile win,xlinux,zlinux,osx jdk11 depends ibmruntimes/openj9-openjdk-jdk11#407

**Comment by pshipton** [comment]
jenkins compile all jdk16 depends ibmruntimes/openj9-openjdk-jdk16#50

**Comment by keithc-ca** [comment]
The AIX failure seems to be a lack of disk space:
```
	INFO: /home/jenkins/workspace/Build_JDK11_ppc64_aix_Personal/openj9/runtime/tests/shared/OpenCacheHelper.cpp(50) openTestCache Opening test cacheJVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 163840, requested bytes = 16777216.
JVMSHRC840E Failed to start up the shared cache.
```

**Comment by pshipton** [comment]
The failed AIX test is related to disk space and not DDR.

**Comment by pshipton** [comment]
Compile against jdk17 staging branch https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-Personal/71/

**Review by pshipton — APPROVED** [review]

**Pull request merged**
