### PR TITLE
Adding missing break statement

### LINKED ISSUE #11741: Missing break or fall through statements
There is no break so `isIndirectCall` is reassigned
https://github.com/eclipse-openj9/openj9/blob/8394cffecaf5ea67e60c837a3b8f27e8c7d5c290/runtime/compiler/optimizer/InterpreterEmulator.cpp#L444-L449

Also unlike here
https://github.com/eclipse-openj9/openj9/blob/a1cfdc2866fe91f5eb5d775ff58a47bd7687a723/runtime/compiler/p/codegen/J9TreeEvaluator.cpp#L8982-L8997
there is no break in this code
https://github.com/eclipse-openj9/openj9/blob/a1cfdc2866fe91f5eb5d775ff58a47bd7687a723/runtime/compiler/p/codegen/J9TreeEvaluator.cpp#L9540-L9554

### PR DESCRIPTION
**Pull request by bhavanisn**
Adding the missing break statement.  
Issue #11741

Signed-off by: Bhavani S N (bhavani.sn@ibm.com)

### CODE REVIEW

**Comment by pshipton** [comment]
Pls use auto-close keywords correctly. `close https://github.com/eclipse-openj9/openj9/issues/11741` (or with another keyword) must be on a line by itself.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by 0xdaryl** [comment]
Sorry, this PR fell through the cracks.  Can you update the copyright header to 2023 and I'll launch CI testing.

**Comment by 0xdaryl** [comment]
A separate PR will eventually be needed for 0.38 once this merges.

**Comment by bhavanisn** [comment]
> 
@0xdaryl I will do that.

**Comment by bhavanisn** [comment]
@0xdaryl  I have changed the copyright header. Thanks.

**Comment by 0xdaryl** [comment]
Jenkins test sanity plinux,aix jdk17

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
I modified the PR comment such that it won't automatically close 11741.  I want the issue to remain open until the fix lands in 0.38.  @bhavanisn , please open a PR for that fix in the 0.38 release branch once this is merged.

**Pull request merged**
