### PR TITLE
Remove vestigal setStackSizeCheckNeeded() calls

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity zlinux jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity zos jdk11

**Comment by 0xdaryl** [comment]
See corresponding OMR commit https://github.com/eclipse/omr/pull/6234/commits/17e7191ffc883942005e0357d129c5f1defb2697

**Comment by 0xdaryl** [comment]
@joransiu : would you mind reviewing and merging please?

**Review by joransiu — APPROVED** [review]
LGTM.  Thanks for the cleanup.

**Pull request merged**
