### PR TITLE
Skip zero-init, checks for some BigInteger methods

### PR DESCRIPTION
**Pull request by ymanton**
This patch recognizes the following BigInteger methods:

* `BigInteger.BigInteger(long): void`
* `BigInteger.toByteArray(): byte[]`
* `BigInteger.stripLeadingZeroBytes(byte[], int, int): int[]`
* `BigInteger.stripLeadingZeroBytes(int, byte[], int, int): int[]`

and skips array zero-initialization, NULL, and bounds checks in these methods.

### CODE REVIEW

**Comment by ymanton** [comment]
Jenkins test sanity.functional all jdk8,jdk21

**Comment by vijaysun-omr** [comment]
I have also asked @klangman for his review on this since he has some prior experience with issues in the relevant code.

**Comment by klangman** [comment]
The risk we face with this type of thing is that we know that someone, at some point, will attempt to access a BigInteger object from two different threads at the same time.  So we have to be sure that there is no room to crash here based on misuse of a BigInteger object. The Java8 (apache) version only has toByteArray() (the other two methods don't exist), and that method is larger (and more scary) then the later versions, but I can't say that I see any potential issues in my review of the Java8 toByteArray() code if checks are removed. On the other hand it's hard to see all the possibilities since issues can be very subtle as evidenced by the number of customer issues we have faced around recognized methods in the past.

**Comment by klangman** [comment]
Since I was unable to find any potential problems, i'll give it a LGTM.

**Comment by vijaysun-omr** [comment]
I looked at the Java code in Semeru JDK and the skipped checks are either on newly allocated arrays (no multithreading issue) or get through a check such as `Objects.checkFromIndexSize` in the code prior to the checks we are skipping.

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Having said that, I did not look through the JCL code for every Java version that is in support. So, @ymanton we may want to check that the guarantees mentioned above still are true in all the Java versions we are supporting before we merge this.

**Comment by ymanton** [comment]
`Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal` failed for reasons unrelated to this PR. It looks like the job ran on CentOS 6 and curl might be too old to do what we want?

```
23:23:07  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK8_x86-64_linux_Personal/540/OpenJ9-JDK8-x86-64_linux-20240527-170825.tar.gz
23:23:07  curl: option -OLJSks: is unknown
23:23:07  curl: try 'curl --help' or 'curl --manual' for more information
```

`Build_JDK8_x86-64_mac_Personal` and `Build_JDK21_x86-64_mac_Personal` were aborted for lack of available machines.

I'm assuming we're only concerned with JDKs 8, 11, 17, 21, 22? And we also have the consider the Harmony version of BigDecimal? These are the versions I looked at.

`BigInteger(long)` is simple in all versions and looks safe to skip. It doesn't exist in Harmony.

`BigInteger.stripLeadingZeroBytes()` has a different signature in JDK 8 and isn't affected by this PR. JDK 22 moves the implementation of this method to another method with a different signature and calls that method from this one, so there should be no allocations or checks left in this method to skip. JDK 11, 17, 21 are functionally identical and look safe. It doesn't exist in Harmony.

`BigInteger.toByteArray()` is the same in all OpenJDK versions and looks safe to skip. As @klangman mentioned, the Harmony version is more convoluted. Looking into that one a bit more.

**Comment by vijaysun-omr** [comment]
Yes, to the versions to check. Is it possible to add the other `stripLeadingZeroBytes` method that exists in JDK22 only to the skip checks list so that that one is also optimized ?

**Comment by ymanton** [comment]
Added the JDK 22 signature, and didn't find any problems testing this change against Harmony BigInteger.

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Jenkins test sanity.functional all jdk8,jdk21

**Comment by vijaysun-omr** [comment]
Jenkins test sanity.functional xlinux jdk8

**Comment by vijaysun-omr** [comment]
Jenkins test sanity.functional xmac jdk21

**Comment by vijaysun-omr** [comment]
Jenkins test sanity.functional xlinux jdk8

**Comment by vijaysun-omr** [comment]
Jenkins test sanity.functional zlinux jdk21

**Comment by vijaysun-omr** [comment]
Checks have passed. Merging.

**Pull request merged**
