### PR TITLE
Improve redirector

### PR DESCRIPTION
**Pull request by keithc-ca**
Only decorate function names on 32-bit Windows
* define and use `DECORATED_NAME()` where appropriate
* eliminates need to remove decoration at runtime

Also:
* define `_IF` in `helpers.m4` and add support for `#else` blocks
* add missing comments on `#else` and `#endif`
* add missing dependency of `generated.c` on `forwarders.m4`
* remove recursion from forwarding functions
* allow for better string sharing
* use `fprintf()` throughout (instead of also using `printf()`)

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity plinux,win,win32 jdk8

**Comment by pshipton** [comment]
Some kind of infra problem, like jenkins was rebooted.

Jenkins test sanity plinux,win,win32 jdk8

**Comment by pshipton** [comment]
win32 build failed `Fatal Error: Missing forwarder for JVM_GetInterfaceVersion()`

**Comment by keithc-ca** [comment]
I'll have to figure out why it's generating
```
    DECORATED_NAME(JVM_GetInterfaceVersion, 4)
```
instead of
```
    DECORATED_NAME(JVM_GetInterfaceVersion, 0)
```

**Comment by keithc-ca** [comment]
I fixed a typo in `decorate_impl`.

**Comment by keithc-ca** [comment]
Jenkins test sanity win32 jdk8

**Comment by keithc-ca** [comment]
The change should only affect x86-32_windows, the other builds can be seen at https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/1097/.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
