### PR TITLE
Halt threads that are being attached in single thread mode take 2

### PR DESCRIPTION
**Pull request by tajila**
Halt threads that are being attached in single thread mode take 2

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
redo of https://github.com/eclipse-openj9/openj9/pull/15000

**Comment by tajila** [comment]
FYI previous compilation failrues on zOS

```
vmthread.cpp", line 142.43: CCN5216 (S) An expression of type "void *" cannot be converted to type "J9RIParameters *".
"./vmthread.cpp", line 1301.26: CCN5216 (S) An expression of type "void *" cannot be converted to type "char *".
"./vmthread.cpp", line 1997.31: CCN5216 (S) An expression of type "void *" cannot be converted to type "char *".
```

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity zlinux jdk11

**Comment by tajila** [comment]
Im also running mz internally

**Comment by tajila** [comment]
@gacholio successfully built mz internally

**Review by gacholio — APPROVED** [review]

**Pull request merged**
