### PR TITLE
Fix StartContinuationProcessing and verbosegc report issues

### PR DESCRIPTION
**Pull request by LinHu2016**
- Remove duplicated StartContinuationProcessing
- Fix missing MM_CopyForwardStats._continuationCandidates merge

Signed-off-by: Lin Hu <linhu@ca.ibm.com>

### CODE REVIEW

**Comment by LinHu2016** [comment]
@amicic @dmitripivkine please review the changes, Thanks

**Comment by LinHu2016** [comment]
> we do the same thing in MM_ScavengerRootScanner::startProcessing ? we should probably rename it to be more specific like startContinuation(Objects?)Processing

yes, same thing in MM_ScavengerRootScanner::startProcessing, or Can we merge startUnfinalizedProcessing into MM_ScavengerRootScanner::startProcessing?

**Comment by amicic** [comment]
Would could merge, but still the point is that startProcessing method needs a bit more specific name, about what kind of processing we start (in that merged case, for example it could be renamed to startClearalbeRootsProcessing). I'd rather keep them separate, since typically for each root or clearable root, we have _separate_ top level methods for any kind of processing.

**Review by amicic — APPROVED** [review]

**Comment by amicic** [comment]
jenkins compile win jdk19

**Pull request merged**
