### PR TITLE
[FFI/Jtreg] Validate the downcall function address in JDK20

### PR DESCRIPTION
**Pull request by ChengJin01**
The changes check the life cycle of the surrounding scope of the downcall
function address to guarantee the validity of the scope during the downcall.

Fixes: #17062

Signed-off-by: ChengJin01 <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
Note:
[1] The PR refactored the code for the validity check on the scope to void duplicate code everywhere to throw the exception.
[2] The changes are verified in OpenJ9 FFI test suites plus the related Jtreg test suites in JDK17/19/20.

**Comment by ChengJin01** [comment]
Reviewer: @tajila
FYI: @pshipton

**Comment by tajila** [comment]
jenkins test sanity,openjdk.sanity plinux jdk20

**Comment by ChengJin01** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_openjdk.sanity_ppc64le_linux_Personal/1/console
```
16:07:58  Error: cannot find the following tests: openjdk.sanity (note: group target such as sanity is not accepted inside testList)
16:07:58  
16:07:58  makeGen.mk:45: recipe for target 'autogen' failed
16:07:58  make[1]: *** [autogen] Error 1
16:07:58  make[1]: Leaving directory '/home/jenkins/workspace/Test_openjdk20_j9_openjdk.sanity_ppc64le_linux_Personal/aqa-tests/TKG'
16:07:58  makefile:49: recipe for target '_openjdk.sanity' failed
16:07:58  make: *** [_openjdk.sanity] Error 2
```
It seems the failure was caused by the incorrect setting in the test job at https://github.com/eclipse-openj9/openj9/pull/17074#issuecomment-1490741247.

**Comment by tajila** [comment]
jenkins test sanity.openjdk plinux jdk20

**Pull request merged**
