### PR TITLE
[FFI/Test] Fix the wrong invocation on the native function in downcall

### PR DESCRIPTION
**Pull request by ChengJin01**
The PR resolves the test issue with the wrong invocation in downcall
to ensure the test code in java calls the correct native function in
native.

Fixes: #20048

Signed-off-by: ChengJin01 <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
The test fix was verified on all supported platforms at https://github.com/eclipse-openj9/openj9/issues/20048#issuecomment-2316414480.

**Comment by ChengJin01** [comment]
Reviewer: @pshipton
FYI: @tajila

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
I assume we need a PR created for 0.48 as well?

**Comment by ChengJin01** [comment]
> I assume we need a PR created for 0.48 as well?

PR is created at https://github.com/eclipse-openj9/openj9/pull/20082

**Pull request merged**
