### PR TITLE
Remove unnecessory Assert in clearArgInfo function

### PR DESCRIPTION
**Pull request by r30shah**

### CODE REVIEW

**Comment by r30shah** [comment]
@hzongaro  Can I please get your review on this change - The assert seems to be meaning less - as if we do not have store node and storeNode is not part (Which we would even get only when symbol reference exists), we skip to next item in the list.

**Review by hzongaro — APPROVED** [review]
Looks good.

**Comment by hzongaro** [comment]
Jenkins test sanity all jdk17

**Comment by hzongaro** [comment]
Very safe fix and testing was all successful.  Merging.

**Pull request merged**
