### PR TITLE
Update VirtualThread test options/requirements

### PR DESCRIPTION
**Pull request by fengxue-IS**
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
Enabling gc option -Xgcpolicy:optthruput, when other policy becomes ready, they should be added as new variations
-Xint option will be kept until JIT changes for P/Z/Arch have been merged

**Comment by babsingh** [comment]
jenkins test sanity amac,zlinux,win,xlinux,osx,plinux,aix jdk19

**Comment by babsingh** [comment]
jenkins test sanity win

**Comment by babsingh** [comment]
jenkins test sanity win jdk19

**Review by babsingh — APPROVED** [review]

**Pull request merged**
