### PR TITLE
(0.48) romToRam cache follow up

### PR DESCRIPTION
**Pull request by theresa-m**
Port from https://github.com/eclipse-openj9/openj9/pull/20196

### CODE REVIEW

**Comment by pshipton** [comment]
Set as draft until the issues in the builds are resolved.

**Comment by keithc-ca** [comment]
Please update this to mirror the changes in #20196.

**Comment by theresa-m** [comment]
I just updated the commits to match https://github.com/eclipse-openj9/openj9/pull/20196

**Comment by theresa-m** [comment]
This has been updated with the same changes as https://github.com/eclipse-openj9/openj9/pull/20196

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
