### PR TITLE
Update Offheap guard macro

### PR DESCRIPTION
**Pull request by midronij**
Replace all remaining instances of `J9VM_GC_ENABLE_SPARSE_HEAP_ALLOCATION` with `J9VM_GC_SPARSE_HEAP_ALLOCATION`

### CODE REVIEW

**Comment by midronij** [comment]
@rmnattas @zl-wang here is the PR to update the remaining instances of the old offheap guard macro (which is what was causing the setMemory failure, as well as (potentially) some other failures/issues).

**Review by rmnattas — APPROVED** [review]

**Review by zl-wang — APPROVED** [review]

**Comment by zl-wang** [comment]
Jenkins test sanity.functional xlinux,aix,plinux,zlinux jdk8,jdk23

**Comment by midronij** [comment]
@zl-wang I believe the previous CI failures were due to this branch being a couple of commits behind. I rebased and confirmed that the build passes locally. Could you please rerun the CI tests when you have a chance?

**Comment by zl-wang** [comment]
Jenkins test sanity.functional xlinux,aix,plinux,zlinux jdk8,jdk23

**Comment by zl-wang** [comment]
xlinux failure is unrelated. aborted aix test was due to infra issue.  merging ...

**Pull request merged**
