### PR TITLE
Factor out SSL context creation, improve SSL log message

### PR DESCRIPTION
**Pull request by cjjdespres**
Signed-off-by: Christian Despres <despresc@ibm.com>

### CODE REVIEW

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk17

**Comment by mpirvu** [comment]
For PPC we have again a timeout for `cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3`
```
01:42:36  ===============================================
01:42:36  Running test cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3 ...
01:42:36  ===============================================
01:42:36  cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3 Start Time: Sat Jul  2 19:29:01 2022 Epoch Time (ms): 1656800941075
01:42:36  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
01:42:36  JVMSHRC005I No shared class caches available
01:42:36  JVMSHRC005I No shared class caches available
01:42:36  cache cleanup done
01:42:36  variation: Mode112
01:42:36  JVM_OPTIONS: -XX:+UseJITServer -Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs 
01:42:36  { itercnt=1; \
01:42:36  mkdir -p "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../TKG/output_16567968709299/cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3"; \
01:42:36  cd "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../TKG/output_16567968709299/cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3"; \
01:42:36  export LD_LIBRARY_PATH="/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/openjdkbinary/openjdk-test-image/openj9:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/openjdkbinary/j2sdk-image/bin/../lib/default:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/openjdkbinary/j2sdk-image/bin/../lib/j9vm:"; \
01:42:36  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs  -Xshareclasses:none \
01:42:36  -DTEST_ROOT="/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests" \
01:42:36  -DJAR="/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../TKG/lib/asm-all.jar" \
01:42:36  -DEXE='"/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs  -Xdump ' \
01:42:36  -DEXTRA_Add_OPEN_OPTION='--add-opens=java.base/java.lang.reflect=ALL-UNNAMED' \
01:42:36  -jar "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar" \
01:42:36  -config "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml" \
01:42:36  -explainExcludes -xids all,linux_ppc-64 -xlist "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_17.xml" -nonZeroExitWhenError; \
01:42:36  if [ $? -eq 0 ] ; then echo ""; echo "cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../TKG/output_16567968709299/cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3"; else echo ""; echo "cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_1/aqa-tests/TKG/../TKG/output_16567968709299/TestTargetResult";
Cancelling nested steps due to timeout
```

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit jdk17

**Comment by mpirvu** [comment]
Again timeout:
```
20:24:37  ===============================================
20:24:37  Running test cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3 ...
20:24:37  ===============================================
20:24:37  cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3 Start Time: Tue Jul  5 21:10:22 2022 Epoch Time (ms): 1657066222587
20:24:37  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
20:24:37  JVMSHRC005I No shared class caches available
20:24:37  JVMSHRC005I No shared class caches available
20:24:37  cache cleanup done
20:24:37  variation: Mode112
20:24:37  JVM_OPTIONS: -XX:+UseJITServer -Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs 
20:24:37  { itercnt=1; \
20:24:37  mkdir -p "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../TKG/output_16570628088887/cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3"; \
20:24:37  cd "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../TKG/output_16570628088887/cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3"; \
20:24:37  export LD_LIBRARY_PATH="/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/openjdkbinary/openjdk-test-image/openj9:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/bin/../lib/default:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/bin/../lib/j9vm:"; \
20:24:37  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs  -Xshareclasses:none \
20:24:37  -DTEST_ROOT="/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests" \
20:24:37  -DJAR="/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../TKG/lib/asm-all.jar" \
20:24:37  -DEXE='"/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs  -Xdump ' \
20:24:37  -DEXTRA_Add_OPEN_OPTION='--add-opens=java.base/java.lang.reflect=ALL-UNNAMED' \
20:24:37  -jar "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar" \
20:24:37  -config "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml" \
20:24:37  -explainExcludes -xids all,linux_ppc-64 -xlist "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_17.xml" -nonZeroExitWhenError; \
20:24:37  if [ $? -eq 0 ] ; then echo ""; echo "cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../TKG/output_16570628088887/cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3"; else echo ""; echo "cmdLineTester_jvmtitests_hcr_openi9_none_SCC_3""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64le_linux_jit_Personal_testList_0/aqa-tests/TKG/../TKG/output_16570628088887/TestTargetResult";
Cancelling nested steps due to timeout
```

**Comment by cjjdespres** [comment]
The 100x grinder https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/25816/ with a nightly SDK ran without any timeouts. Maybe it's something particular to openj9-jenkins?

**Comment by mpirvu** [comment]
Based on the result of the grinder I'll merge this PR.

**Pull request merged**
