### PR TITLE
Remove java.lang.Compiler from Java 21+

### PR DESCRIPTION
**Pull request by keithc-ca**
Update tests to avoid using java.lang.Compiler directly.

Issue: #18430.

Depends on changes to extension repositories to include new shared library in test-image:
* https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/720
* https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/736
* https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/291
* https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/86
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/708

Those changes can safely be merged before this because libraries are only include in test-image if they exist.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Let's keep #18430 open for those other tasks.

**Comment by pshipton** [comment]
jenkins test sanity,extended amac jdk21 depends https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/86

**Comment by pshipton** [comment]
Something is wrong.

**Comment by pshipton** [comment]
I guess testing doesn't pick up the proper extensions, I'll need to use a grinder to test it properly.

**Comment by pshipton** [comment]
> I guess testing doesn't pick up the proper extensions, I'll need to use a grinder to test it properly.

Actually the functional testing doesn't use the extensions afaik. The access library is in the test image, so I'm not sure what is wrong.

**Comment by keithc-ca** [comment]
I think I missed adding `$(ADD_JVM_LIB_DIR_TO_LIBPATH)` in some playlists.

**Comment by keithc-ca** [comment]
Updated a few playlist.xml files to fix failing tests; tests that need native libraries must also define `TEST_LIB_PATH` for OSX.
Tests (using the JDK built in https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_mac_Personal/70) that failed earlier now pass; see https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3099.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
We'll see if any others are missing in the nightly builds tonight.

**Comment by pshipton** [comment]
After we see if anything else is missing, we'll need PRs for 0.42 and 0.43.

**Comment by pshipton** [comment]
More
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_aarch64_linux_Nightly/565
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_aarch64_linux_Nightly/114/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_0/671
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_1/671

If anyone is searching, these errors are a known test problem that will be resolved shortly.
`java.lang.UnsatisfiedLinkError: access (Not found in java.library.path)`

**Comment by pshipton** [comment]
More. I expect most of these are the same problems.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_Nightly_testList_0/674/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_Nightly_testList_1/671/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly/688
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly_testList_0/655
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly_testList_1/655

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Nightly/564
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly/676

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_linux_Nightly/582
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly/586
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly/617

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_ppc64le_linux_Nightly/112/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_Nightly/114/

**Pull request merged**
