### PR TITLE
Fix incompatible arguments for inlining method from hidden class

### PR DESCRIPTION
**Pull request by r30shah**
While inlining non-static method calls, we build the parameters where
the very first slot of the parameters is the class of which that method
belongs to. We later build ArgInfo from the method symbol of the callee
by iterating through this list of parameters and for any parameter which
is Class, we query VM to get the class pointer from the signature of
the class. This was causing an issue when we were trying to inline a
method that belongs to hidden class as VM would return NULL when queried
to get class from signature.

We do not need to call VM to get the class pointer for the
first parameter slot of the non-static method calls as we have that
information avaible through resolvedMethodSymbol.

Signed-off-by: Rahil Shah <rahil@ca.ibm.com>

### CODE REVIEW

**Comment by r30shah** [comment]
@vijaysun-omr  Can I please get your review on this change?

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Jenkins test extended all jdk8,jdk11

**Comment by vijaysun-omr** [comment]
Looks like a safe way to avoid the incompatible arguments problem for hidden classes. Checks have also passed. Merging.

**Comment by mpirvu** [comment]
I ran DT7 throughput experiments, but unfortunately there is no throughput improvement from this change as I hoped. There is a small (2%) increase in CPU sent compiling, but that's tolerable.

**Comment by vij-singh** [comment]
@BradleyWood also observed that this is partially responsible for a CPU regression with Liberty...

**Comment by r30shah** [comment]
Thanks a lot @mpirvu for checking the impact of this change on throughput. It seems bit odd that with more inlining, we did not see a throughput improvement. I will try and reproduce this on our setup and do bit more analysis to understand why we did not get any throughput improvements.

**Comment by vijaysun-omr** [comment]
I am not completely sure that investigating why this change did not improve throughput for DT7 is worth spending much time on @r30shah There was a modest CPU increase of 2% and so the impact on throughput may not have been expected to be much anyway (the ratio between % CPU increase from compiling and % throughput improvement obtained is far from 1:1 from past experience). For the throughput to increase we have to have the right opportunities in the compiled code that runs at steady state, and this is application dependent as we know.

**Pull request merged**
