### PR TITLE
Move ClassSpecializer.java from OpenJ9 to extension repo

### PR DESCRIPTION
**Pull request by JasonFengJ9**
This file is only required by JDK11. When processing OpenJ9 JCL, JPP for other Java levels removes this file which might be generated by another JPP process for extension source files.

Related https://github.com/eclipse-openj9/openj9/issues/15568
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/556.

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by keithc-ca** [comment]
Please elaborate on what you mean by "multiple JPP processes". Do you see a use-case where we need to run JPP more than once where any given output file might not associated with a _unique_ execution of JPP?

**Comment by JasonFengJ9** [comment]
> Please elaborate on what you mean by "multiple JPP processes". Do you see a use-case where we need to run JPP more than once where any given output file might not associated with a unique execution of JPP?

Currently there are three JPP runs [1]:
First on `$(SUPPORT_OUTPUTDIR)/overlay`;
Second on `$(TOPDIR)/closed`;
Last on `$(OPENJ9_TOPDIR)/jcl`.

I want to apply a JCL patch on `java/lang/invoke/ClassSpecializer.java` and also add it to `overlay` folder for JPP process. However openj9 has https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/invoke/ClassSpecializer.java for Java 11 only.
Last JPP run on `$(OPENJ9_TOPDIR)/jcl` determined that `ClassSpecializer.java` is not included, and deleted previously generated file from `overlay`. This PR removes such deletion.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/f8088584b1b7989d3ede6e83d96952f08bed8b16/closed/GensrcJ9JCL.gmk#L92-L96

**Comment by keithc-ca** [comment]
The basic problem with this change is that it may break incremental builds. If the `INCLUDE-IF` condition changes (to false), the output file should _not_ be retained.

Your specific example of `ClassSpecializer` can be solved by removing that class from OpenJ9 and adding an empty stub to jdk11.

**Comment by JasonFengJ9** [comment]
> The basic problem with this change is that it may break incremental builds. If the INCLUDE-IF condition changes (to false), the output file should not be retained.

`-incremental` option probably is only used by eclipse plugin which won't be applied to extension repo code, how about only delete the existing file when `incremental` is `true`?

**Comment by keithc-ca** [comment]
I don't think `-incremental` has a meaning appropriate for that kind of use, and it doesn't address the root issue of conflicts due to non-disjoint sources for any particular output file. Keeping files where there is disagreement among those sources about whether the file is wanted is not a solution.

What's your objection to my proposed solution?

**Comment by JasonFengJ9** [comment]
> If the INCLUDE-IF condition changes (to false), the output file should not be retained.

This mostly happens at development time probably w/ the plugin.

I think we need a generic approach for this kind of problem, what happens if the file in question is preferred to be in OpenJ9 instead of extension repo? 
Maybe adding a flag indicating that the existing files should be retained?

**Comment by keithc-ca** [comment]
You keep referring to the plugin: my comments have nothing to do with that.

Yes, a more generic solution would be nice, but we don't yet have a **_need_** for it. Adding a flag to keep retain such files merely replaces the problem with a different one. Ideally, we would have a tool that considered sources from all (3 or 4) locations so it could ensure that we don't have overlap that signals a problem, but, again, we don't yet have a need for that complexity.

**Comment by JasonFengJ9** [comment]
Converted this PR to move `ClassSpecializer.java` from OpenJ9 to extension repo.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
