### PR TITLE
Add JNI_VERSION_19 for Java 19+

### PR DESCRIPTION
**Pull request by keithc-ca**
See:
* 8286176: Add JNI_VERSION_19 to jni.h and JNI spec

Also a little tidying up: mostly trailing whitespace.

### CODE REVIEW

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins compile amac jdk19

**Comment by pshipton** [comment]
@keithc-ca it didn't actually work, JNI_VERSION_19 didn't show up in the build. Perhaps we aren't defining JAVA_SPEC_VERSION properly yet?

**Comment by keithc-ca** [comment]
I explicitly looked for and found it in `vm/runtime/include/jni.h`.
I'll investigate why that didn't make it into the jdk image.

**Comment by pshipton** [comment]
Actually, we use the OpenJDK version in the builds. I'm assuming the jdk19 change hasn't promoted yet.

**Comment by keithc-ca** [comment]
I'm inclined to adjust the build of OpenJ9 to use that file from upstream instead of the one defined by this repo.

**Comment by pshipton** [comment]
I think the OpenJ9 jni.h is only used for IBM Java 8.

**Pull request merged**
