### PR TITLE
Enable CRC32 to run with AOT enabled on Power

### PR DESCRIPTION
**Pull request by bhavanisn**
CRC32 acceleration is disabled currently on Power when AOT is enabled. This would restrict the advantage of the performance the optimization gives. This code will enable it even when AOT is enabled using helper function.

Signed-off by: bhavani.sn@ibm.com

### CODE REVIEW

**Comment by bhavanisn** [comment]
@ymanton Please review.

**Review by ymanton — CHANGES_REQUESTED** [review]
LGTM, one minor suggestion.

**Review by ymanton — APPROVED** [review]
LGTM.

**Comment by ymanton** [comment]
Jenkins test sanity.functional+aot plinux,aix jdk8,jdk11

**Comment by bhavanisn** [comment]
Testcase failure for ppc64_aix doesn't seem to be caused by this PR changes. 
Previous failures https://github.com/eclipse-openj9/openj9/issues/14943 . The issue is closed but it still happens.

```
 [OUT] fontmanger LIB: libfontmanager.a
 [ERR] Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'unix:0' as the value of the DISPLAY variable.
 [ERR] 	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
 [ERR] 	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
 [ERR] 	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
```

**Comment by pshipton** [comment]
Pls open a new issue for the X11 failure if it's occurring again, and we'll see about getting it fixed.

**Comment by pshipton** [comment]
I do note that I haven't see an X11 issue in any other builds, such as nightly builds. If I got it right, here is a grinder running the same test on the same machine, using the last nightly build. Atm it's waiting for the machine to be available.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2327/

**Comment by pshipton** [comment]
The grinder passed. I had linked the wrong grinder but I've fixed it now. Re-run it with the JVM from the PR build.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2329/

**Comment by pshipton** [comment]
This grinder also passed. Seems like some kind of temporary hiccup. The build which failed did seem to successfully start the server.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_Personal_testList_0/203
```
09:42:18  + /usr/bin/X11/X -force -vfb -x abx -x dbe -x GLX -secIP 000 :0
09:42:18  GLX (INFORMATIONAL): LDR_CNTRL=MAXDATA=0x80000000
09:42:18  :0
[Pipeline] echo
09:42:18  env.DISPLAY is unix:0
```

**Comment by ymanton** [comment]
The only failure is unlikely to be related to these changes; merging.

**Pull request merged**
