### PR TITLE
Use a recent OMR acceptance build as bootjdk for AIX and for s390x Linux

### PR DESCRIPTION
**Pull request by keithc-ca**
No builds are available from Adoptium for these platforms.

### CODE REVIEW

**Comment by pshipton** [comment]
There were some outstanding problems on zlinux, it would be good to wait for the next nightly.

**Comment by keithc-ca** [comment]
> outstanding problems on zlinux

Would those problems inhibit its use as the boot jdk?

**Comment by pshipton** [comment]
Perhaps. If you don't want to wait for tonight, run a build now.

**Comment by keithc-ca** [comment]
We can wait: It would require manual intervention to remove problematic boot JDKs cached on each build machine.

**Comment by pshipton** [comment]
There is also https://github.com/eclipse-openj9/openj9/issues/17337 which doesn't have a fix yet. It seems to only affect jdk8, but who knows. When ready, I will try this in a PR build first so if there is a problem we only have one machine of each flavor to fix.

**Comment by pshipton** [comment]
jenkins compile zlinux jdknext

**Comment by keithc-ca** [comment]
URL for AIX updated.

**Comment by pshipton** [comment]
jenkins compile aix,zlinux jdknext depends ibmruntimes/openj9-openjdk-jdk#openj9-staging

**Comment by pshipton** [comment]
The first AIX build is https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/3774/

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
The head stream builds work, and the staging builds appear to be working, I'll go ahead with the merge.

**Pull request merged**
