### PR TITLE
Don't cache instances of TemporaryLoggerFinder

### PR DESCRIPTION
**Pull request by pshipton**
Fixes https://github.com/eclipse-openj9/openj9/issues/18405

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile alinux64 jdk17,jdk21,jdknext

**Comment by pshipton** [comment]
jenkins compile alinux64 jdk17,jdknext

**Comment by pshipton** [comment]
jenkins compile alinux64 jdk17,jdknext

**Comment by pshipton** [comment]
jenkins compile alinux64 jdk17 depends ibmruntimes/openj9-openjdk-jdk17#openj9-staging

**Comment by pshipton** [comment]
Tested via grinders.

jdk17: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3041/
jdk22: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3040/
```
java/lang/System/LoggerFinder/RecursiveLoading/PlatformRecursiveLoadingTest.java  Passed. Execution successful
java/lang/System/LoggerFinder/RecursiveLoading/RecursiveLoadingTest.java          Passed. Execution successful
java/lang/System/LoggerFinder/SignedLoggerFinderTest/SignedLoggerFinderTest.java  Passed. Execution successful
```

**Comment by pshipton** [comment]
@keithc-ca this needs to be merged concurrently with promoting jdk17 (i.e. pushing openj9-staging to openj9). Either while we're still at the 17.0.10+1 level, or if we get a newer level then new acceptance testing is required first.

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
The openj9 branch of jdk17 is also advanced to [1cd3f35fa7e8a5aa460ef71888ccf377c4c4334f](https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/1cd3f35fa7e8a5aa460ef71888ccf377c4c4334f).

**Comment by pshipton** [comment]
> The openj9 branch of jdk17 is also advanced to [1cd3f35fa7e8a5aa460ef71888ccf377c4c4334f](https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/1cd3f35fa7e8a5aa460ef71888ccf377c4c4334f).

In fact it was not, at least for https://github.com/ibmruntimes/openj9-openjdk-jdk17. All the jdk17 builds failed last night. I've done it now.

**Pull request merged**
