### PR TITLE
Modify JITServerTest to use a new port for each subtest

### PR DESCRIPTION
**Pull request by dmitry-ten**
JITServer tests run multiple test cases where servers frequently
start and shut down. If the port is not immediately released
back into the system, or another process grabs it before the next
server can start, all subsequent test cases will fail because server
will not be able to start.

This commit modifies the test to generate a new JITServer port
for each test case, to minimize the chances that the port is not
available.

Closes: #13801

### CODE REVIEW

**Comment by dmitry-ten** [comment]
Updated. However, I couldn't see that `clientBuilder/serverBuilder` lines are misaligned.

**Comment by mpirvu** [comment]
> However, I couldn't see that clientBuilder/serverBuilder lines are misaligned.

This is what my browser shows me:
image

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit jdk11

**Comment by mpirvu** [comment]
jenkins test sanity plinux,xlinux,zlinux jdk11

**Review by ymanton — APPROVED** [review]
Looks reasonable.

**Comment by mpirvu** [comment]
@dmitry-ten Could you please port this change to 0.29.1? Thanks

**Pull request merged**
