### PR TITLE
Fix incorrect offset for null terminated string

### PR DESCRIPTION
**Pull request by mpirvu**
Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
@dsouzai Please review this PR. Thanks

**Comment by mpirvu** [comment]
jenkins test sanity zlinuxjit jdk17

**Review by dsouzai — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins compile xlinuxgcc10 jdk17

**Comment by pshipton** [comment]
It fixes the gcc10 compilation problem that was found. Irwin approved, the PR testing passed, I'll go ahead and merge.

**Pull request merged**
