### PR TITLE
Refactor TR::DefaultCompilationStrategy::processJittedSample

### PR DESCRIPTION
**Pull request by dsouzai**
This PR refactors `TR::DefaultCompilationStrategy::processJittedSample` by introducing a new class `ProcessJittedSample` (scoped within `TR::DefaultCompilationStrategy`).

### CODE REVIEW

**Comment by dsouzai** [comment]
@mpirvu @ymanton could one of you review this when you get a chance?

**Review by ymanton — COMMENTED** [review]
Took a first pass at this. Much easier to read now, at least from the top down. I appreciate that you've broken down and compartmentalized the various steps. I'll take a closer look at the details shortly.

**Comment by dsouzai** [comment]
FWIW, the reason I created a class and didn't simply just write static functions is because I ended up having functions that had to take in 10-15 parameters, of which some were in/out parameters, which got ugly really quickly. So I just encapsulated it all in `ProcessJittedSample` class.

**Review by ymanton — APPROVED** [review]
LGTM.

Most of the things I see as problems (magic numbers, complicated `if` statements, etc) are simply carried over from the existing code and probably deserve their own independent clean up attempts. No point in letting this stagnate.

**Comment by ymanton** [comment]
Jenkins test sanity.functional all jdk11

**Comment by ymanton** [comment]
The single failure on aarch64 is a case of https://github.com/eclipse-openj9/openj9/issues/14243 hence merging.

**Comment by pshipton** [comment]
Revert this via https://github.com/eclipse-openj9/openj9/pull/15430
See https://github.com/eclipse-openj9/openj9/issues/15426#issuecomment-1167384633

**Comment by pshipton** [comment]
Given the failures in sanity.system and extended.system suites that appear to be caused by this change, I suggest running extended.system PR testing once this change is re-instated. @ymanton

**Pull request merged**
