### PR TITLE
Fix node reference counts in VectorAPIExpansion

### PR DESCRIPTION
**Pull request by gita-omr**
- fix two node reference count issues
- run verifyTrees every time the optimization runs

### CODE REVIEW

**Comment by gita-omr** [comment]
Fixed copyrights.

**Comment by knn-k** [comment]
Jenkins test sanity all jdk18

**Comment by knn-k** [comment]
Jenkins test sanity alinux jdk18

There was a failure in https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.functional_aarch64_linux_Personal/27/.  Running again on alinux.

**Comment by knn-k** [comment]
Jenkins test sanity alinux64 jdk18

**Review by knn-k — APPROVED** [review]
LGTM.

**Pull request merged**
