### PR TITLE
Remove unused print statements on s390

### PR DESCRIPTION
**Pull request by dmitry-ten**
The file `runtime/compiler/z/runtime/Recomp.cpp` defines a
`DEBUG` macro that guards a number of print statements meant
for debugging. These print statements are never used, while
also having incorrect format specifiers that break JITServer builds.

This commit removes the `DEBUG` macro and all associated print
statements.

### CODE REVIEW

**Comment by dmitry-ten** [comment]
@fjeremic could you review this?
@mpirvu fyi. With this change, JITServer builds on z should start working again.

**Review by mpirvu — APPROVED** [review]
I am ok with the change. The question is whether the code has any value for the future (i.e. do we expect future debugging in this area such that someone would have to recreate the code?). Even so, I think the code could be easily recreated from the git history.

Just out of curiosity, which printfs were failing? I see some pointers printed as `%x`, but I am not sure that is the issue here.

**Comment by dmitry-ten** [comment]
Yeah, all of the pointers printed with `%x` were failing.

**Comment by mpirvu** [comment]
jenkins test sanity zlinux,zlinuxjit jdk11

**Comment by mpirvu** [comment]
@fjeremic any concerns with this small PR? If not I am going to merge it. Thanks

**Pull request merged**
