### PR TITLE
Clear pending exception after JVMTI class replacement

### PR DESCRIPTION
**Pull request by gacholio**
JNI exceptions should not be pending upon return from a JVMTI function - the return value conveys success or failure.

Fixes: #16342

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
I've tested this only with a debug internal build (which required disabling the JIT).

**Comment by gacholio** [comment]
jenkins test sanity win jdk8

**Comment by gacholio** [comment]
Tested with personal OpenJ9 build - the reported errors and crash are gone.

**Review by tajila — APPROVED** [review]

**Comment by pshipton** [comment]
This seems low risk and we haven't done the M2 builds yet, if you want to cherry pick this for 0.36 I can put it in.

**Comment by gacholio** [comment]
> This seems low risk and we haven't done the M2 builds yet, if you want to cherry pick this for 0.36 I can put it in.

Will do tomorrow.

**Pull request merged**
