### PR TITLE
Fix a typo in handling vsplats

### PR DESCRIPTION
**Pull request by gita-omr**

### CODE REVIEW

**Comment by gita-omr** [comment]
@jdmpapin @pshipton I am so sorry but I made a stupid mistake in https://github.com/eclipse-openj9/openj9/pull/14522

Of course, we need the fix in 0.31. @midronij thanks so much for noticing!

**Comment by jdmpapin** [comment]
Oh wow, sorry :facepalm:

Could you please also fix the indentation by re-adding the leading spaces that were deleted in #14522?

**Comment by gita-omr** [comment]
Fixed removed spaces.

**Comment by jdmpapin** [comment]
There's a whitespace error now, and an additional early return that doesn't look like it's intended to be part of this change

**Comment by jdmpapin** [comment]
Jenkins test sanity all jdk18

**Comment by gita-omr** [comment]
Just confirmed that aarch is an environment issue. Since the change is common I think we have enough coverage by all the other builds.

**Pull request merged**
