### PR TITLE
Add missing JDK17 native method stubs for jdk.jfr.internal.jvm

### PR DESCRIPTION
**Pull request by yathamravali**
Add missing getHandler and setHandler native API's for JFR JDK17

### CODE REVIEW

**Comment by yathamravali** [comment]
PTAL, @TobiAjila

**Comment by tajila** [comment]
jenkins test sanity xlinux jdk17

**Comment by tajila** [comment]
jenkins test sanity win jdk17

**Comment by thallium** [comment]
Looks like there's some overlaps here, I fixed the method stubs for all jdk versions: https://github.com/eclipse-openj9/openj9/pull/20391

**Comment by yathamravali** [comment]
Closing this as per https://github.com/eclipse-openj9/openj9/pull/20388#issuecomment-2427515887

**Pull request closed without merging**
