### PR TITLE
Use async events for JFR execution samples

### PR DESCRIPTION
**Pull request by gacholio**

### CODE REVIEW

**Comment by gacholio** [comment]
I've verified that samples are generated with this new approach.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
jenkins test sanity xlinux jdk17

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk21

**Comment by gacholio** [comment]
First attempted builds failed instantly. Relaunching.

**Comment by gacholio** [comment]
jenkins test sanity alinux64 jdk21

**Comment by gacholio** [comment]
jenkins test sanity xlinux jdk17

**Pull request merged**
