### PR TITLE
Add tests for JIT arraytranslate

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds tests for char[] to byte[] cases of JIT arraytranslate.

### CODE REVIEW

**Comment by knn-k** [comment]
Some tests in `testJitserverArguments_0` failed on x86-64 Linux, but they are not caused by the arraytranslate tests.

Output of the arraytranslate tests from https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Personal_testList_0/260/consoleText:
```
[2024-10-29T03:29:47.115Z] PASSED: testArrayTranslateTRTO
[2024-10-29T03:29:47.115Z] PASSED: testArrayTranslateTRTO255
[2024-10-29T03:29:47.115Z] 
[2024-10-29T03:29:47.115Z] ===============================================
[2024-10-29T03:29:47.115Z]     ArrayTranslateTest
[2024-10-29T03:29:47.115Z]     Tests run: 2, Failures: 0, Skips: 0
[2024-10-29T03:29:47.115Z] ===============================================
```

**Comment by knn-k** [comment]
@0xdaryl FYI.

**Comment by knn-k** [comment]
Jenkins line endings check

**Comment by knn-k** [comment]
Jenkins test sanity.functional xlinux jdk8

**Comment by knn-k** [comment]
Again, there are some failures with `testJitserverArguments_0` on x86-64 Linux.
Those failures are also seen in a recent nightly test.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/659/consoleText

**Comment by 0xdaryl** [comment]
Jenkins test sanity.functional alinux jdk8

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
