### PR TITLE
Remove depracted idle tuning fields from extension base

### PR DESCRIPTION
**Pull request by tajila**
Remove idleMinimumFree from extension base

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test compile win jdk8

**Comment by tajila** [comment]
jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins compile xlinuxcriu jdk17

**Comment by tajila** [comment]
@amicic please review these changes

**Review by amicic — APPROVED** [review]

**Pull request merged**
