### PR TITLE
Don't differenciate Q from L types in verifier

### PR DESCRIPTION
**Pull request by ehrenjulzert**
In #15053 code was added to ensure Q types could
not be null, and to print different error
messages for Q types. However, according to the
new spec the verifier no longer needs to make
these distinctions

### CODE REVIEW

**Comment by ehrenjulzert** [comment]
@hangshao0

**Comment by hangshao0** [comment]
Can you add a comment in the commit message mentioning the original PR and this is due to new spec that the `null checks` is not needed anymore ?

**Comment by ehrenjulzert** [comment]
Okay, added in fe07095

**Comment by hangshao0** [comment]
Can you review this ? @ChengJin01

This is for the the new [spec](https://cr.openjdk.org/~dlsmith/jep401/jep401-20230404/specs/implicit-value-creation-jvms.html#jvms-4.10.1.2) which says:
`The verification type system does not enforce null restrictions, and makes no distinction between standard reference types (LFoo;) and null-restricted reference types (QFoo;).`
This is the old [spec](https://cr.openjdk.org/~dlsmith/jep401/jep401-20211220/specs/primitive-classes-jvms.html#jvms-4.10.1.2 ).

**Comment by ChengJin01** [comment]
> This is for the the new [spec](https://cr.openjdk.org/~dlsmith/jep401/jep401-20230404/specs/implicit-value-creation-jvms.html#jvms-4.10.1.2) which says:
The verification type system does not enforce null restrictions, and makes no distinction between standard reference types (LFoo;) and null-restricted reference types (QFoo;).
This is the old [spec](https://cr.openjdk.org/~dlsmith/jep401/jep401-20211220/specs/primitive-classes-jvms.html#jvms-4.10.1.2).

@ehrenjulzert ,  you might need to remove all changes with `convertClassNameToStackMapType` related to the Qtypes in the old changes at https://github.com/eclipse-openj9/openj9/pull/15053/files given there is no distinction between standard reference types (LFoo;) and null-restricted reference types (QFoo;). in the latest Spec.

**Comment by ehrenjulzert** [comment]
I've removed all the `convertClassNameToStackMapType` changes related to QTypes and changed the error messages to no longer distinguish between Q types and L types.

**Review by ChengJin01 — APPROVED** [review]
Approve the changes given its intention is to restore everything back to the original code without Valhalla.

**Comment by ChengJin01** [comment]
FYI: @tajila, @DanHeidinga

**Comment by tajila** [comment]
@ehrenjulzert can you post a link to the PR that added the changes

**Review by hangshao0 — APPROVED** [review]
LGTM

**Comment by ehrenjulzert** [comment]
> can you post a link to the PR that added the changes

Changes were added in https://github.com/eclipse-openj9/openj9/pull/15053

**Comment by tajila** [comment]
@ehrenjulzert let me know when this is rebased and Ill launch the tests

**Comment by ehrenjulzert** [comment]
Okay I just rebased

**Comment by tajila** [comment]
jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by tajila** [comment]
Jenkins test sanity,extended plinuxval jdknext

**Comment by tajila** [comment]
@JasonFengJ9 is the VT build broken? there are quite a few failures

**Comment by JasonFengJ9** [comment]
@tajila The latest [nightly build](https://hyc-runtimes-jenkins.swg-devops.com/view/Valhalla%20Tests/job/Build_JDKnext_x86-64_linux_valhalla_Nightly/1031/) was green.

Those test failures are known JDK21 issues: 
* https://github.com/eclipse-openj9/openj9/issues/17280
* https://github.com/eclipse-openj9/openj9/issues/17301

**Pull request merged**
