### PR TITLE
add DYLD_LIBRARY_PATH for osx native testing

### PR DESCRIPTION
**Pull request by llxia**
- temporarily exclude cmdLineTester_pltest
- temporarily exclude cmdLineTest_gpTest
- add DYLD_LIBRARY_PATH for oxs native testing

[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test sanity osx jdk11

**Comment by AdamBrousseau** [comment]
jenkins test sanity osx jdk8

**Comment by llxia** [comment]
jenkins test extended osx jdk11

**Comment by AdamBrousseau** [comment]
jenkins test sanity osx jdk8

**Comment by AdamBrousseau** [comment]
jenkins test extended osx jdk8

**Comment by llxia** [comment]
osx jdk8 PR builds are not ready. They both failed due to no matching label
```
There are no nodes with the label ‘ci.role.build&&hw.arch.x86&&sw.os.osx.10_11’
```

**Comment by llxia** [comment]
- osx jdk11 exnteded.functional build completed without error regarding `UnsatisfiedLinkError`.
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/6/tapResults/
Opened issues for the failures.

- osx jdk11 sanity.functional build hangs at abort test in `cmdLineTest_gpTest_0`, but I do not think it is related to this PR.
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-osx_x86-64_cmprssptrs-OpenJ9/38/consoleFull

- Tested `sanity.fucntional` on oxs on JDK11 in Grinder:
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/75/
No `UnsatisfiedLinkError`. Native test such as `algotest2_0` passed.

@pshipton Could you please review the change? Thanks

**Comment by babsingh** [comment]
- **osx jdk11 extended.functional**: doesn't run the tests listed in https://github.com/eclipse/openj9/issues/3686.
- **osx jdk11 sanity.functional build hangs** at **Testing: abort** which is the first test listed in https://github.com/eclipse/openj9/issues/3686. Other tests listed in https://github.com/eclipse/openj9/issues/3686 aren't run.
- Probably, we should run the tests locally and verify if the `DYLD_LIBRARY_PATH` change is causing the hang.

**Comment by llxia** [comment]
jenkins test sanity osx jdk11

**Comment by llxia** [comment]
jenkins test extended osx jdk11

**Comment by llxia** [comment]
`DYLD_LIBRARY_PATH` should be added so native tests can find libs. (i.e., pthreadDestructor, reattachAfterExit, etc)

Since we had issue of hanging at `Testing: abort` in `cmdLineTest_gpTest_0` before https://github.com/eclipse/openj9/issues/3686#issuecomment-438866415, I suspect it maybe related. Further investgation is needed. Exclude it for now so we can have a build will not hang.

`cmdLineTester_pltest` is excluded due to #3685. It crashes in both `DYLD_LIBRARY_PATH` and `LD_LIBRARY_PATH` case.

**Comment by llxia** [comment]
PR builds failed during compilation (#3810)

**Comment by llxia** [comment]
jenkins test sanity osx jdk11

**Comment by llxia** [comment]
jenkins test extended osx jdk11

**Comment by llxia** [comment]
jenkins test extended osx jdk11

**Comment by llxia** [comment]
jenkins test extended osx jdk11

**Comment by llxia** [comment]
rebased and relaunch the PR builds as #3810 is fixed

**Pull request merged**
