### PR TITLE
Enable -XX:+JITServerAOTCacheIgnoreLocalSCC by default

### PR DESCRIPTION
**Pull request by cjjdespres**

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu. This doesn't necessarily have to go in right away as you said, but these should be all the changes required for ignoring the SCC to be the default.

**Comment by cjjdespres** [comment]
I managed to run the `openjdk` tests locally and got a segfault in `java_lang_0`, so this should probably not be merged until that suite passes. I'm currently checking to see if `-XX:+JITServerAOTCacheIgnoreLocalSCC` is the cause.

**Review by mpirvu — APPROVED** [review]
Code looks fine to me, but I'll hold off merging until you tell me it doesn't cause any problems.

**Comment by cjjdespres** [comment]
I've run `sanity.openjdk`, `sanity.functional`, `extended.functional`, and `sanity.system` manually with this option and have only seen known test failures. The exception is the crash I got in `jdk_lang_0`, but I haven't been able to reproduce it, so I'm unsure if it's caused by this option or some underlying AOT issue.

I think this should be good to merge. It seems unlikely I'll be able to find any more functional issues testing this option myself.

**Comment by mpirvu** [comment]
jenkins test sanity xlinuxjit,zlinuxjit jdk21

**Comment by mpirvu** [comment]
On xlinux one of the cmdLineTests failed with
```
18:15:31  //// can't bind server address: Address already in use
18:15:31  //// Failed to open server socket on port 44070
```
Since this is a known issue, I am going to merge this PR.

**Pull request merged**
