### PR TITLE
Print JITServer options in effect into the verbose log

### PR DESCRIPTION
**Pull request by EmanElsaban**
Added 'F' to the message for JITServer options which means message information
to be printed if this option is in effect.

Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>

### CODE REVIEW

**Comment by EmanElsaban** [comment]
@mpirvu ready for review, thanks

**Review by mpirvu — APPROVED** [review]
LGTM. I would change the title of the commit though to something more generic:
"Print JITServer options in effect into the verbose log"

**Comment by mpirvu** [comment]
Could you please change the title of the commit as well (you already changed the title of the PR)?

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,zlinuxjit jdk11

**Pull request merged**
