### PR TITLE
Clean up GC_TLH_PREFETCH_FTA flag settings in cmake files

### PR DESCRIPTION
**Pull request by knn-k**
This commit removes redundant OMR_GC_TLH_PREFETCH_FTA lines from cmake files for some platforms.
OMR_GC_TLH_PREFETCH_FTA is automatically defined in omrcfg.h during the build depending on J9VM_GC_TLH_PREFETCH_FTA value.

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins test sanity all jdk17

**Comment by knn-k** [comment]
See Issue #18870 for the background information.

**Comment by knn-k** [comment]
Jenkins test sanity xlinux,xmac jdk17

**Comment by knn-k** [comment]
Jenkins test sanity plinux,win,xlinux,xmac jdk17

**Comment by knn-k** [comment]
This PR does not change the flag settings on any platform.  `OMR_GC_TLH_PREFETCH_FTA` in cmake files is useless.

**Comment by knn-k** [comment]
Jenkins test sanity xmac jdk17

Re-running xmac test as it failed with the following message:
```
fatal: unable to access 'https://github.com/adoptium/aqa-tests.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

**Comment by knn-k** [comment]
Jenkins test sanity xlinux jdk17

Re-running xlinux test as it failed in cmdLineTester_criu_nonPortableRestore_5 with the following message:

```
FAILED: testTimeCompensation() preCheckpoint timer delayed 4s elapsedMillisTime (4001ms) should NOT be less than minElapsedMillisTime (6000ms)
```

It looks similar to Issue #18471.
Assuming it is not a failure caused by this PR.

**Comment by knn-k** [comment]
Jenkins test sanity win jdk17

Re-runnning Windows test.  The previous job failed due to timeout, waiting too long in the queue.

**Comment by knn-k** [comment]
Summary:

- x86 platforms: `J9VM_GC_TLH_PREFETCH_FTA` is ON.  Remove the unused `OMR_GC_TLH_PREFETCH_FTA` line.
- linux_ppc-64_le: `J9VM_GC_TLH_PREFETCH_FTA` is ON.  Remove the contradicting and unused `OMR_GC_TLH_PREFETCH_FTA` line.
- zos_390-64: `J9VM_GC_TLH_PREFETCH_FTA` is OFF.  Remove the unused `OMR_GC_TLH_PREFETCH_FTA` line.

**Comment by dmitripivkine** [comment]
Please note GC part of the code rely on OMR_GC_TLH_PREFETCH_FTA to be set properly.

**Comment by knn-k** [comment]
@dmitripivkine `OMR_GC_TLH_PREFETCH_FTA` is set properly in omrcfg.h based on `J9VM_GC_TLH_PREFETCH_FTA` value, as stated in the commit message.  The `OMR_GC_TLH_PREFETCH_FTA` lines in .cmake files are ignored, and it is safe to remove those lines.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
