### PR TITLE
Add ability to merge -Xjit/-Xaot opts

### PR DESCRIPTION
**Pull request by dsouzai**
Partially addresses https://github.com/eclipse-openj9/openj9/issues/12503

This PR introduces the `-XX:+MergeCompilerOptions` and `-XX:-MergeCompilerOptions` flags to allow the merging of multiple `-Xjit` and `-Xaot` options. As the code stands, it allows multiple empty `-Xjit:`/`-Xaot:` as long as there's at least one that isn't empty.

Here are some of the results; I put a printf in the options processing code to demonstrate the options that the JIT will parse:

No Compiler Options:
```
$ ./jdk11/bin/java -Xshareclasses:none -version
xjitCommandLineOptions=
```
```
$ ./jdk11/bin/java -XX:+MergeCompilerOptions -Xshareclasses:none -version
xjitCommandLineOptions=
```
```
$ ./jdk11/bin/java -XX:-MergeCompilerOptions -Xshareclasses:none -version
xjitCommandLineOptions=
```

One JIT option:
```
$ ./jdk11/bin/java -Xshareclasses:none  -Xjit:version -version
xjitCommandLineOptions=version
```
```
$ ./jdk11/bin/java -XX:+MergeCompilerOptions -Xshareclasses:none  -Xjit:version -version
xjitCommandLineOptions=version
```
```
$ ./jdk11/bin/java -XX:-MergeCompilerOptions -Xshareclasses:none  -Xjit:version -version
xjitCommandLineOptions=version
```

Multiple JIT options:
```
$ ./jdk11/bin/java -Xshareclasses:none '-Xjit:verbose={compilePerformance},vlog=vlog' -Xjit:version -version
xjitCommandLineOptions=version
```
```
$ ./jdk11/bin/java -XX:+MergeCompilerOptions -Xshareclasses:none '-Xjit:verbose={compilePerformance},vlog=vlog' -Xjit:version -version
xjitCommandLineOptions=verbose={compilePerformance},vlog=vlog,version
```
```
$ ./jdk11/bin/java -XX:-MergeCompilerOptions -Xshareclasses:none '-Xjit:verbose={compilePerformance},vlog=vlog' -Xjit:version -version
xjitCommandLineOptions=version
```

Both `-XX:+MergeCompilerOptions` and `-XX:-MergeCompilerOptions`:
```
$ ./jdk11/bin/java -XX:+MergeCompilerOptions -XX:-MergeCompilerOptions -Xshareclasses:none '-Xjit:verbose={compilePerformance},vlog=vlog' -Xjit:version -version
xjitCommandLineOptions=version
```
```
$ ./jdk11/bin/java -XX:-MergeCompilerOptions -XX:+MergeCompilerOptions -Xshareclasses:none '-Xjit:verbose={compilePerformance},vlog=vlog' -Xjit:version -version
xjitCommandLineOptions=verbose={compilePerformance},vlog=vlog,version
```

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
I found your answer to my https://github.com/eclipse-openj9/openj9/pull/15799#issuecomment-1247007699 last month good enough for taking this first step. The questions on conflicting options etc. are not really an issue for taking this step of introducing the option, but could be something a user of this option comes across. Based on what you said, the service team considers that risk to be low enough and probably sees use/benefit for this new option.

**Review by ymanton — COMMENTED** [review]
The code for JIT options and AOT options looks more or less identical. Can we avoid the duplication here? It would probably require passing in a lot of variables if done naively, but maybe we don't need custom assert messages and such and can reduce the amount of stuff that would need to be passed in to a common processing function.

**Comment by dsouzai** [comment]
> The code for JIT options and AOT options looks more or less identical. Can we avoid the duplication here? It would probably require passing in a lot of variables if done naively, but maybe we don't need custom assert messages and such and can reduce the amount of stuff that would need to be passed in to a common processing function.

Hm I'll give it a shot.

**Comment by dsouzai** [comment]
@ymanton refactored as requested.

**Review by ymanton — APPROVED** [review]
LGTM.

**Comment by ymanton** [comment]
I don't think we have any tests to exercise this code. Can we add some? There are lots of VM command line tests in https://github.com/eclipse-openj9/openj9/tree/master/test/functional/cmdLineTests but JIT tests are lacking. Now might be a good time to add some.

**Comment by dsouzai** [comment]
jenkins test sanity.functional jdk17 xlinux

^ Single test for now to ensure newly added tests are executed.

**Comment by dsouzai** [comment]
jenkins test sanity.functional xlinux jdk17

**Comment by dsouzai** [comment]
jenkins test sanity.functional xlinux jdk17

**Review by renfeiw — APPROVED** [review]
LGTM!

**Comment by dsouzai** [comment]
Looks like the tests are running:
```
[2022-10-25T21:49:47.373Z] ===============================================
[2022-10-25T21:49:47.373Z] Running test testCompilerArguments_0 ...
[2022-10-25T21:49:47.373Z] ===============================================
[2022-10-25T21:49:47.373Z] testCompilerArguments_0 Start Time: Tue Oct 25 18:49:38 2022 Epoch Time (ms): 1666734578471
[2022-10-25T21:49:47.373Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2022-10-25T21:49:47.373Z] JVMSHRC005I No shared class caches available
[2022-10-25T21:49:47.373Z] JVMSHRC005I No shared class caches available
[2022-10-25T21:49:47.373Z] cache cleanup done
[2022-10-25T21:49:47.373Z] variation: NoOptions
[2022-10-25T21:49:47.373Z] JVM_OPTIONS:  
[2022-10-25T21:49:47.373Z] { success=0; \
[2022-10-25T21:49:47.373Z] itercnt=1; \
[2022-10-25T21:49:47.373Z] mkdir -p "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/aqa-tests/TKG/../TKG/output_16667332444943/testCompilerArguments_0"; \
[2022-10-25T21:49:47.373Z] cd "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/aqa-tests/TKG/../TKG/output_16667332444943/testCompilerArguments_0"; \
[2022-10-25T21:49:47.373Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java" -DEXE='"/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"  ' -jar "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar" \
[2022-10-25T21:49:47.373Z] 		-config "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jit/CompilerArgumentTesting.xml" \
[2022-10-25T21:49:47.373Z] 		-nonZeroExitWhenError; \
[2022-10-25T21:49:47.374Z] 		if [ $? -eq 0 ] ; then echo ""; echo "testCompilerArguments_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/aqa-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/aqa-tests/TKG/../TKG/output_16667332444943/testCompilerArguments_0"; else echo ""; echo "testCompilerArguments_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/aqa-tests/TKG/../TKG/output_16667332444943/TestTargetResult";
[2022-10-25T21:49:47.374Z] *** Starting test suite: CompilerArgumentTesting.xml ***
[2022-10-25T21:49:47.374Z] Testing: JIT Version using -Xjit
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:39 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xjit:version -version
[2022-10-25T21:49:47.374Z] Time spent starting: 144 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 407 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: JIT Version using -Xaot
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:40 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xaot:version -version
[2022-10-25T21:49:47.374Z] Time spent starting: 16 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 371 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Check valid option using -Xjit
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:40 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xjit:verbose={options},disableInlining -version
[2022-10-25T21:49:47.374Z] Time spent starting: 4 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 327 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Check valid option using -Xaot
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:41 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xaot:verbose={options},disableInlining -version
[2022-10-25T21:49:47.374Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 336 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Check invalid option using -Xjit
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:41 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xjit:verbose={options},invalidoption -version
[2022-10-25T21:49:47.374Z] Time spent starting: 4 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 56 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Check invalid option using -Xaot
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:41 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xaot:verbose={options},invalidoption -version
[2022-10-25T21:49:47.374Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 55 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Check valid options using -Xjit and -Xaot
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:41 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xjit:verbose={options},disableAsyncCompilation -Xaot:disableInlining -version
[2022-10-25T21:49:47.374Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 539 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Check empty -Xjit:
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:42 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xjit: -version
[2022-10-25T21:49:47.374Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 65 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Check empty -Xaot:
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:42 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xdump:none -Xaot: -version
[2022-10-25T21:49:47.374Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 276 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Test multiple -Xjit:
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:42 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xjit:disableAsyncCompilation -Xjit:verbose={options} -version
[2022-10-25T21:49:47.374Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 312 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Test multiple -Xaot:
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:42 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -Xaot:disableAsyncCompilation -Xaot:verbose={options} -version
[2022-10-25T21:49:47.374Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 284 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Test -XX:+MergeCompilerOptions with single -Xjit
[2022-10-25T21:49:47.374Z] Test start time: 2022/10/25 18:49:43 Atlantic Standard Time
[2022-10-25T21:49:47.374Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:+MergeCompilerOptions -Xjit:verbose={options} -version
[2022-10-25T21:49:47.374Z] Time spent starting: 4 milliseconds
[2022-10-25T21:49:47.374Z] Time spent executing: 285 milliseconds
[2022-10-25T21:49:47.374Z] Test result: PASSED
[2022-10-25T21:49:47.374Z] 
[2022-10-25T21:49:47.374Z] Testing: Test -XX:+MergeCompilerOptions with single -Xaot
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:43 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:+MergeCompilerOptions -Xaot:verbose={options} -version
[2022-10-25T21:49:47.375Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 389 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:-MergeCompilerOptions with single -Xjit
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:43 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:-MergeCompilerOptions -Xjit:verbose={options} -version
[2022-10-25T21:49:47.375Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 290 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:-MergeCompilerOptions with single -Xaot
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:44 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:-MergeCompilerOptions -Xaot:verbose={options} -version
[2022-10-25T21:49:47.375Z] Time spent starting: 4 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 324 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:+MergeCompilerOptions with multiple -Xjit
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:44 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:+MergeCompilerOptions -Xjit:disableAsyncCompilation -Xjit:verbose={options} -version
[2022-10-25T21:49:47.375Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 562 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:+MergeCompilerOptions with multiple -Xaot
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:44 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:+MergeCompilerOptions -Xaot:disableInlining -Xaot:verbose={options} -version
[2022-10-25T21:49:47.375Z] Time spent starting: 4 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 312 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:-MergeCompilerOptions with multiple -Xjit
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:45 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:-MergeCompilerOptions -Xjit:disableAsyncCompilation -Xjit:verbose={options} -version
[2022-10-25T21:49:47.375Z] Time spent starting: 2 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 304 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:-MergeCompilerOptions with multiple -Xaot
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:45 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:-MergeCompilerOptions -Xaot:disableInlining -Xaot:verbose={options} -version
[2022-10-25T21:49:47.375Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 301 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:+MergeCompilerOptions with multiple -Xjit and -Xaot
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:45 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:+MergeCompilerOptions -Xjit:disableAsyncCompilation -Xaot:disableInlining -Xjit:verbose={options} -Xaot:disableOSR -version
[2022-10-25T21:49:47.375Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 618 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:-MergeCompilerOptions with multiple -Xjit and -Xaot
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:46 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:-MergeCompilerOptions -Xjit:disableAsyncCompilation -Xaot:disableInlining -Xjit:verbose={options} -Xaot:disableOSR -version
[2022-10-25T21:49:47.375Z] Time spent starting: 3 milliseconds
[2022-10-25T21:49:47.375Z] Time spent executing: 324 milliseconds
[2022-10-25T21:49:47.375Z] Test result: PASSED
[2022-10-25T21:49:47.375Z] 
[2022-10-25T21:49:47.375Z] Testing: Test -XX:+MergeCompilerOptions after -XX:-MergeCompilerOptions
[2022-10-25T21:49:47.375Z] Test start time: 2022/10/25 18:49:46 Atlantic Standard Time
[2022-10-25T21:49:47.375Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:-MergeCompilerOptions -XX:+MergeCompilerOptions -Xjit:disableAsyncCompilation -Xjit:verbose={options} -version
[2022-10-25T21:49:47.375Z] Time spent starting: 4 milliseconds
[2022-10-25T21:49:48.382Z] Time spent executing: 567 milliseconds
[2022-10-25T21:49:48.382Z] Test result: PASSED
[2022-10-25T21:49:48.382Z] 
[2022-10-25T21:49:48.383Z] Testing: Test -XX:+MergeCompilerOptions before -XX:-MergeCompilerOptions
[2022-10-25T21:49:48.383Z] Test start time: 2022/10/25 18:49:47 Atlantic Standard Time
[2022-10-25T21:49:48.383Z] Running command: "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"   -XX:+MergeCompilerOptions -XX:-MergeCompilerOptions -Xjit:disableAsyncCompilation -Xjit:verbose={options} -version
[2022-10-25T21:49:48.383Z] Time spent starting: 2 milliseconds
[2022-10-25T21:49:48.383Z] Time spent executing: 274 milliseconds
[2022-10-25T21:49:48.383Z] Test result: PASSED
[2022-10-25T21:49:48.383Z] 
[2022-10-25T21:49:48.383Z] 
[2022-10-25T21:49:48.383Z] ---TEST RESULTS---
[2022-10-25T21:49:48.383Z] Number of PASSED tests: 23 out of 23
[2022-10-25T21:49:48.383Z] Number of FAILED tests: 0 out of 23
[2022-10-25T21:49:48.383Z] 
[2022-10-25T21:49:48.383Z] testCompilerArguments_0_PASSED
```

@ymanton could you review again (I had to change the `strncpy` to a `memcpy` to get around the compiler error.

**Review by ymanton — APPROVED** [review]
LGTM.

**Comment by ymanton** [comment]
Jenkins test sanity.functional all jdk11

**Comment by dsouzai** [comment]
Jenkins test sanity.functional all jdk11

**Comment by dsouzai** [comment]
jenkins test sanity.functional all jdk11

**Comment by dsouzai** [comment]
@ymanton good to merge :)

**Pull request merged**
