### PR TITLE
Add tracepoint that includes timestamps in the share classes code

### PR DESCRIPTION
**Pull request by hangshao0**
Add a new trace point in TimestampManagerImpl.cpp to record the
timestamps.

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
While debugging an issue, I find it is helpful to have a tracepoint that includes the timestamps.

**Comment by pshipton** [comment]
Pls fix the commit message to be more descriptive, it should indicate the tracepoint is added to the share classes code.

**Comment by pshipton** [comment]
jenkins compile amac jdk11

**Comment by hangshao0** [comment]
Link to the PR build: https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/4174/

**Review by pshipton — APPROVED** [review]

**Pull request merged**
