### PR TITLE
Teach ValueTypeUnsafeTests about dual header shape

### PR DESCRIPTION
**Pull request by VermaSh**
Dual header shape adds the ability to toggle dataAddr field based on GC policy. Enabling dual header shape toggles off dataAddr field for Gencon GC policy and disabling it toggles on the field. When toggled off, array header size with compressed refs for Gencon GC policy is 24 bytes and 16 bytes if toggled on.

Fixes: https://github.com/eclipse-openj9/openj9/issues/17359

### CODE REVIEW

**Comment by hangshao0** [comment]
Is this ready to be reviewed ? @VermaSh

**Comment by VermaSh** [comment]
@hangshao0 yes, this is ready for review

**Review by hangshao0 — APPROVED** [review]

**Comment by hangshao0** [comment]
> yes, this is ready for review

Can you remove "WIP" from the title ?

> Personal build to verify the changes: [Pipeline-Build-Test-Personal/16673](https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/16673/)

I noticed you personal build used incorrect repo for jdknext, it should be https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes. I believe @tajila will launch PR build before merging this change.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Pull request merged**
