### PR TITLE
Pass separate JVM options to cmdLineTester

### PR DESCRIPTION
**Pull request by dsouzai**
The existing cmdLineTester tests take options that are supposed to be passed into JVMs that the cmdLineTester invokes and also applies it to the JVM running cmdLineTester.

This PR adds a new variable `CMDLINETESTER_JVM_OPTIONS` which is set to `-Xshareclasses:none`. This decouples the options under test from and also prevents situations where the JVM that's under test ends up generating a bad AOT method that the JVM running cmdLineTester could load.

Closes https://github.com/eclipse-openj9/openj9/issues/17095

### CODE REVIEW

**Comment by dsouzai** [comment]
@llxia could you please review? Also, do you know if PR builds will use the updated definitions from this PR or should I be launching a separate run elsewhere? I did some local testing, but I didn't run everything and on all platforms.

**Comment by pshipton** [comment]
lgtm

**Comment by llxia** [comment]
jenkins test sanity,extended xlinux jdk11

**Comment by pshipton** [comment]
It's a bug in the test, caused by enabling shared classes by default. When creating a new shared cache verification is run. We can modify the tests to use -Xshareclasses:none, except for the "with -Xshareclasses" one, to keep the original intent.

**Comment by pshipton** [comment]
`-XX:+StartupOpts` could also be removed. I'm not sure what this was, but isn't not an option now.
```
java -XX:-IgnoreUnrecognizedXXColonOptions -XX:+StartupOpts a
JVMJ9VM007E Command-line option unrecognised: -XX:+StartupOpts
```

**Comment by dsouzai** [comment]
Made the requested changes:
* Added `-Xshareclasses:none` to the relevant verification tests
* Removed `-XX:+StartupOpts` in all tests that had that specified.

**Review by llxia — APPROVED** [review]
Thanks @dsouzai

**Pull request merged**
