### PR TITLE
Add documentation about EDO optimization mechanics

### PR DESCRIPTION
**Pull request by mpirvu**

### CODE REVIEW

**Comment by mpirvu** [comment]
@a7ehuo Could you please review this doc on EDO mechanics and make sure it meshes well with the rest of the documentation? Thanks

**Review by a7ehuo — COMMENTED** [review]
LGTM. Thank you very much for documenting this topic Marius! 

Just some very minor comments. Could you also update https://github.com/eclipse-openj9/openj9/blob/master/doc/compiler/README.md to add a link to this document under `Control Flow Optimizations` in our document TOC. Something like below: 

```
* <details><summary><b>3. Optimizer</b></summary>

...
  * [Control Flow Optimizations](optimizer/ControlFlowOptimizationsSummary.md)
    * [Exception Directed Optimization (EDO)](optimizer/EdoOptimization.md) //<--- add this one
```

**Comment by mpirvu** [comment]
I have addressed all comments from the review.

**Review by dsouzai — APPROVED** [review]

**Comment by dsouzai** [comment]
Will wait until @a7ehuo approves before merging.

**Review by a7ehuo — APPROVED** [review]
LGTM. Thank you for making all the changes!

**Pull request merged**
