### PR TITLE
Add UTF to String cache for reflection calls

### PR DESCRIPTION
**Pull request by gacholio**
Maintain a cache of J9UTF8 pointers to the matching java String for use
in reflection, StackWalker, etc.

The cache is on by default and can be controlled on the command line via
the -XX:[+|-]UTFCache options.

This is the same as https://github.com/eclipse-openj9/openj9/pull/13311 with the hash table freeing code moved from the GC into the VM release exclusive access (in both the normal and metronome paths).

Fixes: #13289

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
Verified on all platforms internally.

**Comment by gacholio** [comment]
@pshipton

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity,extended plinux jdk17

**Comment by gacholio** [comment]
@pshipton Are you going to magic this into 0.29 or would you like me to open a new PR?

**Comment by tajila** [comment]
@gacholio You'll need to double deliver

**Comment by gacholio** [comment]
https://github.com/eclipse-openj9/openj9/pull/13576

**Pull request merged**
