### PR TITLE
x64 JIT support for virtual threads (Loom)

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Misc. JIT infrastructural changes to support Loom
* x64 inc/dec of `ownedMonitorCount` J9VMThread field on monitor enter/exit
* x64 inc/dec of `callOutCount` J9VMThread field for JNI dispatch

Issue: #15175

### CODE REVIEW

**Comment by 0xdaryl** [comment]
This is essentially the same PR as #15552.  The main difference is that the refactoring of one of the monitor enter/exit out of line sequences to remove a seemingly unnecessary label is not done.  It turns out that label anchors a register dependency that is required to ensure correct register assignment on the OOL sequence.  It was removed in the earlier PR to produce a better instruction sequence.  This PR leaves it in and adds a monitor counter update instruction to the OOL path.

This PR will remain a WIP until internal testing is complete.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17,jdk19

**Comment by pshipton** [comment]
We had some random failures that I assume where caused by the original changes.
I think we should run the sanity.openjdk suite before merging this.

https://github.com/eclipse-openj9/openj9/issues/15977 - sanity.functional jdk17 Windows
https://github.com/eclipse-openj9/openj9/issues/15975 - sanity.openjdk jdk8 Mac
https://github.com/eclipse-openj9/openj9/issues/15974 - extended.functional jdk17 Windows
https://github.com/eclipse-openj9/openj9/issues/15972 - sanity.openjdk jdk11 Mac & Windows
https://github.com/eclipse-openj9/openj9/issues/15971 - extended.functional jdk11 xLinux

**Comment by pshipton** [comment]
jenkins test sanity.openjdk xmac,xlinux,win,win32 jdk8,jdk11,jdk17

**Comment by pshipton** [comment]
Some of the jdk19 sanity.functional testing hung in Jep425Tests_testVirtualThread_0:
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_aarch64_linux_Personal_testList_0/12/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_ppc64_aix_Personal_testList_1/7/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_ppc64le_linux_Personal_testList_0/15/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_x86-64_linux_Personal_testList_0/29/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_x86-64_windows_Personal_testList_1/38/console

Only amac, zlinux, xmac didn't hang.

**Comment by pshipton** [comment]
FYI last nightly build was fine, but there are other changes merged since then.
https://github.com/eclipse-openj9/openj9/compare/cb8605da243...22d152bb290

https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/164/

**Comment by pshipton** [comment]
OMR acceptance is also hanging, so the hangs are not caused by this PR.

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9/issues/16011

**Comment by 0xdaryl** [comment]
Internally I ran sanity.functional, extended.functional, and sanity.system on Linux, macOS, and Windows on JDK 17 and JDK 19 and all were clean.

**Comment by pshipton** [comment]
Given the internal testing, I have no concerns having this merged.

**Comment by 0xdaryl** [comment]
@joransiu : Sorry for the churn.  The previous PR that you reviewed and merged was reverted due to some issues being found on 32-bit.  This PR is largely the same as that, except it avoids some seemingly benign out-of-line instruction refactoring for monitor enter/exit sequences to make placement of the Loom counter updates easier.  It turns out there are some register assignment subtleties that rely on the shape of the OOL sequence so in this PR I left the the OOL sequence largely as-is but did add a counter bump for Loom.  Full testing on 32-bit and JDK 17 and 19 all looks good.  Failures found in this PR testing are attributed to #16011, as Pete mentions above.

Would you mind reviewing and merging again please?  Thanks.

**Review by joransiu — APPROVED** [review]

**Comment by joransiu** [comment]
Given the testing mentioned above, and failures are unrelated to this issue, I'll go ahead and merge.

**Pull request merged**
