### PR TITLE
Add OpenSSL 3 support to JITServer

### PR DESCRIPTION
**Pull request by cjjdespres**
Signed-off-by: Christian Despres <despresc@ibm.com>

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu. I've tested this by building JDK17 with OpenSSL 3.0.2 and running JITServer with each of OpenSSL 1.0.2, 1.1.1, and 1.0.2 installed, and also by building JDK17 with those versions and running JITServer with a system OpenSSL of 3.0.2. The test itself was simply `java -version` connecting to the running JITServer with OpenSSL enabled, to confirm that the OpenSSL context was being set up properly and the compilation requests were being sent correctly.

**Review by mpirvu — COMMENTED** [review]
Since the versions are going to increase over the time, I am suggesting to return integers from `findLibsslVersion` that indicate both the major and the minor version.
So, for 1.0.x, instead of returning 0, we should return 10
For version 1.1.x, instead of returning 1, we should return 11
For version 3.x, instead of returning 2, we should return 30.

**Comment by cjjdespres** [comment]
I could do that. OpenSSL does now claim to be API/ABI compatible across versions with the same major version number, and that's what the JDKs [seem to be assuming](https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/c625f9a5d55a39ce2574a56627ae7f847239658a/closed/src/java.base/share/native/libjncrypto/NativeCrypto.c#L41-L42), so it could be 0 for 1.0, 1 for 1.1, 3 for 3.* potentially.

**Comment by mpirvu** [comment]
I am ok either way

**Review by mpirvu — COMMENTED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk17

**Pull request merged**
