### PR TITLE
Valhalla supports jdk-23+6 update

### PR DESCRIPTION
**Pull request by JasonFengJ9**
`Valhalla` supports `jdk-23+6` update

Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/12

Launched [a person build](https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDKnext_x86-64_linux_valhalla_Personal/342/console) - passed

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by keithc-ca** [comment]
Please spell Valhalla with a capital (in the commit message and the description here); see https://openjdk.org/projects/valhalla/.

**Comment by JasonFengJ9** [comment]
Updated

**Comment by hangshao0** [comment]
Jenkins compile zlinux jdknext

**Review by hangshao0 — APPROVED** [review]
LGTM.

**Pull request merged**
