### PR TITLE
Print full exception details if a jdmpview !-command throws an exception

### LINKED ISSUE #15889: Running a ! command in jdmpview that throws an error provides few details
Java -version output
--------------------

```
java -version
openjdk version "1.8.0_352-internal"
OpenJDK Runtime Environment (build 1.8.0_352-internal-_2022_09_14_18_38-b00)
Eclipse OpenJ9 VM (build master-430e01e, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220914_000000 (JIT enabled, AOT enabled)
OpenJ9   - 430e01e
OMR      - 38e2433
JCL      - 8e8d4d3 based on jdk8u352-b05)
```

Summary of problem
------------------

When a !-command throws an exception, `com.ibm.j9ddr.tools.ddrinteractive.Context` [catches it and only prints the exception's message](https://github.com/eclipse-openj9/openj9/blob/8fc8728/debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/Context.java#L231-L235), which is not useful for some exceptions; for example:

```
Problem running command:
null
```

A `java.util.logging.Logger` trace specification can be configured to get the full exception but this can be very complicated in certain environments (in my example, Eclipse). Given that the main end-user of these diagnostic tools can be assumed to be technical, it would be nice to simply print the entire exception details, including its class and stack.

### PR DESCRIPTION
**Pull request by kgibm**
Fixes #15889

```
Problem running command:
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:194)
	at java.nio.ByteBuffer.put(ByteBuffer.java:867)
	at com.ibm.j9ddr.tools.ddrinteractive.commands.TraceFileHeaderWriter.writeStartupSection(TraceFileHeaderWriter.java:331)
	at com.ibm.j9ddr.tools.ddrinteractive.commands.TraceFileHeaderWriter.writeTraceFileHeader(TraceFileHeaderWriter.java:203)
	at com.ibm.j9ddr.tools.ddrinteractive.commands.TraceFileHeaderWriter.createAndWriteTraceFileHeader(TraceFileHeaderWriter.java:164)
	at com.ibm.j9ddr.tools.ddrinteractive.commands.SnapBaseCommand.createAndWriteTraceFileHeader(SnapBaseCommand.java:177)
	at com.ibm.j9ddr.tools.ddrinteractive.commands.SnapBaseCommand.extractTraceData(SnapBaseCommand.java:88)
	at com.ibm.j9ddr.tools.ddrinteractive.commands.SnapFormatCommand.run(SnapFormatCommand.java:458)
	at com.ibm.j9ddr.tools.ddrinteractive.commands.SnapFormatWrapperCommand.run(SnapFormatWrapperCommand.java:70)
	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
	at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:78)
	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:258)
	at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:169)
	at com.ibm.jvm.dtfjview.Session.execute(Session.java:813)
	at com.ibm.jvm.dtfjview.Session.execute(Session.java:767)
	at DTFJTest.main(DTFJTest.java:15)
```

Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
If it's useful, we could double deliver this to 0.35

**Comment by pshipton** [comment]
btw, there is no requirement to create an Issue for every PR. If you already have a fix you could just put the details into the PR.

**Comment by kgibm** [comment]
> If it's useful, we could double deliver this to 0.35

No urgency, so only if it's minimal effort to do that.

> btw, there is no requirement to create an Issue for every PR. If you already have a fix you could just put the details into the PR.

Makes sense, will do.

By the way, I haven't gotten into the habit of running tests. As I'm spending most of my time in DTFJ, what would be the easiest way to run local DTFJ regression/unit tests to make sure I haven't broken any?

**Comment by pshipton** [comment]
Depending on the risk of breaking something, and what you want to run:
- create a PR and have somebody start a PR build
- start an IBM internal personal build with your changes, running the suites needed (like sanity, extended to cover all DDR testing)
- start a personal build to compile the JVM, and then use a grinder to run the suites to want by listing them out using "testList TESTLIST=` in the TARGET
- run tests manually using https://github.com/eclipse-openj9/openj9/blob/master/test/README.md

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
jenkins compile amac jdk19

**Pull request merged**
