### PR TITLE
Add new build flag to split value object feature from Valhalla

### LINKED ISSUE #17235: New build flag for Project Valhalla
Currently the VM Valhalla code is inside `#if defined(J9VM_OPT_VALHALLA_VALUE_TYPES)`. All Valhalla features can be turned on by this build flag. However, OpenJDK has splited Valhalla features mainly into value objects and primitive value type. They are in different JEPs and planned to be released separately. We need a new build flag to split value object code and primitive value type code.

The current J9VM_OPT_VALHALLA_VALUE_TYPES can be used for value objects, a new flag J9VM_OPT_VALHALLA_FLATTENABLE_VALUE_TYPES can be introduced for primitive value types.

### PR DESCRIPTION
**Pull request by hangshao0**
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/8
Closes #17235

### CODE REVIEW

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by tajila** [comment]
@hangshao0 Does this depend on the extensions changes?

**Comment by hangshao0** [comment]
> Does this depend on the extensions changes?

Yes, it is in the description. 
`Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/8`

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext depends ibmruntimes/openj9-openjdk-jdk.valuetypes#8

**Pull request merged**
