### PR TITLE
Recognize AArch64 and RISC-V in DDR TraceFileHeaderWriter

### PR DESCRIPTION
**Pull request by knn-k**
Fixes: #18647

### CODE REVIEW

**Comment by knn-k** [comment]
This commit depends on https://github.com/eclipse/omr/pull/7208 and #18643.

**Comment by knn-k** [comment]
Jenkins compile alinux64 jdk17

**Comment by knn-k** [comment]
How can I test this?  Are the steps below correct?

1. Generate a core file
2. Run `!snaptrace` command in jdmpview to generate a .trc file
3. Run traceformat to generate a .fmt file from the .trc file

**Comment by pshipton** [comment]
Perhaps @keithc-ca will comment in the new year.

**Comment by keithc-ca** [comment]
> Are the steps below correct?

Yes, that is the way you would test this.

**Comment by knn-k** [comment]
Jenkins compile alinux64 jdk17

**Comment by knn-k** [comment]
Jenkins compile alinux64 jdk17

The previous build failed with the following error:

```
[2024-01-10T23:27:33.999Z] curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
```

**Comment by knn-k** [comment]
Build failed again with the curl error again:

```
[2024-01-10T23:38:01.457Z] + curl -LJkO 'https://api.adoptopenjdk.net/v3/binary/latest/17/ga/linux/aarch64/jdk/openj9/normal/adoptopenjdk?project=jdk'
...
 60  197M   60  120M    0     0   140k      0  0:23:54  0:14:34  0:09:20     0
[2024-01-10T23:52:36.874Z] curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
```

**Comment by knn-k** [comment]
I can see the following information in the .fmt file generated from a .trc file on AArch64 Linux, using my local build.  Arch family is set correctly.  Processor Sub-type is wrong, but it seems other architectures do not set it correctly, as I showed an example on x86-64 Linux in https://github.com/eclipse-openj9/openj9/issues/18647#issuecomment-1862112018.

```
Processor information:
        Arch family:         AArch64
        Processor Sub-type:  i486
        Num Processors:      8
        Big Endian:          false
        Word size:           64
        Using Trace Counter: J9 timer
```

**Comment by knn-k** [comment]
Jenkins compile alinux64 jdk17

**Comment by knn-k** [comment]
I haven't tested this on RISC-V.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
