### PR TITLE
TGC allocation stats per thread

### PR DESCRIPTION
**Pull request by amicic**
Report core TLH/allocation-cache stats per thread via -Xtgc:allocation. We already report cumulative stats, but it could be useful to know what are the hungry threads, and how their TLH's change size.

The new stats are hooked to mutator cache flushing at GC start, before they are cleared by the flush.

### CODE REVIEW

**Comment by amicic** [comment]
An example of both stats:

```
<exclusive-start id="2873" timestamp="2024-03-04T07:55:12.401" intervalms="3960.380">
  <response-info timems="0.794" idlems="0.794" threads="0" lastid="000000000087D600" lastname="Group1.Backend.CompositeBackend{Tier1}.7" />
</exclusive-start>
<af-start id="2874" threadId="000000000087E020" totalBytesRequested="24" timestamp="2024-03-04T07:55:12.402" intervalms="3960.353" type="nursery" />
----- Per Thread Allocation Statistics Mar 04 07:55:12 2024 ----
   OMR thread ID |                                                                             name | refresh/remaining cache size | TLH fresh count/bytes | TLH discards
0000000000774E20 |                                                                  RunDataWriter.1 |          12288          6144 |        1         8192 |            0
0000000000778A20 |                                                                       Controller |          36864          3960 |        4       106496 |          136
0000000000772220 |                                                                     MapReducer.1 |          49152         43544 |        6       208896 |           72
0000000000833420 |                                                    Heartbeat: Leader.heartbeat.1 |           8192          3968 |        1         4096 |            0
0000000000802A20 |                           Heartbeat: Group1.Backend.CompositeBackend.heartbeat.1 |           8192          3968 |        1         4096 |            0
0000000000819920 |                     Heartbeat: Group1.TxInjector.CompositeTxInjector.heartbeat.1 |          12288          7776 |        1         8192 |            0
0000000000824720 |                           Heartbeat: Group1.Backend.CompositeBackend.heartbeat.2 |           8192          3680 |        1         4096 |            0
0000000000812020 |                     Heartbeat: Group1.TxInjector.CompositeTxInjector.heartbeat.2 |           8192          3968 |        1         4096 |            0
0000000000834120 |                  Group1.TxInjector.CompositeTxInjector.I.driver.service.1.quartz |          12288           512 |        1         8192 |            0
0000000000815D20 |                    Group1.TxInjector.CompositeTxInjector.I.driver.probe.1.quartz |          12288           512 |        1         8192 |            0
00000000007A9F20 |                 Group1.TxInjector.CompositeTxInjector.I.driver.saturate.1.quartz |          12288           464 |        1         8192 |            0
00000000007AE020 |                   Group1.TxInjector.CompositeTxInjector.I.driver.tokens.1.quartz |          12288           464 |        1         8192 |            0
0000000000777020 |                                                    Heartbeat: Leader.heartbeat.2 |           8192          3584 |        1         4096 |            0
00000000007B1C20 |                                                            controller-periodic.1 |          16384          8032 |        2        20480 |            0
000000000078E820 |                                         Group1.Backend.CompositeBackend{Tier1}.1 |         131072             0 |     1391    181702656 |       101424
0000000000813E20 |                                         Group1.Backend.CompositeBackend{Tier1}.2 |         131072        122176 |     1119    146112512 |        60648
0000000000814A20 |                                         Group1.Backend.CompositeBackend{Tier1}.3 |         131072         97216 |     1006    131178496 |        57856
000000000082DC20 |                                         Group1.Backend.CompositeBackend{Tier1}.5 |         131072         46240 |     1142    149012984 |        68984
0000000000895F20 |                                         Group1.Backend.CompositeBackend{Tier1}.6 |         131072             0 |     1252    163446784 |        77240
000000000087E020 |                                         Group1.Backend.CompositeBackend{Tier1}.7 |         131072             0 |     1200    156602368 |        72544
000000000087EC20 |                                         Group1.Backend.CompositeBackend{Tier1}.8 |         131072           152 |     1383    180686848 |        83776
00000000008DBF20 |                                         Group1.Backend.CompositeBackend{Tier1}.4 |         131072        115672 |     1549    202395648 |        91920
0000000000AB5520 |                                         Group1.Backend.CompositeBackend{Tier3}.1 |         131072         15456 |      111     13991936 |         7712
0000000000AB9220 |                                         Group1.Backend.CompositeBackend{Tier3}.2 |         131072         49496 |      121     15302656 |         6680
0000000000ABCE20 |                                         Group1.Backend.CompositeBackend{Tier3}.3 |         131072         13584 |      113     14127104 |         7424
0000000000913620 |                                         Group1.Backend.CompositeBackend{Tier3}.4 |         131072         79936 |      118     14934016 |         8776
0000000000914220 |                                         Group1.Backend.CompositeBackend{Tier3}.5 |         131072        105760 |      115     14389248 |         6208
0000000000914E20 |                                         Group1.Backend.CompositeBackend{Tier3}.6 |         131072         55096 |      125     15699968 |         5864
000000000096B520 |                                         Group1.Backend.CompositeBackend{Tier3}.7 |         131072         97376 |      117     14671872 |         5168
000000000096C120 |                                         Group1.Backend.CompositeBackend{Tier3}.8 |         131072         26472 |      137     17272832 |         7120
<cycle-start id="2875" type="scavenge" contextid="0" timestamp="2024-03-04T07:55:12.404" intervalms="3960.524" />
----- Cumulative Allocation Statistics ----
TLH Refresh Count Total:              11313
TLH Refresh Count Fresh:              11022
TLH Refresh Count Reused:               291
TLH Refresh Bytes Total:         1431263880
TLH Refresh Bytes Fresh:         1431933432
TLH Discarded Bytes:                 669552
TLH Refresh Bytes Reused:           1120104
TLH Requested Bytes:             1469943808
TLH Max Abandoned List Length:            4
Normal Allocated Count:                 370
Normal Allocated Bytes:            87241840
<gc-start id="2876" type="scavenge" contextid="2875" timestamp="2024-03-04T07:55:12.405">
```

**Review by dmitripivkine — APPROVED** [review]

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux jdk21

**Comment by dmitripivkine** [comment]
Jenkins compile win jdk11

**Comment by pshipton** [comment]
Should we have a doc update for this? 
https://eclipse.dev/openj9/docs/xtgc/

**Comment by amicic** [comment]
> Should we have a doc update for this? https://eclipse.dev/openj9/docs/xtgc/

https://github.com/eclipse-openj9/openj9-docs/pull/1295

**Pull request merged**
