### PR TITLE
Remove evaluators for String.compress() and some other methods

### PR DESCRIPTION
**Pull request by knn-k**
This commit removes the evaluators for the following methods for p and x platforms.  They are no longer used.

- String.compress([C[BII)I
- String.compressNoCheck([C[BII)V
- String.andOR([CII)I

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins compile xlinux,plinux jdk8,jdk11,jdk17,jdk21

**Comment by knn-k** [comment]
Jenkins compile xlinux,xmac,aix jdk17

**Comment by knn-k** [comment]
Jenkins compile xmac jdk8,jdk17

**Comment by knn-k** [comment]
Jenkins compile win32 jdk8

**Comment by knn-k** [comment]
It is strange that xmac builds fail with the following errors:

From https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_mac_Personal/574/
```
[2024-10-02T01:01:13.277Z] [ 20%] Building ASM object runtime/codert_vm/CMakeFiles/j9codert_vm.dir/xnathelp.s.o
[2024-10-02T01:01:13.277Z] /Users/jenkins/workspace/Build_JDK17_x86-64_mac_Personal/build/macosx-x86_64-server-release/vm/runtime/codert_vm/xnathelp.s:12493:20: error: unexpected token in '.section' directive
[2024-10-02T01:01:13.277Z]  .section .note.GNU-stack,"",@progbits
[2024-10-02T01:01:13.277Z]                    ^
[2024-10-02T01:01:13.277Z] runtime/codert_vm/CMakeFiles/j9codert_vm.dir/build.make:243: recipe for target 'runtime/codert_vm/CMakeFiles/j9codert_vm.dir/xnathelp.s.o' failed

[2024-10-02T01:01:15.551Z] [ 22%] Building ASM object runtime/util/CMakeFiles/j9util.dir/fpusup.s.o
[2024-10-02T01:01:15.551Z] /Users/jenkins/workspace/Build_JDK17_x86-64_mac_Personal/build/macosx-x86_64-server-release/vm/runtime/util/fpusup.s:140:20: error: unexpected token in '.section' directive
[2024-10-02T01:01:15.551Z]  .section .note.GNU-stack,"",@progbits
[2024-10-02T01:01:15.551Z]                    ^
[2024-10-02T01:01:15.551Z] runtime/util/CMakeFiles/j9util.dir/build.make:1155: recipe for target 'runtime/util/CMakeFiles/j9util.dir/fpusup.s.o' failed
```

On the other hand, running xmac builds at the internal build server finishes successfully.
I have no idea what makes the difference.

**Comment by pshipton** [comment]
Must be different SHAs? The breaking change https://github.com/eclipse-openj9/openj9/pull/20278 was recently merged.
I see it broken internally with the latest SHA.

**Comment by knn-k** [comment]
Thank you for the information.  I will try again after Issue #20281 is fixed.

**Comment by pshipton** [comment]
Jenkins compile xmac jdk8,jdk17

**Comment by knn-k** [comment]
None of the `String` classes in Semeru Runtimes 8/11/17/21 contains those three methods.
The `String` classes have `compress()` methods with 5 arguments, while this PR is removing the evaluator for 4 argument `compress()`.  There is no method with the name `compressNoCheck()` nor `andOR()`.

I also made sure it is the same for IBM SDK for Java 8.

**Review by hzongaro — COMMENTED** [review]
I think the changes look good.

Will there be a follow-on pull request in OMR to remove the declarations and uses of `TR_{IA32|AMD64|PPC}compressString`, and others from [Helpers.inc](https://github.com/eclipse/omr/blob/13d47ea4def377422793a23813b6b25c76bbd56d/compiler/runtime/Helpers.inc#L202-L206) and [Debug.cpp](https://github.com/eclipse/omr/blob/13d47ea4def377422793a23813b6b25c76bbd56d/compiler/ras/Debug.cpp#L3830-L3834)?

**Review by hzongaro — APPROVED** [review]

**Comment by hzongaro** [comment]
Jenkins test sanity.functional,sanity.openjdk xmac,win,xlinux,aix,plinux jdk8,jdk21

**Comment by hzongaro** [comment]
Jenkins test sanity.functional,sanity.openjdk win32 jdk8

**Comment by knn-k** [comment]
Yes, I am going to open a pull request in OMR later.  There is no need for coordinated merge.

**Comment by knn-k** [comment]
Jenkins compile win32,xlinux,plinux jdk8 depends eclipse/omr#7485

**Comment by hzongaro** [comment]
Builds and testing were successful.  Changes look safe functionally, and careful investigation by @knn-k shows the impacted Java methods no longer exist.  Merging.

**Pull request merged**
