### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by keithc-ca**
And collapse sequences of two or more blank lines to one.

The line endings check in https://github.com/eclipse-openj9/openj9-docs/pull/1368 noticed a problem
with `jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/java/JavaMonitor.java`.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile jdk8,jdk11 alinux

**Comment by pshipton** [comment]
jenkins compile alinux jdk8,jdk11

**Comment by pshipton** [comment]
```
16:28:04  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/zos/dumpreader/Dump.java:185: space before tab in indent.
16:28:04  +        	} else {
```

**Comment by keithc-ca** [comment]
> space before tab in indent

Sorry, I didn't think about that possibility; I'll fix them.

**Comment by keithc-ca** [comment]
Only whitespace changes (and two blank lines deleted) in https://github.com/eclipse-openj9/openj9/compare/9414bfb9bc0a1f38de6bcd0e87e62b0b07c8ee32..c3d3135bad3c499ed8fcdc867bc9f5bbbb5055b2?w=1.

**Comment by pshipton** [comment]
Old PR https://openj9-jenkins.osuosl.org/view/Pull%20Requests/job/PullRequest-OpenJ9/5803/

jenkins compile amac jdk11

**Review by pshipton — APPROVED** [review]

**Pull request merged**
