### PR TITLE
Adjust bound for out-of-line call to StringUTF16.toBytes

### PR DESCRIPTION
**Pull request by hzongaro**
Recognized Call Transformer generates IL that implements an inline version of `StringUTF16.toBytes` for values in the range [0,0x3fffffff], and that falls back to calling the Java implementation otherwise.  In JDK levels up to 22, the Java implementation throws an `OutOfMemoryException` if the length is greater than 0x3fffffff.  JDK Level 23, however, was changed to throw an `OutOfMemoryException` if the length is greater than _or equal to_ 0x3fffffff.

This change alters the IL that Recognized Call Transformer generates to fall back to the Java implementation if the length is greater than or equal to 0x3fffffff, so that it will work with all JDK levels.

Fixes:  #20021

### CODE REVIEW

**Comment by hzongaro** [comment]
@0xdaryl, may I ask you to review this change?  It's represents an adjustment to the bounds introduced in Pull Request #19953 that are used to decide whether to perform an out-of-line call to `StringUTF16.toBytes`.  This is needed due to a difference in JDK level 23 versus earlier versions.

**Comment by hzongaro** [comment]
Jenkins test sanity,sanity.openjdk all jdk21,jdk23

**Comment by 0xdaryl** [comment]
The code changes look fine, but can you sort through all the test failures to see if there are any real ones in there pertaining to this PR?

**Comment by hzongaro** [comment]
- Windows builds are still out of commission, so the [JDK 21](https://openj9-jenkins.osuosl.org/job/Build_JDK21_x86-64_windows_Personal/247/) and [JDK 23](https://openj9-jenkins.osuosl.org/job/Build_JDK23_x86-64_windows_Personal/2/) Windows build timeouts are not unexpected.
- [JDK 21 aarch64 Linux sanity.openjdk test failures](https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Personal/40/) appear to be known issues #14692 and #18463
- [JDK 21 ppc64 AIX sanity.openjdk test failure](https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Personal/35/) appears to have been due to an infrastructure problem
- [JDK 23 aarch64 Linux sanity.functional test failure](https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.functional_aarch64_linux_Personal/5/) appears to be caused by known issue #14594
- [JDK 23 aarch64 macOS sanity.functional testing](https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.functional_aarch64_mac_Personal/14/) failed to run due to an infrastructure problem.  I will rerun it.
- [JDK 23 s390x Linux sanity.openjdk test failure](https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_s390x_linux_Personal/1/) was caused by known issue #19932
- [JDK 23 x86-64 Linux sanity.openjdk test failure](https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_x86-64_linux_Personal/1/) appears to be due to known issue #17038

Jenkins test sanity amac jdk23

**Comment by pshipton** [comment]
Pls create PRs for 0.47 and 0.48

**Pull request merged**
