### PR TITLE
Add temporary Linux GCC10 specs to pipeline build

### PR DESCRIPTION
**Pull request by vsebe**
Add the following Linux specs to build with GCC 10 compiler:
- aarch64_linux_gcc10
- ppc64le_linux_gcc10
- x86-64_linux_gcc10
- s390x_linux_gcc10

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
Build_JDK17_x86-64_linux_gcc10_Personal: [Build Status](https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_linux_gcc10_Personal/4/)
@pshipton please review, thank you!

**Comment by pshipton** [comment]
jenkins compile alinux64gcc10 jdk11

**Comment by pshipton** [comment]
jenkins compile alinux64gcc10 jdk17

**Review by pshipton — APPROVED** [review]

**Comment by vsebe** [comment]
Supported versions are: 17, 18, next

jenkins compile alinux64gcc10 jdk17

**Comment by pshipton** [comment]
```
17:41:39  * Toolchain:      gcc (GNU Compiler Collection)
17:41:39  * C Compiler:     Version 10.3.0 (at /usr/local/gcc10/bin/gcc-10.3)
17:41:39  * C++ Compiler:   Version 10.3.0 (at /usr/local/gcc10/bin/g++-10.3)
```

**Pull request merged**
