### PR TITLE
Re-enables JNI-direct for AOT on Power

### PR DESCRIPTION
**Pull request by bhavanisn**

### CODE REVIEW

**Comment by pshipton** [comment]
For history, we tried this before in https://github.com/eclipse-openj9/openj9/pull/14894 but it caused https://github.com/eclipse-openj9/openj9/issues/14941 so this PR should have some jdk8 testing before merge.

**Comment by bhavanisn** [comment]
Yes @pshipton . I have run ppc64le tests. But not on aix_ppc64. I am currently doing that.

**Comment by bhavanisn** [comment]
Aix build on jdk8:
https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/12763/
ppc64le_linux build on jdk8:
https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/12770/

@pshipton  I have run these 2 tests on the branch. Do you want me to run any more tests like on jdk11 or others ?

**Comment by ymanton** [comment]
Jenkins test sanity.functional plinux,aix,xlinux jdk8,jdk11

**Pull request merged**
