### PR TITLE
Set CurrentThread sym ref in defaultMethodDefAliases

### PR DESCRIPTION
**Pull request by a7ehuo**
For JDK19 and up, `CurrentThread` could be modified by any method calls. Set `CurrentThread` sym ref in `defaultMethodDefAliases`. 

Also removed `setVolatile` on `CurrentThread` symbol which is not needed.

### CODE REVIEW

**Comment by a7ehuo** [comment]
@jdmpapin May I ask you to review this change? Thanks!
@0xdaryl fyi

**Comment by jdmpapin** [comment]
I feel that the name `methodMetaDataSymRefs()` suggests that the set should contain all method metadata symrefs, but in fact it will only contain `CurrentThread`, which is the only one we want to include in `defaultMethodDefAliases()`.

Since the point is just to include `CurrentThread`, does it need to be a set? I think it might be better just to remember that particular symref and add it into `defaultMethodDefAliases()`. Otherwise, I think the set should have a name that is more descriptive of what it contains

**Comment by a7ehuo** [comment]
> I think it might be better just to remember that particular symref and add it into defaultMethodDefAliases().

This makes sense. I'll make the change

**Comment by jdmpapin** [comment]
The new change LGTM, though please see https://github.com/eclipse-openj9/openj9/issues/17120#issuecomment-1533471391

Also, could you please reword the title/message? It it stands it sounds like the change will cause us to set some state on the `CurrentThread` symref, when in fact it's `defaultMethodDefAliases()` that will be modified to include it. Please also add a mention that this is meant to fix #17120

**Comment by a7ehuo** [comment]
@jdmpapin all comments are addressed. Ready for another review. Thanks!

**Review by jdmpapin — APPROVED** [review]

**Comment by jdmpapin** [comment]
The JDK17 AIX failure is #8625:
```
[2023-05-05T17:33:13.432Z] Sjavac server failed to initialize: Deadlock condition if locked
[2023-05-05T17:33:13.432Z] Process output:
[2023-05-05T17:35:19.883Z] <End of process output>
[2023-05-05T17:35:19.883Z] IOException caught during compilation: Server failed to initialize: Deadlock condition if locked
```
The JDK17 x86 Mac failure is an infrastructure problem. It looks just like what happened in #16138, but on a different machine:
```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
The JDK20 AArch64 Linux failure is #13577:
```
Testing: -Xlockword minimizeFootprint mode
Test start time: 2023/05/05 17:16:52 Coordinated Universal Time
Running command: "/home/jenkins/workspace/Test_openjdk20_j9_sanity.functional_aarch64_linux_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java"   -Xdump -cp "/home/jenkins/workspace/Test_openjdk20_j9_sanity.functional_aarch64_linux_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/utils/utils.jar" -Xlockword:mode=minimizeFootprint VMBench.FibBench
Time spent starting: 4 milliseconds
Time spent executing: 2427 milliseconds
Test result: FAILED
Output from test:
 [OUT] Fibonacci: iterations = 10000
 [OUT] fibonacci(12) = 144
 [ERR] Unhandled exception
 [ERR] Type=Segmentation error vmState=0x00000000
```

**Comment by jdmpapin** [comment]
Jenkins test sanity aix,xmac jdk17

**Comment by jdmpapin** [comment]
Jenkins test sanity alinux64 jdk20

**Comment by jdmpapin** [comment]
The JDK20 x86 Linux failure looks to be #17333:
```
Testing: Test Metrics Disabled
...
Test result: FAILED
Output from test:
...
 [ERR] #JITServer: Sent clientSessionTerminate message
 [ERR]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 [ERR]                                  Dload  Upload   Total   Spent    Left  Speed
 [ERR] 
 [ERR]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to ::1: No route to host
 [ERR] /home/jenkins/workspace/Test_openjdk20_j9_sanity.functional_x86-64_linux_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jitserver/jitserverScript.sh: line 65: 13916 Killed                  $TEST_JDK_BIN/jitserver $JITSERVER_OPTIONS
>> Required condition was found: [Output match: (java|openjdk|semeru) version]
>> Failure condition was not found: [Output match: jitserver_cpu_utilization]
>> Failure condition was not found: [Output match: jitserver_available_memory]
>> Failure condition was not found: [Output match: jitserver_connected_clients]
>> Failure condition was not found: [Output match: jitserver_active_threads]
>> Success condition was not found: [Output match: Connection refused]
>> Failure condition was not found: [Output match: (Fatal|Unhandled) Exception]
```
Instead of restarting it, I'll consider Test_openjdk20_j9_sanity.functional_x86-64_linux_Personal to be passing. The fix #17313 that's just been merged (as it pertains to this failure) merely removes the failing test:
> The `Test Metrics Disabled` test is removed as it is not all that useful

**Comment by jdmpapin** [comment]
All other builds have passed

**Pull request merged**
