### PR TITLE
Refactor J9JVMTI_HEAP_EVENT_STACK data parsing

### PR DESCRIPTION
**Pull request by fengxue-IS**
Added new structure to hold JNI and Stack local referrer data. Update JNI locals found via jniLocalReferences table to be marked as Stack root.

Closes: #18416 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
#19486 reverted some of the changes in #18180 to properly handle reference chain walking on virtual thread stack.
This change corrects the behaviour by caching the virtual thread object in `ReferenceChainWalker` and fill the value into `J9MM_StackSlotDescriptor->vmThread` before executing the callback function.

**Comment by fengxue-IS** [comment]
@babsingh @LinHu2016 can you please take a look at this

**Comment by babsingh** [comment]
### Consistent formatting

There are places where there is space before and after `*`. Others only have space before `*`; there is no space after `*`. The latter is the preferred approach. If we're making small changes, then we should follow the existing formatting used in the file. If we're changing majority of the function, then should update the function to follow the preferred approach.
```
processStackRoot(J9JVMTIObjectIteratorData * data, J9JVMTIObjectTag * entry, jlong size, jlong classTag, jvmtiHeapRootKind kind, J9MM_StackSlotDescriptor *stackSlotDescriptor)
```

Similarly, if we're adding a cast, then the preferred approach is to not have space after the closing bracket `)`. Use the above logic to either employ existing formatting or transition to the preferred approach. 
```
		slot = (jint) walkState->slotIndex;
```

**Comment by babsingh** [comment]
How have these changes been tested? Were any personal builds run? If so, which test suites were selected?

**Comment by fengxue-IS** [comment]
> How have these changes been tested? Were any personal builds run? If so, which test suites were selected?

I've include link to personal build, see above https://github.com/eclipse-openj9/openj9/pull/18864#issuecomment-2327492510

**Comment by babsingh** [comment]
> local testing passed, [personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/23749/) passed

Are any of the failures and unstable builds related to this PR?

>  Note VThreadStackRefTest.java is still excluded atm

Will VThreadStackRefTest.java pass on all platforms?

**Comment by fengxue-IS** [comment]
> > local testing passed, [personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/23749/) passed
> 
> Are any of the failures and unstable builds related to this PR?

No
> > Note VThreadStackRefTest.java is still excluded atm
> 
> Does VThreadStackRefTest.java pass on all platforms?

I've only tested on xlinux and amac for JDK 21, be since the test are all testing JVM internals, there shouldn't be any platform related differences. 
I've opened https://github.com/adoptium/aqa-tests/pull/5567 to re-enable the test

**Comment by LinHu2016** [comment]
LGTM, need to confirm  ReferenceChainWalker is not caller during concurrent scavenger(currently it is only used during STW GC, read threadObject via Java API during concurrent scavenger might cause an infinity loop).

**Comment by fengxue-IS** [comment]
@LinHu2016 added assertions to ensure API only used under exclusive access

**Review by LinHu2016 — APPROVED** [review]

**Comment by babsingh** [comment]
jenkins test sanity alinux jdk21

**Comment by babsingh** [comment]
jenkins test sanity alinux jdk11

**Comment by babsingh** [comment]
There are compilation errors on JDK11. vthread code is missing ifdefs.

```
11:38:59  /home/jenkins/workspace/Build_JDK11_aarch64_linux_Personal/openj9/runtime/gc_base/ReferenceChainWalker.cpp: In function 'void j9gc_ext_reachable_objects_do(J9VMThread*, jvmtiIterationControl (*)(J9Object**, J9Object*, void*, IDATA, IDATA, IDATA), void*, uintptr_t)':
11:38:59  /home/jenkins/workspace/Build_JDK11_aarch64_linux_Personal/openj9/runtime/gc_base/ReferenceChainWalker.cpp:95:24: error: 'class MM_ReferenceChainWalker' has no member named 'includeVThreadObject'
11:38:59     95 |   referenceChainWalker.includeVThreadObject();
11:38:59        |                        ^~~~~~~~~~~~~~~~~~~~
11:38:59  /home/jenkins/workspace/Build_JDK11_aarch64_linux_Personal/openj9/runtime/gc_base/ReferenceChainWalker.cpp: In function 'void j9gc_ext_reachable_from_object_do(J9VMThread*, J9Object*, jvmtiIterationControl (*)(J9Object**, J9Object*, void*, IDATA, IDATA, IDATA), void*, uintptr_t)':
11:38:59  /home/jenkins/workspace/Build_JDK11_aarch64_linux_Personal/openj9/runtime/gc_base/ReferenceChainWalker.cpp:129:24: error: 'class MM_ReferenceChainWalker' has no member named 'includeVThreadObject'
11:38:59    129 |   referenceChainWalker.includeVThreadObject();
11:38:59        |                        ^~~~~~~~~~~~~~~~~~~~
11:38:59  runtime/gc_base/CMakeFiles/j9gcbase.dir/build.make:335: recipe for target 'runtime/gc_base/CMakeFiles/j9gcbase.dir/ReferenceChainWalker.cpp.o' 
```

**Comment by fengxue-IS** [comment]
Added ifdef to fix JDK11 compile error, the JDK 21 PR build also failed due to jenkins flow error, @babsingh can you restart the builds please

**Comment by babsingh** [comment]
jenkins test sanity,extended.openjdk zlinux jdk21

**Comment by babsingh** [comment]
jenkins test sanity win,alinux jdk11

**Review by babsingh — APPROVED** [review]
LGTM. `Test_openjdk21_j9_extended.openjdk` PR build has unrelated security/SSL failures.

**Pull request merged**
