### PR TITLE
Update classloader when cached rom to ram entry is found

### PR DESCRIPTION
**Pull request by theresa-m**
Issue: https://github.com/eclipse-openj9/openj9/issues/20368

### CODE REVIEW

**Comment by hangshao0** [comment]
Jenkins test sanity,extended alinux jdk17

**Comment by hangshao0** [comment]
Jenkins test sanity,extended amac jdk21

**Comment by pshipton** [comment]
jenkins test extended amacaot jdk11

**Comment by pshipton** [comment]
jenkins test sanity.functional,extended amacaot jdk11

**Comment by hangshao0** [comment]
@theresa-m Please create a PR for 0.48.

**Comment by pshipton** [comment]
Only expected failures.

**Review by hangshao0 — APPROVED** [review]
I will merge this once the 0.48 PR is open.

**Comment by pshipton** [comment]
Better to merge it now and get it into the nightly build tonight. The issue will stay open.

**Comment by pshipton** [comment]
I went ahead with the merge as the first nightly build starts in 2 minutes.

**Pull request merged**
