### PR TITLE
(0.30.0) Fix inconsistency between J9Class and annotation data when redefine

### PR DESCRIPTION
**Pull request by EricYangIBM**
If a class is redefined between annotation fetch and parse, a
`Wrong type at constant pool index` or `Constant pool index out of bounds`
exception may be thrown due to inconsistency between the annotation data
and J9Class. Pass the J9ConstantPool along with the annotation data to
ensure that `parseAnnotations` looks up the correct constant pool.

- Add new class `InternalConstantPool` that `ConstantPool` will hold an
  instance of (instead of `InternalRamClass`)
- Change `getConstantPool` to take `InternalConstantPool` or `Class`
  (if `Class`, create `InternalConstantPool` from it).
- Change `sun/reflect/ConstantPool` natives to take an `InternalConstantPool`
  argument so that the correct constant pool is looked up (e.g. after HCR)
- Add a jithelper to get `J9ConstantPool` from `J9Class`
- Add test that redefines a class while fetching its annotations

Port of #13836 for the 0.30.0 release.

Closes: #10026
Signed-off-by: Eric Yang <eric.yang@ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
I'll wait till tomorrow before merging this, to give it some time in the head stream.

**Comment by pshipton** [comment]
Setting as draft until the problems with https://github.com/eclipse-openj9/openj9/pull/13836 are resolved.

**Comment by tajila** [comment]
@EricYangIBM Please update this to the new version

**Review by tajila — APPROVED** [review]

**Comment by pshipton** [comment]
We need to figure out https://github.com/eclipse-openj9/openj9/issues/14115 before this is merged to 0.30.

**Comment by tajila** [comment]
> We need to figure out #14115 before this is merged to 0.30.

After looking at #14115 it is unrelated to the changes in this PR and looks similar to #14014

**Comment by tajila** [comment]
@pshipton would removing the test from this PR be an option?

**Comment by pshipton** [comment]
> would removing the test from this PR be an option?

I don't see a problem keeping the test. It only fails intermittently and we can ignore any failure. 

> After looking at #14115 it is unrelated to the changes in this PR and looks similar to #14014

This is sufficient for me if you want to take this out of draft and merge it before Milestone 2.

**Pull request merged**
