### PR TITLE
Fix incorrect free in ensure hashed parsing

### PR DESCRIPTION
**Pull request by gacholio**
Fixes: #15688

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
FYI @EricYangIBM

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
white space issue

```
16:16:26  runtime/vm/jvminit.c:8277: trailing whitespace.
16:16:26  +			hashtableEntry = NULL;	
```

**Comment by tajila** [comment]
Jenkins compile sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity amac jdk17

**Comment by EricYangIBM** [comment]
Does the same issue exist for https://github.com/eclipse-openj9/openj9/blob/cb0bf58fd85ac9c2197bdf29d2c7e549c65b6fa4/runtime/vm/lockwordconfig.c#L209-L220?

**Comment by tajila** [comment]
@EricYangIBM Does the lockword option table store two modes? like enable and disable?

If so I dont think GACs solution in this PR would apply there, since we would actually have to remove a previous option in order to update it with a new one.

**Comment by gacholio** [comment]
The lockword code is correct if possibly inefficient (no reason to delete and re-add when you can just update the mode in an existing entry). It fetches the data before freeing the table entry.

**Pull request merged**
