### PR TITLE
Revert "Fix off-by-one error in String.indexOf acceleration on z15"

### PR DESCRIPTION
**Pull request by fjeremic**
This reverts commit 409d860.

### CODE REVIEW

**Comment by fjeremic** [comment]
This was accidentally pushed to the master branch. Apologies for this.

**Comment by keithc-ca** [comment]
This doesn't look right. It seems to me that 75f2ae5209f48277f11139614e6ec971304707ff only changes one file relative to 7cae4c19859500772b3faf693d04fae6193c792a so this should only revert that file.

**Comment by fjeremic** [comment]
> This doesn't look right. It seems to me that [75f2ae5](https://github.com/eclipse-openj9/openj9/commit/75f2ae5209f48277f11139614e6ec971304707ff) only changes one file relative to [7cae4c1](https://github.com/eclipse-openj9/openj9/commit/7cae4c19859500772b3faf693d04fae6193c792a) so this should only revert that file.

Thanks! Yes you're totally right. Fixed.

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
The resulting tree is identical to 7cae4c19859500772b3faf693d04fae6193c792a; no PR testing required.

**Pull request merged**
