### PR TITLE
AArch64: Adding additional arraycopy helper entries

### PR DESCRIPTION
**Pull request by sahithiponangi**
This commit adds additional arraycopy helper entries.

Signed-off-by: Siri Sahithi Ponangi <sahithi.ponangi@unb.ca>

### CODE REVIEW

**Comment by sahithiponangi** [comment]
This PR is dependent on omr/pull/6188

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11 depends eclipse/omr#6188

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11 depends eclipse/omr#6188

The previous build job failed with an unknown reason.  Trying to run again.

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11 depends eclipse/omr#6188

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11 depends eclipse/omr#6188

**Review by knn-k — APPROVED** [review]

**Comment by knn-k** [comment]
Jenkins test sanity alinux64 jdk8,jdk11 depends eclipse/omr#6188

**Pull request merged**
