### PR TITLE
Add java.specification.maintenance.version=4 jdk8 system property

### PR DESCRIPTION
**Pull request by pshipton**
As per the jdk8 JSR 337 Maintenance Release 4 spec
https://jcp.org/aboutJava/communityprocess/maintenance/jsr337/jsr337-mr4-changes.html

See also OpenJDK 8285497
https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/df84c26757ec70ef67fd94d1cfacd77f1b4c302f

Also related https://github.com/eclipse-openj9/openj9/pull/15784

### CODE REVIEW

**Comment by pshipton** [comment]
@tajila or @babsingh pls review

**Comment by babsingh** [comment]
Minor note for the future from https://bugs.openjdk.org/browse/JDK-8285497:
> If and when the 11 and 17 platform specs have their next (or first) maintenance reviews, it would be reasonable to add the property at that time.

**Comment by babsingh** [comment]
jenkins test sanity win jdk8

**Comment by pshipton** [comment]
Confirmed the system property is set in the build using `-XshowSettings:properties`
```
    java.specification.maintenance.version = 4
```

**Pull request merged**
