### PR TITLE
Ensure all necessary cached JITServer AOT cache records are valid during deserialization

### PR DESCRIPTION
**Pull request by cjjdespres**
When deserializing a method from the JITServer AOT cache, the client, if ignoring its local SCC, must ensure that all serialization records referred to by that method are still valid. This is necessary to fulfill the requests for cached data that the TR_J9DeserializerSharedCache will make of the deserializer during the relocation of that method.

A few verbose log lines related to class loader deserialization failures due to class loader invalidation were also added.

Fixes: https://github.com/eclipse-openj9/openj9/issues/19461

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu.

**Comment by cjjdespres** [comment]
This may not have fixed it completely, only made it more intermittent.

Actually, now that I think about it, this solution may not be correct after all. I think we should instead check the loader record validity when deserializing an already-cached class loader record. I'll test that out.

**Comment by cjjdespres** [comment]
Okay, that should be correct.

**Comment by cjjdespres** [comment]
I've found another bug that is caused by a similar issue as this one, and they can be both fixed in the same way. I'll rewrite this.

**Comment by cjjdespres** [comment]
I think this now fixes the particular class of bug I mentioned in the linked issue - both the class loaders and the other record types I mentioned in https://github.com/eclipse-openj9/openj9/issues/19461#issuecomment-2105326487.

**Comment by mpirvu** [comment]
jenkins test sanity xlinuxjit,zlinuxjit,alinux64jit jdk21

**Pull request merged**
