### PR TITLE
AArch64: Implement BNDCHKwithSpineCHKEvaluator()

### PR DESCRIPTION
**Pull request by knn-k**
This commit implements BNDCHKwithSpineCHKEvaluator() for AArch64.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
This PR depends on eclipse/omr#5440 and eclipse/omr#5442.

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11

**Comment by knn-k** [comment]
jenkins test sanity.system alinux64 jdk11

**Comment by knn-k** [comment]
There are two failures in sanity.system.  They are known issues with JlmRemote #9046, and not introduced by this PR.

**Comment by DanHeidinga** [comment]
@0xdaryl Can you review this?  It's related to a jdk15 (0.22) release issue.  @knn-k can you confirm whether this needs to be in the 0.22 release?

**Comment by knn-k** [comment]
> It's related to a jdk15 (0.22) release issue.

Is there any issue or test failure with JDK 15 AArch64 that is caused by unimplemented BNDCHKwithSpineCHKEvaluator()?

**Comment by DanHeidinga** [comment]
> > It's related to a jdk15 (0.22) release issue.
> 
> Is there any issue or test failure with JDK 15 AArch64 that is caused by unimplemented BNDCHKwithSpineCHKEvaluator()?

It was linked from https://github.com/eclipse/openj9/issues/9046 but reading more closely thru this issue indicates this isn't the fix for that issue:
> They are known issues with JlmRemote #9046, and not introduced by this PR.

So it's not needed for the 0.22 release

**Comment by knn-k** [comment]
Resolved the merge conflict.

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11

**Comment by knn-k** [comment]
@0xdaryl Could you review this PR, please?  Thanks.

**Comment by knn-k** [comment]
Fixed a bug found in extended.functional (using the test mode settings from https://github.com/AdoptOpenJDK/TKG/pull/97)

**Comment by knn-k** [comment]
Updated the code by removing calls to `vm.heapBaseAddress()` (See #11688).

**Comment by knn-k** [comment]
I updated the code to resolve a merge conflict.

**Comment by 0xdaryl** [comment]
No technical barriers, just resources for a careful review.  We'll target review by May 21, but likely sooner.

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by 0xdaryl** [comment]
Jenkins test sanity.system,sanity.functional alinux64 jdk11

**Comment by 0xdaryl** [comment]
The mauve failure looks real, but it can't be because of this PR because this PR only affects the balanced GC policy.  I opened #12732.

**Comment by 0xdaryl** [comment]
Jenkins test sanity.functional alinux64 jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity.functional alinux64 jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity.system alinux64 jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity.system alinux64 jdk11

**Comment by knn-k** [comment]
Please wait for #12758 to be merged, so that the sanity.system tests pass.

**Comment by knn-k** [comment]
Jenkins test sanity.system alinux64 jdk11

**Comment by 0xdaryl** [comment]
System test failed with a JLink hash error:
```
JLNK Error: Hash of java.xml (0cda2bac40a86a8ab5b1f5797ec814fdde552f74f8ee487f0cb81de019dd0912) differs to expected hash (3bc50f598c51e86ab18a95be560cf4e11411fe9d30f381011d0e81aea1c609a4) recorded in java.base
```
We've seen this before intermittently and don't believe it is an OpenJ9 problem.  I'll re-run the testing.

**Comment by 0xdaryl** [comment]
Jenkins test sanity.system alinux64 jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity.system alinux64 jdk11

Trying again.  Build never got off the ground.

**Comment by 0xdaryl** [comment]
Jenkins test sanity.system alinux64 jdk11

Trying again. Build aborted.

**Comment by knn-k** [comment]
There are some failures with sanity.system in another PR (#12731) today.  They look like the known issue related to openssl.

**Comment by knn-k** [comment]
sanity.system is OK.
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_aarch64_linux_Personal/7/

On the other hand, a build job failed with the following exception:
https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_linux_Personal/17/
```
java.lang.SecurityException: SHA-256 digest error for org/eclipse/jgit/lib/PersonIdent.class
	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:239)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:243)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
```

**Comment by knn-k** [comment]
Jenkins build alinux64 jdk11

**Comment by knn-k** [comment]
Jenkins compile alinux64 jdk11

**Comment by knn-k** [comment]
Jenkins compile alinux64 jdk11

**Comment by 0xdaryl** [comment]
Jenkins compile alinux64 jdk11

**Comment by 0xdaryl** [comment]
Jenkins compile alinux64 jdk11

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
I just realized that most of the testing run in this PR wasn't testing the code paths with `-Xgcpolicy:balanced` because those tests have been excluded on AArch64.

Shouldn't #10321, or a reversion of #8569, or enabling the disabled test modes be included as part of this PR?

**Comment by knn-k** [comment]
I moved the change in #10321 to this PR.

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11

**Comment by 0xdaryl** [comment]
> Balanced GC tests in system tests will be enabled by adoptium/TKG#97

Thanks.

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
We will enable system tests in the adoptium repo after demonstrating they run successfully.

**Pull request merged**
