### PR TITLE
Hoist getSupportsInlineStringHashCode check for better readability

### PR DESCRIPTION
**Pull request by VermaSh**

### CODE REVIEW

**Comment by VermaSh** [comment]
Personal build passed without any failures http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=50514

@0xdaryl Can I please get a review?

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux,win,xmac jdk17

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux jdk17

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Only failure is infrastructural (CRIU).  Merging.

**Pull request merged**
