### PR TITLE
Make VP erase interface types in array types from signatures

### PR DESCRIPTION
**Pull request by jdmpapin**
The verifier treats interface types as `java/lang/Object` even within array component types. In particular, when any parameter, instance or static field, or return type is declared with a signature naming an array of an interface type, its value is guaranteed to be a reference array, but not necessarily the named array type. For example, if a parameter is declared to be of type `List[]`, it can actually be any `Object[]`.

----

There is one preparatory refactoring commit:
- Factor VP interface type signature detection logic into its own method

### CODE REVIEW

**Comment by jdmpapin** [comment]
This depends on eclipse/omr#6814

**Comment by jdmpapin** [comment]
@vijaysun-omr, could you please review?

**Comment by vijaysun-omr** [comment]
Jenkins test sanity all jdk17

**Comment by vijaysun-omr** [comment]
Checks have passed. Merging.

**Pull request merged**
