### PR TITLE
Remove JITServer tech preview message from the server

### PR DESCRIPTION
**Pull request by dmitry-ten**
Do not print the message on x86 and Power architectures.

Closes: #13491

### CODE REVIEW

**Comment by dmitry-ten** [comment]
@mpirvu ready for review.

**Review by mpirvu — COMMENTED** [review]
`TR_HOST_S390` is more of a JIT thing. In the VM code I see `J9VM_ARCH_S390` being used. Does the code work as intended?

**Comment by dmitry-ten** [comment]
Changed to the above env variable.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit jdk17

**Pull request merged**
