### PR TITLE
Enable Gencon/Balanced/OptAvgPause GC policy in testing

### PR DESCRIPTION
**Pull request by fengxue-IS**
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
Per discussion with Lin, GC policy have been updated to support VirtualThread/Continuation
@LinHu2016 can you please review this

**Comment by LinHu2016** [comment]
LGTM

**Comment by pshipton** [comment]
Trying the test on a number of platforms
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1330/

**Comment by pshipton** [comment]
A crash in https://openj9-jenkins.osuosl.org/job/Grinder/1331/tapResults/

**Comment by pshipton** [comment]
A crash running balanced on most platforms, see the previous comment for details.

**Comment by dmitripivkine** [comment]
> A crash running balanced on most platforms, see the previous comment for details.

Crash in Balanced and incomplete handling in Gencon
Fixing the problem in https://github.com/eclipse-openj9/openj9/pull/16087

**Comment by babsingh** [comment]
Reopening, accidentally closed by https://github.com/eclipse-openj9/openj9/pull/16087.

**Comment by fengxue-IS** [comment]
@LinHu2016 can you take another look please

**Comment by pshipton** [comment]
New grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1374/

**Comment by pshipton** [comment]
I guess we need to wait until tomorrow, as the fix was just merged today and I'm using nightly builds for the testing.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1383

**Comment by LinHu2016** [comment]
LGTM

**Review by pshipton — APPROVED** [review]

**Pull request merged**
