### PR TITLE
Update functional tests dependencies part1

### PR DESCRIPTION
**Pull request by renfeiw**
- remove unnecessary import from test build.xml
- add dependencies in build.xml

[ci skip]

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
tested in grinder_TKG: 
| build |      BUILD_LIST      |  Target |
|----------|:-------------:|------:|
| 1372 |  functional/JavaAgentTest | all |
| 1371 |    functional/Java12andUp   |   all |
| 1370 |    functional/Java11andUp   |   all |
| 1369 |    functional/Java9andUp   |   all |
| 1368 |    functional/Java10andUp   |   all |
| 1364 | functional/IllegalAccessError_for_protected_method |    all |
| 1363 | functional/HealthCenter |    all |
| 1362 | functional/DDR_Test |    all |
| 1361 | functional/CacheManagement |    all |

**Comment by renfeiw** [comment]
reviewers: @llxia @smlambert

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
jenkins test sanity,extended xlinux,plinux,win jdk8,jdk11

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
