### PR TITLE
Refactor TR::DefaultCompilationStrategy::processJittedSample

### PR DESCRIPTION
**Pull request by dsouzai**
This PR is a retry of https://github.com/eclipse-openj9/openj9/pull/15137; the main difference is that I removed the fatal assert. I've verified there's no issues by running extended.system tests internally.

### CODE REVIEW

**Comment by dsouzai** [comment]
@ymanton do you mind reviewing again? Also as per https://github.com/eclipse-openj9/openj9/pull/15137#issuecomment-1167402450 I suppose we should run the sanity.system and extended.system suites.

**Review by ymanton — APPROVED** [review]
Difference to #15137 is minor. LGTM.

**Comment by ymanton** [comment]
Jenkins test sanity.system,extended.system all jdk11

**Comment by dsouzai** [comment]
Test_openjdk11_j9_sanity.system_x86-64_linux_Personal failure is due to
```
[2022-08-08T21:04:01.154Z] CL2 j> 2022/08/08 18:03:59.386 Writing report data ...
[2022-08-08T21:04:03.736Z] CL2 stderr Exception in thread "main" java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
[2022-08-08T21:04:03.737Z] CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ExpectedMBeanInfo.writeOutCategoryReport(ExpectedMBeanInfo.java:238)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ExpectedMBeanInfo.writeOutChecklistReport(ExpectedMBeanInfo.java:284)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ThreadData.writeMBeanInfo(ThreadData.java:900)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ThreadData.writeData(ThreadData.java:427)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.getStatsViaServer(ThreadProfiler.java:199)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.main(ThreadProfiler.java:99)
[2022-08-08T21:04:03.737Z] CL2 stderr Caused by: java.lang.invoke.StringConcatException: Generator failed
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:764)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.MethodHandleResolver.invokeBsm(MethodHandleResolver.java:176)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:238)
[2022-08-08T21:04:03.737Z] CL2 stderr 	... 6 more
[2022-08-08T21:04:03.737Z] CL2 stderr Caused by: java.lang.NullPointerException
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.BruteArgumentMoverHandle.permuteArguments(BruteArgumentMoverHandle.java:286)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.MethodHandles.dropArgumentsUnsafe(MethodHandles.java:2961)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.MethodHandles.dropArguments(MethodHandles.java:2978)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1536)
[2022-08-08T21:04:03.737Z] CL2 stderr 	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:756)
[2022-08-08T21:04:03.737Z] CL2 stderr 	... 10 more
```
which is seen before in https://github.com/eclipse-openj9/openj9/issues/8972#issuecomment-969168369

**Pull request merged**
