### PR TITLE
Fix potential Segmentation Error due to a NULL hotFieldPoolMutex

### PR DESCRIPTION
**Pull request by jonoommen**
Potentially fix segmentation error with vmState=0x000565ff due to a NULL hotFieldPoolMutex. I have been unable to reproduce the issue, however, from analyzing the code, this patch addresses the corner case where the `hotFieldPool` for the `classloader` is successfully created while the `hotFieldPoolMutex` for the `classloader` is not successfully created.

Related to: https://github.com/eclipse-openj9/openj9/issues/12782 

Signed-off-by: Jonathan Oommen <jon.oommen@gmail.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Hey @jonoommen thanks for the contribution. The PR title and description does not match that of the commit. One says we are potentially fixing an issue (what does this mean?), and the other says we are fixing it.

I think the commit title could also be worded better. When you're writing commit messages, it helps to think about how those commit messages will be consumed by the readers. For example if I am another developer looking at `git log --pretty=oneline` the title "Fix Power Segmentation Error" will not give me much information about what the change was. The code in question being change is also cross-platform. A better title may tell me a bit about what segmentation error was fixed, for example "Fix SIGSEGV when hotFieldPoolMutex is NULL". Hope that helps and that you understand the context on why it is important we document our commits with descriptive titles and bodies.

**Comment by jonoommen** [comment]
@pshipton should I be trying to get this PR merged to see if it resolves https://github.com/eclipse-openj9/openj9/issues/12782, or how should we proceed with this?

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
The code is fine, but the commit and PR titles are still questionable - perhaps "Fix potential Segmentation Error due to a NULL hotFieldPoolMutex".

**Comment by pshipton** [comment]
I ran a full internal vmfarm test build with no issues.

jenkins test sanity win jdk11

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/373/

**Pull request merged**
