### PR TITLE
Simplify fePreProcess

### PR DESCRIPTION
**Pull request by singh264**
Refactor fePreProcess into smaller methods.

Closes: #12504
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com

### CODE REVIEW

**Comment by singh264** [comment]
@ymanton @dsouzai @fjeremic, requesting feedback

`method_name line_start - line_end`

fePreProcess [1205 - 2131](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1205-L2131)

preProcessMmf [1263 - 1336](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1263-L1336)
preProcessMode [1343 – 1399](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1343-L1399)
preProcessJniAccelerator [1411 - 1440](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1411-L1440)
preProcessCodeCache [1401 – 1409](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1401-L1409), [1442 – 1851](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1442-L1851)
preProcessCodeCacheIncreaseTotalSize [1442 – 1501](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1442-L1501)
preProcessCodeCachePrintCodeCache [1503 - 1512](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1503-L1512)
preProcessCodeCacheXlpCodeCache [1514 – 1851](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1514-L1851)
preProcessSamplingExpirationTime [1853 – 1861](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1853-L1861)
preProcessCompilationThreads [1863 - 1875](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1863-L1875)
preProcessTLHPrefetch [1877 – 1907](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1877-L1907)
preProcessHwProfiler [1913 – 1949](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L1913-L1948)
preProcessDeterministicMode [2022 - 2037](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L2022-L2037)
preProcessJitServer [2041 - 2124](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/J9Options.cpp#L2041-L2124)

**Review by dsouzai — CHANGES_REQUESTED** [review]
Thanks for taking this on, and also breaking it up into small commits. Overall LGTM. Couple of changes:

1. Could you add doxygen comments for the new methods you added
2. In all places where you invoke your new methods, you have to do `self()->newMethod` in order to make the linter happy; because `J9::Options` is an extensible class, when invoking methods, you have to use `self()` (it's essentially like invoking methods like `this->myMethod` but `self()` contains some code to ensure the compiler generates the right method to dispatch to).

**Comment by singh264** [comment]
> 1. Could you add doxygen comments for the new methods you added

what documentation or examples should I refer to for adding doxygen comments?

**Comment by ymanton** [comment]
> > 1. Could you add doxygen comments for the new methods you added
> 
> what documentation or examples should I refer to for adding doxygen comments?

Here are some files with documented methods that you can refer to:

https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/codegen/J9CodeGenerator.hpp
https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/z/codegen/J9CodeGenerator.hpp

**Comment by dsouzai** [comment]
jenkins test sanity all jdk11

**Comment by fjeremic** [comment]
Thanks for tackling this. Could we update the commits to be a little more descriptive? For example I'm a developer browsing `git log --pretty=oneline` and I see a commit with the name "preProcessJniAccelerator". I would be left wondering what exactly was the purpose of that commit. A better commit may be "Extract a portion of fePreProcess into preProcessJniAccelerator". This now tells me this is a refactoring commit moving code from one function into another.

**Comment by singh264** [comment]
how would you recommend to organize the commits before merging the PR?

I have amended my commits for the team.

**Comment by dsouzai** [comment]
I think the commits are fine as is.

jenkins tests osx jdk11

(since the mac build failed for unrelated reasons)

**Comment by dsouzai** [comment]
jenkins test osx jdk11

**Comment by dsouzai** [comment]
jenkins test sanity osx jdk11

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
