### PR TITLE
Ensure MessageTypes.hpp sees the definition of J9VM_OPT_METHOD_HANDLE

### PR DESCRIPTION
**Pull request by mpirvu**
MessageTypes.hpp file has some code conditional on J9VM_OPT_METHOD_HANDLE.
The definition of J9VM_OPT_METHOD_HANDLE comes from j9cfg.h which needs
to be included in MessageTypes.hpp. Otherwise, the code guarded by
J9VM_OPT_METHOD_HANDLE will be compiled in or not depending on whether
j9cfg.h was included before MessageTypes.hpp in other files, which can lead
to some puzzling behavior. In particular this commit addresses the issue
where J9VM_OPT_METHOD_HANDLE appeared defined in the enum for the various
message types, but undefined for the array with the message names, leading
to some inconsistencies.
This commit solves the issue by including j9cfg.h into MessageTypes.hpp.
This commit also separates the array with the message names into a separate
file: MessageTypes.cpp

Fixes: #14040

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
@dsouzai Could you please review/merge this PR? Thanks

**Comment by mpirvu** [comment]
jenkins compile all jdk8

**Review by dsouzai — APPROVED** [review]

**Comment by dsouzai** [comment]
jenkins test sanity.functional xlinuxjit jdk17

**Comment by mpirvu** [comment]
All tests have passed.

**Pull request merged**
