### PR TITLE
Fix cmdLineTester_criu_keepCheckpoint

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Fix cmdLineTester_criu_keepCheckpoint input arguments
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/14486

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
@llxia @tajila Could you review it? Thanks.

**Comment by LongyuZhang** [comment]
Test Link: hyc_grinder 26119

**Comment by LongyuZhang** [comment]
New test link: hyc_grinder 26447

**Review by llxia — APPROVED** [review]
LGTM

**Review by tajila — APPROVED** [review]

**Pull request merged**
