### PR TITLE
Update disable element

### PR DESCRIPTION
**Pull request by renfeiw**
- use new format of disable

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewers: @llxia @smlambert

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list functional --target _sanity --jdk_version 11 --jdk_impl openj9 --platform x86-64_windows

**Comment by renfeiw** [comment]
internal grinder: Grinder_TKG/1288

**Comment by renfeiw** [comment]
run aqa --sdk_resource nightly --build_list functional --target _sanity.regular --jdk_version 11 --jdk_impl openj9 --platform x86-64_windows

**Comment by renfeiw** [comment]
> @renfeiw Build(s) failed.
> Workflow Run ID: [1016276294](https://github.com/eclipse-openj9/openj9/actions/runs/1016276294)

The failure is unrelated.

**Review by smlambert — APPROVED** [review]
LGTM

**Review by llxia — APPROVED** [review]
LGTM

**Comment by renfeiw** [comment]
run aqa --help

**Pull request merged**
