### PR TITLE
Fix CRIU ghost file test

### PR DESCRIPTION
**Pull request by tajila**
Fixes: https://github.com/eclipse-openj9/openj9/issues/19003

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity plinux jdk21

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk21

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk21

**Comment by pshipton** [comment]
jenkins test sanity alinux jdk21

**Pull request merged**
