### PR TITLE
Refactor SFFF for InterpreterEmulator and record/replay InterpreterEmulator constants

### PR DESCRIPTION
**Pull request by jdmpapin**
This series consists of some initial preparations for expanded static final field folding (SFFF) in `InterpreterEmulator`, primarily in the two ways mentioned in the title. Brief summary of each commit:
- Make `KnownObjectTable::addStableArray()` safe to call on the server: *needed for the following refactoring*
- Refactor static final field folding for reuse in `InterpreterEmulator`: *exposes SFFF logic that will facilitate later guarded/speculative folding in inliner*
- Declare `isFearPointPlacementUnrestricted()`: *names a concept that will be needed later for early guarded folding*
- Delete unused flags in the IL generator held over from multitenancy: *minor cleanup prior to record/replay*
- Record/replay `InterpreterEmulator` constants: *ensures consistency between inliner and IL, which will become more important later with expanded folding, and which will also inform the placement of fear points for guarded folding*

This PR depends on https://github.com/eclipse/omr/pull/7282

### CODE REVIEW

**Comment by jdmpapin** [comment]
@0xdaryl and/or @vijaysun-omr, please review

**Comment by jdmpapin** [comment]
Converted to draft because I need to also record/replay constants from array element loads

**Comment by jdmpapin** [comment]
Rebased to fix the `MINOR_NUMBER` conflict

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk21

**Review by 0xdaryl — APPROVED** [review]

**Comment by knn-k** [comment]
I opened PR #19222 for fixing a build break on macOS.

**Pull request merged**
