### PR TITLE
Stop sharing TR_VirtualGuard between multiple guards with the same BCI

### PR DESCRIPTION
**Pull request by jdmpapin**
These are a few adjustments to remain compatible with OMR after the corresponding OMR commit.

### CODE REVIEW

**Comment by jdmpapin** [comment]
This depends on eclipse/omr#6712, and a coordinated merge will be needed

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11 depends eclipse/omr#6712

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17 depends eclipse/omr#6712

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11,jdk17 depends eclipse/omr#6712

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
