### PR TITLE
Restrict presubmit.yml permissions, delete assign-to-project.yml

### PR DESCRIPTION
**Pull request by pshipton**
https://github.com/ossf/scorecard/blob/c61f6bc297ee71dc4b5f2511144d6c031b946089/docs/checks.md#token-permissions

As determined by https://github.com/ossf/scorecard#scorecard-command-line-interface

https://app.stepsecurity.io/secureworkflow/eclipse-openj9/openj9/presubmit.yml/master?enable=permissions

Delete assign-to-project.yml since it's no longer needed.

### CODE REVIEW

**Comment by pshipton** [comment]
@DanHeidinga can you pls take a look.

@AdamBrousseau @llxia fyi

**Comment by pshipton** [comment]
@tajila @babsingh are you in agreement to delete assign-to-project.yml ?

**Comment by tajila** [comment]
> I'd actually be tempted to delete the assign-to-project.yml action as it's no longer required. 

No concerns with this

**Comment by babsingh** [comment]
No objections on deleting `assign-to-project.yml`.

**Review by DanHeidinga — APPROVED** [review]

**Pull request merged**
