### PR TITLE
Avoid scanning the compilation queue for duplicates

### PR DESCRIPTION
**Pull request by mpirvu**
When a compilation request is added to the compilation queue,
the JIT needs to scan the queue for a duplicate request and
coalesce the two requests into one if a duplicate exists.
In some corner cases the compilation queue can grow to thousand
of entries and scanning the queue for duplicates adds a lot of
overhead. This commit avoids scanning the queue based on the fact
that asynchronous queued entries always have
j9method->extra == J9_JIT_QUEUED_FOR_COMPILATION
This optimization can be disabled by defining the following env var:
TR_DisableSkipSearchingForRequestDuplicates = 1

Partially addresses issue #13807

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
@dsouzai Please review/merge this PR. Thanks!

**Review by dsouzai — APPROVED** [review]
LGTM. Out of curiosity, why can't we set `J9_JIT_QUEUED_FOR_COMPILATION` for methods that have been queued for a sync compile?

**Comment by dsouzai** [comment]
jenkins test sanity.functional xlinux,plinux,zlinux jdk17

**Comment by mpirvu** [comment]
> Out of curiosity, why can't we set J9_JIT_QUEUED_FOR_COMPILATION for methods that have been queued for a sync compile?

For sync compilations we want the application threads to wait for the compilation result. When j9method->extra is negative (J9_JIT_QUEUED_FOR_COMPILATION is -5) the interpreter will not try to queue a compilation, but continue to interpret the method. Thus, we need to leave j9method->extra untouched (at 0); the interpreter sees that the invocation count reached 0 and will call the JIT to compile, and the JIT will block the app thread until the compilation result is available.

**Comment by mpirvu** [comment]
All tests have passed

**Pull request merged**
