### PR TITLE
Suppress inlining of recognized methods without a call node

### PR DESCRIPTION
**Pull request by jdmpapin**
The recognized method can be found based on the call site's  `_initialCalleeMethod`. The only remaining uses of the call node and its treetop are within the cases handling `add`, `subtract`, and `multiply` for `BigInteger` and `BigDecimal`, along with `BigDecimal.valueOf`. All of the other listed methods can be suppressed without a call node. In particular this prevents `TR_EstimateCodeSize` from looking for and later estimating targets for call sites that belong to methods other than the root method, i.e. call sites within methods that have not yet been inlined.

This change is broken into multiple commits for the sake of the readability of the diffs.

There is also a small fix to avoid conflating `StringLatin1.inflate()` with `Integer`/`Long.stringSize()`.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17

**Comment by 0xdaryl** [comment]
Jenkins test sanity aix jdk17

CI failure is infrastructural (git)

**Review by 0xdaryl — APPROVED** [review]

**Review by vijaysun-omr — APPROVED** [review]

**Comment by mpirvu** [comment]
I have measured the DT8 throughput with and without this change and there is no throughput difference between the two configurations.
```
Baseline (no change)
Results for JDK=/home/mpirvu/FullJava11/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk jvmOpts=-Xmx1024m
Throughput      avg=4231.82     min=3949.10     max=4367.10     stdDev=122.8    maxVar=10.58%   confInt=1.68%   samples=10
CompTime        avg=137936.10   min=129018.00   max=172575.00   stdDev=12489.2  maxVar=33.76%   confInt=5.25%   samples=10
Footprint       avg=698063.20   min=689816.00   max=734216.00   stdDev=12936.4  maxVar=6.44%    confInt=1.07%   samples=10

With inliner change
Results for JDK=/home/mpirvu/FullJava11/devin jvmOpts=-Xmx1024m
Throughput      avg=4238.37     min=4196.50     max=4298.60     stdDev=38.8     maxVar=2.43%    confInt=0.53%   samples=10
CompTime        avg=140824.80   min=134362.00   max=175032.00   stdDev=12221.2  maxVar=30.27%   confInt=5.03%   samples=10
Footprint       avg=700290.40   min=695248.00   max=728968.00   stdDev=10163.5  maxVar=4.85%    confInt=0.84%   samples=10
```

**Comment by jdmpapin** [comment]
Is anything else needed before this PR can be merged?

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
