### PR TITLE
Make Artifactory links in buildDescription optional

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Default to true. Set to false for Eclipse Foundation (open) builds, at the request of the Eclipse Foundation.

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk11

**Comment by pshipton** [comment]
Ready now, or should I wait?

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk11

**Comment by pshipton** [comment]
Pls change the commit comment similarly to how I've changed the PR comment, and then update the PR to match if necessary.

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk11

**Comment by AdamBrousseau** [comment]
image

**Comment by mstoodle** [comment]
Please hold off on this pull request. We are seeking clarity on the requirement.

**Pull request closed without merging**
