### PR TITLE
Move value type  jni methods to their own file

### PR DESCRIPTION
**Pull request by theresa-m**
Suggestion from https://github.com/eclipse-openj9/openj9/pull/19911#discussion_r1714084813

### CODE REVIEW

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk17

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by theresa-m** [comment]
@tajila I fixed the error in the Java next build. Can you rerun the tests?

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Pull request merged**
