### PR TITLE
Put select system property names and values in allocated memory

### PR DESCRIPTION
**Pull request by keithc-ca**
Improve `!coreinfo` command to continue despite encountering faults trying to read information from the core file.

Fixes: #17397.

### CODE REVIEW

**Comment by keithc-ca** [comment]
@pshipton ping

**Comment by pshipton** [comment]
jenkins test extended amac jdk11

**Comment by pshipton** [comment]
jenkins compile win jdk8

**Comment by pshipton** [comment]
jenkins test extended amac jdk17

**Comment by pshipton** [comment]
jenkins test extended amac jdk11

**Pull request merged**
