### PR TITLE
Add all vector opcodes except related to masks and shuffles

### PR DESCRIPTION
**Pull request by gita-omr**
Depends on https://github.com/eclipse/omr/pull/6547

### CODE REVIEW

**Comment by gita-omr** [comment]
Rebased

**Comment by gita-omr** [comment]
Rebased.

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk8,jdk18 depends eclipse/omr#6547

**Comment by gita-omr** [comment]
Fixed incompletely resolved conflict.

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk8,jdk18 depends eclipse/omr#6547

**Comment by gita-omr** [comment]
Rebased.

**Comment by gita-omr** [comment]
Added recognition of reductionCoersed intrinsic and rebased.

**Comment by gita-omr** [comment]
Small correction in the latest commit.

**Comment by gita-omr** [comment]
Fixed line ending in the last commit

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11 depends eclipse/omr#6547

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11 depends eclipse/omr#6547

**Comment by 0xdaryl** [comment]
Jenkins test sanity win jdk11 depends eclipse/omr#6547

**Comment by 0xdaryl** [comment]
Jenkins test sanity win jdk11 depends eclipse/omr#6547

**Comment by 0xdaryl** [comment]
Jenkins test sanity win jdk11 depends eclipse/omr#6547

**Comment by 0xdaryl** [comment]
Jenkins test sanity win jdk11 depends eclipse/omr#6547

**Comment by 0xdaryl** [comment]
Jenkins test sanity win,win32 jdk8 depends eclipse/omr#6547

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
