### PR TITLE
Modify the translated PII files in nls folder

### PR DESCRIPTION
**Pull request by panlei080988**
Check in the new translation packages from translators after J182F's TVT pass 1 is completed.

Signed-off-by: Lei Pan pleinb@cn.ibm.com

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
`Error: J9NLS_VM_LOADING_CONSTRAINT_OVERRIDE_VIOLATION Message "betöltési korlátsértés a(z) "%2$.*1$s.%4$.*3$s%6$.*5$s" metódus felülbírálásakor: a(z) "%8$.*7$s@%9$x" betöltő a(z) "%11$.*10$s" osztályban és a(z) "%13$.*12$s@%14$x" betöltő a(z) "%16$.*15$s" osztályban eltérő típusú metódusaláírásokat tartalmaz" in /home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/nls/j9vm/j9vm_hu.nls is different from "loading constraint violation when overriding method "%2$.*1$s.%4$.*3$s%6$.*5$s" during creation of class "%18$.*17$s": loader "%8$.*7$s@%9$x" of class "%11$.*10$s" and loader "%13$.*12$s@%14$x" of class "%16$.*15$s" have different types for the method signature" in /home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/nls/j9vm/j9vm.nls`

**Comment by pshipton** [comment]
`%18$.*17$s` was removed from J9NLS_VM_LOADING_CONSTRAINT_OVERRIDE_VIOLATION in j9vm_hu.nls

**Comment by panlei080988** [comment]
So if this issue is fixed, the pull request will be ready to merge?

**Comment by pshipton** [comment]
> So if this issue is fixed, the pull request will be ready to merge?

yes. Once the PR testing is complete and successful in #2279

**Pull request closed without merging**
