### PR TITLE
Check options on whether or not to inline Thread.currentThread

### PR DESCRIPTION
**Pull request by a7ehuo**
Check option `disableRecognizeCurrentThread` and environment variable `TR_DisableRecognizeCurrentThread` on whether or not to inline `Thread.currentThread`. 

Depends on 
 - [x] https://github.com/eclipse/omr/pull/6950

### CODE REVIEW

**Comment by a7ehuo** [comment]
Removed `WIP`

@0xdaryl Just a reminder. This PR should be merged only after https://github.com/eclipse/omr/pull/6950 is promoted to openj9-omr

**Comment by 0xdaryl** [comment]
jenkins test sanity all jdk17 depends eclipse/omr#6950

**Comment by 0xdaryl** [comment]
The dependent OMR change is merged but has not promoted yet.  @hzongaro (or others) should be able to merge this PR once it does.

**Review by hzongaro — APPROVED** [review]

**Comment by hzongaro** [comment]
As [Annabelle @a7ehuo mentioned](#issuecomment-1513305140), the pull request on which this depends has been merged to OpenJ9-OMR.  All testing has passed.  Merging.

**Pull request merged**
