### PR TITLE
Simplify INL frame build in System.arraycopy

### PR DESCRIPTION
**Pull request by gacholio**
The arraycopy INL builds a frame for many error cases and the value type case which may require allocation. Simplifying the code so the frame is always built early greatly simplifies the code and corrects a problem introduced in #17732 (INL frame build, tear down and rebuild is no longer allowed in general and I missed a case here). It also appear to fix the reported issue, though I'm not entirely sure why.

Also fix a missing frame build in the Thread interrupted INL.

Fixes: #17875

### CODE REVIEW

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by tajila** [comment]
jenkins test sanity alinux64 jdk21

**Comment by gacholio** [comment]
JVMTI failures appear to be either a filesystem issue or a broken exclude mechanism in the testing:
```
12:49:58  java.io.FileNotFoundException: /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_22.xml (No such file or directory)
12:49:58  	at java.base/java.io.FileInputStream.open0(Native Method)
12:49:58  	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
12:49:58  	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
12:49:58  	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
12:49:58  	at com.oti.j9.exclude.ExcludeList.readFrom(ExcludeList.java:71)
12:49:58  	at MainTester.main(MainTester.java:97)
12:49:58  java.lang.NullPointerException
12:49:58  	at java.base/java.io.Reader.<init>(Reader.java:168)
12:49:58  	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:88)
12:49:58  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:468)
12:49:58  	at com.oti.j9.exclude.XMLInterface.parse(XMLInterface.java:138)
12:49:58  	at com.oti.j9.exclude.ExcludeList.readFrom(ExcludeList.java:83)
12:49:58  	at com.oti.j9.exclude.ExcludeList.readFrom(ExcludeList.java:75)
12:49:58  	at MainTester.main(MainTester.java:97)
12:49:58  Exiting...
12:49:58  Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.oti.j9.exclude.ExcludeList.explain(java.io.PrintStream)" because "excludeList" is null
12:49:58  	at MainTester.main(MainTester.java:99)
```

**Comment by gacholio** [comment]
The JCL tests fail for more real-looking reasons, but I doubt it has anything to do with this change (is the VT build just stale and broken?).

**Comment by gacholio** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by gacholio** [comment]
The JCL tests continue to fail (no surprise since the above fix was only for JVMTI tests):

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal/39/tapTestReport/

@tajila @JasonFengJ9 Are these failures expected?

**Comment by JasonFengJ9** [comment]
> FAILED: test_loadMessages_EN

Missed `latest_exclude_22.txt`, just opened
* https://github.com/eclipse-openj9/openj9/pull/17898

**Comment by JasonFengJ9** [comment]
@gacholio Could you try another run?

**Comment by gacholio** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by gacholio** [comment]
Thanks @JasonFengJ9 - it's passing now. @tajila This is ready to go.

**Comment by gacholio** [comment]
@JasonFengJ9 Consider automatically propagating the exclude lists (and whatever else is versioned for the JDK level) when a new release is added. While it may be inaccurate, it's certainly better than failing 100s of tests in each new release.

**Comment by JasonFengJ9** [comment]
Created 
* https://github.com/eclipse-openj9/openj9/issues/17901

**Pull request merged**
