### PR TITLE
Update J9Runtime.hpp

### PR DESCRIPTION
**Pull request by SurajKarmakar1**
Issue #17450  
Fixing typo : Renamed TR_InlinedSiteHastTableEntry to  TR_InlinedSiteHashTableEntry

### CODE REVIEW

**Comment by SurajKarmakar1** [comment]
@hzongaro  Can you review it ?

**Review by hzongaro — CHANGES_REQUESTED** [review]
There are several references to the `struct` using the misspelled name in `runtime/compiler/codegen/J9CodeGenerator.cpp` that will also need to be updated - for instance in the signature of  `processAOTGuardSites`](https://github.com/eclipse-openj9/openj9/blob/f988e1597c5b4b54570192a9db7a437f8874f476/runtime/compiler/codegen/J9CodeGenerator.cpp#L2728)

**Comment by hzongaro** [comment]
Beside the specific review comment that I made, please take a look at [**Contributing to Eclipse OpenJ9**](https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md) for some further guidance.  In particular, please update the first line of your commit to better describe the effect of applying the commit - something along the lines of `Correct typo in name of TR_InlinedSiteHastTableEntry`.  It's also good practice to attempt to build and test OpenJ9 with your changes, to ensure that it will build and operate as expected with your changes.

Also, please read the [`Legal Considerations`](https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md#legal-considerations) of that document.  You will need to complete an Eclipse Foundation Contributor Agreement in order for us to accept and merge your change.

**Comment by SurajKarmakar1** [comment]
@hzongaro  I will sign the contributors agreement and raise a new pull request.

**Comment by hzongaro** [comment]
>  I will sign the contributors agreement and raise a new pull request.

Thanks for responding, @SurajKarmakar1.  I could be mistaken, but I think you should still be able to use the current pull request to contribute your changes once you've signed the contributor's agreement.

**Comment by SurajKarmakar1** [comment]
Will keep it in mind from next time .

**Pull request closed without merging**
