### PR TITLE
Add J9VMThread.publicFlags2 and move flags

### PR DESCRIPTION
**Pull request by EricYangIBM**
Move Java flags to publicFlags2 to make room for more halt flags.
Flags moved:
- J9_PUBLIC_FLAGS_THREAD_WAITING
- J9_PUBLIC_FLAGS_THREAD_BLOCKED
- J9_PUBLIC_FLAGS_THREAD_SLEEPING
- J9_PUBLIC_FLAGS_THREAD_PARKED
- J9_PUBLIC_FLAGS_THREAD_TIMED

Signed-off-by: Eric Yang <eric.yang@ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
What's the status of this item?

**Comment by EricYangIBM** [comment]
I think it is ready for review. Also, Keith has a [question](https://github.com/eclipse-openj9/openj9/pull/13706#discussion_r730975830) that maybe you could answer in more detail

**Comment by keithc-ca** [comment]
> I think it is ready for review. Also, Keith has a [question](https://github.com/eclipse-openj9/openj9/pull/13706#discussion_r730975830) that maybe you could answer in more detail

Yes, I would still like to know why this is needed given there is plenty of room in `publicFlags` for the flags that this moves to `publicFlags`. See https://github.com/eclipse-openj9/openj9/pull/13706#discussion_r730975830.

**Comment by tajila** [comment]
> Yes, I would still like to know why this is needed given there is plenty of room in publicFlags for the flags that this moves to publicFlags. See #13706 (comment).

I initially miscounted the number of available flags, I no longer think it is necessary to move the java thread flags. It is sufficient to simply name the available flags.

**Comment by keithc-ca** [comment]
Some relatively recent improvements to DDR would allow us to instead change the type of `publicFlags` from `UDATA` to `U_64` so 64 bits would be available even on 32-bit platforms.

**Comment by gacholio** [comment]
> Some relatively recent improvements to DDR would allow us to instead change the type of `publicFlags` from `UDATA` to `U_64` so 64 bits would be available even on 32-bit platforms.

The VM already requires that 64-bit atomics are possible on every platform, so this would be a better solution than adding a second field.

**Comment by gacholio** [comment]
Placeholder defines: https://github.com/eclipse-openj9/openj9/pull/13851

**Pull request closed without merging**
