### PR TITLE
Exclude test for aarch and ppc

### PR DESCRIPTION
**Pull request by EricYangIBM**
Crashes in new test specific to these platforms.

See https://github.com/eclipse-openj9/openj9/issues/14014#issuecomment-987012106
Signed-off-by: Eric Yang <eric.yang@ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
Jenkins test sanity alinux jdk8,jdk11,jdk17

**Comment by tajila** [comment]
Jenkins test sanity alinux64 jdk8,jdk11,jdk17

**Comment by tajila** [comment]
Jenkins test sanity alinux64 jdk8,jdk11,jdk17

**Comment by pshipton** [comment]
I don't think we should be merging this. We've already merged a fix https://github.com/eclipse-openj9/openj9/pull/14071. We should be removing the exclude for jdk17 if the problem has been resolved.

Also note that excluding the entire test rather than just rc021 could hide other issues.

**Pull request closed without merging**
