### PR TITLE
Use signed comparisons for Latin-1 encoded indexOf

### PR DESCRIPTION
**Pull request by hzongaro**
The implementations of `String.indexOf` operations cast the target char to a byte if Latin-1 encoded Strings are involved.  The value might be cast to type byte by the caller or in the implementation itself, depending of the version of the JDK involved.  Value Propagation has to ensure that it uses signed byte comparisons if it transforms an `indexOf` involving a known `String`.

Fixes:  #18974

### CODE REVIEW

**Review by jdmpapin — COMMENTED** [review]
These changes LGTM but it looks like the `targetIsConstChar` path is also affected

**Comment by hzongaro** [comment]
> looks like the targetIsConstChar path is also affected

Good catch!

**Comment by jdmpapin** [comment]
```
public class IndexOf {
    public static void main(String[] args) {
        System.out.println(go());
        System.out.println(go());
    }

    public static int go() {
        return "°".indexOf(0xb0);
    }
}
```
This should print 0 twice, but the second result is -1 instead when run with Java 11 and the following command line:
```
$ java -Xjit:'limit=go,count=1,disableAsyncCompilation,initialOptLevel=warm,inhibitRecompilation,tryToInline={java/lang/String.indexOf*}' IndexOf
```

**Comment by hzongaro** [comment]
@jdmpapin, thanks for your review.  I've added another commit &mdash; 68e8cff0d62ffbd2171142faf6a335451e41a04f &mdash; to handle the `targetIsConstChar` case you pointed out.  I'm running a personal build on that change, just to be sure, but I think it's likely safe enough to ask you to rereview it.

Once you're OK with the changes, I'll squash the commits.

**Review by jdmpapin — APPROVED** [review]
LGTM

I was concerned about what would happen when we transform `String.indexOf()` itself (as opposed to a particular Latin-1 or UTF-16 variant) and the string is compressed. But it turns out that these changes have no effect in that case. When transforming `String.indexOf()`, `is16Bit` is true, so none of the truncation/extension will happen. It sounds wrong for `is16Bit` to be true even for compressed strings, but it works because prior to this change, `is16Bit` was only used in the `knownObject` case, and this method rejects known object constraints that don't refer to arrays. For `String.indexOf()`, if we had a known object constraint (rather than a constant string constraint), then it would refer to a `String`, and we'd refuse to transform. If we want to change this code later on to allow `String.indexOf()` itself to be transformed based on a known object constraint, then I think we'll have to be careful to avoid accidentally engaging these truncations and extensions, since that could cause negative values to be spuriously found in the string. But for now we're good :sweat_smile:

**Comment by jdmpapin** [comment]
Thanks for the update! good to squash

**Comment by hzongaro** [comment]
Squashed the commits into f788c3be29e73f23b74177bd048874967f232931

**Comment by jdmpapin** [comment]
Jenkins test sanity zlinux,alinux64,aix,win,win32 jdk8,jdk11,jdk17,jdk21

Excluding xlinux, plinux, xmac, and amac due to UNB outage

**Comment by jdmpapin** [comment]
I agree those CRIU test failures are unrelated

**Pull request merged**
