### PR TITLE
Reenable all ValueTypeTestsJIT tests

### PR DESCRIPTION
**Pull request by a7ehuo**
Reenable all ValueTypeTestsJIT tests

Fixes: #19708

### CODE REVIEW

**Comment by a7ehuo** [comment]
@hzongaro May I ask you to review this change? Thank you! 

[Tested internally, these tests pass](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkValhalla_j9_sanity.functional_aarch64_linux_valhalla_Personal/40/tapTestReport/) with recent changes.

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

**Comment by hzongaro** [comment]
Jenkins test sanity.functional xlinuxval,alinuxval,zlinuxval,plinuxval,winval,xmacval,aixval jdknext

**Comment by hzongaro** [comment]
[Windows testing](https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_windows_valhalla_Personal/43/) looks like it failed due to an infrastructure problem.

```
10:42:54  ERROR: Cannot delete workspace :Unable to delete 'F:\Users\jenkins\workspace\Build_JDKnext_x86-64_windows_valhalla_Personal\openssl\NUL'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

I'll give it one more try. . . .

Jenkins test sanity.functional winval jdknext

**Comment by hzongaro** [comment]
Windows value type testing failed with the same "Unable to delete" error again.  It looks like the most recent previous attempt in PR #19690 hit the same problem.

Testing was successful on all other platforms.  Merging.

**Pull request merged**
