### PR TITLE
Run VectorAPIExpansion earlier in hot, scorching, and AOT strategies

### PR DESCRIPTION
**Pull request by gita-omr**
- move VectorAPIExpansion as early as possible to allow other optimizations
  to be applied after API calls were scalarized or vectorized(PRE, striding, etc)
- VectorAPIExpansion itself requires PRE to happen, so add loop canonicalization and
  PRE using IfVectorAPI flag
- during cold and warm, VectorAPIExpansion does not always happen anyway, so we
  can treat those as a separate issue.

### CODE REVIEW

**Comment by gita-omr** [comment]
Fixed copyright.

**Comment by gita-omr** [comment]
@jdmpapin @vijaysun-omr could you please take a look? I think this change will speedup things quite a bit and will allow more performance tuning during  the codegen work since there is much less redundant code inside vectorized loops with this change.

**Comment by vijaysun-omr** [comment]
Should loop canonicalization (the opt or the group) also be run prior to the extra pass of PRE etc. with the same conditional IfVcetorAPI flag ? This would create a loop pre-header that could be useful when hoisting expressions from the loop.

**Comment by gita-omr** [comment]
> Should loop canonicalization (the opt or the group) also be run prior to the extra pass of PRE etc. with the same conditional IfVcetorAPI flag ? This would create a loop pre-header that could be useful when hoisting expressions from the loop.

Maybe it's already in the PRE group? I know striding is. I was thinking of taking minimalistic approach for now. This change makes all the right things happen on a simple microbenchmark. But I am sure some refining will be possible/needed.

**Comment by gita-omr** [comment]
Added loopCanonicalizatin pass before PRE, under IfVectorAPI as well.

**Comment by vijaysun-omr** [comment]
jenkins test sanity all jdk8,jdk11

**Comment by vijaysun-omr** [comment]
Please correct typo `strategires` in commit message and PR description

**Comment by jdmpapin** [comment]
> VectorAPIExpansion itself requires PRE to happen

Could you comment on the nature of this requirement? Is it just that opportunities will be missed if PRE hasn't run?

> during hot and warm, VectorAPIExpansion does not always happen anyway, so we
can treat those as a separate issue

The hot strategy is updated in this PR. Did you mean cold?

The vector API-related parts of the warm strategy look similar to the hot and scorching strategies, so I'm not sure what you mean by "does not always happen anyway." Maybe this is related to the lack of PRE below hot?

I'm not sure why `AOTStrategyOpts` are updated when warm is being treated as a separate issue. Come to think of it, I'm not sure whether that strategy is even used for anything. At a glance, it doesn't look like it. @vijaysun-omr, do you know about that?

**Review by jdmpapin — APPROVED** [review]
My questions above are mostly for my information, and these changes look fine regardless of the answers, assuming that that any errors in the commit message/PR title are corrected

**Comment by jdmpapin** [comment]
I don't see the checks from Vijay's previous comment. Trying to launch them again

Jenkins test sanity all jdk8,jdk11

**Comment by vijaysun-omr** [comment]
@jdmpapin Unfortunately, I don't have additional context around `AOTStrategyOpts` (maybe it was used in some context in the past but that is'nt relevant anymore).

**Comment by gita-omr** [comment]
Corrected typos in the commit message(strategies and cold). Thanks for noticing!

**Comment by gita-omr** [comment]
PRE creates more opportunities for Vector API Expansion to happen. I updated the strategies that already include PRE. It is possible that expansion does not happen at cold and warm exactly because they don't have PRE. Generally, I think it's a work in progress and more tuning will be possible in the future.

@jdmpapin hope it answers your questions.

**Comment by jdmpapin** [comment]
Jenkins test sanity all jdk8,jdk11

**Review by vijaysun-omr — APPROVED** [review]

**Comment by knn-k** [comment]
AArch64 build failures today: See #14335

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk8,jdk11

**Comment by jdmpapin** [comment]
Thanks, @knn-k!

**Pull request merged**
