### PR TITLE
Remove build configuration entries for jdk22

### PR DESCRIPTION
**Pull request by keithc-ca**
Builds for Java 22 are not possible since #20286.

### CODE REVIEW

**Comment by pshipton** [comment]
We should update https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy#L69 as well.

**Comment by keithc-ca** [comment]
> We should update https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy#L69 as well.

Done in 5bf6bad287895b50617a1e09bc05be204c41c622.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins compile amac jdk21

**Comment by pshipton** [comment]
The build successfully started, and I stopped it.

**Pull request merged**
