### PR TITLE
AArch64: Implement arraytranslateTRTO255

### PR DESCRIPTION
**Pull request by knn-k**
This commit implements arraytranslateTRTO255 for AArch64.

### CODE REVIEW

**Comment by knn-k** [comment]
This PR depends on https://github.com/eclipse/omr/pull/7499

**Comment by knn-k** [comment]
Jenkins test sanity amac jdk17,jdk21 depends eclipse/omr#7499

**Comment by knn-k** [comment]
I will add support for other arraytranslateTRTO and arraytranslateTROT operations in separate PRs later.

**Comment by knn-k** [comment]
The evaluator is in the OMR side, while the helper function is in the OpenJ9 side.  That is the same as p and x platforms.

**Comment by knn-k** [comment]
PR #20427 adds some functional tests for arraytranslate.

**Comment by knn-k** [comment]
Jenkins test sanity amac,alinux64 jdk17 depends eclipse-omr/omr#7499

**Comment by knn-k** [comment]
Jenkins test sanity.system amac jdk17 depends eclipse-omr/omr#7499

**Comment by knn-k** [comment]
I moved the helper implementation to the PR in the OMR side.
It still requires a coordinated merge.

**Comment by 0xdaryl** [comment]
Jenkins test sanity amac,alinux64 depends eclipse-omr/omr#7499

**Comment by 0xdaryl** [comment]
Jenkins test sanity amac,alinux64 jdk21 depends eclipse-omr/omr#7499

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
