### PR TITLE
Handle EINTR errors in JITServer networking

### PR DESCRIPTION
**Pull request by cjjdespres**
Fixes: #15394
Signed-off-by: Christian Despres <despresc@ibm.com>

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk17

**Comment by mpirvu** [comment]
jenkins test sanity xlinuxjit jdk17

**Pull request merged**
