### PR TITLE
Fix use of Thread.resume(), stop(), suspend() in tests for jdk20

### PR DESCRIPTION
**Pull request by pshipton**
Tested in grinders
jdk20: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1476/
jdk11: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1477

Fixes https://github.com/eclipse-openj9/openj9/issues/16213

### CODE REVIEW

**Comment by keithc-ca** [comment]
The grinders were run on 03a6ab99488cfb976c10ce8b9500426ae9a25364 which differs only cosmetically from the latest commit here.

**Comment by keithc-ca** [comment]
Jenkins compile amac jdk17,jdknext

**Comment by pshipton** [comment]
Afaik the compiles won't build these tests, not sure what use they are. Started a grinder on jdk8, just in case there is something incompatible with that version.

https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1479/

**Comment by keithc-ca** [comment]
That grinder didn't help: it tested Java 8 and consumed fd7e4b9412846fae2f90f3504868bde5690b9214 which predates this change.

**Review by keithc-ca — APPROVED** [review]

**Comment by pshipton** [comment]
Proper grinder, which passed https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1482

**Pull request merged**
