### PR TITLE
Use playlist.xml to exclude test in VT standard build

### PR DESCRIPTION
**Pull request by hangshao0**
issue #12878

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
The tests are extended.functional in vt standard build.

**Comment by llxia** [comment]
Jenkins test extended alinuxvalst jdknext

**Comment by hangshao0** [comment]
The tests are not running, however, the job failed as:

```
===============================================
    GCRetransformTest
    Tests run: 0, Failures: 0, Skips: 0
===============================================


===============================================
JavaAgentTest
Total tests run: 0, Failures: 0, Skips: 0
===============================================

[TestNG] No tests found. Nothing was run

...
...
TestGCClassWithStaticRetransformInGencon_0_FAILED
```

Should I disable them in the playlist.xml instead ?

**Comment by hangshao0** [comment]
The tests are not running, however, the job failed as:

```
===============================================
    GCRetransformTest
    Tests run: 0, Failures: 0, Skips: 0
===============================================


===============================================
JavaAgentTest
Total tests run: 0, Failures: 0, Skips: 0
===============================================

[TestNG] No tests found. Nothing was run

...
...
TestGCClassWithStaticRetransformInGencon_0_FAILED
```

Should I disable them in the playlist.xml instead ?

**Comment by llxia** [comment]
Yes, if they are the only tests, we should exclude them from the playlist. Otherwise, it will be treated as a failure.

**Comment by hangshao0** [comment]
> we should exclude them from the playlist

Change updated.

**Comment by hangshao0** [comment]
The tests are excluded as expected. The failures in the PR build are not related to this change.

**Review by llxia — APPROVED** [review]

**Pull request merged**
