### PR TITLE
Replace x86/libffi with the latest version in GitHub

### PR DESCRIPTION
**Pull request by ChengJin01**
The changes entirely replace the outdated x86/libffi
with the latest version at
https://github.com/libffi/libffi/tree/master/src/x86
so as to better support the struct work in JEP389
(Foreign Linker API) which is part of the Panama
project.

The latest committed SHA: 5651bea284ad0822eafe768e3443c2f4d7da2c8f

Fixes: #12787

Signed-off-by: Cheng Jin <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
The changes replace whole `x86` directory with the latest version at https://github.com/libffi/libffi/tree/master/src/x86
except the files (`ffiw32.c` & `win32.S`) for Windows/32bit from the existing directory (`ffi.c` is renamed to `ffiw32.c`)

The changes also include the updated header files (`ffi.h`) at libffi/preconf based on the latest one at https://github.com/libffi/libffi/blob/master/include/ffi.h.in
Changes in Cmake & UMA are based on the setting at https://github.com/libffi/libffi/blob/master/configure.host
and https://github.com/libffi/libffi/blob/master/generate-darwin-source-and-headers.py

**Comment by ChengJin01** [comment]
Verified on internal builds and open source builds

Reviewer: @dnakamura, @pshipton, @tajila 
FYI: @gacholio, @DanHeidinga, @mstoodle

**Comment by pshipton** [comment]
Setting as draft since this needs an Eclipse CQ before it can be merged.

**Comment by pshipton** [comment]
CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23466

**Comment by pshipton** [comment]
Are the files with IBM copyright added modified from the libffi originals? For anything unmodified there should not be an IBM copyright added. It's ok if the copyright check fails. 

Please record the SHA from which the libffi code was obtained.

**Comment by AdamBrousseau** [comment]
>anything unmodified there should not be an IBM copyright

You can add the files here explicitly if they don't need an IBM Copyright.
https://github.com/eclipse-openj9/openj9/blob/master/.copyrightignore

However, that does run the risk of the file being ignored if it is ever modified and needs a copyright.

**Comment by ChengJin01** [comment]
Remove IBM copyright from all unmodified fifes as suggested above.

**Comment by pshipton** [comment]
> You can add the files here explicitly if they don't need an IBM Copyright.
> However, that does run the risk of the file being ignored if it is ever modified and needs a copyright.

Yes, we don't want to do this. It's ok for the copyright check to fail on this initial contribution, but not if the files are modified in the future.

**Comment by pshipton** [comment]
Looking at the last force push, too much was removed from some of the files. The file should be the same as in the libffi git, with no IBM copyright added. The libffi copyright and license should not be removed.
https://github.com/eclipse-openj9/openj9/compare/5825fe9993233cac984ab2e87d54d22e73d34918..183e8296dd1e075a37bee27812c12b1fde20abe1

**Comment by ChengJin01** [comment]
> 
> 
> Looking at the last force push, too much was removed from some of the files. The file should be the same as in the libffi git, with no IBM copyright added. The libffi copyright and license should not be removed.
> https://github.com/eclipse-openj9/openj9/compare/5825fe9993233cac984ab2e87d54d22e73d34918..183e8296dd1e075a37bee27812c12b1fde20abe1

The libffi copyright and license of these files mentioned above was added by myself based on the commit date in the x86/libffi.
The original file has nothing in there except the code . e.g. https://github.com/libffi/libffi/blob/master/src/x86/win64.S
```
#ifdef __x86_64__
#define LIBFFI_ASM
#include <fficonfig.h>
#include <ffi.h>
#include <ffi_cfi.h>
#include "asmnames.h"

#if defined(HAVE_AS_CFI_PSEUDO_OP)
        .cfi_sections   .debug_frame
#endif

```

**Comment by ChengJin01** [comment]
> Please record the SHA from which the libffi code was obtained.

Added the latest SHA to the commit message as suggested above.

**Comment by pshipton** [comment]
jenkins test sanity,sanity.openjdk win,win32,xlinux,osx jdk8,jdk16

**Comment by pshipton** [comment]
An internal build is having problems with this change, on vmfarm see jobs_by_status.php?build_id=7151&status=PROLOGUE_FAILED&categories=17

**Comment by ChengJin01** [comment]
> An internal build is having problems with this change on xlinux 32-bit, on vmfarm see jobs_by_status.php?build_id=7151&status=PROLOGUE_FAILED&categories=17

I will double-check by adding back the original files on Linux/32bit to see how it goes as we don't use it in JEP389.

**Comment by ChengJin01** [comment]
I already stored the original files on 32bit which seems working in internal builds:
1) Linux/32bit includes `ffi.c`, `sysv.S`, `win32.S`
2) Windows/32bit includes `ffi.c` and `win32.S`

In addition,  I will need double-check a new fix committed at https://github.com/libffi/libffi/commit/5651bea284ad0822eafe768e3443c2f4d7da2c8f which is intended for the nested float struct to see whether it works good as expected to avoid create another PR for this fix.

**Comment by ChengJin01** [comment]
The latest changes with the new fix in `ffi64.c` were verified in internal & open source builds which works good as expected.

**Comment by pshipton** [comment]
Is this ready to move out of draft? The CQ was approved.

**Comment by ChengJin01** [comment]
> 
> 
> Is this ready to move out of draft? The CQ was approved.

The change is ready for merging.

**Comment by pshipton** [comment]
jenkins test sanity all jdk8

**Comment by pshipton** [comment]
jenkins test sanity all jdk11

**Comment by pshipton** [comment]
no problems found in internal testing (build 8708)

**Comment by pshipton** [comment]
@ChengJin01 if you want to have this merged then it needs to be ready for review and not in draft.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
