### PR TITLE
Fix build error on big endian platforms

### PR DESCRIPTION
**Pull request by a7ehuo**
Fix build error on big endian platforms

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Review by hzongaro — APPROVED** [review]
I think the changes look good.

Although the build problems showed up on big-endian platforms, I think that's just a coincidence because of the compilers that happen to be used to build on those platforms.  I would suggest changing the commit comment to reflect what you actually needed to change and why.

**Comment by 0xdaryl** [comment]
Thanks for fixing Annabelle.  I agree with Henry's request too.

**Comment by a7ehuo** [comment]
> I would suggest changing the commit comment to reflect what you actually needed to change and why.
updated the commit message in 420d199

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdknext

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux jdknext

**Comment by 0xdaryl** [comment]
CI failures on x86 Linux are infrastructural.  Since other Linux jobs with g++ succeeded I will merge.

**Pull request merged**
