### PR TITLE
Fix memory leaks when using fast client session destruction

### PR DESCRIPTION
**Pull request by AlexeyKhrabrov**
PR #12458 introduced fast client session destruction: most of the destructor code can be skipped since most data in the client session is allocated with the per-client persistent allocator and is freed in bulk when the per-client allocator is destroyed. Any objects allocated globally (not with the per-client allocator) still need to be freed. This PR fixes missing deallocation of `std::string` objects in the client session (which are allocated using the global `malloc` heap).

This is a temporary fix until we get rid of `malloc` usage in client session data.

### CODE REVIEW

**Comment by AlexeyKhrabrov** [comment]
@mpirvu This PR fixes the memory leak discussed in #12659 (which currently only affects AOT cache).

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity xlinuxjit jdk11

**Comment by mpirvu** [comment]
Build failed due to infra.
jenkins test sanity xlinuxjit jdk11

**Pull request merged**
