### PR TITLE
fix schema error in playlist.xml

### PR DESCRIPTION
**Pull request by OscarQQ**
[ci skip]

Signed-off-by: Yixin Qian <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
Grinder/15294/

**Comment by llxia** [comment]
@renfeiw  Could you review this? Thanks

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by OscarQQ** [comment]
`<tag>test:largepages</tag> ` at test/functional/JLM_Tests/playlist.xml was added in the initial commit. There was no history to trace. Since we do not support it, remove it in this PR.

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
https://ci.eclipse.org/openj9/job/Grinder/1799/

**Pull request merged**
