### PR TITLE
CRIU ensures the test thread prints pass/fail messages

### PR DESCRIPTION
**Pull request by JasonFengJ9**
`CRIU` ensures the test thread prints `pass/fail` messages

close https://github.com/eclipse-openj9/openj9/issues/17909

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
jenkins test sanity zlinux jdk21

**Comment by JasonFengJ9** [comment]
Looking at the test failure - https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_Personal/67/tapResults/
Some of them seem similar with 
* https://github.com/eclipse-openj9/openj9/issues/18456

**Comment by JasonFengJ9** [comment]
The PR test failures have been addressed in separate PRs
* https://github.com/eclipse-openj9/openj9/pull/18509
* https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/69
* https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/64

@tajila Could you please re-launch the PR build?

**Comment by tajila** [comment]
jenkins test sanity zlinux jdk21

**Pull request merged**
