### PR TITLE
Add missing value type check before zero the lockword

### PR DESCRIPTION
**Pull request by hangshao0**

### CODE REVIEW

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
@dmitripivkine please review these changes

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity,extended plinuxval jdknext

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Review by dmitripivkine — APPROVED** [review]

**Comment by hangshao0** [comment]
The failure of PR build https://openj9-jenkins.osuosl.org/job/Test_openjdkValhalla_j9_sanity.functional_ppc64le_linux_valhalla_Personal/24 is a know issue:

- https://github.com/eclipse-openj9/openj9/issues/17359

**Pull request merged**
