### PR TITLE
Add a flag to return 0 if only one data point has been recorded

### PR DESCRIPTION
**Pull request by thallium**
Currently, getProcessCpuLoad() and getSystemCpuLoad() return -1 if only one data point has been recorded. A compatibility flag -XX:[+/-]CpuLoadCompatibility is added to match the behaviour of the RI, which is to return 0.

Fixes: https://github.com/eclipse-openj9/openj9/issues/13389
Related: https://github.com/eclipse/omr/pull/7189
Related: https://github.com/eclipse-openj9/openj9/issues/18634

### CODE REVIEW

**Comment by thallium** [comment]
FYI @tajila @pshipton

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
@thallium don't forget to open the docs issue 
https://github.com/eclipse-openj9/openj9-docs/issues/

**Comment by pshipton** [comment]
@TobiAjila did you want this in 0.43?

**Comment by tajila** [comment]
> @TobiAjila did you want this in 0.43?

Yes, lets add to 0.43

**Comment by thallium** [comment]
Docs issue has been open https://github.com/eclipse-openj9/openj9-docs/issues/1232. FYI @pshipton @tajila

**Comment by pshipton** [comment]
@thallium pls cherry pick the commit and create a PR on https://github.com/eclipse-openj9/openj9/tree/v0.43.0-release

**Comment by thallium** [comment]
Just found that a comment wasn't updated correctly and there's a minor formatting issue. I will open a PR to fix them first.

**Pull request merged**
