### PR TITLE
Compile Windows jdk11 with VS2019

### PR DESCRIPTION
**Pull request by pshipton**
Issue https://github.com/eclipse-openj9/openj9/issues/15582
See also
https://github.com/adoptium/temurin-build/pull/2992
https://github.com/ibmruntimes/temurin-build/pull/25

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile win jdk8,jdk11

**Comment by pshipton** [comment]
jenkins test sanity,extended,sanity.openjdk win jdk11

**Comment by pshipton** [comment]
jenkins test sanity,extended,sanity.openjdk,sanity.system win jdk11

**Comment by pshipton** [comment]
jdk11 testing
https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/2599/
and the rebuild [Build Status](https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_x86-64_windows_Personal_testList_1/6/)

**Review by AdamBrousseau — APPROVED** [review]

**Pull request merged**
