### PR TITLE
Remove UNB Artifactory from builds

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Hopefully temporary until the machines at
UNB are restored.

Infra Issue 9282

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
jenkins compile alinux jdk11

**Comment by AdamBrousseau** [comment]
Jenkins line endings check

**Comment by AdamBrousseau** [comment]
Actually I'm not sure this unblocks anything. The only platform that resides at both UNB and another site is ppc64le however all the compile machines are at UNB.
So builds should already work on alinux, zlinux, aix and windows without this. Even with this, plinux compiles are still blocked. We can only launch plinux testing.

**Comment by AdamBrousseau** [comment]
jenkins compile amac jdk11

**Comment by pshipton** [comment]
I had disabled all the amac build machines. Re-enabled https://openj9-jenkins.osuosl.org/computer/mac11%2Daarch64%2D1/

**Comment by pshipton** [comment]
Is the intent to remove the ci.role.test label from the unb amac machines?

**Comment by AdamBrousseau** [comment]
Well, we could allow test and see if the network can handle it? If not we can remove the test labels and tell  devs that Mac will be compile only for now.

**Comment by pshipton** [comment]
> Why does this only fix mac?

Ah, because plinux and xlinux machines are still down. But perhaps we can get xlinux going again since it came up before?

**Comment by pshipton** [comment]
Not all xlinux is down, only some of it. We have build machines up.

**Comment by AdamBrousseau** [comment]
Right sorry, this would unblock xlinux as well.

**Comment by AdamBrousseau** [comment]
Done

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
@AdamBrousseau some other change is needed, the testing can't run.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_mac_OpenJDK17/47
```
17:01:21  Redirecting OSU artifactory artifactory downloads from UNB artifactory mirror
17:01:21  Original parameter: https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_aarch64_mac_OpenJDK17/56/OpenJ9-JDK17-aarch64_mac-20240503-064518.tar.gz
17:01:21  Modified to UNB mirror: https://192.168.10.216/artifactory/ci-openj9/Build_JDK17_aarch64_mac_OpenJDK17/56/OpenJ9-JDK17-aarch64_mac-20240503-064518.tar.gz
17:02:44  curl: (7) Failed to connect to openj9-artifactory.osuosl.org port 443: Operation timed out
```

**Pull request merged**
