### PR TITLE
Tweak inliner to improve compilation overhead

### PR DESCRIPTION
**Pull request by mpirvu**
To revert (more or less) to the old behavior, define the following environment variable: `TR_NodeEstimateNumerator=1`

The default value for the above knob is 4 for warm compilations and 1 for compilations performed at hot (or above) opt level.

### CODE REVIEW

**Comment by mpirvu** [comment]
jenkins test sanity all jdk17

**Comment by mpirvu** [comment]
xlinux had 14 errors in CRIU tests, errors that likely have nothing to do with this PR

**Comment by mpirvu** [comment]
Attn : @vijaysun-omr

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Failures appear to be unrelated to this change to inlining heuristic. Merging.

**Pull request merged**
