### PR TITLE
Preserve entire contents of XMM registers across helper calls on X

### PR DESCRIPTION
**Pull request by gacholio**
See issue for details.

Fixes: #12585

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins copyright check

**Comment by gacholio** [comment]
jenkins copyright check

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
@0xdaryl Please review these changes

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by gacholio** [comment]
@0xdaryl Please review.

**Comment by 0xdaryl** [comment]
I'll take a deeper look at this tomorrow.

This particular PR covers the XMM (128-bit) and not the YMM (256-bit) or ZMM (512-bit) registers.  Presumably, this preservation technique can be expanded to include those other registers when we need them (should be within a few months).  The wrinkle there is that we'll need to check for AVX support (for YMM) and AVX-512 support (for ZMM) on the target processor before preserving those registers.  Is that possible to do in this runtime code, or how would we handle those processor capability checks?

**Comment by gacholio** [comment]
We would do it in the same way as the other platforms - with the bit.

I've never heard of those other registers, so if that's going to be a requirement, perhaps this PR is pointless.

**Comment by gacholio** [comment]
I think the overall structure remains correct here, so perhaps it's just a matter of adding the runtime check in the `movdqa` case.

**Comment by tajila** [comment]
@0xdaryl What is the timeframe for adding YMM/ZMM support in the JIT? I'm wondering if we can start with XMM first since thats these are the only vector registers the JIT currently uses. And incrementally add YMM/ZMM as the JIT starts to leverage those.

**Comment by fjeremic** [comment]
> @0xdaryl What is the timeframe for adding YMM/ZMM support in the JIT? I'm wondering if we can start with XMM first since thats these are the only vector registers the JIT currently uses. And incrementally add YMM/ZMM as the JIT starts to leverage those.

I believe @BradleyWood is working on this so tagging him here. FYI.

**Comment by BradleyWood** [comment]
I am working on the YMM/ZMM support. Don't have a timeline as of yet.

**Comment by tajila** [comment]
@0xdaryl Based on Brad's comment, do you have any objections to enabling the XMM register saves now, and adding YMM ZMM support once the JIT begins using it?

**Review by 0xdaryl — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity xlinux jdk16,jdk11

**Pull request merged**
