### PR TITLE
Set thread blocked flag before triggering JVMTI Monitor Contended Enter

### PR DESCRIPTION
**Pull request by thallium**
Fixes https://github.com/eclipse-openj9/openj9/issues/16685

### CODE REVIEW

**Comment by thallium** [comment]
@fengxue-IS FYI

**Review by fengxue-IS — APPROVED** [review]
lgtm, can you add a short explanation for this change in the original issue (ie why test failed, how this change addresses the issue).

**Comment by babsingh** [comment]
jenkins test sanity alinux64 jdk19

**Comment by babsingh** [comment]
jenkins test sanity win jdk19

**Comment by babsingh** [comment]
jenkins test sanity xlinux jdk8

**Review by babsingh — APPROVED** [review]

**Pull request merged**
