### PR TITLE
Handle find virtual of interface methods

### PR DESCRIPTION
**Pull request by tajila**
We need to handle cases like this:
```
    interface Intf { void ig1(); void ig2(); void ig3(); void ig4();
void m1(); }
    abstract static class Super implements Intf { public abstract void
m2(); public int f2; }
    abstract static class Sub extends Super { }

    ...

    MethodHandle m1 = lookup().findVirtual(Sub.class, "m1",
methodType(void.class));
```

This PR adds a check to linkToVirtual to check if the target method is
an interface method, if so it does a itable lookup.

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
@DanHeidinga please review these changes

**Review by DanHeidinga — APPROVED** [review]
looks reasonable

**Comment by DanHeidinga** [comment]
Jenkins test sanity win,linux jdk16

**Comment by DanHeidinga** [comment]
Jenkins test sanity win,xlinux jdk16

**Pull request merged**
