### PR TITLE
Refactor classesOnHeap

### PR DESCRIPTION
**Pull request by singh264**
I think the conditional statements in the caller
methods of the classesOnHeap method are refactored
based on the return value of the classesOnHeap method
that is always true.

Closes: #11791
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com

### CODE REVIEW

**Comment by singh264** [comment]
@ymanton

**Review by ymanton — CHANGES_REQUESTED** [review]
Content looks good on first pass. Please squash to a single commit and provide a meaningful commit message.

**Review by ymanton — APPROVED** [review]
LGTM.

**Comment by ymanton** [comment]
Jenkins test sanity.functional all jdk11

**Comment by singh264** [comment]
I think the pull request could be merged.

**Pull request merged**
