### PR TITLE
[JDK20/21] Add support for JVMTI Local Variable functions

### PR DESCRIPTION
**Pull request by babsingh**
For suspended virtual threads, the JVMTI spec only allows to set the
value of a local variable in the topmost frame. Otherwise, it expects
JVMTI_ERROR_OPAQUE_FRAME to be returned.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
@gacholio Requesting your review.

This behaviour is mentioned implicitly in the JVMTI spec:
- JDK20: https://docs.oracle.com/en/java/javase/20/docs/specs/jvmti.html#local
- JDK21: https://download.java.net/java/early_access/jdk21/docs/specs/jvmti.html#local

>  The SetLocalXXX functions may be used to set the value of a local variable in the topmost frame of a virtual thread suspended at an event. 

>  JVMTI_ERROR_OPAQUE_FRAME: The thread is a suspended virtual thread and the implementation does not support           setting the value of locals in the frame of the given depth. See Local Variables.

**Comment by gacholio** [comment]
To me, that says setting in the topmost frame is required, setting in other frames is allowed if the implementation can support it.

**Comment by gacholio** [comment]
In fact, the spec says it:
```
 An implementation may support setting locals in other cases.
```

**Comment by gacholio** [comment]
Converting to draft while a test is challenged.

**Comment by babsingh** [comment]
Closing: The tests were updated accordingly. So, this fix is no longer needed.

**Pull request closed without merging**
