### PR TITLE
Include missing header file Bytes.hpp

### PR DESCRIPTION
**Pull request by mpirvu**

### CODE REVIEW

**Comment by mpirvu** [comment]
jenkins compile plinux,xlinux,zlinux jdk8

**Comment by mpirvu** [comment]
@dsouzai Could you please review and merge this PR when the tests pass? Thanks

**Review by dsouzai — APPROVED** [review]

**Comment by mpirvu** [comment]
jenkins compile plinux,xlinux,zlinux jdk8

**Comment by mpirvu** [comment]
@douzai Tests have passed. Ready for merging.

**Pull request merged**
