### PR TITLE
Cleanup CompilationThread.cpp

### PR DESCRIPTION
**Pull request by singh264**
Remove dead code.

Closes: #12498
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com

### CODE REVIEW

**Comment by singh264** [comment]
@ymanton @fjeremic @dsouzai requesting feedback

**Review by dsouzai — APPROVED** [review]
LGTM

**Comment by dsouzai** [comment]
jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
mac build failed due to infra issues. Merging.

**Pull request merged**
