### PR TITLE
Remove unused frontend function isString(uintptr_t objectPointer)

### PR DESCRIPTION
**Pull request by mpirvu**
Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
Jenkins compile all jdk8

**Comment by mpirvu** [comment]
@dsouzai Could you please review/merge this PR? Thanks

**Review by dsouzai — APPROVED** [review]

**Comment by dsouzai** [comment]
jenkins test sanity.functional xlinux,plinux,zlinux,xlinuxjit jdk17

**Comment by mpirvu** [comment]
Rebased and updated copyrights

**Comment by mpirvu** [comment]
jenkins test sanity.functional xlinux,plinux,zlinux,xlinuxjit jdk17

**Comment by mpirvu** [comment]
Tests passed except the JITServer one, but the "TAP Extended Test Results" don't show any error.

**Comment by dsouzai** [comment]
The reason for the failure is because https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_jit_Personal_testList_0/20/console timed out :

```
17:35:34  if [ $? -eq 0 ] ; then echo ""; echo "cmdLineTester_jvmtitests_debug_4""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_jit_Personal_testList_0/aqa-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_jit_Personal_testList_0/aqa-tests/TKG/../TKG/output_16426278197783/cmdLineTester_jvmtitests_debug_4"; else echo ""; echo "cmdLineTester_jvmtitests_debug_4""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_jit_Personal_testList_0/aqa-tests/TKG/../TKG/output_16426278197783/TestTargetResult";
Cancelling nested steps due to timeout
02:11:48  Sending interrupt signal to process
```

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
