### PR TITLE
Add criu vmstates

### PR DESCRIPTION
**Pull request by tajila**
Add criu vmstates

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
Jenkins test sanity xlinuxcriu jdk17

**Comment by tajila** [comment]
Jenkins test sanity xlinuxcriu jdk17

**Comment by tajila** [comment]
Jenkins test sanity xlinuxcriu jdk17

**Comment by tajila** [comment]
@gacholio please review

**Comment by tajila** [comment]
White space changes, build is here --> https://openj9-jenkins.osuosl.org/view/Pull%20Requests/job/PullRequest-OpenJ9/2735/

**Comment by gacholio** [comment]
I think it would make sense to use the VMHelpers implementation in the interpreter.

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins compile win jdk8

**Comment by gacholio** [comment]
jenkins test sanity xlinuxcriu jdk11

**Comment by tajila** [comment]
jenkins compile win jdk8

**Comment by tajila** [comment]
jenkins test sanity xlinuxcriu jdk11

**Pull request merged**
