### PR TITLE
Set default VARIABLE_FILE parameter

### PR DESCRIPTION
**Pull request by fengxue-IS**
infra issue 6519

### CODE REVIEW

**Comment by fengxue-IS** [comment]
FYI @AdamBrousseau

**Comment by AdamBrousseau** [comment]
jenkins compile amac jdk11

**Comment by AdamBrousseau** [comment]
Test without change shows variable file is not getting processed is all 3 VENDOR args are not passed. We typically only pass repo and branch for the openj9 release builds.
https://openj9-jenkins.osuosl.org/job/Pipeline-Release-0.40.0-Build11/13/
Child jobs show the openssl version passed in get source args is 3.10* which is the latest from defaults.yml.
With this change,
https://openj9-jenkins.osuosl.org/job/Pipeline-Release-0.40.0-Build11/15/
Shows the proper openssl version 1.1.1v from the 40-release branch defaults.yml is being passed.
eg
https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK11_ppc64le_linux/1880/parameters/

**Review by AdamBrousseau — APPROVED** [review]
Looks good. Thanks for the fix.

**Pull request merged**
