### PR TITLE
[JDK19+] Fix JVMTI GetAllStackTraces

### PR DESCRIPTION
**Pull request by babsingh**
JVMTI GetAllStackTraces only tracks live platform threads.

This change correctly and consistently derives the threadObject
from J9VMThread->carrierThreadObject in GetAllStackTraces for JDK19+.

Currently, J9VMThread->threadObject is used in some places, which is
incorrect since it can also point to a virtual thread.

Related: #17868

### CODE REVIEW

**Comment by babsingh** [comment]
@gacholio Requesting your review.

**Comment by babsingh** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/25 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/638 require this PR to be merged first.

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins test sanity win jdk8

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk21

**Pull request merged**
