### PR TITLE
All 64k pagesize tests fix

### PR DESCRIPTION
**Pull request by singh264**
Closes: #11104 #12706
Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile aix jdk8,jdk11 depends eclipse/omr#6032

**Comment by pshipton** [comment]
jenkins compile aix jdk8,jdk11

**Comment by pshipton** [comment]
pltest is passing with the OMR change:
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/14/
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/15/

**Comment by singh264** [comment]
@pshipton @ymanton @0xdaryl @babsingh these changes depend on https://github.com/eclipse/omr/pull/6032

**Comment by pshipton** [comment]
I'm setting this to draft until the OMR change is merged.

**Review by babsingh — APPROVED** [review]

**Review by pshipton — APPROVED** [review]

**Pull request merged**
