### PR TITLE
Replace forceUnresolvedDispatch() with isResolved*DispatchGuaranteed()

### LINKED ISSUE #14124: jdk18+ crash <unknown>+0x0
This is using the latest source for everything, including OpenJDK. Happens quite often, I haven't been able to get a clean test run. Three tries and always 1/2 of the child jobs crashes.

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_1/16/ - ub18-390-2
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_1/16/functional_test_output.tar.gz

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/17/ - ub18-390-2
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/17/functional_test_output.tar.gz

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/18 - rh7-390-4
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/18/functional_test_output.tar.gz
```
10:52:10       [exec] Unhandled exception
10:52:10       [exec] Type=Segmentation error vmState=0x00000000
10:52:10       [exec] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=7cf59e70 Signal_Code=00000001
10:52:10       [exec] Handler1=000003FF991C8578 Handler2=000003FF990B2260 InaccessibleAddress=0006000000000000
10:52:10       [exec] gpr0=FFFFFFFFFFFFFAB6 gpr1=00000000A68F9488 gpr2=00000000000F2A00 gpr3=00000000000F5600
10:52:10       [exec] gpr4=000003FF8D1A2072 gpr5=0000000000158028 gpr6=00000000000F5600 gpr7=0000000000000008
10:52:10       [exec] gpr8=0000000000000001 gpr9=00000000A68F9488 gpr10=00000000000F2A00 gpr11=000003FF71FF4630
10:52:10       [exec] gpr12=00000000000F5600 gpr13=0000000000069700 gpr14=000003FF71FF43D6 gpr15=000003FF99FFE318
10:52:10       [exec] psw=0006000000000000 mask=0705200180000000 fpc=0008fe00 bea=000003FF71FF43D4
10:52:10       [exec] fpr0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr1 489dec8000000000 (f: 0.000000, d: 6.516833e+41)
10:52:10       [exec] fpr2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr3 3b9a00c100000000 (f: 0.000000, d: 1.376584e-21)
10:52:10       [exec] fpr4 489dec8000000000 (f: 0.000000, d: 6.516833e+41)
10:52:10       [exec] fpr5 3e9249ac47ae147b (f: 1202590848.000000, d: 2.725092e-07)
10:52:10       [exec] fpr6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr7 3e3a340000000000 (f: 0.000000, d: 6.100890e-09)
10:52:10       [exec] fpr8 000000002ba3e130 (f: 732160320.000000, d: 3.617353e-315)
10:52:10       [exec] fpr9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr10 000000002ba3e488 (f: 732161152.000000, d: 3.617357e-315)
10:52:10       [exec] fpr11 0000000004b538f0 (f: 78985456.000000, d: 3.902400e-316)
10:52:10       [exec] fpr12 000003ff942f91e8 (f: 2486145536.000000, d: 2.172030e-311)
10:52:10       [exec] fpr13 0000000004b538d0 (f: 78985424.000000, d: 3.902398e-316)
10:52:10       [exec] fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr15 000003ffbc0fe250 (f: 3155157504.000000, d: 2.172361e-311)
10:52:10       [exec] Target=2_90_20211209_159 (Linux 3.10.0-1160.25.1.el7.s390x)
10:52:10       [exec] CPU=s390x (4 logical CPUs) (0x1ec1b5000 RAM)
10:52:10       [exec] ----------- Stack Backtrace -----------
10:52:10       [exec] (0x000003FF990AE84A [libj9prt29.so+0x2e84a])
10:52:10       [exec] (0x000003FF990B33CE [libj9prt29.so+0x333ce])
10:52:10       [exec] (0x000003FF990AE8F4 [libj9prt29.so+0x2e8f4])
10:52:10       [exec] (0x000003FF990AEA0E [libj9prt29.so+0x2ea0e])
10:52:10       [exec] (0x000003FF990B33CE [libj9prt29.so+0x333ce])
10:52:10       [exec] (0x000003FF990AE6F0 [libj9prt29.so+0x2e6f0])
10:52:10       [exec] (0x000003FF991C84AE [libj9vm29.so+0x484ae])
10:52:10       [exec] (0x000003FF990B33CE [libj9prt29.so+0x333ce])
10:52:10       [exec] (0x000003FF991C86E4 [libj9vm29.so+0x486e4])
10:52:10       [exec] (0x000003FF990B24E4 [libj9prt29.so+0x324e4])
10:52:10       [exec] (0x000003FF99FFDE90 [<unknown>+0x0])
10:52:10       [exec] ---------------------------------------
```
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/String.format(String.java:4895)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Scanner.scanIdentifier(Scanner.java:952)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Scanner.xscan(Scanner.java:1125)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Scanner.scan(Scanner.java:138)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseName(Parser.java:315)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseMethod(Parser.java:837)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseClassMembers(Parser.java:1728)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseClass(Parser.java:1419)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseFile(Parser.java:1988)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Main.compile(Main.java:255)
5XESTACKTRACE                   (entered lock: org/openjdk/asmtools/jasm/Main@0x000000002BABE608, entry count: 1)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Main.main(Main.java:328)
4XESTACKTRACE                at org/openjdk/asmtools/Main.jasm(Main.java:95)
4XESTACKTRACE                at org/openjdk/asmtools/Main.main(Main.java:55)
```

### LINKED ISSUE #14230: JDK18 DaaLoadTest_daa1_special_5m_FAILED Segmentation error vmState=0x00000000 - Invalid JIT return address 0000000000000010 in 0000010029ACE480
Failure link
------------

From an internal build `job/Test_openjdk18_j9_special.system_ppc64_aix_Personal/1/tapResults/`(`paix821`):
```
15:19:17  openjdk version "18-internal" 2022-03-22
15:19:17  OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDK18ppc64aixPersonal)
15:19:17  Eclipse OpenJ9 VM (build master-3cf0509e7e0, JRE 18 AIX ppc64-64-Bit Compressed References 20220105_1 (JIT enabled, AOT enabled)
15:19:17  OpenJ9   - 3cf0509e7e0
15:19:17  OMR      - b5643d01920
15:19:17  JCL      - 03a0ab353e1 based on jdk-18+29)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=special.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK18_ppc64_aix_Personal%2F1%2FOpenJ9-JDK18-ppc64_aix-20220105-143607.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK18_ppc64_aix_Personal%2F1%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=18&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk18.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=3cf0509e7e001405e2caaa8126282833b542ff40&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=5&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test DaaLoadTest_daa1_special_5m_4 ...
===============================================
DaaLoadTest_daa1_special_5m_4 Start Time: Wed Jan  5 16:46:36 2022 Epoch Time (ms): 1641419196411
variation: Mode112
JVM_OPTIONS:  -Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs 

DLT 16:46:56.447 - Starting thread. Suite=0 thread=61
DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x00000000
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
DLT stderr Handler1=09001000A0CA9540 Handler2=09001000A0B0A810
DLT stderr R0=0000010013657278 R1=0000010029ADC650 R2=08001000A01D6D78 R3=0A000003FBFB3050
DLT stderr R4=000001002415CF00 R5=000001002415A300 R6=0000000000000022 R7=0000000000000010
DLT stderr R8=0000000000000029 R9=0A000003FBFB32E6 R10=0000000000000000 R11=0000010013657934
DLT stderr R12=000001002415CF00 R13=0000010029AE7800 R14=000001002B170020 R15=00000100287A8400
DLT stderr R16=0000010023312198 R17=FFFFFFFFFFFFFFFF R18=0000000000000000 R19=09001000A077C268
DLT stderr R20=0000000000000000 R21=0A000000005371C8 R22=0000000000000000 R23=0000000000000000
DLT stderr R24=0000000000000000 R25=0A0000000067C090 R26=0A000003FC155058 R27=0A000003FBFB3020
DLT stderr R28=0A000003FBFB3020 R29=0A000003FBFB3050 R30=0A000000000FFE10 R31=000001002415CF00
DLT stderr IAR=0006000000000000 LR=0000010013657278 MSR=A00000000200D032 CTR=0006000000000000
DLT stderr CR=2400012460040000 FPSCR=8200000000000000 XER=6004000082000000
DLT stderr FPR0 0000000000000001 (f: 1.000000, d: 4.940656e-324)
DLT stderr FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
DLT stderr FPR2 3fed05d28c000000 (f: 2348810240.000000, d: 9.069607e-01)
DLT stderr FPR3 433000000020f537 (f: 2159927.000000, d: 4.503600e+15)
DLT stderr FPR4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR5 43300000000310fe (f: 200958.000000, d: 4.503600e+15)
DLT stderr FPR6 41407a9b80000000 (f: 2147483648.000000, d: 2.159927e+06)
DLT stderr FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR8 bebb4960afefe5e1 (f: 2951734784.000000, d: -1.626410e-06)
DLT stderr FPR9 bf64e5045a569e80 (f: 1515626112.000000, d: -2.550610e-03)
DLT stderr FPR10 402c915ad5154047 (f: 3574939648.000000, d: 1.428390e+01)
DLT stderr FPR11 3fd55555555450ef (f: 1431589120.000000, d: 3.333333e-01)
DLT stderr FPR12 4530000000000000 (f: 0.000000, d: 1.934281e+25)
DLT stderr FPR13 4028000000000000 (f: 0.000000, d: 1.200000e+01)
DLT stderr FPR14 40062e42fefa39ef (f: 4277811712.000000, d: 2.772589e+00)
DLT stderr FPR15 40026bb1bbb55516 (f: 3149223168.000000, d: 2.302585e+00)
DLT stderr FPR16 4010000000000000 (f: 0.000000, d: 4.000000e+00)
DLT stderr FPR17 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
DLT stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr Target=2_90_20220105_1 (AIX 7.2)
DLT stderr CPU=ppc64 (64 logical CPUs) (0x1000000000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr runJavaThread+0x280 (0x0900000003B50204 [libj9vm29.so+0x74204])
DLT stderr javaProtectedThreadProc+0x11c (0x0900000003ADEFC0 [libj9vm29.so+0x2fc0])
DLT stderr omrsig_protect+0x4fc (0x0900000003EB6C60 [libj9prt29.so+0x5ec60])
DLT stderr javaThreadProc+0x70 (0x0900000003ADEE34 [libj9vm29.so+0x2e34])
DLT stderr thread_wrapper+0x558 (0x09000000037FC77C [libj9thr29.so+0x577c])
DLT stderr _pthread_body+0xe8 (0x09000000005B204C [libpthreads.a+0x404c])
DLT stderr ---------------------------------------
DLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2022/01/05 16:47:46 - please wait.

DLT stderr *** Invalid JIT return address 0000000000000010 in 0000010029ACE480

DaaLoadTest_daa1_special_5m_4_FAILED
```

```
===============================================
Running test DaaLoadTest_daa1_special_5m_6 ...
===============================================
DaaLoadTest_daa1_special_5m_6 Start Time: Wed Jan  5 16:48:31 2022 Epoch Time (ms): 1641419311085
variation: Mode121
JVM_OPTIONS:  -Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs 

DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x00000000
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
DLT stderr Handler1=09001000A0CA9540 Handler2=09001000A0B0A810
DLT stderr R0=000001001313AA90 R1=00000100282AA650 R2=08001000A01D6D78 R3=0A00000002AE44D8
DLT stderr R4=0000010023DD1B00 R5=0000010023DD4700 R6=0000010023DD4700 R7=0000010023DD1B00
DLT stderr R8=0000010023DD3130 R9=0000010023DD1B00 R10=0000000000000000 R11=000001001313B12C
DLT stderr R12=0000010023DD4700 R13=00000100282B5800 R14=000001002AC615D0 R15=0000010027C18100
DLT stderr R16=0000010022F8C1D8 R17=FFFFFFFFFFFFFFFF R18=0000000000000000 R19=09001000A077C268
DLT stderr R20=0000000000000000 R21=0A0000000016D308 R22=0A00000001933358 R23=0A00000001932DC8
DLT stderr R24=0000000000000004 R25=0A000000025BD368 R26=0A00000002AE4418 R27=0A00000002AE44A8
DLT stderr R28=0A00000002AE44A8 R29=0000000000000000 R30=0A00000002AE44D8 R31=0000010023DD4700
DLT stderr IAR=8CF80A00020008A0 LR=000001001313AA90 MSR=A00000000200D032 CTR=8CF80A00020008A1
DLT stderr CR=2400022420040000 FPSCR=8200000000000000 XER=2004000082000000
DLT stderr FPR0 412e848000000000 (f: 0.000000, d: 1.000000e+06)
DLT stderr FPR1 40c3880000000000 (f: 0.000000, d: 1.000000e+04)
DLT stderr FPR2 fffff454dbe09c90 (f: 3688930560.000000, d: -NaNQ)
DLT stderr FPR3 c2a756483ec6e000 (f: 1053220864.000000, d: -1.282967e+13)
DLT stderr FPR4 c1d31e21c9c00000 (f: 3384803328.000000, d: -1.282967e+09)
DLT stderr FPR5 c00061e92c09fa6e (f: 738851456.000000, d: -2.047808e+00)
DLT stderr FPR6 bfa87a4b027e9b95 (f: 41851796.000000, d: -4.780802e-02)
DLT stderr FPR7 4000000000000000 (f: 0.000000, d: 2.000000e+00)
DLT stderr FPR8 3f3892ecdae86afd (f: 3672664832.000000, d: 3.749684e-04)
DLT stderr FPR9 3fc55520e8e8967f (f: 3907556864.000000, d: 1.666604e-01)
DLT stderr FPR10 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
DLT stderr FPR11 beda36365f5f612d (f: 1600086272.000000, d: -6.249372e-06)
DLT stderr FPR12 3fc555555555553e (f: 1431655680.000000, d: 1.666667e-01)
DLT stderr FPR13 412e848000000000 (f: 0.000000, d: 1.000000e+06)
DLT stderr FPR14 3e83f88763a9c9f1 (f: 1672071680.000000, d: 1.487942e-07)
DLT stderr FPR15 bf66c16c16bebd93 (f: 381599136.000000, d: -2.777778e-03)
DLT stderr FPR16 3f11562ac78a4541 (f: 3347727616.000000, d: 6.613384e-05)
DLT stderr FPR17 be2ff3cdcc756fce (f: 3430248448.000000, d: -3.719744e-09)
DLT stderr FPR18 3f11566aaf25de2c (f: 2938494464.000000, d: 6.613756e-05)
DLT stderr FPR19 bebbbcdb6774cecb (f: 1735708416.000000, d: -1.653297e-06)
DLT stderr FPR20 3dd9979767497dad (f: 1732869504.000000, d: 9.310371e-11)
DLT stderr FPR21 bebbbd41c5d26bf1 (f: 3318901760.000000, d: -1.653390e-06)
DLT stderr FPR22 3e66376972bea4d0 (f: 1925096704.000000, d: 4.138137e-08)
DLT stderr FPR23 3fee848000000000 (f: 0.000000, d: 9.536743e-01)
DLT stderr FPR24 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
DLT stderr FPR25 3fa7b80000000000 (f: 0.000000, d: 4.632568e-02)
DLT stderr FPR26 bf5224a5191957e0 (f: 421091296.000000, d: -1.107370e-03)
DLT stderr FPR27 bfa8492528c8cabf (f: 684247744.000000, d: -4.743305e-02)
DLT stderr FPR28 bf5224a5191957d2 (f: 421091296.000000, d: -1.107370e-03)
DLT stderr FPR29 3c4baf4e740749c8 (f: 1946634752.000000, d: 3.001591e-18)
DLT stderr FPR30 3c4d103800000000 (f: 0.000000, d: 3.151055e-18)
DLT stderr FPR31 bc060e98bf8b6382 (f: 3213583360.000000, d: -1.494642e-19)
DLT stderr Target=2_90_20220105_1 (AIX 7.2)
DLT stderr CPU=ppc64 (64 logical CPUs) (0x1000000000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr runJavaThread+0x280 (0x0900000003B50204 [libj9vm29.so+0x74204])
DLT stderr javaProtectedThreadProc+0x11c (0x0900000003ADEFC0 [libj9vm29.so+0x2fc0])
DLT stderr omrsig_protect+0x4fc (0x0900000003EB6C60 [libj9prt29.so+0x5ec60])
DLT stderr javaThreadProc+0x70 (0x0900000003ADEE34 [libj9vm29.so+0x2e34])
DLT stderr thread_wrapper+0x558 (0x09000000037FC77C [libj9thr29.so+0x577c])
DLT stderr _pthread_body+0xe8 (0x09000000005B204C [libpthreads.a+0x404c])
DLT stderr ---------------------------------------
DLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2022/01/05 16:49:25 - please wait.
DLT stderr 
DLT stderr 
DLT stderr *** Invalid JIT return address 0000010023DD1B00 in 0000010026508880

DaaLoadTest_daa1_special_5m_6_FAILED
```

Note a few other segmentation errors at `jdk_util` https://github.com/eclipse-openj9/openj9/issues/14228 https://github.com/eclipse-openj9/openj9/issues/14229

### PR DESCRIPTION
**Pull request by jdmpapin**
Certain transformations in the compiler rely on a guarantee that a given resolved call node will simply call the target method without attempting to resolve a constant pool entry, since the constant pool entry may not correspond to the call in the usually expected way.

We always have this guarantee in non-AOT compilations.

In AOT compilations, we currently have this guarantee for direct calls when using the symbol validation manager (SVM) on x86, Power, and z.

In the SVM case, each code generator must now opt in to this class of transformations by explicitly declaring that it provides the needed guarantee for direct calls, virtual calls, or both.

Special-case virtual and interface resolution in AOT now respects `isResolved*DispatchGuaranteed()`. In particular, private `invokevirtual`, private `invokeinterface`, and final `Object` `invokeinterface` will all become direct, so heed `isResolvedDirectDispatchGuaranteed()`, and non-final `Object` `invokeinterface` will become virtual, so now heeds `isResolvedVirtualDispatchGuaranteed()`.

Additionally, refinement of `invokeBasic()` and `linkTo*()` now also respects these queries, though it shouldn't (currently) be attempted in AOT regardless. Refinement requires a known object index for either the `MethodHandle` or the `MemberName`, and AOT does not support the known object table.

It probably also makes sense to gate value propagation's type refinement of indirect calls on `isResolvedDirectDispatchGuaranteed()` for fixed type and `isResolvedVirtualDispatchGuaranteed()` for type bounds, but this is not done in this commit. That change would require modifications to OMR, and there is currently no problem with call refinement in VP because it respects `canDevirtualizeDispatch()`, which is false in AOT compilations.

As a result of the above, this commit effectively stops AOT compilations using the SVM from generating resolved virtual calls for `invokeinterface` calling non-final methods of `Object`. Instead, such calls are left to be treated as (unresolved) interface calls as in non-SVM AOT. This ilgen transformation can be re-enabled for a particular code generator by overriding `guaranteesResolvedVirtualDispatchForSVM()` to return true, but first it will be necessary to ensure that the code generator really provides that guarantee. If the sequence generated for a resolved virtual call is simply a call through the vtable, then providing the guarantee should only involve:
- sending execution to the resolved path when the SVM is enabled, and
- generating an appropriate J2I thunk validation.

However, the required J2I thunk validation does not yet exist. It will be implemented separately.

----

There is one preparatory refactoring commit.

----

Fixes #14124
Fixes #14230

### CODE REVIEW

**Review by dsouzai — APPROVED** [review]
LGTM

**Comment by dsouzai** [comment]
jenkins test sanity+aot all jdk17

**Comment by dsouzai** [comment]
jenkins test sanity+aot all jdk17

**Comment by 0xdaryl** [comment]
jenkins test sanity+aot all jdk17

Builds worked but the testing did not start.  Trying again.

**Comment by dsouzai** [comment]
jenkins test sanity all jdk17

Gonna run non-aot tests to see if maybe they'll trigger.

**Comment by dsouzai** [comment]
Worth mentioning, prior to merging jitserver should also be tested.

**Comment by 0xdaryl** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk17

**Comment by 0xdaryl** [comment]
jenkins test sanity plinuxaot,xlinuxaot,zlinuxaot jdk17

**Comment by 0xdaryl** [comment]
@jdmpapin : please triage the AOT failures to see if they are related to this PR.  It seems only the x86 failing job was retained.

**Comment by jdmpapin** [comment]
That restarted Build_JDK17_x86-64_linux_aot_Personal instead of Test_openjdk17_j9_sanity.functional_x86-64_linux_aot_Personal, which is what I was trying to restart. Hopefully this will be the right one now

Jenkins test sanity+aot xlinux jdk17

**Comment by dsouzai** [comment]
the `jit_compareAndBranch_0` is failing in a different PR build as well https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_mac_Personal_testList_1/56/console.

**Comment by dsouzai** [comment]
Opened https://github.com/eclipse-openj9/openj9/issues/14459. Will likely disable this test from the forceAOT runs so it can be re-enabled once fixed. (see https://github.com/eclipse-openj9/openj9/issues/6057).

**Comment by dsouzai** [comment]
@0xdaryl All failures are unrelated to this PR. Could you approve if everything looks good to you?

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Please go ahead with the merge @dsouzai.  FYI @pshipton 

@jdmpapin : please create a PR for 0.31 as well.  It can be merged after this PR soaks for a day.

**Comment by dsouzai** [comment]
jenkins test sanity xlinuxjit jdk17

sanity test for jitserver.

**Comment by dsouzai** [comment]
oh i missed that we already tested jitserver.

**Comment by jdmpapin** [comment]
Opened  #14463 for 0.31

**Pull request merged**
