### PR TITLE
Add missing checks to convert store to load

### PR DESCRIPTION
**Pull request by VermaSh**
These checks were accidentally removed in
`Update IdiomRecognitionUtils.cpp to use new TransformUtil APIs` commit.

Fixes: https://github.com/eclipse-openj9/openj9/issues/19666

### CODE REVIEW

**Comment by VermaSh** [comment]
cc: @r30shah @zl-wang

**Comment by VermaSh** [comment]
For reference, we were failing because we were missing call to `convertStoreToLoadWithI2LIfNecessary` for the index node. Other changes in this PR are to improve readability and to stay consistent with other call sites in the code.


[1] https://github.com/eclipse-openj9/openj9/blob/825b666313e360e83823ee7f957efab04dc1eb8b/runtime/compiler/optimizer/IdiomRecognitionUtils.cpp#L863

**Review by r30shah — COMMENTED** [review]
Just a comment, not suggesting change rn. Will wait for WIP to get removed.

**Comment by VermaSh** [comment]
Local testing passed without any failure. Comparing the failing and passing logs to get the trees responsible for the failure.

**Comment by VermaSh** [comment]
This doesn't fix https://github.com/eclipse-openj9/openj9/issues/19666 but still needed because it fixes index node reference count bug. The index node ends up with reference count higher than actual number of references resulting in a register being kept alive longer than it should. The original code duplicated the index node before using it in new array address trees, the duplication was accidentally removed during the code refactoring for off-heap changes. 

While going through the off-heap change I noticed that the original code was subtracting - array header size whereas we are adding array header size. I am in the process of updating the `TR::TransformUtil::` APIs to support this, should have a WIP PR soon. I'll leave the WIP tag for now because this code will need to be updated again after the transform util changes have been merged.

**Comment by VermaSh** [comment]
https://github.com/eclipse/omr/pull/7405 must be merged before this.

**Comment by zl-wang** [comment]
be careful with that though:  @rmnattas once pointed it out to me that the subtraction is needed because caller added it already. in off-heap case, you access elements with dataAddr pointer such that you need to effectively make arrayBaseOffset as zero (so that subtraction is needed).

**Comment by VermaSh** [comment]
@zl-wang I am not removing the subtraction. It wasn't really a subtraction actually, we were adding header size to the offset by subtracting negative header size from it. The subtraction got replaced by addition so this change just reverts it back to subtraction. This change applies only to non off-heap path.

**Comment by VermaSh** [comment]
Removing my second commit to remove OMR dependency so that this can be merged sooner as my OMR change is causing failures. This change on it's own fixes https://github.com/eclipse-openj9/openj9/issues/19666, I'll launch a set of personal builds to verify this.

**Comment by VermaSh** [comment]
Personal build without OMR changes: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/23174/

**Review by r30shah — APPROVED** [review]
Checking out this change alone (I do think what Julian mentioned could be a issue needs to be checked at for the OMR PR),  Comparing changes in this PR  with the Utils without changes added for supporting off-heap, it looks good to me. 

@zl-wang  Appreciate if you can also review the changes.

**Comment by r30shah** [comment]
jenkins test all jdk11,jdk21

**Comment by r30shah** [comment]
jenkins test sanity.functional all jdk11,jdk21

**Comment by VermaSh** [comment]
My personal build passed without failures so removing WIP tag.

**Comment by r30shah** [comment]
@VermaSh  Can you verify if failures on windows are related or not ?

**Comment by VermaSh** [comment]
@r30shah x builds were aborted because all nodes were offline

**Comment by r30shah** [comment]
jenkins test sanity.functional windows jdk11,jdk21

**Comment by r30shah** [comment]
jenkins test sanity.functional win jdk11,jdk21

**Comment by r30shah** [comment]
Based on the testing done by Shubham and finished tests on other platform, I do not think this will cause any issue on windows, and we can merge this safely. 

@VermaSh This one resolves the blocker right ? Can we update the Commit message to reflect that ? 

@zl-wang  Ping to see if you have any recommendation for Shubham's PR reverting the checks that was removed accidentally.

**Comment by VermaSh** [comment]
Yup, from my testing this does fix [failure ](https://github.com/eclipse-openj9/openj9/issues/19666). I have updated the PR description to reflect that.

**Comment by VermaSh** [comment]
All windows machines are still offline because they can't access github.com ([issue](https://github.ibm.com/runtimes/infrastructure/issues/8756)).

**Review by zl-wang — APPROVED** [review]
LGTM

**Comment by r30shah** [comment]
As changes are approved and testing has done to satisfactory level, merging this change.

**Pull request merged**
