### PR TITLE
Build-Test-All remove `8` from aarch64_mac, and add aarch64_mac to `all`

### PR DESCRIPTION
**Pull request by pshipton**

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile all jdk8

**Comment by pshipton** [comment]
jenkins compile all jdk11

**Comment by pshipton** [comment]
jdk8 PR build https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/1716/
jdk11 PR build https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJ9/1717/

**Comment by pshipton** [comment]
Builds started without error8 platform build
    [Pipeline_Build_Test_JDK8_aarch64_linux](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_aarch64_linux/)
    [Pipeline_Build_Test_JDK8_ppc64_aix](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_ppc64_aix/)
    [Pipeline_Build_Test_JDK8_ppc64le_linux](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_ppc64le_linux/)
    [Pipeline_Build_Test_JDK8_s390x_linux](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_s390x_linux/)
    [Pipeline_Build_Test_JDK8_x86-32_windows](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_x86-32_windows/)
    [Pipeline_Build_Test_JDK8_x86-64_linux](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_x86-64_linux/)
    [Pipeline_Build_Test_JDK8_x86-64_mac](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_x86-64_mac/)
    [Pipeline_Build_Test_JDK8_x86-64_windows](https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_x86-64_windows/)

**Review by knn-k — APPROVED** [review]

**Comment by knn-k** [comment]
I will wait for PR #14638 to be merged before I merge this PR.

**Comment by pshipton** [comment]
When this is merged I'll also add amac to all the acceptance builds for OMR, 11, 17, 18 19.

**Comment by knn-k** [comment]
I opened #14648 for updating README for Jenkins jobs.

**Pull request merged**
