### PR TITLE
Print time spent in compilation queue in JIT performance vlogs

### PR DESCRIPTION
**Pull request by AlexeyKhrabrov**
When the `-Xjit:verbose=compilePerformance` option is enabled, record the time spent in the compilation queue in JIT verbose logs for successful compilations and AOT cache hits (as `... queueTime=NNNus`). This time represents the total compilation request latency which is a useful JIT performance metric. The high-resolution (microsecond) timestamp of when the compilation is queued is stored in the `MethodToBeCompiled` struct (which is reduced in size in order to make room for the newly added field without increasing memory footprint).

### CODE REVIEW

**Comment by AlexeyKhrabrov** [comment]
@mpirvu Please note that this change is not JITServer-specific, so it should be tested on all platforms.

**Review by mpirvu — APPROVED** [review]
LGTM. One thing to point out is that for a method that is compiled, fails compilation and is retried, the new introduced time will include all the compilation attempts because `_entryTime_usec` is not reset when the entry is requeued after a failure. I guess that's ok because we don't print the new time for compilation failures like we do for the old compilation time.
Maybe it's worth adding a comment in case someone has a question around this topic so that we don't have to read the code again to find the answer.

**Comment by AlexeyKhrabrov** [comment]
> One thing to point out is that for a method that is compiled, fails compilation and is retried, the new introduced time will include all the compilation attempts because `_entryTime_usec` is not reset when the entry is requeued after a failure.

That's on purpose, to measure total latency. I'll add a comment to explain that.

I also noticed that the existing `_entryTime` field is not actually used anywhere in the code after it's set. Is the intention to look at it in the debugger? Is it worth keeping?

**Comment by mpirvu** [comment]
Yes, that field was meant to be inspected under gdb. We haven't used it a very long while and it can be deleted.

**Comment by AlexeyKhrabrov** [comment]
Updated to add the comment and keep only one timestamp field.

**Review by mpirvu — APPROVED** [review]

**Comment by mpirvu** [comment]
jenkins test sanity all jdk17

**Comment by mpirvu** [comment]
Builds on plinux, xlinux, plinux failed. This is suspicious because all these platforms where JITServer is enabled.
From zlinux build:
```

**Comment by mpirvu** [comment]
jenkins test sanity plinux,xlinux,zlinux jdk17

**Comment by mpirvu** [comment]
Linux builds failed again:
```
11:44:05  Bad scan type for object pointer 00000000FF648A70
11:44:05  16:44:04.389 0x16f00    j9mm.141    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/openj9/runtime/gc_glue_java/ScavengerDelegate.cpp:392: ((false))
11:44:05  JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/02/09 12:44:04 - please wait.
11:44:05  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/make/core.20220209.124404.20560.0001.dmp' in response to an event
11:44:07  JVMDUMP010I System dump written to /home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/make/core.20220209.124404.20560.0001.dmp
11:44:07  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/make/javacore.20220209.124404.20560.0002.txt' in response to an event
11:44:07  JVMDUMP010I Java dump written to /home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/make/javacore.20220209.124404.20560.0002.txt
11:44:07  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/make/Snap.20220209.124404.20560.0003.trc' in response to an event
11:44:07  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/make/Snap.20220209.124404.20560.0003.trc
11:44:07  JVMDUMP013I Processed dump event "traceassert", detail "".
11:44:07  CreateJmods.gmk:226: recipe for target '/home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/build/linux-x86_64-server-release/support/images/jmods/_create_openj9.dtfj.jmod_exec.marker' failed
11:44:07  gmake[3]: *** [/home/jenkins/workspace/Build_JDK17_x86-64_linux_Personal/build/linux-x86_64-server-release/support/images/jmods/_create_openj9.dtfj.jmod_exec.marker] Error 1
```
@AlexeyKhrabrov Could you please rebase the code just in case we got some unrelated bug included? Thanks

**Comment by AlexeyKhrabrov** [comment]
Rebased. I still can't reproduce the issue locally. It might be worth waiting until https://github.com/eclipse/omr/pull/6345 is promoted (or specify it as a dependency) so that we get symbolic stack traces in the test output without having to dig into core files if the crashes still happen.

**Comment by mpirvu** [comment]
jenkins test sanity plinux,xlinux,zlinux jdk17

**Comment by mpirvu** [comment]
Something is not right because tests on other PRs pass.

**Comment by AlexeyKhrabrov** [comment]
I removed the method details pointer change. Let's see if that was the issue (even though the code is valid either way).

**Comment by mpirvu** [comment]
jenkins test sanity plinux,xlinux,zlinux jdk17

**Comment by mpirvu** [comment]
jenkins test sanity all jdk8

**Comment by mpirvu** [comment]
All checks have passed. This PR can be merged.

**Pull request merged**
