### PR TITLE
Send AOT header to server whenever JITServer AOT cache is requested

### PR DESCRIPTION
**Pull request by cjjdespres**
A client will now send a `TR_AOTHeader` as part of its VM info whenever the AOT cache as been requested to be used. As we currently only create and enable the deserializer with a local SCC present, this should not change any current behaviour.

The new TR_RelocationRuntime::fillAOTHeader is responsible for filling in a new TR_AOTHeader. Actual allocation of this header is still handled by TR_SharedCacheRelocationRuntime::createAOTHeader.

### CODE REVIEW

**Comment by cjjdespres** [comment]
Attn @mpirvu. In #18301 `fillAOTHeader` will be used to create and send a client's AOT header without a local SCC being present.

**Comment by cjjdespres** [comment]
Force-pushed and changed the PR topic slightly because I thought it might be easier to have the entire header-sending change in one merge.

**Comment by cjjdespres** [comment]
Force-pushed to bring in the latest merges. Shouldn't have changed anything.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity all jdk21

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit,alinux64jit jdk17

**Comment by mpirvu** [comment]
jenkins test sanity alinux,alinux64jit jdk21

**Comment by mpirvu** [comment]
The failure on ARM was due to infra, so I triggered another round of testing.
```
20:21:54  Cloning into 'openj9'...
20:21:55  update to openj9 sha: origin/pr/18889/merge
20:21:55  git fetch -q --unshallow
20:22:28  error: pathspec 'origin/pr/18889/merge' did not match any file(s) known to git
20:22:28  SHA not yet found. Continue fetching PR refs and tags...
20:22:28  git fetch -q --tags https://github.com/eclipse-openj9/openj9.git +refs/pull/*:refs/remotes/origin/pr/*
20:22:54  error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
20:22:54  error: 2295 bytes of body are still expected
20:22:54  fetch-pack: unexpected disconnect while reading sideband packet
20:22:54  fatal: early EOF
20:22:54  fatal: fetch-pack: invalid index-pack output
```

**Comment by mpirvu** [comment]
The test on aarch64 failed due to infra:
```
20:21:54  git clone --depth 1 --reference-if-able /home/****/openjdk_cache -b master https://github.com/eclipse-openj9/openj9.git
20:21:54  Cloning into 'openj9'...
20:21:55  update to openj9 sha: origin/pr/18889/merge
20:21:55  git fetch -q --unshallow
20:22:28  error: pathspec 'origin/pr/18889/merge' did not match any file(s) known to git
20:22:28  SHA not yet found. Continue fetching PR refs and tags...
20:22:28  git fetch -q --tags https://github.com/eclipse-openj9/openj9.git +refs/pull/*:refs/remotes/origin/pr/*
20:22:54  error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
20:22:54  error: 2295 bytes of body are still expected
20:22:54  fetch-pack: unexpected disconnect while reading sideband packet
20:22:54  fatal: early EOF
20:22:54  fatal: fetch-pack: invalid index-pack output
```
Since other tests have passed (including one of aarch64) I am merging this PR.

**Pull request merged**
