### PR TITLE
Use 32-bit XOR to zero registers in x64

### LINKED ISSUE #19236: Use 32-bit XORRegReg to zero registers on x64
When XORRegReg is used to zero a register on x64, the 32-bit operand form should be used because the upper 32-bits of the result are automatically zero extended.  This will save a REX prefix on each of these instructions (1 byte savings).

Sweep through the x86 code generator looking at where XORRegReg or XOR8RegReg is used for the purpose of zeroing a register and ensure it uses XOR4RegReg instead.  I found a few on inspection.

OpenJ9 companion issue to eclipse/omr#7295

### PR DESCRIPTION
**Pull request by R2steven**
Swept through x86 codegen and replaced XORRegReg with XOR4RegReg when used to zero a register

Closes #19236
Signed-off-by: Ryan Stevens <restevens52@gmail.com>

### CODE REVIEW

**Review by BradleyWood — COMMENTED** [review]
Looks good. I found two missing cases in [AMD64JNILinkage.cpp](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp)

**Comment by R2steven** [comment]
Thanks @BradleyWood, I wasn't sure whether the x/amd64 folder was meant to generate code to run on an x86 machine. I also noticed a PXORRegReg instruction in J9TreeEvaluator.cpp. Do you happen to know if this instruction is already 32 bit, or is it 64 bit and I should look into optimizing it?

**Comment by BradleyWood** [comment]
> I also noticed a PXORRegReg instruction in J9TreeEvaluator.cpp.

No, that is a vector instruction and wouldn't apply to this issue.

@0xdaryl Can you launch a build?

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux,windows,xmac jdk21

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux,win,xmac jdk21

**Comment by 0xdaryl** [comment]
Changes appear fine.  Please squash your commits.

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux,win,xmac jdk21

**Comment by R2steven** [comment]
failures appear to be infrastructure related again.

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Windows testing succeeded.  Linux and Mac still afflicted by UNB outage.  Changes look safe to me.

**Comment by BradleyWood** [comment]
@R2steven If you are interested, we have a similar issue in eclipse/omr#7295

**Pull request merged**
