### PR TITLE
Allow for overriding Simplifier handlers defined by OMR

### PR DESCRIPTION
**Pull request by hzongaro**
OMR pull request https://github.com/eclipse/omr/pull/6821 introduces changes to the Simplifier optimization that allows a downstream project to override handlers that are supplied for core OMR opcodes in addition to supplying handlers for opcodes that the downstream project provides. The overriding is performed in the new files SimplifierHandlers.hpp and SimplifierTable.enum.

This is a coordinated change that allows OpenJ9 to accommodate the OMR changes without actually taking advantage of the ability to override any simplifier handlers.

### CODE REVIEW

**Comment by hzongaro** [comment]
Daryl @0xdaryl, may I ask you to review this change?  Once approved, it will require a coordinated merge with OMR pull request eclipse/omr#6821, so I've marked it as a work in progress.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11,jdk17 depends eclipse/omr#6821

**Comment by 0xdaryl** [comment]
Please move this out of draft state.

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux jdk17 depends eclipse/omr#6821

Previous acceptance test run was successful.  As a couple of days has passed since it was run, I'll re-run a sniff test on x Linux before merging.

**Pull request merged**
