### PR TITLE
Limit the number of startup hints in SCC

### PR DESCRIPTION
**Pull request by hangshao0**
1. Add a new field in the cache header which is the number of additional
startup hints that are allowed to be stored to the SCC.
2. Add a CML option to adjust this number.
3. Add test cases.

Fixes: https://github.com/eclipse-openj9/openj9/issues/19308

### CODE REVIEW

**Comment by pshipton** [comment]
Pls open an docs issue.

**Comment by pshipton** [comment]
jenkins test extended.system amac jdk11

**Comment by hangshao0** [comment]
Doc issue: https://github.com/eclipse-openj9/openj9-docs/issues/1433

**Comment by pshipton** [comment]
Ran ShareClassesCMLTests-6.xml via grinder, which passed.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3899

**Review by pshipton — APPROVED** [review]

**Pull request merged**
