### PR TITLE
WIP: Replace MemberName class with OpenJDK implementation

### PR DESCRIPTION
**Pull request by fengxue-IS**
Part of: #7352 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
Note: First 9 commits are picked from #7625 and should be removed from this PR once the it is delivered.

Also, the native method headers added in MethodHandleNatives are for compilation requirements (VM compiles & passes simple testcases), there may still be patchings required to enable the actual functionality in VM native code.

**Comment by pshipton** [comment]
@fengxue-IS @babsingh is this still relevant?

**Comment by babsingh** [comment]
> is this still relevant?

yes, we are planning to merge these changes in a disabled form.

https://github.com/eclipse/openj9/pull/10097, https://github.com/eclipse/openj9/pull/10094 and few other PRs depend on this PR.

**Comment by fengxue-IS** [comment]
Closing this PR as it is no longer relevent.

**Pull request closed without merging**
