### PR TITLE
Implement JVM_LoadZipLibrary()

### PR DESCRIPTION
**Pull request by keithc-ca**
The stub had the wrong signature: this corrects it and provides an implementation.

Fixes: #17996.

### CODE REVIEW

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
jenkins test sanity alinux jdk21

**Comment by tajila** [comment]
jenkins test sanity win jdk8

**Comment by keithc-ca** [comment]
I think you meant "alinux64" instead of "alinux". I'll let you decide whether the Windows build is sufficient or you want that build as well.

**Comment by keithc-ca** [comment]
If https://github.com/eclipse-openj9/openj9/pull/18069 is accepted, "alinux" will be equivalent to "alinux64".

**Comment by tajila** [comment]
jenkins test sanity alinux jdk21

**Comment by keithc-ca** [comment]
Jenkins test sanity alinux64 jdk21

**Comment by tajila** [comment]
Known failure

```
23:16:03.320 0x19200j9vmutil(j9vm).15     *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK21_aarch64_linux_Personal/openj9/runtime/util/mthutil.c:600: ((((uintptr_t)-1) != methodIndex))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2023/09/01 19:16:03 - please wait.
```

**Pull request merged**
