### PR TITLE
MH J2I Thunk API Nomenclature Clarification

### PR DESCRIPTION
**Pull request by dsouzai**
There are two types of J2I thunks the JIT generates; thunks for normal J2I transitions, and thunks for invokeExact J2I transitions. Thunks of the former kind are stored in a hashtable maintained in the VM whereas thunks of the latter kind are stored in a table maintained by the JIT. However, both thunks are referred to as "J2I Thunks", which, while technically correct, can be very confusing to a reader of the code.

This PR renames `TR_J2IThunk` (which was the data structure to describe invokeExact J2I Thunks) to `TR_MHJ2IThunk`. It also updates frontend queries to refer to invokeExact J2I thunks as MH J2I Thunks.

### CODE REVIEW

**Comment by dsouzai** [comment]
Regarding https://github.com/eclipse-openj9/openj9/pull/16625#pullrequestreview-1277419302, defining a struct to describe non-invokeExact J2I thunks is actually quite a decent amount of work, and so it probably deserves it's own future cleanup PR. This PR is primarily targeted at clarifying the the APIs used to find/store the two types of J2I Thunks.

**Comment by dsouzai** [comment]
@mpirvu @jdmpapin could you please review?

**Review by jdmpapin — APPROVED** [review]

**Review by mpirvu — CHANGES_REQUESTED** [review]
LGTM. There is one change needed in VMJ9Server.hpp

**Review by mpirvu — APPROVED** [review]

**Comment by mpirvu** [comment]
jenkins test sanity all jdk17

**Pull request merged**
